import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';
import {proseFixture} from '../helpers/loi-single-call.mjs';import {authoredOutput} from '../helpers/loi-authored.mjs';
import {validateAuthoredSingleCallPlans,compositionInput} from '../../server/loi-composition.mjs';
import {AUTHORED_GUARD,authoredReview,proseUnits} from '../../server/loi-prose-contract.mjs';
import {writeLoi,readLoi,replayLoiHandoff} from '../../server/private-commands.mjs';import {loiEvidencePin} from '../../server/loi-evidence.mjs';import {MRX_AREAS} from '../../server/research-standard.mjs';import * as v from '../../server/validation.mjs';
function append(row,text,refs){const start=row.text.length+2;row.text+='\n\n'+text;for(const u of proseUnits(text))row.claims.push({start:start+u.start,end:start+u.end,refs});}
for(const [text,refs,code] of [
 ['The clinic receives 95% of graduates.',['evidence:0'],'loi_composition_invented_quantity'],
 ['Residents train at Other Hospital.',['evidence:0'],'loi_composition_invented_identity'],
 ['I founded a clinic.',['fact:0'],'loi_composition_invented_event'],
 ['Your program guarantees a fellowship.',['evidence:0'],'loi_composition_unsupported'],
 ['Your program offers robotic surgery.',['evidence:0'],'loi_composition_unsupported'],
 ['Residents do not attend a supervised continuity clinic.',['evidence:0'],'loi_composition_contradiction'],
 ['I have interviewed at this program.',['context:interviewState'],'loi_composition_contradiction'],
 ['My award is a reason to write.',['program'],'loi_composition_unsupported'],
 ['I want to discuss this detail.',[],'loi_composition_unmapped'],
])test('properly traced detectable invention rejects: '+text,()=>{const i=proseFixture(),out=authoredOutput(i);append(out.candidates[0],text,refs);assert.throws(()=>validateAuthoredSingleCallPlans(out,i),{code});});
test('wrong self trace, unknown/conflicted sources and arbitrary associations cannot certify facts',()=>{const i=proseFixture(),out=authoredOutput(i);append(out.candidates[0],'I have interviewed at this program.',['evidence:0']);assert.throws(()=>validateAuthoredSingleCallPlans(out,i));for(const state of ['UNKNOWN','CONFLICTED']){const x=proseFixture();x.refs.find(r=>r.kind==='evidence').state=state;assert.throws(()=>validateAuthoredSingleCallPlans(authoredOutput(x),x));}});
test('undecidable authored meaning remains visible even with valid IDs; edited negated statuses reject',()=>{const i=proseFixture(),out=authoredOutput(i);append(out.candidates[0],'This clinic feels like a setting where my priorities could take shape.',['reason:0','evidence:0']);const r=validateAuthoredSingleCallPlans(out,i)[0];assert.equal(r.review.automaticFactualCertification,false);assert.equal(r.review.studentVerificationRequired,true);assert.ok(r.review.units.at(-1).sourceTexts.length===2);assert.equal(r.review.units.at(-1).flag,'UNRESOLVED_SEMANTIC_SUPPORT');for(const text of ['I have interviewed at this program.','Residents do not attend a supervised continuity clinic.'])assert.throws(()=>authoredReview(r.text+'\n\n'+text,i.refs,i.program),{code:'loi_composition_contradiction'});const positive=proseFixture();positive.refs.find(r=>r.ref==='context:interviewState').text='I have interviewed at this program.';assert.throws(()=>authoredReview(r.text,positive.refs,positive.program),{code:'loi_composition_contradiction'});});
function fixture(){const actor={id:randomUUID(),role:'student',wpUserId:1397,tier:'ivprep_complete',eligible:true},id=randomUUID(),program=proseFixture().program,now='2026-10-07T12:00:00.000Z',hash=x=>createHash('sha256').update(x).digest('hex'),claim='rise-claim:'+hash('claim'),source={claimRef:'rise-claim:'+hash('source'),reviewRef:'rise-review:'+hash('review'),urls:['https://hospital.edu/curriculum'],retrievedAt:now,reviewedAt:now},e={area:'curriculum_training',field:'research.curriculum',state:'SUPPORTED',claimRef:claim,value:'Residents attend a supervised continuity clinic each week.',retrievedAt:now,asOf:{kind:'current',label:'2026'},sources:[source]},config={loi:{enabled:true,ownerId:actor.id,programId:program.id},loiComposition:{enabled:true,evidencePins:[loiEvidencePin(program,e)]}},legacy=[null,'legacy',{private:'keep'}],anchors=structuredClone(legacy),row={id,owner_id:actor.id,program_id:program.id,program_name:program.name,program_track:''};
 const research=()=>{const coverage={programId:program.id,registryReleaseId:program.registryReleaseId,observedAt:now,fields:Object.entries(MRX_AREAS).flatMap(([area,fields])=>fields.map(field=>({area,field,state:field===e.field?'SUPPORTED':'UNKNOWN'}))).sort((a,b)=>a.field.localeCompare(b.field,'en'))};coverage.receipt={sha256:hash(JSON.stringify(coverage)),publicRef:'rise-coverage-v1'};const body={schema:'rise-interviewiq-research-results-v1',coverage,facts:[structuredClone(e)]};return {...body,receipt:{sha256:hash(JSON.stringify(body)),publicRef:'rise-results-v1'}};};
 const db={async query(sql,args){if(sql.startsWith('SELECT * FROM iiq.interviews'))return {rows:args[1]===actor.id?[row]:[]};if(sql.includes('FROM iiq.preparation'))return {rows:[{anchors:structuredClone(anchors)}]};if(sql.includes('FROM iiq.consents'))return {rows:[]};if(sql.startsWith('INSERT INTO iiq.preparation')){assert.equal(args[0],actor.id);anchors.push(...JSON.parse(args[2]));return {rows:[{id:randomUUID()}]};}assert.fail('Unexpected SQL '+sql);}},owners={async getProgram(a,p){assert.equal(a.id,actor.id);assert.equal(p,program.id);return structuredClone(program);},async getProgramResearch(){return research();}},ctx={db,owners,config,actor,interviewId:id,clock:()=>new Date(now)};
 const i=proseFixture(),data={letterId:null,expectedHead:null,expectedLetterVersion:0,context:Object.fromEntries(i.refs.filter(r=>r.kind==='context').map(r=>[r.ref.split(':')[1],r.text])),motivations:[{id:randomUUID(),text:i.refs.find(r=>r.kind==='reason').text,confirmed:true}],facts:[{id:randomUUID(),text:i.refs.find(r=>r.kind==='fact').text,confirmed:true}],selectedEvidence:[{field:e.field,claimRef:claim}]},input=compositionInput({...data,contextConfirmed:true,count:1,approach:'DIRECT_CONCISE'},{program,evidence:[e],evidenceDigest:v.digest({program,evidence:[e]})},null,'DIRECT_CONCISE'),proposal=validateAuthoredSingleCallPlans(authoredOutput(input),input)[0],save={...data,text:proposal.text,storyRefs:[],studentFactualConfirmation:true,studentSpecificityConfirmation:true,compositionApproach:'DIRECT_CONCISE'},origin={schema:1,guard:AUTHORED_GUARD,generationId:randomUUID(),refs:input.refs,originalTextDigest:v.digest(proposal.text),originalClaims:proposal.claims};
 const run=(command,data,extra={})=>writeLoi({...ctx,command,data,...extra}),current=()=>anchors.filter(x=>x?.type==='iiq.loi.revision').at(-1),head=()=>{const c=current();return {letterId:c.letterId,expectedHead:c.revisionId,expectedLetterVersion:c.letterVersion,contentHash:c.contentHash};};return {ctx,actor,anchors,legacy,e,config,save,origin,run,current,head};}
test('real private handlers preserve authored provenance, gate current approval and freeze exact bytes through handoff',async()=>{const x=fixture();await x.run('loi.save',x.save,{authoredComposition:x.origin});const saved=x.current();assert.equal(saved.authoredComposition.review.state,'STUDENT_VERIFICATION_REQUIRED');assert.equal(saved.authoredComposition.review.editedTrace,false);assert.equal(saved.authoredComposition.studentSourceVerification,false);const approve=()=>({...x.head(),studentFactualConfirmation:true,studentSpecificityConfirmation:true});await assert.rejects(x.run('loi.approve',approve()),{code:'loi_source_verification_required'});const pins=x.config.loiComposition.evidencePins;x.config.loiComposition.evidencePins=[];await assert.rejects(x.run('loi.approve',{...approve(),studentSourceVerification:true}),{code:'loi_research_needed'});x.config.loiComposition.evidencePins=pins;const value=x.e.value;x.e.value+=' Curriculum changed.';await assert.rejects(x.run('loi.approve',{...approve(),studentSourceVerification:true}),{code:'loi_evidence_changed'});x.e.value=value;await x.run('loi.approve',{...approve(),studentSourceVerification:true});const approved=x.current();assert.equal(approved.text,saved.text);assert.equal(approved.contentHash,saved.contentHash);assert.equal(approved.authoredComposition.verifiedContentHash,approved.contentHash);assert.equal(approved.authoredComposition.studentSourceVerification,true);const handoff=await x.run('loi.handoff',{...x.head(),recipient:'director@hospital.edu',subject:'Interest',channel:'copy',recipientConfirmed:true});assert.equal(handoff.handoff.text,saved.text);assert.equal((await replayLoiHandoff(x.ctx,handoff.id)).handoff.text,saved.text);assert.deepEqual(x.anchors.slice(0,3),x.legacy);assert.equal((await readLoi(x.ctx)).history.length,3);await assert.rejects(x.run('loi.approve',{...x.head(),contentHash:'f'.repeat(64),studentFactualConfirmation:true,studentSpecificityConfirmation:true,studentSourceVerification:true}),{code:'loi_content_conflict'});await assert.rejects(writeLoi({...x.ctx,actor:{...x.actor,id:randomUUID()},command:'loi.save',data:x.save}));});
test('saving authored edits resets verification and approval; unknown meaning is shown without fabricated trace support',async()=>{const x=fixture();await x.run('loi.save',x.save,{authoredComposition:x.origin});const h=x.head();await x.run('loi.approve',{...h,studentFactualConfirmation:true,studentSpecificityConfirmation:true,studentSourceVerification:true});const {contentHash,...head}=x.head();await x.run('loi.save',{...x.save,...head,text:x.save.text+'\n\nThis clinic feels like a setting where my priorities could take shape.'});const c=x.current();assert.equal(c.state,'draft');assert.equal(c.approval,null);assert.equal(c.authoredComposition.studentSourceVerification,false);assert.equal(c.authoredComposition.review.editedTrace,true);assert.equal(c.authoredComposition.review.units.at(-1).flag,'UNRESOLVED_SEMANTIC_SUPPORT');assert.notEqual(c.contentHash,contentHash);const {contentHash:changed,...next}=x.head();await assert.rejects(x.run('loi.save',{...x.save,...next,text:x.save.text+'\n\nI have interviewed at this program.'}),{code:'loi_composition_contradiction'});assert.equal(x.current().contentHash,changed);});
