import test from 'node:test';import assert from 'node:assert/strict';import {maxCostBound,createNativeLoiProseComposer,LOI_CANARY_OWNER} from '../../server/loi-openai.mjs';import {validateAuthoredSingleCallPlans as validateSingleCallPlans} from '../../server/loi-composition.mjs';import {AUTHORED_GUARD as SINGLE_CALL_GUARD,validateAuthoredTrace as validateLocalProseTrace} from '../../server/loi-prose-contract.mjs';import {checkedUsage,providerAvailable,lifetimeAllowance} from '../../server/loi-generation.mjs';import {APPROVED_LOI_EVIDENCE_PINS} from '../../server/loi-evidence.mjs';import {proseFixture} from '../helpers/loi-single-call.mjs';import {authoredOutput as singleOutput} from '../helpers/loi-authored.mjs';import {native,configuration,request} from '../helpers/loi-single-provider.mjs';
const canary={id:LOI_CANARY_OWNER,wpUserId:1397,role:'student'};
test('one normal draft makes one bounded writer call with one receipt and no verifier/retry',async()=>{const x=native(),r=request(),out=await x.composer.compose(r);assert.equal(x.calls.length,1);assert.equal(x.composer.policy.singleRequest,true);assert.equal(x.composer.policy.providerPasses,1);assert.equal(providerAvailable(x.c,x.composer,canary),true);assert.equal(out.usage.passes.length,1);assert.equal(out.usage.costMicros,30);assert.deepEqual(checkedUsage(out.usage,x.c),out.usage);assert.equal(out.output.verification,undefined);assert.equal(SINGLE_CALL_GUARD,'PROSE_AUTHORED_REVIEW_V5');await assert.rejects(x.composer.compose(r),{code:'LOI_PROVIDER_ALREADY_ATTEMPTED'});assert.equal(x.calls.length,1);});
test('three explicit approaches use one response with distinct organization/opening/cadence',async()=>{const x=native(),input=proseFixture({approaches:['WARM_PERSONAL','DIRECT_CONCISE','ACADEMIC_PROGRAM']}),out=await x.composer.compose(request(input)),rows=validateSingleCallPlans(out.output,input);assert.equal(x.calls.length,1);assert.equal(rows.length,3);assert.equal(new Set(rows.map(r=>validateLocalProseTrace({approach:r.approach,text:r.text,claims:r.claims,fitLinks:r.fitLinks},input.refs,input.program).opening)).size,3);});
test('authored paraphrase and two confirmed motives produce different personalized drafts',()=>{const a=proseFixture(),b=proseFixture();b.refs.find(r=>r.kind==='reason').text='I want longitudinal mentorship in an outpatient clinic.';const aa=validateSingleCallPlans(singleOutput(a),a)[0],bb=validateSingleCallPlans(singleOutput(b),b)[0];assert.ok(aa.text.includes('thread that draws my interest'));assert.notEqual(aa.text,bb.text);assert.ok(!bb.text.includes(a.refs.find(r=>r.kind==='reason').text));assert.equal(aa.studentReviewRequired,true);assert.equal(aa.studentFactualConfirmation,false);});
for(const attack of ['I won a national research award.','I have not volunteered anywhere.','Your program guarantees fellowship admission.','The passing rate is 95%.','Your program has a strong fellowship match.','I would like to explain my interest in your guaranteed fellowship.'])test('local output contract rejects '+attack,async()=>{const x=native({author:input=>{const out=singleOutput(input);out.candidates[0].text+='\n\n'+attack;return out;}});await assert.rejects(x.composer.compose(request()),e=>e.code==='LOI_PROVIDER_FAILED'&&e.validatedUsage.passes.length===1&&e.validatedUsage.costMicros===30);assert.equal(x.calls.length,1);});
test('negation/suffix/unknown trace/offset shift/missing spans reject independently of author labels',()=>{for(const mutate of [r=>{const c=r.claims[1];r.text=r.text.slice(0,c.start)+'Not '+r.text.slice(c.start);for(const q of r.claims.slice(1)){q.start+=4;q.end+=4;}},r=>{const c=r.claims.at(-1);r.text=r.text.slice(0,c.end)+' guaranteeing admission'+r.text.slice(c.end);},r=>r.claims[1].ref='invented',r=>r.claims[1].start++,r=>r.claims.pop()]){const input=proseFixture(),out=singleOutput(input);mutate(out.candidates[0]);assert.throws(()=>validateSingleCallPlans(out,input));}});
test('program substitution and generic or topic-unrelated fit reject without character ratios',()=>{for(const change of [i=>i.program.name='Other Program',i=>i.refs.find(r=>r.kind==='evidence').text='Excellent training with supportive faculty.',i=>i.refs.find(r=>r.kind==='reason').text='I like your program.',i=>i.refs.find(r=>r.kind==='reason').text='I want protected laboratory research opportunities.']){const input=proseFixture();change(input);assert.throws(()=>validateSingleCallPlans(singleOutput(input),input));}});
test('provider uncertainty retains unknown single pass and consumes attempt',async()=>{const x=native({fail:true}),r=request();await assert.rejects(x.composer.compose(r),e=>{const u=checkedUsage(e.validatedUsage,x.c);assert.equal(u.passes[0].status,'OUTCOME_UNKNOWN');assert.equal(u.costMicros,0);return true;});await assert.rejects(x.composer.compose(r));assert.equal(x.calls.length,1);});
test('uncertain intent blocks call; uncertain usage blocks proposal; neither retries',async()=>{for(const denied of ['STARTED','USAGE_RECORDED']){const x=native(),r={...request(),recordPass:async p=>{if(p.status===denied)throw Error('uncertain durable commit');}};await assert.rejects(x.composer.compose(r));await assert.rejects(x.composer.compose(r));assert.equal(x.calls.length,denied==='STARTED'?0:1);}});
test('missing key/default-off/inadequate reserve/two-pass policy cannot activate',()=>{for(const mutate of [c=>delete c.loiOpenai.apiKey,c=>c.loiComposition.aiEnabled=false,c=>c.loiComposition.maxCostMicros=maxCostBound(4096)-1]){const c=configuration();mutate(c);assert.equal(createNativeLoiProseComposer(c,{fetchImpl:()=>assert.fail('no call')}),null);}const x=native();assert.equal(providerAvailable(x.c,{...x.composer,policy:{...x.composer.policy,providerPasses:2}},canary),false);});
test('shared aggregate guard fails closed for missing function or exhausted total; exact approved canary evidence pin remains fixed',async()=>{assert.deepEqual(APPROVED_LOI_EVIDENCE_PINS,['eb1d9718ce6cf52cc9f4f6de452ab3aac35655470a18a3a6757b9508922ffcd0']);const c=configuration().loiComposition;assert.equal((await lifetimeAllowance({query:async()=>({rows:[{available:false}]})},canary,c)).allowed,false);let n=0;assert.equal((await lifetimeAllowance({query:async()=>({rows:[++n===1?{available:true}:{allowance:{allowed:false,reason:'SHARED_LIFETIME_LIMIT'}}]})},canary,c)).allowed,false);});
test('usage cannot hide a second call, lower known spend or rename writer as verifier',async()=>{const x=native(),out=await x.composer.compose(request());for(const mutate of [u=>u.passes.push(structuredClone(u.passes[0])),u=>u.costMicros--,u=>u.passes[0].stage='VERIFIER']){const u=structuredClone(out.usage);mutate(u);assert.throws(()=>checkedUsage(u,x.c));}});

test('full authored paraphrases need no finite framing phrases and remain explicitly uncertified',()=>{const input=proseFixture(),out=validateSingleCallPlans(singleOutput(input),input),r=out[0];assert.ok(!r.text.includes(input.refs.find(x=>x.kind==='evidence').text));assert.equal(r.review.state,'STUDENT_VERIFICATION_REQUIRED');assert.equal(r.review.automaticFactualCertification,false);assert.ok(r.review.units.every(x=>x.flag==='UNRESOLVED_SEMANTIC_SUPPORT'));});

test('actual single native writer request accepts original full prose beyond literal paragraphs or finite phrases',async()=>{const {AUTHORED_SCHEMA,proseUnits}=await import('../../server/loi-prose-contract.mjs');const x=native({author:input=>{const paragraphs=[['Dear Program Leadership,',[]],[`${input.program.name} is receiving this follow-up on my application.`,['program','context:whyNow']],['I have applied to your program.',['context:applicationState']],['I have not interviewed at this program.',['context:interviewState']],['Continuity with underserved patients guides the kind of outpatient care I hope to practice.',['reason:0','evidence:0']],['A weekly supervised clinic gives residents a recurring setting for continuity care.',['evidence:0']],['My community clinic volunteering last year gave that priority a personal setting.',['fact:0','reason:0']],['Thank you for considering my perspective.',[]]];let text='',bindings=[];for(const [part,refs]of paragraphs){if(text)text+='\n\n';const start=text.length;text+=part;bindings.push({start,end:text.length,refs});}return {schema:AUTHORED_SCHEMA,candidates:[{approach:input.approaches[0],text,claims:proseUnits(text).map(u=>({start:u.start,end:u.end,refs:bindings.filter(b=>b.start<u.end&&b.end>u.start).flatMap(b=>b.refs)})),fitLinks:[{evidenceRef:'evidence:0',reasonRef:'reason:0'}]}]};}});const result=await x.composer.compose(request());assert.equal(x.calls.length,1);assert.equal(result.usage.passes.length,1);const row=validateSingleCallPlans(result.output,proseFixture())[0];assert.ok(row.text.includes('recurring setting for continuity care'));assert.equal(row.review.automaticFactualCertification,false);assert.equal(row.review.studentVerificationRequired,true);});
