import {authoredOutput} from '../helpers/loi-authored.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {randomUUID} from 'node:crypto';
import * as v from '../../server/validation.mjs';import {requireValue,notFound} from '../../server/errors.mjs';import * as openai from '../../server/loi-openai.mjs';import * as contracts from '../../server/loi-prose-contract.mjs';import * as composition from '../../server/loi-composition.mjs';import {qualifyLoiEvidence,loiEvidencePin} from '../../server/loi-evidence.mjs';import {configuration,native} from '../helpers/loi-single-provider.mjs';
// Execute the real reservation/claim/pass/result/replay orchestration. Only the
// private DB and subject/read methods are injected offline; transport is mock.
function engine({invalidTrace=false,failure=false,unknownResult=false,sharedAllowed=true,legacyReservation=false,noncanary=false,unpinned=false,unsupported=false}={}){
 const events=new Map(),requests=new Map(),a={id:noncanary?'22222222-2222-4222-8222-222222222222':openai.LOI_CANARY_OWNER,wpUserId:noncanary?2468:1397,role:'student',tier:'ivprep_complete',eligible:true},c=configuration();let revision=1,sharedReserve=0;const fresh={program:{id:'rise-test',name:'Test Program',track:'',registryReleaseId:'registry-test'},evidence:[{field:'research.curriculum',state:'SUPPORTED',claimRef:'rise-claim:'+'a'.repeat(64),value:'Residents attend a supervised continuity clinic each week.',retrievedAt:'2026-10-07T00:00:00.000Z',asOf:{kind:'current',label:'2026'},sources:[{claimRef:'rise-claim:'+'b'.repeat(64),reviewRef:'rise-review:'+'c'.repeat(64),urls:['https://source.example.org/curriculum'],retrievedAt:'2026-10-07T00:00:00.000Z',reviewedAt:'2026-10-07T00:00:00.000Z'}]}],evidenceDigest:'evidence',resultDigest:'result',coverageDigest:'coverage',observedAt:'2026-10-07T00:00:00.000Z'};c.loiComposition.evidencePins=unpinned?[]:[loiEvidencePin(fresh.program,fresh.evidence[0])];if(unsupported)fresh.evidence[0].state='UNSUPPORTED';
 const db={query:async(sql,args=[])=>{
  if(sql.includes('SELECT id,payload FROM iiq.outbox_events'))return {rows:events.has(args[2])?[events.get(args[2])]:[]};
  if(sql.startsWith('INSERT INTO iiq.outbox_events')){const payload=JSON.parse(args[3]);if(legacyReservation&&args[1]==='iiq.loi.generation.reserved')payload.proseContract=contracts.SINGLE_CALL_GUARD;if(args[1]==='iiq.loi.generation.result'&&unknownResult)throw Error('synthetic commit uncertainty');events.set(args[2],{id:randomUUID(),payload});if(args[1]==='iiq.loi.generation.reserved')sharedReserve+=payload.reservedCostMicros;return {rows:[{id:randomUUID()}]};}
  if(sql.includes('SELECT * FROM iiq.request_idempotency'))return {rows:requests.has(args[1])?[requests.get(args[1])]:[]};
  if(sql.startsWith('INSERT INTO iiq.request_idempotency'))requests.set(args[1],{request_digest:args[2],result_type:args[3],result_id:args[4]});
  if(sql.startsWith('INSERT INTO iiq.revisions'))revision=args[1];
  if(sql.includes('to_regprocedure'))return {rows:[{available:true}]};
  if(sql.includes('iiq.loi_budget_allowance'))return {rows:[{allowance:sharedAllowed?{allowed:true,contract:'iiq-loi-shared-budget-v1',capMicros:25000000,totalReservedMicros:sharedReserve}:{allowed:false,reason:'SHARED_LIFETIME_LIMIT'}}]};
  if(sql.includes('count(*)::int AS requests'))return {rows:[{requests:0,cost:'0'}]};
  return {rows:[]};
 }};const database={withActor:async(who,op)=>{assert.equal(who.id,a.id);return op(db);}},subject={id:'11111111-1111-4111-8111-111111111111',program_id:fresh.program.id},x=native({c,fail:failure,author:invalidTrace?input=>{const out=authoredOutput(input);out.candidates[0].claims[1].refs=['unknown-source'];return out;}:undefined});
 const imports={...openai,...contracts,...composition,qualifyLoiEvidence,randomUUID,v,requireValue,notFound,requireLoi:()=>{},loiEnabled:()=>true,readLoi:async()=>({current:null}),loiSubject:async()=>subject,evidenceFor:async()=>fresh,headCheck:()=>{},writeLoi:async()=>{throw Error('not a selection fixture');},revision:async()=>revision,syncActor:async()=>{}};
 const source=fs.readFileSync(new URL('../../server/loi-generation.mjs',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'');const execute=new Function(...Object.keys(imports),source+'\nreturn executeComposition;')(...Object.values(imports));
 const envelope={command:'loi.generate',interviewId:subject.id,requestId:randomUUID(),expectedVersion:1,bodyHash:'same-body',data:{letterId:null,expectedHead:null,expectedLetterVersion:0,context:{whyNow:'I am following up on my application.',applicationState:'I have applied to your program.',interviewState:'I have not interviewed at this program.'},contextConfirmed:true,motivations:[{id:randomUUID(),text:'I value longitudinal follow-up with underserved patients.',confirmed:true}],facts:[],selectedEvidence:[{field:fresh.evidence[0].field,claimRef:fresh.evidence[0].claimRef}],count:1,approach:'DIRECT_CONCISE'}};
 return {events,composer:x,c,run:()=>execute({database,actor:a,envelope,owners:{},config:c,proseComposer:x.composer,revalidateActor:async()=>a,bootstrap:async()=>({version:revision})}),reserved:()=>sharedReserve};
}
test('eligible noncanary AI flag on and unpinned supported evidence preserves deterministic drafting without provider or reserve',async()=>{const x=engine({noncanary:true,unpinned:true});const r=await x.run();assert.equal(r.generation.status,'STANDARD_FALLBACK');assert.equal(r.generation.reason,'AI_CANARY_SCOPE');assert.ok(r.generation.proposals.length);assert.equal(x.composer.calls.length,0);assert.equal(x.reserved(),0);assert.equal([...x.events.values()].filter(e=>e.payload.stage).length,0);});
test('paid canary unpinned supported evidence fails before reservation and provider',async()=>{const x=engine({unpinned:true});await assert.rejects(x.run(),e=>e.code==='loi_research_needed');assert.equal(x.events.size,0);assert.equal(x.composer.calls.length,0);assert.equal(x.reserved(),0);});
test('paid canary unsupported evidence remains denied with no provider or durable reservation',async()=>{const x=engine({unsupported:true});await assert.rejects(x.run(),e=>e.code==='loi_research_needed');assert.equal(x.events.size,0);assert.equal(x.composer.calls.length,0);assert.equal(x.reserved(),0);});
test('paid canary exact admitted evidence retains one writer pass and free replay',async()=>{const x=engine();const r=await x.run();assert.equal(r.generation.status,'PROPOSED');await x.run();assert.equal(x.composer.calls.length,1);assert.equal(x.reserved(),openai.maxCostBound(4096));assert.deepEqual([...x.events.values()].map(e=>e.payload).filter(e=>e.stage).map(e=>e.stage+':'+e.status),['AUTHOR:STARTED','AUTHOR:USAGE_RECORDED']);});

test('rejected authored trace persists safe diagnostic with deterministic fallback and free replay',async()=>{const x=engine({invalidTrace:true});const r=await x.run();assert.equal(r.generation.status,'STANDARD_FALLBACK');const result=[...x.events.values()].find(e=>e.payload.status==='STANDARD_FALLBACK').payload;assert.equal(result.diagnostic.code,'loi_composition_trace');assert.equal(result.diagnostic.stage,'PROSE_VALIDATION');assert.match(result.diagnostic.outputSha256,/^[a-f0-9]{64}$/);assert.deepEqual(Object.keys(result.diagnostic).sort(),['code','outputSha256','stage']);assert.equal(r.generation.diagnostic,undefined);await x.run();assert.equal(x.composer.calls.length,1);assert.equal(x.reserved(),openai.maxCostBound(4096));});
