import test from 'node:test';import assert from 'node:assert/strict';import{randomUUID}from'node:crypto';
import{loiHandoff,loiChecks,loiHistory,loiEnabled,loiCanonicalLookup,loiProgramAllowed,loiInterviewAllowed}from'../../server/private-commands.mjs';import{commandEnvelope}from'../../server/validation.mjs';import{readConfig}from'../../server/config.mjs';import{createCommands}from'../../server/commands.mjs';
test('LOI compose uses exact encoded approved bytes and no arbitrary origin/header',()=>{const text='Dear Program,\nMy reason: research & care <script> & é',r=loiHandoff({recipient:'a+b@hospital.edu',subject:'Interest & follow-up',text});const u=new URL(r.gmailUrl);assert.equal(u.origin,'https://mail.google.com');assert.equal(u.searchParams.get('body'),text);assert.equal(u.searchParams.get('su'),'Interest & follow-up');const m=new URL(r.mailtoUrl);assert.equal(m.searchParams.get('body'),text);for(const recipient of ['a@hospital.edu\r\nBcc:x@y.edu','Name <a@hospital.edu>','a@hospital.edu,b@hospital.edu','mailto:a@hospital.edu','a@hospital.edu?subject=x'])assert.throws(()=>loiHandoff({recipient,subject:'Interest',text}));assert.throws(()=>loiHandoff({recipient:'a@hospital.edu',subject:'Interest\nBcc:x',text}));});
test('long exact letter remains complete in explicit copy fallback',()=>{const text='É'.repeat(10000),r=loiHandoff({recipient:'a@hospital.edu',subject:'Interest',text});assert.equal(r.copyOnly,true);assert.equal(r.gmailUrl,null);assert.equal(r.mailtoUrl,null);assert.equal(r.text,text);});
test('limited checks need supported detail and confirmed reasons; no factual verification claim',()=>{const e={text:'Program P: I value research. Verified curriculum detail',program:{name:'Program P'},context:{whyNow:'After interview',applicationState:'Applied',interviewState:'Completed'},motivations:[{text:'I value research.',confirmed:true}],facts:[],evidence:[{value:'Verified curriculum detail'}],evidenceDigest:'a'.repeat(64),studentFactualConfirmation:true,studentSpecificityConfirmation:true};assert.deepEqual(loiChecks(e).reasons,[]);assert.equal(loiChecks({...e,text:'A generic unchanged letter'}).specificity,false);assert.equal(loiChecks({...e,motivations:[{text:'Invented',confirmed:false}]}).reasons.length>0,true);assert.equal(loiChecks({...e,studentFactualConfirmation:false}).reasons.length>0,true);});
test('history keeps approved bytes/future schema and marks retargeted binding historical',()=>{const row={id:randomUUID(),program_id:'p',program_name:'P',program_track:'Preliminary'},e={type:'iiq.loi.revision',schemaVersion:1,revisionId:randomUUID(),interviewId:row.id,program:{id:'p',name:'P',track:'Preliminary'},text:'Exact approved bytes',state:'approved'},future={type:'iiq.loi.revision',schemaVersion:2,text:'future private'};const anchors=[null,'legacy',e,future],copy=JSON.stringify(anchors),r=loiHistory(anchors,row);assert.equal(r.current.text,e.text);assert.equal(r.history[1].unavailable,true);assert.equal(r.history[1].text,undefined);assert.equal(r.currentBindingValid,true);assert.equal(loiHistory(anchors,{...row,program_track:'Categorical'}).currentBindingValid,false);assert.equal(JSON.stringify(anchors),copy);});
test('capability default OFF and signed singleton student gate; underscore envelope remains allowlisted',async()=>{assert.equal(readConfig({}).loi.enabled,false);const actor={id:randomUUID(),role:'student',tier:'360',eligible:true},config={coreOnly:true,loi:{enabled:true,ownerId:actor.id,programId:'p'}};assert.equal(loiEnabled(config,actor),true);assert.equal(loiEnabled(config,{...actor,role:'admin'}),false);assert.equal(loiEnabled(config,{...actor,id:randomUUID()}),false);const b={command:'loi.mark_sent',data:{},requestId:randomUUID(),expectedVersion:0};assert.equal(commandEnvelope(b).command,'loi.mark_sent');let calls=0;const c=createCommands({database:{withActor(){calls++;throw Error('must not reach DB');}},owners:{},config});await assert.rejects(c.execute(actor,{...b,command:'loi.not_allowed'}),{code:'coming_soon'});assert.equal(calls,0);assert.throws(()=>commandEnvelope({...b,ownerId:randomUUID()}),{code:'unexpected_fields'});});
test('explicit eligible configuration never broadens default CANARY or enables research dispatch',()=>{
 const env={INTERVIEWIQ_ENABLED:'true',INTERVIEWIQ_DATABASE_URL:'synthetic-test-only',INTERVIEWIQ_JWT_SECRET:'j'.repeat(32),INTERVIEWIQ_OWNER_PROOF_SECRET:'o'.repeat(32),INTERVIEWIQ_GATEWAY_SECRET:'g'.repeat(32),INTERVIEWIQ_RISE_ENABLED:'true',INTERVIEWIQ_RISE_REQUEST_SECRET:'r'.repeat(32),INTERVIEWIQ_LOI_ENABLED:'true'},owner=randomUUID();
 assert.equal(readConfig({}).loi.mode,'CANARY');assert.throws(()=>readConfig(env),{code:'invalid_configuration'});
 const canary=readConfig({...env,INTERVIEWIQ_LOI_OWNER_ID:owner,INTERVIEWIQ_LOI_PROGRAM_ID:'canonical-p'});assert.equal(canary.loi.mode,'CANARY');
 for(const overrides of [{INTERVIEWIQ_LOI_OWNER_ID:owner},{INTERVIEWIQ_LOI_PROGRAM_ID:'p'},{INTERVIEWIQ_LOI_MODE:'eligible'},{INTERVIEWIQ_LOI_MODE:'UNKNOWN'},{INTERVIEWIQ_LOI_MODE:'ELIGIBLE',INTERVIEWIQ_LOI_OWNER_ID:'invalid'},{INTERVIEWIQ_LOI_MODE:'ELIGIBLE',INTERVIEWIQ_LOI_PROGRAM_ID:'p / bad'},{INTERVIEWIQ_LOI_MODE:'ELIGIBLE',INTERVIEWIQ_RISE_ENABLED:'false'},{INTERVIEWIQ_LOI_MODE:'ELIGIBLE',INTERVIEWIQ_RISE_REQUEST_SECRET:''}])assert.throws(()=>readConfig({...env,...overrides}),{code:'invalid_configuration'});
 const eligible=readConfig({...env,INTERVIEWIQ_LOI_MODE:'ELIGIBLE'});assert.equal(eligible.coreOnly,true);assert.equal(eligible.loi.ownerId,'');assert.equal(eligible.loi.programId,'');assert.equal(eligible.deepResearch.enabled,false);assert.equal(eligible.researchProof.enabled,false);assert.equal(eligible.researchMissionsEnabled,false);assert.equal(eligible.rise.researchResultsEnabled,true);
 assert.equal(readConfig({INTERVIEWIQ_LOI_MODE:'ELIGIBLE'}).loi.enabled,false);
});
test('shared eligible predicates enforce owner AND program filters and retain canary-only scope',()=>{
 const a={id:randomUUID(),role:'student',tier:'360',eligible:true},b={...a,id:randomUUID(),tier:'ivprep_complete'},config={loi:{enabled:true,mode:'ELIGIBLE'}},row={owner_id:a.id,program_id:'canonical-p'};
 for(const actor of [a,b]){assert.equal(loiEnabled(config,actor),true);assert.equal(loiCanonicalLookup(config,actor),true);assert.equal(loiInterviewAllowed(config,actor,{...row,owner_id:actor.id}),true);}
 assert.equal(loiInterviewAllowed(config,b,row),false);assert.equal(loiInterviewAllowed(config,a,{...row,program_id:null}),false);
 for(const actor of [{...a,eligible:false},{...a,tier:'mission_residency'},{...a,role:'admin'},{...a,role:'mentor'}])assert.equal(loiCanonicalLookup(config,actor),false);
 const filtered={loi:{...config.loi,ownerId:a.id,programId:'canonical-p'}};assert.equal(loiInterviewAllowed(filtered,a,row),true);assert.equal(loiEnabled(filtered,b),false);assert.equal(loiProgramAllowed(filtered,a,'other-p'),false);
 for(const l of [{enabled:true},{enabled:true,ownerId:a.id},{enabled:true,programId:'canonical-p'},{enabled:true,mode:'invalid'}])assert.equal(loiEnabled({loi:l},a),false);
 const canary={loi:{enabled:true,ownerId:a.id,programId:'canonical-p'}};assert.equal(loiEnabled(canary,a),true);assert.equal(loiCanonicalLookup(canary,a),false);
});
test('eligible canonical-data exception cannot activate other core commands or configured-out programs',async()=>{
 const actor={id:randomUUID(),role:'student',tier:'360',eligible:true},config={coreOnly:true,loi:{enabled:true,mode:'ELIGIBLE',programId:'allowed'}},database={withActor(){throw Error('DB_ENTERED');}},commands=createCommands({database,owners:{},config});
 const envelope=(command,data)=>({command,data,requestId:randomUUID(),expectedVersion:0});
 for(const command of ['interview.create','interview.identity'])await assert.rejects(commands.execute(actor,envelope(command,{program:'allowed'})),/DB_ENTERED/);
 for(const [command,data] of [['interview.create',{program:'other'}],['interview.identity',{program:'other'}],['interview.schedule',{program:'allowed'}],['research.check',{}],['research.refresh',{}],['mission.create',{program:'allowed'}]])await assert.rejects(commands.execute(actor,envelope(command,data)),{code:'coming_soon'});
});
