import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHmac,createHash} from 'node:crypto';
import {createOwnerReadReceipts} from '../../server/owner-read-receipts.mjs';
import {createRiseResearchJobTransport} from '../../server/research-dispatch.mjs';
import {researchJobDigest} from '../../server/research-job-store.mjs';
const owner='c94abcfb-dfda-4c74-9a27-f58fcf56f9b2',program='rise_ps_1e3d2dbb-149a-57b2-8ea1-4431da0b42ab',sha=x=>createHash('sha256').update(x).digest('hex');
const actor=()=>({id:owner,wpUserId:1397,role:'student',tier:'ivprep_complete',eligible:true}),binding=()=>({requestId:randomUUID(),demandId:randomUUID(),interviewId:randomUUID(),ownerId:owner,programId:program,registryReleaseId:'rise_registry_acgme_2026-09-20_50d08ea6f2da'});
const request=trace=>({method:'POST',url:'/api/commands',headers:{'x-iiq-request-id':trace}});
async function execute({enabled=true,who=actor(),trace=randomUUID(),command='interview.create',rejectResponse=false}={}){const receipts=createOwnerReadReceipts({enabled}),b=binding(),secret='offline-transport-fixture-'.repeat(3),wire=[];const transport=createRiseResearchJobTransport({enabled:true,requestSecret:secret},{ownerReadReceipts:receipts,fetchImpl:async(url,init)=>{wire.push({url,init});const nonce=init.headers['X-MMED-IIQ-Job-Nonce'],timestamp=Number(init.headers['X-MMED-IIQ-Job-Timestamp']),payload=JSON.stringify({audience:'rise-interviewiq-research-job',nonce,request_sha256:researchJobDigest(b),...b,status:'QUEUED',jobId:randomUUID(),iat:timestamp,exp:timestamp+30,...(init.headers['X-MMED-IIQ-Job-Receipt']?{proofNonceSha256:sha('proof nonce'),proofRequestSha256:sha('proof raw json')}:{})});return new Response(JSON.stringify({payload,signature:rejectResponse?'0'.repeat(64):createHmac('sha256',secret).update('iiq-research-job-v1\nresponse\n'+payload).digest('hex')}),{headers:{'Content-Type':'application/json'}});}});const value=await receipts.run(who,request(trace),async()=>({receipt:await transport(b,researchJobDigest(b))}),command);return {value,wire,b,trace,receipts};}
test('verified real transport emits only exact signed POST/nonce/body hashes in synthetic v2',async()=>{const {value,wire,b,trace}=await execute(),r=value.ownerReadReceipts,q=r.jobRequests[0],init=wire[0].init;assert.equal(r.schema,'iiq-owner-read-receipts-v2');assert.equal(r.callerTrace,trace);assert.deepEqual(Object.keys(q).sort(),['bodySha256','issuer','method','nonceSha256','path','requestSha256']);const expected=['iiq-research-job-v2','request','rise-interviewiq-research-job',init.headers['X-MMED-IIQ-Job-Timestamp'],init.headers['X-MMED-IIQ-Job-Nonce'],'POST','/api/rise/v1/interviewiq/research-jobs',researchJobDigest(b)].join('\n');assert.equal(q.requestSha256,sha(expected));assert.equal(q.nonceSha256,sha(init.headers['X-MMED-IIQ-Job-Nonce']));assert.equal(q.bodySha256,researchJobDigest(b));assert.deepEqual(r.proofRequests,[{issuer:'rise-research-proof',nonceSha256:sha('proof nonce'),requestSha256:sha('proof raw json'),bodySha256:researchJobDigest(b),phase:'reserve'}]);assert.notEqual(q.requestSha256,q.bodySha256);const safe=JSON.stringify(r);assert.ok(!safe.includes(init.headers['X-MMED-IIQ-Job-Nonce']));assert.ok(!safe.includes('Signature')&&!safe.includes('verifier')&&!safe.includes('offline-transport-fixture'));});
test('unchanged research.check response still includes its actual unique POST',async()=>{const {value}=await execute({command:'research.check'});assert.equal(value.ownerReadReceipts.jobRequests.length,1);});
for(const [label,args]of [['defaultoff',{enabled:false}],['wrongactor',{who:{...actor(),id:randomUUID()}}],['wrongwp',{who:{...actor(),wpUserId:1}}],['wrongtrace',{trace:'bad'}]])test(label+' exposes no receipt',async()=>{const x=await execute(args);assert.equal(x.value.ownerReadReceipts,undefined);assert.equal(x.wire[0].init.headers['X-MMED-IIQ-Job-Receipt'],undefined);});
test('unverified response cannot emit any job receipt',async()=>{await assert.rejects(execute({rejectResponse:true}));});
test('GET v1 receipt shape remains unchanged and cannot carry a job POST',async()=>{const r=createOwnerReadReceipts({enabled:true}),a=actor(),trace=randomUUID();const out=await r.run(a,{method:'GET',url:'/api/bootstrap',headers:{'x-iiq-request-id':trace}},async()=>({ok:true}));assert.equal(out.ownerReadReceipts.schema,'iiq-owner-read-receipts-v1');assert.equal(Object.hasOwn(out.ownerReadReceipts,'jobRequests'),false);await assert.rejects(r.run(a,{method:'GET',url:'/api/bootstrap',headers:{'x-iiq-request-id':trace}},async()=>{r.recordJob(binding(),{nonceSha256:'a'.repeat(64),requestSha256:'b'.repeat(64),bodySha256:'c'.repeat(64),method:'POST',path:'/api/rise/v1/interviewiq/research-jobs'});}));});
