import {createRiseOwner} from '../../server/rise-owner.mjs';import {bindOwnerSession} from '../../server/owner-session.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {validateMediaInput,validateMediaDecision,mediaAuthority,assertMediaAuthority,publicMedia,mediaRoute,parseMediaJson} from '../../../rise/src/program-media.mjs';
import {projectOwnerMedia,attachProgramMedia} from '../../server/program-media-owner.mjs';
import {mediaInput,decision,session,NOW,PROGRAM,RELEASE} from '../fixtures/program-media.mjs';
const c={id:randomUUID(),payload:mediaInput()},d=decision('APPROVED').review,rev={state:'APPROVED',version:1};
const wire=()=>({schema:'rise-program-media-v1',programId:PROGRAM,registryReleaseId:RELEASE,observedAt:new Date(NOW).toISOString(),media:publicMedia(c,{state:'APPROVED',review:d},rev,NOW)}),program={id:PROGRAM,registryReleaseId:RELEASE};
test('existing candidate schema reused; historical conflict and source/asset/checksum/rights attribution retained',()=>{const x=validateMediaInput(mediaInput(),NOW);assert.equal(x.candidate.approvalState,'CANDIDATE');assert.notEqual(x.provenance.pageReportedDate,x.provenance.exifReportedDate);assert.ok(wire().media.caption.includes('Historical photograph; source dates differ.'));const h=projectOwnerMedia(wire(),program,NOW);assert.equal(h.url,c.payload.candidate.assetRef);assert.equal(h.licenseUrl,c.payload.provenance.licenseUrl);assert.equal(h.assetSha256,c.payload.provenance.assetSha256);assert.equal(h.notes,undefined);assert.equal(h.created_by,undefined);});
for(const [label,change]of Object.entries({autoapproval:x=>x.candidate.approvalState='APPROVED',arbitraryAsset:x=>x.candidate.assetRef='https://other-hospital.org/photo.jpg',svg:x=>x.candidate.assetRef=x.candidate.assetRef.replace('JPG','svg'),redirectQuery:x=>x.candidate.assetRef+='?url=https://127.0.0.1',sourcePrivate:x=>x.candidate.sourceUrl='https://127.0.0.1/photo',credentials:x=>x.candidate.assetRef='https://u:p@upload.wikimedia.org/wikipedia/commons/3/39/UIC.JPG',missingConflict:x=>x.provenance.dateConflict='',noChecksum:x=>x.provenance.assetSha256='',unknownPrivateKey:x=>x.provenance.studentName='PRIVATE'}))test('candidate rejects '+label,()=>{const x=mediaInput();change(x);assert.throws(()=>validateMediaInput(x,NOW));});
test('approval requires all explicit reviewed attestations; grant cannot be forged or preview/demoted',()=>{const x=decision('APPROVED');x.review.explicitHumanApproval=false;assert.throws(()=>validateMediaDecision(x,NOW));for(const s of [session('student'),{...session(),preview:true},{...session(),expiresAt:new Date(NOW-1).toISOString()}])assert.throws(()=>mediaAuthority(s,NOW));assert.throws(()=>assertMediaAuthority({actor:'forged',expiresAt:NOW+10000},NOW));});
for(const [label,change]of Object.entries({wrongProgram:x=>x.media.programId='rise_other',unapproved:x=>x.media.approvalState='CANDIDATE',wrongCategory:x=>x.media.category='CAMPUS',notPermitted:x=>x.media.licenseState='NOT_PERMITTED',expired:x=>x.media.validThrough=new Date(NOW-1).toISOString(),wrongRelease:x=>x.registryReleaseId='old-release',stale:x=>x.observedAt=new Date(NOW-300001).toISOString(),arbitraryURL:x=>x.media.url='https://unrelated.org/image.jpg'}))test('IIQ approved projection rejects '+label,()=>{const x=wire();change(x);assert.throws(()=>projectOwnerMedia(x,program,NOW));});
test('retracted/expired read yields null and default-off hydrator makes zero calls; failed owner read leaves fallback',async()=>{assert.equal(publicMedia(c,{state:'APPROVED',review:d},{state:'WITHDRAWN',version:2},NOW),null);let calls=0;const state={},owners={getProgramMedia:async()=>{calls++;throw Error('failure');}};await attachProgramMedia({state,actor:{eligible:true,role:'student'},config:{},owners,programIds:[PROGRAM]});assert.equal(calls,0);await attachProgramMedia({state,actor:{eligible:true,role:'student'},config:{programMediaEnabled:true,rise:{programMediaEnabled:true}},owners,programIds:[PROGRAM]});assert.equal(calls,1);assert.deepEqual(Object.keys(state.programMedia),[]);});
test('media-specific duplicate JSON keys reject and unavailable native handler does not invoke writes',async()=>{assert.throws(()=>parseMediaJson(Buffer.from('{"state":"CANDIDATE","state":"APPROVED"}')));const r=await mediaRoute({method:'POST'},new URL('https://synthetic.test/api/rise/v1/operator/program-media/candidates'),{session:session(),store:{enabled:false}});assert.equal(r.status,503);});

test('real IIQ owner adapter uses existing signed pinned detail read and returns minimized exact hero',async()=>{const actor=Object.freeze({id:randomUUID(),wpUserId:900001,role:'student',tier:'360',eligible:true});bindOwnerSession(actor,{verifier:'f'.repeat(64),expiresAt:NOW+60000});let calls=0;const owner=createRiseOwner({enabled:true,programMediaEnabled:true,requestSecret:'synthetic-media-read-'.repeat(3)},{now:()=>NOW,fetchImpl:async(url,o)=>{calls++;assert.equal(new URL(url).origin,'https://missionmed-rise-production.up.railway.app');assert.ok(new URL(url).pathname.endsWith('/'+PROGRAM));assert.equal(o.method,'GET');assert.equal(o.redirect,'error');assert.equal(o.headers.Cookie,undefined);assert.ok(o.headers['X-MMED-IIQ-Signature']);return new Response(JSON.stringify({id:PROGRAM,name:'SYNTHETIC media program',track:'Categorical',registryReleaseId:RELEASE,programMedia:wire()}),{headers:{'Content-Type':'application/json'}});}});assert.equal((await owner.getProgramMedia(actor,PROGRAM)).programId,PROGRAM);assert.equal(calls,1);});
