import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {THREEBOX_CATEGORIES,THREEBOX_TEACHING,threeboxEnabled,normalizeReasons,checkThreebox,assembleThreebox,threeboxHistory} from '../../server/threebox.mjs';
import {readConfig} from '../../server/config.mjs';
import {digest} from '../../server/validation.mjs';
const program={id:'synthetic-p',name:'SYNTHETIC River Program',track:'Categorical',registryReleaseId:'r1'},fact={field:'research.curriculum',claimRef:'rise-claim:'+'a'.repeat(64),state:'SUPPORTED',value:'The published schedule includes continuity clinic at River Hospital.',selectionHash:'b'.repeat(64)};
const reason=(overrides={})=>({id:randomUUID(),general:{category:'Didactics'},details:[{field:fact.field,claimRef:fact.claimRef,selectionHash:fact.selectionHash}],personal:{enabled:false,text:'',confirmed:false},selected:true,rank:1,followUpDefense:'I would ask how the River Hospital clinic is supervised.',intel:[],...overrides});
const review={factualConfirmed:true,specificityConfirmed:true};
test('feature defaults off and allows only an eligible explicitly scoped student',()=>{assert.equal(readConfig({}).threebox.enabled,false);const c={threebox:{enabled:true,ownerId:'a'}},a={id:'a',role:'student',tier:'360',eligible:true};assert.equal(threeboxEnabled(c,a),true);for(const x of [{id:'b'},{role:'admin'},{role:'mentor'},{tier:'mission_residency'},{eligible:false}])assert.equal(threeboxEnabled(c,{...a,...x}),false);assert.equal(threeboxEnabled({threebox:{enabled:false}},a),false);});
test('teaching defines actual categories with no forced personal story',()=>{assert.match(THREEBOX_TEACHING,/2025-2026/);assert.ok(THREEBOX_CATEGORIES.includes('Resident feedback'));const r=normalizeReasons([reason()]);assert.equal(r[0].personal.enabled,false);assert.equal(checkThreebox(r,[fact],review).ready,true);});
test('each selected General needs reviewed supported concrete evidence',()=>{for(const r of [reason({details:[]}),reason({details:[{field:fact.field,claimRef:fact.claimRef,selectionHash:'c'.repeat(64)}]})])assert.equal(checkThreebox([r],[fact],review).ready,false);for(const state of ['STALE','UNKNOWN','CONFLICTED','WEAK'])assert.equal(checkThreebox([reason()],[{...fact,state}],review).ready,false);});
test('personal words require exact student confirmation only when enabled',()=>{for(const personal of [{enabled:true,text:'I want continuity experience.',confirmed:false},{enabled:true,text:'',confirmed:false}])assert.equal(checkThreebox([reason({personal})],[fact],review).ready,false);assert.equal(checkThreebox([reason({personal:{enabled:true,text:'I want continuity experience.',confirmed:true}})],[fact],review).ready,true);assert.throws(()=>normalizeReasons([reason({personal:{enabled:false,text:'I rotated here.',confirmed:true}})]),{code:'threebox_personal_confirmation'});});
test('rank collisions and client-supplied evidence value or verified status are refused',()=>{assert.throws(()=>normalizeReasons([reason(),reason()]),{code:'threebox_duplicate_rank'});assert.throws(()=>normalizeReasons([reason({details:[{field:fact.field,claimRef:fact.claimRef,selectionHash:fact.selectionHash,value:'Invented'}]})]),{code:'unexpected_fields'});assert.throws(()=>normalizeReasons([reason({personal:{enabled:true,text:'X',confirmed:true,fromCV:true}})]),{code:'unexpected_fields'});});
test('missing follow-up support, location placement and about-three guidance are actionable warnings',()=>{const r=reason({general:{category:'Location'},followUpDefense:''}),s=reason({rank:2});const c=checkThreebox([r,s],[fact],review);assert.ok(c.warnings.some(x=>x.includes('Location usually')));assert.ok(c.warnings.some(x=>x.includes('authenticity risk')));assert.ok(c.warnings.some(x=>x.includes('about three')));assert.ok(!checkThreebox([r,s],[fact],{...review,locationException:true}).warnings.some(x=>x.includes('Location usually')));});
test('program name alone or an unconfirmed specificity/factual gate cannot pass',()=>{for(const confirmations of [{},{factualConfirmed:true},{specificityConfirmed:true}])assert.equal(checkThreebox([reason()],[fact],confirmations).ready,false);assert.equal(checkThreebox([reason({details:[]})],[fact],review).ready,false);});
test('assembly preserves supported detail, optional personal meaning and three delivery forms',()=>{const r=reason({personal:{enabled:true,text:'I want to build continuity skills.',confirmed:true}}),a=assembleThreebox(program,[r],[fact]);for(const key of ['standard','concise','bullets']){assert.match(a[key],/River Hospital/);assert.match(a[key],/continuity skills/);}assert.match(a.standard,/SYNTHETIC River Program/);assert.match(a.bullets,/Didactics →/);assert.doesNotMatch(a.standard,/rotated|family|cardiology|board pass/);});
test('delivery adaptations change depth/order without inventing evidence',()=>{const second={...fact,field:'research.research_opportunities',claimRef:'rise-claim:'+'c'.repeat(64),value:'Dr Example leads the published continuity study.'},r=reason(),q=reason({rank:2,general:{category:'Research'},details:[{field:second.field,claimRef:second.claimRef,selectionHash:second.selectionHash}]});const a=assembleThreebox(program,[r,q],[fact,second],'RESEARCH');assert.ok(a.standard.indexOf('Research:')<a.standard.indexOf('Didactics:'));assert.match(a.standard,/Dr Example/);});
test('live intel stays a different private source class and never enters assembled factual prose',()=>{const r=normalizeReasons([reason({intel:[{id:randomUUID(),speaker:'Resident',role:'PGY2',text:'SYNTHETIC unverified new research clinic',confirmed:true}]})])[0];assert.equal(r.intel[0].verification,'NEEDS_VERIFICATION');assert.match(checkThreebox([r],[fact],review).warnings.join(' '),/not verified program Details/);assert.doesNotMatch(assembleThreebox(program,[r],[fact]).standard,/unverified new/);});
test('history preserves old prose and LOI entries, marks legacy divergence and future schema',()=>{const row={id:'i1',program_id:program.id,program_name:program.name,program_track:program.track},e={type:'iiq.threebox.revision',schemaVersion:1,revisionId:'v1',answerVersion:1,interviewId:'i1',program,reasons:[],answers:{},state:'assembled',contentHash:digest('Current')},anchors=[null,{type:'iiq.loi.revision',text:'PRIVATE LOI'},e];assert.equal(threeboxHistory({anchors,why_program:'Current'},row).threebox.ready,true);const p=threeboxHistory({anchors,why_program:'Older client edit'},row);assert.equal(p.text,'Older client edit');assert.equal(p.threebox.manualEdit,true);assert.equal(p.threebox.ready,false);assert.equal(p.threebox.history.length,1);assert.equal(anchors[1].text,'PRIVATE LOI');assert.equal(threeboxHistory({anchors:[...anchors,{type:'iiq.threebox.revision',schemaVersion:99}]},row).threebox.futureSchema,true);assert.equal(threeboxHistory(null,row).text,'');assert.equal(threeboxHistory({anchors,why_program:'Current'},{...row,program_id:'changed'}).threebox.ready,false);});

test('supported generic praise cannot pass just by confirming the specificity checkbox',()=>{assert.equal(checkThreebox([reason()],[{...fact,value:'excellent didactics fellowship opportunities research diverse patient population family atmosphere'}],review).ready,false);assert.match(checkThreebox([reason()],[{...fact,value:'great didactics'}],review).errors.join(' '),/generic praise/);assert.equal(checkThreebox([reason()],[{...fact,value:'Chicago'}],review).ready,true);});

test('malformed typed history is retained as unavailable and cannot crash private read projection',()=>{const p=threeboxHistory({anchors:[{type:'iiq.threebox.revision',schemaVersion:1}],why_program:'Keep original'}, {id:'i'});assert.equal(p.text,'Keep original');assert.equal(p.threebox.current,null);assert.equal(p.threebox.futureSchema,true);assert.equal(p.threebox.history[0].unavailable,true);});

test('enabled Three-Box config qualifies the existing RISE results seam without enabling LOI or preparation',()=>{const c=readConfig({INTERVIEWIQ_ENABLED:'true',INTERVIEWIQ_DATABASE_URL:'postgresql://synthetic@localhost/synthetic',INTERVIEWIQ_JWT_SECRET:'a'.repeat(40),INTERVIEWIQ_OWNER_PROOF_SECRET:'b'.repeat(40),INTERVIEWIQ_GATEWAY_SECRET:'c'.repeat(40),INTERVIEWIQ_RISE_ENABLED:'true',INTERVIEWIQ_RISE_REQUEST_SECRET:'d'.repeat(40),INTERVIEWIQ_THREEBOX_ENABLED:'true'});assert.equal(c.threebox.enabled,true);assert.equal(c.rise.researchResultsEnabled,true);assert.equal(c.coreOnly,true);assert.equal(c.loi.enabled,false);});
