/* MR-WEB-0912 commerce truth + MR-WEB-0914 Fable 5 CRO closure. */
(function(){
  'use strict';
  var main=document.getElementById('main');
  var page=window.MM_MR_PAGE||new URLSearchParams(location.search).get('view')||'mission-residency';
  var configUrl=window.MM_CONFIG_URL||'../config/campaign-state.json';
  function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);}
  function node(tag,cls,text){var e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
  function track(eventName,details){window.dataLayer=window.dataLayer||[];window.dataLayer.push(Object.assign({event:eventName,mission:'MR-WEB-0914-FABLE5-CRO-CLOSURE'},details||{}));}
  function section(cls,id){var s=node('section','section '+(cls||''));if(id)s.id=id;var w=node('div','wrap');s.appendChild(w);main.appendChild(s);return w;}
  function routeHref(href){return href.charAt(0)==='#'?location.pathname+location.search+href:href;}
  function anchor(host,href,label,cls){var a=node('a','btn '+(cls||'primary'),label);a.href=routeHref(href);host.appendChild(a);return a;}
  function button(host,offer,key,label){var runtime=offer.runtime||{};if(runtime.checkout_allowed&&runtime.checkout_url){var a=anchor(host,runtime.checkout_url,label,'primary');a.addEventListener('click',function(){track('mr_offer_cta_click',{offer:key,price:runtime.woo_price});});}else{var x=node('span','btn disabled','Enrollment is not currently available');x.setAttribute('aria-disabled','true');host.appendChild(x);}}
  function currentCompletePrice(cfg){var early=cfg.payment_options.early_card_paid_in_full||{};return early.public_verified&&typeof early.amount==='number'?early.amount:cfg.offers.complete.standard_price;}
  function hero(cfg,title,lede,facts,ctaOffer,ctaKey){var h=node('header','hero');var media=node('div','hero-media');var img=node('img');img.src=cfg.cro.assets.hero;img.alt='Mission Residency embroidered patch on a white coat';img.fetchPriority='high';img.decoding='async';media.appendChild(img);h.appendChild(media);var w=node('div','wrap');h.appendChild(w);w.appendChild(node('span','eyebrow','Mission Residency · Fall 2026'));w.appendChild(node('h1','',title));w.appendChild(node('p','lede',lede));var f=node('div','facts');facts.forEach(function(v){f.appendChild(node('span','fact',v));});w.appendChild(f);var actions=node('div','actions');if(ctaOffer)button(actions,ctaOffer,ctaKey,ctaKey==='complete'?'Enroll in Complete':'Enroll in Interview Week');else anchor(actions,'#programs','Choose your path','primary');anchor(actions,page==='mission-residency'?'#method':'/mission-residency/#method','See how training works','secondary');w.appendChild(actions);var strip=node('div','proof-strip');var faces=node('div','proof-faces');cfg.cro.testimonials.slice(0,5).forEach(function(t){var face=node('img');face.src=t.poster;face.alt='';face.loading='lazy';face.decoding='async';faces.appendChild(face);});strip.appendChild(faces);strip.appendChild(node('p','','Real MissionMed students, shown in already-published Match Day moments.'));w.appendChild(strip);main.appendChild(h);}
  function boutique(cfg){var w=section('navy','boutique');var split=node('div','split');var copy=node('div');copy.appendChild(node('span','eyebrow','The MissionMed difference'));copy.appendChild(node('h2','',cfg.cro.boutique.headline));copy.appendChild(node('p','section-intro',cfg.cro.boutique.body));split.appendChild(copy);var figure=node('figure','media-frame');var img=node('img');img.src=cfg.cro.assets.class;img.alt='A real MissionMed group mentorship session with students on a live video call';img.loading='lazy';img.decoding='async';figure.appendChild(img);var badge=node('figcaption','media-badge');badge.appendChild(node('b','','Live, mentor-led training'));badge.appendChild(node('span','','A real MissionMed group session'));figure.appendChild(badge);split.appendChild(figure);w.appendChild(split);}
  function needs(){var w=section('alt','start');w.appendChild(node('span','eyebrow','Start with your need'));w.appendChild(node('h2','','You should not need to learn our product names first.'));var g=node('div','need-grid');[['I need the live interview foundation','Choose Interview Week','#programs'],['I want support through interview season','Choose Complete','#programs'],['I want to see every difference','Open the detailed comparison','/mission-residency-courses/'],['I need the highest-touch model','See why 360 is closed','#mentorship-360']].forEach(function(x){var a=node('a','need');a.href=routeHref(x[2]);a.appendChild(node('b','',x[0]));a.appendChild(node('span','',x[1]+' →'));g.appendChild(a);});w.appendChild(g);}
  function method(cfg){var w=section('deep','method');w.appendChild(node('span','eyebrow','The Mission Residency method'));w.appendChild(node('h2','','Learn. Practice. Mock. Analyze. Remediate. Repeat.'));w.appendChild(node('p','section-intro','A repeatable system replaces improvisation with deliberate improvement.'));var g=node('div','method-grid');cfg.cro.method.forEach(function(x){var d=node('article','method-step');d.appendChild(node('h3','',x.title));d.appendChild(node('p','',x.body));g.appendChild(d);});w.appendChild(g);}
  function journey(cfg){var w=section('dark','season');w.appendChild(node('span','eyebrow','Your interview-season journey'));w.appendChild(node('h2','','Strong preparation progresses in order.'));w.appendChild(node('p','section-intro','Interview Week starts the foundation. Complete continues the improvement loop through interview season.'));var g=node('div','journey');cfg.cro.journey.forEach(function(x){var d=node('article','journey-step');d.appendChild(node('h3','',x.title));d.appendChild(node('p','',x.body));g.appendChild(d);});w.appendChild(g);}
  function videos(cfg,limit){var w=section('deep','proof');w.appendChild(node('span','eyebrow','Match Day · already published by MissionMed'));w.appendChild(node('h2','','Hear the moment in their own words.'));w.appendChild(node('p','section-intro','Nothing plays automatically. Choose a video when you are ready.'));var g=node('div','video-grid');cfg.cro.testimonials.slice(0,limit||8).forEach(function(t){var fig=node('figure','video-card');var media=node('div','video-media');var poster=node('img');poster.src=t.poster;poster.alt=t.name+' on Match Day';poster.loading='lazy';poster.decoding='async';media.appendChild(poster);var play=node('button','video-play','▶');play.type='button';play.setAttribute('aria-label','Play '+t.name+' Match Day video');media.appendChild(play);fig.appendChild(media);var cap=node('figcaption','video-caption');cap.appendChild(node('span','',t.tag));cap.appendChild(node('b','',t.name));cap.appendChild(node('p','','“'+t.quote+'”'));fig.appendChild(cap);play.addEventListener('click',function(){var v=node('video');v.controls=true;v.playsInline=true;v.preload='none';v.setAttribute('aria-label',t.name+' Match Day video');v.src=t.video;media.textContent='';media.appendChild(v);track('mr_proof_video_play',{student:t.name});v.play().catch(function(){});});g.appendChild(fig);});w.appendChild(g);}
  function listCard(cfg,offer,key,featured){var c=node('article','card'+(featured?' featured':''));c.appendChild(node('span','tag',featured?'Whole-season path':'Live kickoff'));c.appendChild(node('h3','',offer.name));c.appendChild(node('p','',offer.descriptor));var amount=key==='complete'?currentCompletePrice(cfg):offer.price;var p=node('div','price',money(amount));var priceLabel=key==='complete'&&amount!==offer.standard_price?'early card paid in full through September 23 · '+money(offer.standard_price)+' standard tuition':'one payment';p.appendChild(node('small','',priceLabel));c.appendChild(p);var ul=node('ul','clean');(offer.includes||offer.benefits||[]).forEach(function(x){ul.appendChild(node('li','',x));});c.appendChild(ul);if(key==='interview_week')c.appendChild(node('div','note','No individual Signature Mock Interview is included. Complete students do not buy Interview Week separately.'));if(key==='complete')c.appendChild(node('div','note','Interview Week is included. It is not an additional $500. Your enrollment confirmation supplies the approved placement and Signature Mock details.'));var a=node('div','actions');button(a,offer,key,key==='complete'?'Enroll in Complete':'Enroll in Interview Week');c.appendChild(a);return c;}
  function choice(cfg){var w=section('alt','programs');w.appendChild(node('span','eyebrow','Two open card paths'));w.appendChild(node('h2','','Train first—or build the whole season around it.'));w.appendChild(node('p','section-intro','Interview Week is the $500 live kickoff. Complete includes Interview Week and continues the coaching, practice, and feedback. The two prices are never added together.'));var g=node('div','grid');g.appendChild(listCard(cfg,cfg.offers.interview_week,'interview_week',false));g.appendChild(listCard(cfg,cfg.offers.complete,'complete',true));w.appendChild(g);}
  function comparison(cfg){var w=section('','comparison');w.appendChild(node('span','eyebrow','Detailed comparison'));w.appendChild(node('h2','','See the boundary before you choose.'));var outer=node('div','comparison-wrap');var table=node('table','comparison');var thead=node('thead');var hr=node('tr');['','Interview Week','IV Prep Complete'].forEach(function(x){hr.appendChild(node('th','',x));});thead.appendChild(hr);table.appendChild(thead);var tbody=node('tbody');[['Current tuition',money(cfg.offers.interview_week.price),money(currentCompletePrice(cfg))+(currentCompletePrice(cfg)!==cfg.offers.complete.standard_price?' through September 23; '+money(cfg.offers.complete.standard_price)+' standard tuition':' standard tuition')],['Interview Week','This is Interview Week','Included—never an additional $500'],['Foundational live curriculum','Included','Included'],['Continued interview-season coaching','Not included','Included'],['Continued practice and personalized feedback','Not included','Included'],['Individual Signature Mock','Not included in tuition','Details confirmed with enrollment'],['Best fit','You need the live foundation','You want the foundation plus continued support'],['Verified public payment rail','Stripe/card','Stripe/card']].forEach(function(row){var tr=node('tr');row.forEach(function(x,i){tr.appendChild(node(i===0?'th':'td','',x));});tbody.appendChild(tr);});table.appendChild(tbody);outer.appendChild(table);w.appendChild(outer);var actions=node('div','actions');anchor(actions,'/product/iv-prep-essentials/','View Interview Week','ink');anchor(actions,'/product/iv-prep-complete/','View Complete','ink');w.appendChild(actions);}
  function signature(cfg){var w=section('navy','signature-mock');w.appendChild(node('span','eyebrow','Signature Mock'));w.appendChild(node('h2','',cfg.cro.signature_mock.headline));w.appendChild(node('p','section-intro',cfg.cro.signature_mock.body));}
  function mentor(cfg){var w=section('alt','dr-brian');var split=node('div','split');var figure=node('figure','media-frame mentor-photo');var img=node('img');img.src=cfg.cro.assets.dr_brian;img.alt='Dr. Brian, founder and Match strategy mentor at MissionMed Institute';img.loading='lazy';img.decoding='async';figure.appendChild(img);split.appendChild(figure);var copy=node('div');copy.appendChild(node('span','eyebrow','Your mentor'));copy.appendChild(node('h2','',cfg.cro.mentor.headline));copy.appendChild(node('p','section-intro',cfg.cro.mentor.body));copy.appendChild(node('p','','Technology supports the training process; it does not replace the physician mentor.'));split.appendChild(copy);w.appendChild(split);}
  function closed360(cfg){var w=section('deep','mentorship-360');var box=node('div','closed-anchor');box.appendChild(node('span','closed-status',cfg.cro.closed_360.status));box.appendChild(node('h2','',cfg.cro.closed_360.name));box.appendChild(node('p','section-intro',cfg.cro.closed_360.body));box.appendChild(node('p','fine','For the two currently available interview-preparation paths, compare Interview Week and IV Prep Complete above.'));w.appendChild(box);}
  function expectations(cfg){var w=section('alt','after-enrollment');w.appendChild(node('span','eyebrow','After enrollment'));w.appendChild(node('h2','','Know what happens next.'));w.appendChild(node('p','section-intro','The checkout confirmation and your MissionMed account are the bridge into the approved program details.'));var g=node('div','expectation-grid');cfg.cro.post_enrollment.forEach(function(x){g.appendChild(node('div','expectation',x));});w.appendChild(g);}
  function schedule(cfg){var w=section('','schedule');w.appendChild(node('span','eyebrow','Live online · Eastern Time'));w.appendChild(node('h2','','Six dates. One training arc.'));w.appendChild(node('p','section-intro','Exact evening clock times will be published only after approval.'));var g=node('div','schedule');cfg.schedule.forEach(function(x){var c=node('article','slot');c.appendChild(node('b','',x.date+' · '+x.label));c.appendChild(node('span','',x.time));g.appendChild(c);});w.appendChild(g);}
  function curriculum(cfg){var w=section('alt','curriculum');w.appendChild(node('span','eyebrow','What you learn'));w.appendChild(node('h2','','A communication system, not canned answers.'));w.appendChild(node('p','section-intro',cfg.positioning.career_value));var g=node('div','need-grid');cfg.curriculum.forEach(function(x){var c=node('div','need');c.appendChild(node('b','',x));g.appendChild(c);});w.appendChild(g);}
  function faq(cfg){var w=section('','faq');w.appendChild(node('span','eyebrow','Straight answers'));w.appendChild(node('h2','','Questions applicants ask before choosing.'));var list=node('div','faq-list');cfg.cro.faq.forEach(function(x,i){var d=node('details');if(i===0)d.open=true;d.appendChild(node('summary','',x.question));d.appendChild(node('p','',x.answer));d.addEventListener('toggle',function(){if(d.open)track('mr_faq_open',{question:x.question});});list.appendChild(d);});w.appendChild(list);}
  function close(cfg){var w=section('navy','enroll');w.classList.add('narrow');w.appendChild(node('span','eyebrow','Choose with confidence'));w.appendChild(node('h2','','Start with the level of support you actually need.'));w.appendChild(node('p','section-intro','Interview Week teaches the live foundation. Complete includes Interview Week and stays with you through interview season.'));var actions=node('div','actions');button(actions,cfg.offers.complete,'complete','Enroll in Complete');anchor(actions,'/mission-residency-courses/','Compare both programs','secondary');w.appendChild(actions);}
  function home(cfg){hero(cfg,cfg.positioning.headline,'Physician-led residency interview preparation for applicants who want a framework, live practice, and feedback before programs see them.',['Interview Week · '+money(cfg.offers.interview_week.price),'Complete includes Interview Week','Live online']);boutique(cfg);needs();method(cfg);journey(cfg);videos(cfg,8);choice(cfg);comparison(cfg);signature(cfg);mentor(cfg);closed360(cfg);expectations(cfg);faq(cfg);close(cfg);}
  function interviewWeek(cfg){var o=cfg.offers.interview_week;hero(cfg,o.name,'The live interview-season kickoff: build the communication framework and practice it before your real interviews.',[money(o.price)+' · one card payment','Orientation + five training days','Complete students do not buy this separately'],o,'interview_week');curriculum(cfg);schedule(cfg);method(cfg);choice(cfg);comparison(cfg);expectations(cfg);videos(cfg,4);faq(cfg);close(cfg);}
  function complete(cfg){var o=cfg.offers.complete;hero(cfg,o.name,'Interview Week plus continued practice, personalized feedback, debrief, action planning, and coaching through interview season.',[money(currentCompletePrice(cfg))+(currentCompletePrice(cfg)!==o.standard_price?' early card PIF':' standard tuition'),money(o.standard_price)+' standard tuition','Interview Week included—never +$500'],o,'complete');journey(cfg);method(cfg);choice(cfg);comparison(cfg);signature(cfg);mentor(cfg);expectations(cfg);videos(cfg,4);faq(cfg);close(cfg);}
  function compare(cfg){hero(cfg,'Two clear ways to prepare.','Start with the live foundational kickoff, or choose the path that continues through interview season.',['No double purchase','Card checkout','Physician-led']);choice(cfg);comparison(cfg);signature(cfg);expectations(cfg);faq(cfg);close(cfg);}
  fetch(configUrl,{credentials:'same-origin',cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('config');return r.json();}).then(function(cfg){main.textContent='';if(page==='interview-week')interviewWeek(cfg);else if(page==='complete')complete(cfg);else if(page==='compare')compare(cfg);else home(cfg);track('mr_fable5_page_ready',{page:page});if(location.hash){var target=document.querySelector(location.hash);if(target)requestAnimationFrame(function(){target.scrollIntoView();});}}).catch(function(){main.innerHTML='<section class="section"><div class="wrap"><h1>Mission Residency is temporarily unavailable.</h1><p>Please contact Admissions before attempting enrollment.</p></div></section>';});
})();
