/* MR-WEB-0912 isolated release assets. */
(function(){
  'use strict';
  var main=document.getElementById('main');
  var page=window.MM_MR_PAGE||new URLSearchParams(location.search).get('view')||'mission-residency';
  var configUrl=window.MM_CONFIG_URL||'../config/campaign-state.json';
  function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);}
  function node(tag,cls,text){var e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
  function section(cls){var s=node('section','section '+(cls||''));var w=node('div','wrap');s.appendChild(w);main.appendChild(s);return w;}
  function button(host,offer,label){var runtime=offer.runtime||{};if(runtime.checkout_allowed&&runtime.checkout_url){var a=node('a','btn primary',label);a.href=runtime.checkout_url;host.appendChild(a);}else{var x=node('span','btn disabled','Enrollment is not currently available');x.setAttribute('aria-disabled','true');host.appendChild(x);}}
  function header(title,lede,facts){var h=node('header','hero');var w=node('div','wrap');h.appendChild(w);w.appendChild(node('span','eyebrow','Mission Residency · Fall 2026'));w.appendChild(node('h1','',title));w.appendChild(node('p','lede',lede));var f=node('div','facts');facts.forEach(function(v){f.appendChild(node('span','fact',v));});w.appendChild(f);main.appendChild(h);}
  function schedule(cfg){var w=section('alt');w.appendChild(node('span','eyebrow','Live online · Eastern Time'));w.appendChild(node('h2','','Six dates. One training arc.'));w.appendChild(node('p','section-intro','Exact evening clock times will be published only after approval.'));var g=node('div','schedule');cfg.schedule.forEach(function(x){var c=node('article','slot');c.appendChild(node('b','',x.date+' · '+x.label));c.appendChild(node('span','',x.time));g.appendChild(c);});w.appendChild(g);}
  function curriculum(cfg){var w=section('');w.appendChild(node('span','eyebrow','Train Before You Test'));w.appendChild(node('h2','','A communication system, not canned answers.'));w.appendChild(node('p','section-intro',cfg.positioning.career_value+' The same skills carry into patient care, teams, presentations, feedback, leadership, and future interviews.'));var g=node('div','curriculum');cfg.curriculum.forEach(function(x){g.appendChild(node('div','',x));});w.appendChild(g);}
  function listCard(cfg,offer,key,featured){var c=node('article','card'+(featured?' featured':''));c.appendChild(node('span','tag',featured?'Whole-season path':'Live kickoff'));c.appendChild(node('h3','',offer.name));c.appendChild(node('p','',offer.descriptor));var p=node('div','price',money(key==='complete'?offer.standard_price:offer.price));p.appendChild(node('small','',key==='complete'?' standard tuition':' one payment'));c.appendChild(p);if(key==='complete'){var early=cfg.payment_options.early_card_paid_in_full||{};if(early.public_verified&&typeof early.amount==='number')c.appendChild(node('p','status','Card paid in full: '+money(early.amount)+' through September 23.'));}var ul=node('ul','clean');(offer.includes||offer.benefits||[]).forEach(function(x){ul.appendChild(node('li','',x));});c.appendChild(ul);if(key==='interview_week')c.appendChild(node('div','note','No individual Signature Mock Interview is included. Complete students do not buy Interview Week separately.'));if(key==='complete')c.appendChild(node('div','note','Interview Week is included. Your enrollment confirmation will include group placement and Signature Mock details.'));var a=node('div','actions');button(a,offer,key==='complete'?'Enroll in Complete':'Enroll in Interview Week');c.appendChild(a);return c;}
  function choice(cfg){var w=section('dark');w.appendChild(node('span','eyebrow','Choose one path'));w.appendChild(node('h2','','Train first—or build the whole season around it.'));w.appendChild(node('p','section-intro','Complete includes Interview Week. The two prices are never added together.'));var g=node('div','grid');g.appendChild(listCard(cfg,cfg.offers.interview_week,'interview_week',false));g.appendChild(listCard(cfg,cfg.offers.complete,'complete',true));w.appendChild(g);}
  function faq(){var w=section('');w.appendChild(node('span','eyebrow','Straight answers'));w.appendChild(node('h2','','Frequently asked questions.'));[['Do I buy both programs?','No. IV Prep Complete includes Interview Week.'],['Does Interview Week include a mock interview?','No individual Signature Mock Interview is included in the $500 tuition. A limited standalone reservation opportunity may be offered separately.'],['Are the evening times final?','No exact evening clock time is published yet.'],['Is September the final training this season?','No. The next foundational training is anticipated around November 8, 2026.']].forEach(function(x){var d=node('details');d.appendChild(node('summary','',x[0]));d.appendChild(node('p','',x[1]));w.appendChild(d);});}
  function home(cfg){header(cfg.positioning.headline,'You can spend years earning residency interviews without ever being systematically taught how to perform in them.',['Interview Week · '+money(cfg.offers.interview_week.price),'Starts September 24','Live online']);var w=section('');w.appendChild(node('span','eyebrow',cfg.positioning.premise));w.appendChild(node('h2','','Practice the skill before the stakes are real.'));w.appendChild(node('p','section-intro','Mission Residency teaches how to communicate, build answers, read interview formats, research programs, and handle what happens during and after the conversation.'));schedule(cfg);curriculum(cfg);choice(cfg);faq();}
  function interviewWeek(cfg){var o=cfg.offers.interview_week;header(o.name,o.descriptor,[money(o.price)+' · one payment','Orientation + five training days','Live online']);schedule(cfg);curriculum(cfg);var w=section('dark');w.appendChild(node('span','eyebrow','What tuition includes'));w.appendChild(node('h2','','Focused foundational training.'));var g=node('div','grid');g.appendChild(listCard(cfg,o,'interview_week',true));var c=node('article','card');c.appendChild(node('h3','','Know the boundary.'));var ul=node('ul','clean');o.excludes.forEach(function(x){ul.appendChild(node('li','',x));});c.appendChild(ul);c.appendChild(node('div','note','Complete already includes Interview Week. Do not purchase both.'));g.appendChild(c);w.appendChild(g);faq();}
  function complete(cfg){var o=cfg.offers.complete;header(o.name,o.descriptor,[money(o.standard_price)+' standard tuition','Interview Week included','Full-season support']);var w=section('');w.appendChild(node('span','eyebrow','One complete path'));w.appendChild(node('h2','','Interview Week, then continued coaching.'));w.appendChild(node('p','section-intro','New Complete students begin with Interview Week. Continued practice, debrief, action planning, personalized feedback, and interview-season support follow.'));var g=node('div','grid');g.appendChild(listCard(cfg,o,'complete',true));var c=node('article','card');c.appendChild(node('h3','','Enrollment details'));c.appendChild(node('p','','Your enrollment confirmation will include group placement and Signature Mock details.'));c.appendChild(node('p','fine',cfg.campaign.next_foundation+'. September is not the final training opportunity of the season.'));g.appendChild(c);w.appendChild(g);faq();}
  function compare(cfg){header('Two clear ways to prepare.','Start with the live kickoff, or choose the full interview-season path.',['No double purchase','Live online','Physician-led']);var w=section('');w.appendChild(node('span','eyebrow','Simple comparison'));w.appendChild(node('h2','','Choose by the support you need.'));w.appendChild(node('p','compare-line','Interview Week: Train first. Decide what comes next.'));w.appendChild(node('p','compare-line','IV Prep Complete: Interview Week + the whole season around it.'));var g=node('div','grid');g.appendChild(listCard(cfg,cfg.offers.interview_week,'interview_week',false));g.appendChild(listCard(cfg,cfg.offers.complete,'complete',true));w.appendChild(g);}
  fetch(configUrl,{credentials:'same-origin',cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('config');return r.json();}).then(function(cfg){main.textContent='';if(page==='interview-week')interviewWeek(cfg);else if(page==='complete')complete(cfg);else if(page==='compare')compare(cfg);else home(cfg);}).catch(function(){main.innerHTML='<section class="section"><div class="wrap"><h1>Mission Residency is temporarily unavailable.</h1><p>Please contact Admissions before attempting enrollment.</p></div></section>';});
})();
