/* IR-0002: presentation and verified curation around the preserved Fable engine. */
CATALOG.online=RESEARCH.online;
CATALOG['in-person']=RESEARCH.inperson;
const allItems=()=>[...CATALOG.online,...CATALOG['in-person']].flatMap(c=>c.items);
const keyFor=(g,c,i)=>`${g}:${c.id}:${i.t}:${i.asin||'plan'}`;
for(const g of ['online','in-person'])CATALOG[g].forEach(c=>c.items.forEach(i=>i.key=keyFor(g,c,i)));
const external=(u,label,cls='')=>`<a class="${cls}" href="${esc(u)}" target="_blank" rel="${/^https:\/\/(www\.)?amazon\.com\//.test(u)?'noopener sponsored':'noopener noreferrer'}">${label} ↗</a>`;
const main=document.getElementById('main'); main.setAttribute('tabindex','-1');
document.querySelector('.skip').onclick=e=>{e.preventDefault();main.focus();};
document.querySelector('.topbar .title').innerHTML='<b>INTERVIEW READY</b><br><span style="font-size:8px;letter-spacing:.19em">LOOK PREPARED. FEEL CONFIDENT. DO MORE GOOD.</span>';
document.querySelector('.topbar .tag').innerHTML='GEAR TODAY.<br>A BRIGHTER TOMORROW.<i></i>';
document.getElementById('railnav').insertAdjacentHTML('afterbegin','<i class="nav-tracer" aria-hidden="true"></i>');
document.querySelector('.rail .kit').insertAdjacentHTML('beforeend','<div class="rail-progress"><i id="railProgress"></i></div><span class="rail-label" id="railReady">YOUR NEXT CHAPTER</span><p class="rail-purpose">Prepared people.<br>Brighter tomorrows.</p>');
document.body.insertAdjacentHTML('beforeend','<button class="motion-toggle" id="motionToggle" aria-pressed="false">Pause motion</button><div class="sr-status" role="status" id="saveStatus"></div>');
const announce=t=>document.getElementById('saveStatus').textContent=t;
document.getElementById('page-home').innerHTML=`
 <div class="guide-masthead">
  <a class="guide-brand" href="#home"><img src="img/mountain-mark.webp" alt="">MissionMed<small>HIGHER PURPOSE IN MEDICINE</small></a>
  <div class="guide-title">INTERVIEW GEAR GUIDE<small>LOOK PREPARED. FEEL CONFIDENT. DO MORE GOOD.</small></div>
  <p>GEAR TODAY. A BRIGHTER<br>TOMORROW FOR PATIENTS.</p>
 </div>
 <div class="board-hero">
  <div class="board-panel" data-parallax><img src="img/hero-online-photo.webp" alt="The supplied Interview Ready portrait: a smiling woman at an interview desk with microphone and camera.">
   <div class="hero-copy"><h1 tabindex="-1">Your Next Chapter<br>Starts Here.</h1><p>Expert-informed gear. Real interview scenarios.<br>A more confident you.</p><a class="btn gold" href="#online">EXPLORE THE GUIDE →</a></div>
  </div>
  <div class="board-panel travel" data-parallax><img src="img/hero-inperson-board.webp" alt="The supplied interview travel flatlay: carefully packed clothing, portfolio and travel essentials.">
   <div class="travel-title sr-only"><h2>From Packing<br>to Showing Up —<br>We’ve Got You.</h2><p>Real essentials. Real scenarios.<br>Real peace of mind.</p></div>
   <div class="travel-mask">Prepare. Present.<br>Belong.</div><a class="travel-action" href="#in-person">✈ INTERVIEW READY<br>ANYWHERE →</a>
  </div>
 </div>
 <div class="category-story reveal">
  <div class="tiles">${[
   ['online/webcam','camera','CAMERA','Look sharp. Be seen.'],['online/mic','microphone','MICROPHONE','Sound professional.'],
   ['online/light','lighting','LIGHTING','Look your best.'],['online/accessories','accessories','ACCESSORIES','The little things matter.'],
   ['in-person/luggage','travel','TRAVEL ESSENTIALS','Be ready anywhere.'],['in-person/emergency','emergency','EMERGENCY KIT','For the unexpected.']
  ].map(([u,img,n,s])=>`<a class="tile" href="#${u}" data-depth><img src="${ASSET['category-'+img+'.webp']}" alt="" loading="lazy"><div class="cap"><b>${n}</b><span>${s}</span></div></a>`).join('')}</div>
  <div class="purpose-mini"><img src="img/purpose-landscape.webp" alt="A physician looking toward a mountain landscape" loading="lazy"><p>Prepared<br>People Change<br>Patient Lives.</p></div>
 </div>
 <div class="home-editorial reveal">
  <div><div class="micro-heading">CHOOSE YOUR PATH</div><div class="micro-sub">ONE NEXT CHAPTER. FOUR WAYS TO PREPARE.</div>
   <div class="paths">${[
   ['online','01','Online Interview','Look sharp. Sound like yourself.'],['in-person','02','In-Person Essentials','Pack confidence for the journey.'],
   ['test','03','Test My Setup','Diagnose before you buy.'],['checklist','04','My Readiness Journey','A clear plan. Progress that stays.']
   ].map(([u,n,t,d])=>`<a class="path" href="#${u}" data-depth><div class="path-num">${n}<span class="arrow">→</span></div><b>${t}</b><span>${d}</span></a>`).join('')}</div>
  </div>
  <article class="featured-pick"><span class="eyebrow">AN EXPERT-INFORMED SHORTLIST</span><div class="feature-top"><div class="feature-symbol"><img src="img/product-facecam-mk2.webp" alt="Elgato Facecam MK.2, exact manufacturer press image"></div><div><h3>Elgato Facecam MK.2</h3><p>A repeatable Elgato camera path.<br>Set it up well. Then focus on your story.</p><a class="btn gold sm" href="#online/webcam">Compare cameras →</a></div></div>
   <div class="feature-bottom"><div><b>WHY IT MAKES THE SHORTLIST</b><p>Manual image controls. 1080p60.<br>Built for a considered desk setup.</p></div><div><b>WHAT TO KNOW</b><p>Owner-approved rating exception.<br>Fixed focus needs the right distance.</p></div></div><p class="research-note">Exact listing researched October 4, 2026 UTC. Read current buyer ratings on Amazon. ${external(RESEARCH.reviews.facecam.url,'EposVox’s exact-model review')}</p>
  </article>
 </div>
 <div class="home-footer reveal" data-parallax>
  <div class="trust-tile"><img src="{{DRBRIAN}}" alt="Dr. Brian" loading="lazy"><div><p>YOUR MISSIONMED MENTOR</p><b>Dr. Brian</b><p>Prepare. Present. Belong.</p></div></div>
  <a class="trust-tile" href="#test" style="text-decoration:none"><div><p>BEFORE YOU SHOP</p><b>Diagnose first.</b><p>Your existing gear may be enough.</p></div></a>
  <a class="trust-tile" href="#dress" style="text-decoration:none"><div><p>THE FINISHING DETAILS</p><b>Style Studio</b><p>Look prepared. Feel like yourself.</p></div></a>
  <div class="footer-script">Better Doctors.<br>A Kinder World.</div>
 </div><p class="disclosure" id="disclosure-home">${DISCLOSURE}</p>`;

const intros={
 online:['01','Your story.<br>Clearly seen.','An interview technology guide that starts with the gear you already own.','interview-portrait',''],
 'in-person':['02','Arrive prepared.<br>Stay composed.','From your front door to the program’s lobby: a considered packing plan.','travel-detail','travel'],
 test:['03','Welcome to your<br>interview studio.','See the frame. Hear your voice. Fix one thing at a time.','interview-portrait',''],
 checklist:['04','One next chapter.<br>A clear path there.','From a week before to the moment you join. Your progress stays on this device.','purpose-landscape','journey'],
 dress:['05','Dress with intention.<br>Show up as yourself.','A residency interview Style Studio: considered outfits, comfortable tailoring and finishing details.','style-portrait','fashion'],
 wardrobe:['06','Your visual closet.<br>Your day, decided.','Save, compare and choose a look. A calmer morning begins here.','travel-detail','travel'],
 community:['07','A shared eye<br>for the details.','Explore editorial outfit examples. Community sharing is not yet available.','style-portrait','fashion'],
 experts:['08','Listen. Watch.<br>Make a better choice.','Product-specific tests beside the gear they inform. Independent voices, clear context.','category-microphone',''],
 'prime-day':['09','Buy thoughtfully.<br>Timing comes second.','An evergreen shortlist to compare during a sale. No unverified deal claims.','travel-detail','travel'],
 kit:['10','Only what you need.<br>All in one place.','Your saved choices, with setup reminders and the original listing one click away.','travel-detail','travel']
};
for(const [id,[n,title,desc,img,cls]] of Object.entries(intros)){
 const p=document.getElementById('page-'+id);
 // Keep controls and their listeners; remove only old presentation text.
 const titleEl=p.querySelector('h2'); if(titleEl)titleEl.remove();
 const ey=p.querySelector('.eyebrow');if(ey)ey.remove();
 const lede=p.querySelector(':scope > .lede'); if(lede)lede.remove();
 p.insertAdjacentHTML('afterbegin',`<header class="route-intro ${cls}" data-parallax><img class="intro-image" src="${ASSET[img+'.webp']}" alt="" loading="lazy"><div class="intro-copy"><span class="eyebrow">MISSIONMED · ${esc(p.dataset.title)}</span><h1 tabindex="-1">${title}</h1><p>${desc}</p></div><span class="intro-number" aria-hidden="true">${n}</span></header>`);
}

const ecosystemText={
none:'Keep a good camera and mic. A free framing or lighting adjustment may be the whole upgrade.',
Elgato:'Keep Camera Hub, Control Center and Stream Deck in one familiar workflow. Lighting/mute plugins still need a rehearsal in your actual interview app. Wave Link is optional; avoid adding routing complexity you do not need.',
Logitech:'Brio + Litra Glow can keep video and light controls familiar. A webcam and light do not require a new audio ecosystem; keep a microphone that already passes.',
Sony:'Already own a Sony camera? Check its exact model’s USB streaming or clean HDMI guide. For ZV-E10 II, use an E-mount lens at a useful desk focal length, stable mount and reliable power; HDMI adds a capture card. Test focus, heat and power for the full session. This kit’s checked Amazon listing did not meet our default threshold.',
Canon:'Canon EOS R50 + RF-S 18–45mm is a qualified camera kit. Clean HDMI needs a micro-HDMI cable, capture card, mount and compatible continuous power. Check USB streaming separately. Keep a simple webcam ready as backup.',
Nikon:'If you own a Z30, use its 16–50mm lens, a stable mount and supported USB-C power. Nikon documents Webcam Utility and a capture-device route for optimal streaming. Confirm software/OS compatibility and test the full session. The checked new-purchase kit did not meet our threshold.',
Shure:'MV7+ can go straight to USB-C. SM7B needs an XLR interface and enough clean gain; a booster is conditional. SM7dB has a built-in powered preamp but still needs an interface. Avoid buying a studio chain for one interview.',
DJI:'Pocket 3 is relevant if you already own it for travel/content. Use USB webcam mode, a stable mount, reliable power and steady framing. Test or turn off distracting gimbal tracking; a wireless lavalier is not automatically a better desk microphone.'
};
function ecosystem(){const choice=store.get('ecosystem','none');return `<section class="ecosystem-strip reveal"><div><span class="eyebrow">STAY IN YOUR ECOSYSTEM</span><h2>Build on what you own.</h2><p>A better interview setup should feel more familiar, not more complicated.</p></div><div><div class="ecosystem-controls" role="group" aria-label="Equipment you already own">${Object.keys(ecosystemText).map(k=>`<button data-eco="${k}" aria-pressed="${choice===k}">${k==='none'?'Starting simple':k}</button>`).join('')}</div><div class="ecosystem-answer" role="status">${esc(ecosystemText[choice]||ecosystemText.none)}</div></div></section>`;}
function reviewBlock(i){if(!i.review)return '';const r=i.review;return `<div class="product-review"><span class="play-chip" aria-hidden="true">▶</span><div>${external(r.url,esc(r.title))}<small>${esc(r.by)} · independent review; no MissionMed endorsement</small>${r.video?`<button class="btn plain sm" data-preview="${r.video}" style="font-size:9px;margin-top:6px">Load YouTube preview</button>`:''}</div></div>`;}
function productVisual(i){return `<div class="product-visual">${i.image?`<img src="${i.image}" alt="${esc(i.name)}" loading="lazy">`:`<div class="product-wordmark">${esc((i.name||'').split(' ').slice(0,2).join(' '))}<small>${i.asin?'EXACT MODEL · RESEARCHED SELECTION':'USE WHAT YOU ALREADY OWN'}</small></div>`}${i.asin?external(i.source||amazonUrl(i),'See product photos','photo-link'):''}</div>`;}
tierCard=function(i,c,g){const t=tierOf(i.t);return `<article class="tier reveal ${c.pick===i.t?'pick':''}" aria-label="${esc(t.name)}: ${esc(i.name)}">${c.pick===i.t?'<span class="pickbadge">A considered starting point</span>':''}${productVisual(i)}<div class="product-content"><div class="lvl">${ico(t.icon)}<div><b>${t.name}</b><small>${t.sub}</small></div></div><h3>${esc(i.name)}</h3><p class="why"><b>Interview take.</b> ${esc(i.why)}</p><dl><dt>Best for</dt><dd>${esc(i.best)}</dd><dt>Setup / ecosystem</dt><dd>${esc(i.complexity)} · ${esc(i.ecosystem)}</dd>${i.up?`<dt>Moving up</dt><dd>${esc(i.up)}</dd>`:''}${i.down?`<dt>Keeping it simpler</dt><dd>${esc(i.down)}</dd>`:''}</dl><details class="more"><summary>Pros, cons & the complete setup</summary><b>Advantages</b><ul>${i.pros.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><b>Tradeoffs</b><ul>${i.cons.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p><b>Setup & compatibility:</b> ${esc(i.setup)}</p><p><b>What else / package:</b> ${esc(i.box)}</p>${i.source?external(i.source,'Manufacturer / source details'):''}</details>${i.exception?'<p class="product-status">Owner-approved Elgato exception · check current buyer feedback carefully.</p>':''}${reviewBlock(i)}<p class="verify">${i.asin?'Listing researched October 4, 2026 UTC. Current rating, price and availability are on Amazon.':'A preparation plan. No shopping required.'}</p><div class="actions">${i.asin?`<a class="btn gold sm" href="${amazonUrl(i)}" target="_blank" rel="noopener noreferrer${IR_CONFIG.affiliateTag?' sponsored':''}">View exact listing ↗</a>`:''}<button class="btn plain sm" data-kit="${esc(i.key)}" aria-pressed="${kit.has(i.key)}">${kit.has(i.key)?'Saved ✓':'Save to kit'}</button></div></div></article>`;};
renderCatalog=function(g){const cats=CATALOG[g];let cur=location.hash.split('/')[1];const c=cats.find(x=>x.id===cur)||cats[0];cur=c.id;
 const nav=document.getElementById('catnav-'+g);nav.setAttribute('role','group');nav.setAttribute('aria-label','Gear categories');
 nav.innerHTML=cats.map(x=>`<button data-cat="${x.id}" aria-pressed="${x.id===cur}">${esc(x.name)}</button>`).join('');
 nav.querySelectorAll('button').forEach(b=>b.onclick=()=>location.hash=`#${g}/${b.dataset.cat}`);
 const host=document.getElementById('catalog-'+g);host.innerHTML=(g==='online'?ecosystem():'')+`<div class="section-head"><div><span class="eyebrow">${g==='online'?'A CLEARER CONVERSATION':'A CALMER JOURNEY'}</span><h2 style="font-size:36px">${esc(c.name)}</h2><p class="lede" style="font-size:13px;max-width:65ch">${esc(c.intro)}</p></div></div><div class="comparison" tabindex="0" role="region" aria-label="Compare the three gear tiers"><table><caption class="sr-only">Three levels of value and complexity</caption><thead><tr><th scope="col">Level</th><th scope="col">Value philosophy</th><th scope="col">Complexity</th></tr></thead><tbody>${c.items.map(i=>`<tr><th scope="row">${tierOf(i.t).name}</th><td>${esc(i.best)}</td><td>${esc(i.complexity)}</td></tr>`).join('')}</tbody></table></div><div class="tiers">${c.items.map(i=>tierCard(i,c,g)).join('')}</div>`;
 if(g==='online'&&c.id==='webcam'){const i=RESEARCH.alternatives[0];i.key='online:webcam:fc:'+i.asin;host.insertAdjacentHTML('beforeend',`<div class="paper reveal"><span class="eyebrow">ALREADY OWN A DJI CAMERA?</span><h3>One camera. Two useful roles.</h3><p>${esc(i.why)}</p><p>${esc(i.setup)}</p>${reviewBlock(i)}${external(amazonUrl(i),'Pocket 3 exact listing','btn ghost sm')}</div>`);}
 const held=RESEARCH.held.filter(x=>g==='online'?!/Samsonite|Travelpro/.test(x.name):/Samsonite|Travelpro|Anker/.test(x.name));
 host.insertAdjacentHTML('beforeend',`<details class="held-research"><summary>Why some familiar products are absent</summary><p class="note">We did not qualify these exact listings at the October 3 check. A product can be useful to keep without being a default new purchase.</p><ul>${held.map(x=>`<li>${esc(x.name)} — ${esc(x.reason)}</li>`).join('')}</ul></details>`);
 nav.onkeydown=e=>{const bs=[...nav.querySelectorAll('button')];const n=bs.indexOf(document.activeElement);if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const to=e.key==='Home'?0:e.key==='End'?bs.length-1:(n+(e.key==='ArrowRight'?1:-1)+bs.length)%bs.length;bs[to].focus();}};
 bindEditorial(host);
};
renderKit=function(){const l=kit.list(),h=document.getElementById('kit');h.innerHTML=!l.length?`<div class="empty-state reveal"><span class="eyebrow">A SMALLER, SMARTER KIT</span><h3>Your best setup may already be yours.</h3><p>Test first. Save one considered upgrade or a preparation plan when it solves a real problem.</p><a class="btn gold" href="#test">Enter the studio →</a><a class="btn ghost" href="#online">Explore the guide →</a></div>`:`<div class="kit-list">${l.map(x=>{const i=allItems().find(i=>i.key===x.key&&i.name===x.name);return `<article class="kit-item reveal"><span class="pill">${esc(tierOf(x.tier)?.name||'Saved choice')}</span><h3>${esc(x.name)}</h3><p class="note">${esc(x.cat)} · ${i?'Current researched selection':'Saved from the earlier guide. Recheck the exact model before buying.'}</p>${i?`<p class="note">${esc(i.setup)}</p>`:''}<div class="actions">${i?.asin?external(amazonUrl(i),'Exact Amazon listing','btn gold sm'):''}<button class="btn plain sm" data-remove-kit="${esc(x.key)}">Remove</button></div></article>`}).join('')}</div><div class="paper"><h3>Rehearse the whole chain.</h3><p>Camera, cable, capture, power, software and sound all need to work together. The kit is a plan, not a requirement to purchase.</p><a class="btn ghost sm" href="#test">Check what you own →</a></div>`;bindEditorial(h);};
document.addEventListener('click',e=>{const b=e.target.closest('[data-remove-kit]');if(b){store.set('kit',kit.list().filter(x=>x.key!==b.dataset.removeKit));renderKitCount();renderKit();announce('Removed from your kit.');}});
const oldToggle=kit.toggle;kit.toggle=function(...args){oldToggle.apply(this,args);announce(this.has(args[0].key)?'Saved to your interview kit.':'Removed from your interview kit.');};
renderPrimeDay=function(){const picks=CATALOG.online.filter(c=>['webcam','mic','light','accessories'].includes(c.id)).map(c=>[c,c.items.find(i=>i.t===c.pick&&i.asin)||c.items.find(i=>i.asin)]);document.getElementById('primeday').innerHTML=`<div class="editorial-note">Sale labels and countdowns belong to verified offers. We have not verified a current deal for these products. Compare the exact model and total setup before buying.</div><div class="shopping-story">${picks.map(([c,i])=>tierCard(i,c,'online')).join('')}</div>`;bindEditorial(document.getElementById('primeday'));};

/* Preserve diagnostic measurements; improve interpretation and privacy lifecycle. */
if(store.get('autoVersion',1)!==2){store.set('auto',{});store.set('autoVersion',2);}
runEnv=function(){const out=document.getElementById('envResults');const online=navigator.onLine;const conn=navigator.connection||{};const rows=[
 [online?'ok':'bad','Browser connectivity',online?'The browser reports online. This does not test bandwidth, packet loss or the interview server.':'The browser reports offline. Reconnect before joining.'],
 ['warn','Actual platform rehearsal','Open the program’s app and test a call. Verify the exact browser/app version, permissions and account.'],
 ['warn','Notifications & backup','Enable Focus / Do Not Disturb yourself. Test your backup connection and keep the coordinator contact accessible.'],
 ['warn','Power','Plug in your laptop. Battery status is unavailable in some browsers.']];
 if(conn.effectiveType||conn.downlink)rows.push(['warn','Network estimate',`${conn.effectiveType||'Network'}${conn.downlink?' · estimated '+conn.downlink+' Mbps':''}. Browser estimate only; not a speed test.`]);
 const render=()=>{out.innerHTML=rows.map(r=>resultEl('e',...r)).join('');results.env={status:online?'pass':'fail',online};verdict();};render();
 if(navigator.getBattery)navigator.getBattery().then(b=>{rows[3]=[b.charging?'ok':'warn','Power',`${b.charging?'Plugged in':'Running on battery'} · ${Math.round(b.level*100)}%. Check the charger connection before the interview.`];render();}).catch(()=>{});
};document.getElementById('envRun').onclick=runEnv;
verdict=function(){const {cam:c,mic:m,env:e}=results;const tested=[c,m,e].filter(x=>x.status).length;if(!tested){const a=store.get('auto',{});if(a.setup||a.cam||a.mic||a.env){a.setup=a.cam=a.mic=a.env=false;store.set('auto',a);renderChecklist();}document.getElementById('verdict').innerHTML='<b>Measurement in progress.</b><p>Finish the camera, microphone and environment checks. Your previous result is being reassessed.</p>';return;}
 const allPass=[c,m,e].every(x=>x.status==='pass');const fail=[c,m,e].some(x=>x.status==='fail');const warnings=[c,m].some(x=>x.status==='warn');
 const steps=[];if(c.status==='fail'&&c.exposure==='bad')steps.push('Face a window or move a soft light in front of you.');else if(c.status==='fail')steps.push('Resolve camera access, then rerun the preview.');else if(c.status==='warn')steps.push('Adjust exposure, backlight or framing; rerun the camera check.');
 if(m.status==='fail'||m.status==='warn')steps.push(m.noiseLevel==='bad'?'Close the door and silence fans; record again before considering a microphone.':'Move closer, adjust input gain and keep a steady speaking distance.');
 if(e.status==='fail')steps.push('Reconnect to the network and rehearse your interview app.');
 document.getElementById('verdict').innerHTML=`<b>${allPass?'Your measured setup looks ready.':fail?'One step at a time.':warnings?'Working, with adjustments to make.':'Finish the remaining checks.'}</b><p>${tested}/3 check areas completed. These are browser measurements, not a certification of interview quality.</p>${allPass?'<p><b>You do not need to buy anything on the basis of these measurements.</b> Listen to playback, confirm your framing and rehearse your actual platform.</p>':steps.length?`<p><b>Your next free fix:</b> ${esc(steps[0])}</p>`:'<p>Run camera, microphone and environment checks to complete this review.</p>'}<p>Always check eye line, echo, power, notifications and your backup plan yourself.</p>`;
 const a=store.get('auto',{});const changed=a.setup!==allPass||a.cam!==(c.status==='pass')||a.mic!==(m.status==='pass')||a.env!==false;if(changed){a.setup=allPass;a.cam=c.status==='pass';a.mic=m.status==='pass';a.env=false;store.set('auto',a);store.set('autoAt',Date.now());renderChecklist();}
};
const testPage=document.getElementById('page-test');testPage.querySelector('#verdict').parentElement.className='studio-verdict';
testPage.querySelector('.test-grid').insertAdjacentHTML('beforebegin','<div class="privacy-line"><i></i><span>Camera and microphone stay in this browser. Start either test only when you are ready to grant access. No recording upload.</span></div>');
testPage.querySelector('#camResults').setAttribute('aria-live','polite');testPage.querySelector('#micResults').setAttribute('aria-live','polite');
testPage.querySelector('.test-grid').insertAdjacentHTML('afterend','<p class="note" style="font-size:11px;margin-top:15px">Camera exposure uses a fixed centre zone, not face detection. Mic consistency depends on speech, distance and room noise. Confirm the result with your eyes and local playback.</p>');
document.getElementById('verdict').innerHTML='Start with a camera preview, then listen to your voice and review the environment. Good equipment earns a recommendation to keep it.';
const oldStopMic=stopMic;stopMic=function(){oldStopMic();const a=document.getElementById('micPlayback');a.pause();if(a.getAttribute('src'))URL.revokeObjectURL(a.src);a.removeAttribute('src');a.style.display='none';};document.getElementById('micStop').onclick=stopMic;
const progressRow=document.getElementById('clProgress').parentElement.parentElement;progressRow.classList.add('journey-dashboard');progressRow.querySelector('.progress').setAttribute('role','progressbar');progressRow.querySelector('.progress').setAttribute('aria-label','Interview checklist completion');progressRow.querySelector('.progress').setAttribute('aria-valuemin','0');progressRow.querySelector('.progress').setAttribute('aria-valuemax','100');
const oldChecklist=renderChecklist;renderChecklist=function(){oldChecklist();const pct=document.getElementById('clPct').textContent;document.getElementById('railProgress').style.width=pct;document.getElementById('railReady').textContent=`${pct} OF YOUR ${mode==='online'?'ONLINE':'IN-PERSON'} JOURNEY`;progressRow.querySelector('.progress').setAttribute('aria-valuenow',parseInt(pct)||0);document.querySelectorAll('.auto').forEach(x=>x.textContent='✓ Measured in your latest setup test · confirm again before interview day');};

/* Style Studio: explicit choices, no body analysis and no third-party uploads. */
let styleFocus=store.get('styleFocus','women');let editingLook=null;
const styleGuides={
women:[['A considered silhouette','A matching trouser or skirt suit, or a tailored dress with a blazer, can form a clear interview outfit. Choose the shape you feel comfortable in.'],['Test it sitting down','Check neckline, hem coverage, jacket movement and sleeve length while seated. A fit alteration usually matters more than a designer label.'],['Finish for the whole day','Use comfortable polished shoes you can walk in. Keep jewelry and fabrics from creating glare or microphone noise. Religious dress belongs in the outfit you rehearse.']],
men:[['Start with a coherent suit','Navy or charcoal, a light shirt and a restrained tie is a conventional starting point. Follow the program’s dress instructions; an open collar may suit a less formal event.'],['Tailor the details','Check shoulders, collar, sleeve length and trouser break standing and seated. The jacket should close without pulling; shoes should already be broken in.'],['A quiet finishing layer','Coordinate belt and shoes if worn. Test tie patterns on camera, simplify shiny accessories and rehearse a comfortable all-day outfit.']],
any:[['The outfit is your choice','These are presentation options, not identity rules. Any silhouette is available in every studio view. Pick a professional outfit that feels comfortable and authentic.'],['Fit, movement and access','Check the outfit while seated, walking and using mobility or assistive devices. Clothing should support your day rather than distract you.'],['Rehearse the real context','Follow the program’s instructions. Check the full outfit in your camera light or a daylight mirror; bring layers appropriate to the trip.']]};
const dress=document.getElementById('page-dress');dress.querySelector('.look').className='style-editors';dress.querySelector('.style-editors > .card').className='look-preview';
dress.querySelector('.style-editors').insertAdjacentHTML('beforebegin','<div class="style-tabs" role="group" aria-label="Style guidance"><button data-style="women">Women’s studio</button><button data-style="men">Men’s studio</button><button data-style="any">Any presentation</button></div>');
dress.querySelector('#dressguide').className='style-fit-guide';dress.querySelector('#dressguide').parentElement.querySelector('h2').textContent='The details that make it yours.';dress.querySelector('#dressguide').parentElement.querySelector('.eyebrow').textContent='FIT · COMFORT · CONTEXT';
dress.insertAdjacentHTML('beforeend',`<section class="paper reveal"><span class="eyebrow">VIRTUAL TRY-ON · RESEARCHED PROVIDER</span><h2>See a look. Protect your photo.</h2><p>The colour planner above runs locally. It does not predict garment fit. Photorealistic virtual try-on is not available in this build.</p><p>We evaluated FASHN’s existing try-on model and API. A photo-based service needs an approved processing destination and a clear retention choice before it can accept your images.</p><details><summary>Read the provider and privacy research</summary><p>FASHN’s API processes images externally. Its documented request records are not deleted automatically; standard CDN outputs expire after three days. Base64 input and output reduce exposure, with their own retention periods. We have not connected an upload service.</p><p>${external('https://docs.fashn.ai/api-overview/data-retention-privacy','FASHN privacy details')} · ${external('https://github.com/fashn-AI/fashn-vton-1.5','Existing model and license')}</p></details></section>`);
figureSVG=function(l){const c=k=>PALETTE[l[k]]||'#263c49';const skirt=l.sil==='jacket-skirt',d=l.sil==='dress-blazer';const w=l.fit==='slim'?0:l.fit==='relaxed'?10:5;const x=52-w;
 return `<svg viewBox="0 0 200 340" role="img" aria-label="${esc(l.sil)} outfit colour plan"><defs><linearGradient id="fabric-${l.id||'current'}"><stop stop-color="${c('outer')}"/><stop offset=".55" stop-color="${c('outer')}"/><stop offset="1" stop-color="#111e29"/></linearGradient></defs><ellipse cx="100" cy="331" rx="60" ry="7" fill="#0003"/><path d="M85 67v19h30V67" fill="#d4b496"/><ellipse cx="100" cy="45" rx="21" ry="27" fill="#d9bca1"/><path d="M78 41q-2-28 23-27 26 2 22 32l-5-17-32 1z" fill="#363c40"/><path d="M${x} 89l31-9h34l${31+w} 9 10 133-${21+w} 3-7-111H72l-7 111-${21+w}-3z" fill="url(#fabric-${l.id||'current'})"/><path d="M77 83h46l-4 125H81z" fill="${c('top')}"/><path d="M${x+15} 87l19-7 14 49-19 58-19 24zM${185-x} 87l-19-7-14 49 19 58 19 24z" fill="${c('outer')}" stroke="#fff2" stroke-width=".8"/><path d="M89 79l11 8 11-8-5 17-6-9-6 9z" fill="${c('top')}" stroke="#5b6c761f"/>${l.accent!=='none'?`<path d="M97 88h6l3 61-6 10-6-10z" fill="${PALETTE[l.accent]}"/>`:''}<path d="M100 152v62" stroke="#ffffff1c"/><circle cx="103" cy="161" r="1.8" fill="#c5b895"/><circle cx="103" cy="179" r="1.8" fill="#c5b895"/><path d="M62 182h17M121 182h17" stroke="#a5b4bf55"/>${skirt||d?`<path d="M67 210h66l12 ${d?72:65}H55z" fill="${c('bottom')}"/><path d="M77 278h14v40H75zM109 278h14l2 40h-16z" fill="#d6b99d"/>`:`<path d="M67 210h66l-3 111h-26l-4-87-4 87H70z" fill="${c('bottom')}"/><path d="M84 226v89M117 226v89" stroke="#fff2"/>`}<path d="M73 315h24v11H66q-1-6 7-11zM105 315h24l7 9q0 3-5 3h-26z" fill="${c('shoes')}"/><path d="M${x+1} 221l19 2-1 12q-5 7-13 0zM${180-x} 223l19-2-5 14q-8 7-13 0z" fill="#d6b99d"/></svg>`;};
const studioCapsules={
women:[{name:'The tailored trouser suit',sil:'jacket-trousers',outer:'navy',top:'ivory',bottom:'navy',shoes:'black',accent:'none',note:'A matched jacket and trouser line, with a soft light top. Test the waistband and jacket while seated.'},{name:'The considered skirt suit',sil:'jacket-skirt',outer:'charcoal',top:'lightblue',bottom:'charcoal',shoes:'black',accent:'none',note:'A coherent dark suit and calm contrast. Check hem coverage, movement and shoe comfort throughout the day.'},{name:'The dress and blazer',sil:'dress-blazer',outer:'navy',top:'ivory',bottom:'navy',shoes:'oxblood',accent:'none',note:'A simple dress layer with a structured jacket. Check neckline and jacket movement in your actual camera frame.'}],
men:[{name:'The classic navy suit',sil:'jacket-trousers',outer:'navy',top:'white',bottom:'navy',shoes:'brown',accent:'burgundy',note:'A conventional formal starting point. Test tie texture on camera and check collar, sleeve and trouser lengths.'},{name:'The charcoal suit',sil:'jacket-trousers',outer:'charcoal',top:'lightblue',bottom:'charcoal',shoes:'black',accent:'navy',note:'Restrained contrast with a quiet tie. Rehearse the jacket buttoned and seated; adjust pulling at the waist.'},{name:'The open-collar option',sil:'suit-no-tie',outer:'navy',top:'white',bottom:'navy',shoes:'brown',accent:'none',note:'A less formal option for an event that explicitly welcomes it. Follow the program’s instructions for the interview itself.'}]
};studioCapsules.any=[studioCapsules.women[0],studioCapsules.men[1],studioCapsules.women[2]];
dress.querySelector('.style-tabs').insertAdjacentHTML('afterend','<div id="studioCapsules" class="capsule-gallery" role="group" aria-label="Outfit starting points"></div>');
dress.querySelector('#dressguide').parentElement.insertAdjacentHTML('afterend',`<section class="fitting-room paper"><div><span class="eyebrow">YOUR FITTING ROOM</span><h2>Rehearse the outfit.<br>Keep the comfort.</h2><p>These are your own checks. The colour planner does not measure your body or confirm a garment’s fit.</p><span id="fitCount" class="pill"></span></div><div id="fitChecks"></div></section>`);
const fitChecks=['Sit for twenty minutes without pulling or pinching','Raise your arms and move comfortably','Check the neckline, collar, sleeves and hem','Walk in the shoes you intend to wear','Check contrast, glare and pattern in interview light','Follow the program’s dress instructions'];
function renderFitting(){const done=store.get('fitChecks',[]);document.getElementById('fitCount').textContent=`${done.length} / ${fitChecks.length} rehearsed`;document.getElementById('fitChecks').innerHTML=fitChecks.map((t,i)=>`<label><input type="checkbox" data-fit-check="${i}" ${done.includes(i)?'checked':''}><span>${t}</span></label>`).join('');document.querySelectorAll('[data-fit-check]').forEach(b=>b.onchange=()=>{const a=new Set(store.get('fitChecks',[]));b.checked?a.add(+b.dataset.fitCheck):a.delete(+b.dataset.fitCheck);store.set('fitChecks',[...a]);document.getElementById('fitCount').textContent=`${a.size} / ${fitChecks.length} rehearsed`;});}renderFitting();
const oldRenderLook=renderLook;renderLook=function(){oldRenderLook();document.getElementById('lookAdvice').innerHTML='<b>Style note:</b> Choose a comfortable, coherent outfit. Check neckline, tailoring, shoes and camera contrast; personal or religious presentation choices remain yours.';document.querySelectorAll('[data-style]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.style===styleFocus));document.getElementById('dressguide').innerHTML=(styleGuides[styleFocus]||styleGuides.any).map(([t,d],i)=>`<article class="reveal"><span class="step">0${i+1}</span><h3>${t}</h3><p>${d}</p></article>`).join('')+`<article><span class="step">04</span><h3>For a virtual interview</h3><p>Try the full outfit under your interview light. Check fine patterns, fabric glare and noisy accessories. A simple solid colour often reads clearly after video compression.</p></article><article><span class="step">05</span><h3>For an in-person day</h3><p>Walk, sit, use stairs and carry your portfolio in the full outfit. Pack weather layers, a backup shirt and familiar finishing tools.</p></article><article><span class="step">06</span><h3>Shop with a fit plan</h3><p>Buy only a missing piece. Check measurements, return terms and alteration time. A blazer bought online is not a verified fit until you try it.</p>${external('https://students-residents.aamc.org/applying-residency/virtual-interviews-applicant-preparation-guide','AAMC preparation guide')}</article>`;
 document.getElementById('studioCapsules').innerHTML=(studioCapsules[styleFocus]||studioCapsules.any).map((l,i)=>`<article class="capsule-look"><div class="capsule-art">${figureSVG({...l,id:'capsule'+i,fit:'regular'})}</div><div><span class="eyebrow">OUTFIT STARTING POINT 0${i+1}</span><h3>${l.name}</h3><p>${l.note}</p><button class="btn plain sm" data-capsule="${i}">Use this palette →</button></div></article>`).join('');
 document.querySelectorAll('[data-capsule]').forEach(b=>b.onclick=()=>{const l=(studioCapsules[styleFocus]||studioCapsules.any)[+b.dataset.capsule];look={sil:l.sil,outer:l.outer,top:l.top,bottom:l.bottom,shoes:l.shoes,accent:l.accent,fit:'regular',name:l.name};store.set('look',look);renderLook();document.getElementById('figure').scrollIntoView({behavior:motionQuery.matches||paused?'auto':'smooth',block:'center'});announce('Outfit palette applied. Adjust it to your preferences.');});
 document.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{styleFocus=b.dataset.style;store.set('styleFocus',styleFocus);renderLook();});
 document.getElementById('lookName').setAttribute('aria-label','Name this look');
 document.getElementById('saveLook').textContent=editingLook?'Update saved look':'Save to My Wardrobe';
 document.getElementById('saveLook').onclick=()=>{const w=store.get('wardrobe',[]);const id=editingLook||Date.now();const entry={...look,id,name:look.name||`Look ${w.length+1}`};const n=w.findIndex(x=>x.id===id);if(n>=0)w[n]=entry;else w.push(entry);store.set('wardrobe',w);editingLook=null;announce('Look saved on this device.');location.hash='#wardrobe';};
 bindEditorial(dress);
};
document.getElementById('facePhoto').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/')||f.size>10*1024*1024){announce('Choose an image smaller than 10 MB.');e.target.value='';return;}if(faceURL)URL.revokeObjectURL(faceURL);faceURL=URL.createObjectURL(f);renderLook();};
renderWardrobe=function(){const w=store.get('wardrobe',[]),sel=store.get('selectedLook',null),h=document.getElementById('wardrobe');h.innerHTML=!w.length?`<div class="paper wardrobe-empty" style="grid-column:1/-1"><div><span class="eyebrow">YOUR FIRST LOOK</span><h3>Decide the details.<br>Then let them go.</h3><p>Build a colour and silhouette plan, save it here, and choose what you will wear.</p><a class="btn gold sm" href="#dress">Enter Style Studio →</a></div><div class="palette-ribbon" aria-hidden="true">${['navy','white','charcoal','lightblue','brown'].map(c=>`<i style="background:${PALETTE[c]}"></i>`).join('')}</div></div>`:w.map(l=>`<article class="wardrobe-look reveal"><div class="look-art">${figureSVG(l)}</div><div class="look-info"><span class="pill">${sel===l.id?'CHOSEN FOR YOUR INTERVIEW':'SAVED ON THIS DEVICE'}</span><h3>${esc(l.name)}</h3><p class="note">${esc(SILHOUETTES.find(x=>x[0]===l.sil)?.[1]||l.sil)} · ${esc(l.fit)} presentation</p><div class="actions"><button class="btn gold sm" data-wear="${l.id}" aria-pressed="${sel===l.id}">${sel===l.id?'Selected ✓':'Wear this'}</button><button class="btn plain sm" data-look-edit="${l.id}">Edit</button><button class="btn plain sm" data-look-delete="${l.id}">Delete</button></div></div></article>`).join('');h.querySelectorAll('[data-wear]').forEach(b=>b.onclick=()=>{store.set('selectedLook',+b.dataset.wear);renderWardrobe();announce('Interview look selected.');});h.querySelectorAll('[data-look-edit]').forEach(b=>b.onclick=()=>{const l=w.find(x=>x.id===+b.dataset.lookEdit);editingLook=l.id;look={...l};store.set('look',look);location.hash='#dress';});h.querySelectorAll('[data-look-delete]').forEach(b=>b.onclick=()=>{const id=+b.dataset.lookDelete;store.set('wardrobe',w.filter(x=>x.id!==id));if(sel===id)store.set('selectedLook',null);renderWardrobe();announce('Look removed from this device.');});bindEditorial(h);};
const examples=[{...look,name:'Classic navy',sil:'jacket-trousers',outer:'navy',top:'white',bottom:'navy',shoes:'black',accent:'burgundy',fit:'regular',id:1},{...look,name:'Soft contrast',sil:'dress-blazer',outer:'charcoal',top:'ivory',bottom:'charcoal',shoes:'black',accent:'none',fit:'regular',id:2},{...look,name:'Quiet confidence',sil:'jacket-skirt',outer:'navy',top:'lightblue',bottom:'navy',shoes:'black',accent:'none',fit:'regular',id:3}];
const comm=document.getElementById('page-community');comm.querySelector(':scope > .grid').remove();comm.insertAdjacentHTML('beforeend',`<div class="editorial-note">Editorial examples, not student submissions. No votes, user photos or sharing are collected. Your saved looks remain private on this device.</div><div class="gallery-grid">${examples.map((l,i)=>`<article class="gallery-look reveal"><div class="look-art">${figureSVG(l)}</div><div class="look-info"><small>EDITORIAL LOOK 0${i+1}</small><h3>${esc(l.name)}</h3><p>A starting palette to adapt to your fit, comfort and presentation.</p><button class="btn gold sm" data-example="${i}">Make it mine →</button></div></article>`).join('')}</div>`);comm.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{look={...examples[+b.dataset.example]};delete look.id;look.name='';editingLook=null;store.set('look',look);location.hash='#dress';});
const experts=document.getElementById('experts');experts.className='expert-index';experts.innerHTML=Object.values(RESEARCH.reviews).map(r=>`<article class="expert-feature reveal"><div class="expert-poster">${esc(r.by)}<span class="play" aria-hidden="true">▶</span></div><div class="copy"><span class="eyebrow">INDEPENDENT PRODUCT EVIDENCE</span><h3>${esc(r.title)}</h3><p>Use the reviewer’s tests to understand limitations. Their content does not endorse MissionMed.</p>${external(r.url,'Open the original review')}${r.video?`<p><button class="btn plain sm" data-preview="${r.video}">Load YouTube preview</button></p>`:''}</div></article>`).join('');document.getElementById('page-experts').querySelector(':scope > .note').textContent='These same links appear beside the relevant products. Older reviews may describe an earlier hardware generation; compare the exact model before buying.';

// Name each collection before its item headings; keep the visual composition intact.
const collectionHeadings={test:'Studio measurements',checklist:'Your readiness journey',dress:'Outfit starting points',wardrobe:'Saved outfit collection',community:'Editorial outfit gallery',experts:'Independent review library','prime-day':'Evergreen product shortlist',kit:'Your saved interview plan'};
for(const [id,label] of Object.entries(collectionHeadings))document.querySelector('#page-'+id+' .route-intro').insertAdjacentHTML('afterend',`<h2 class="sr-only">${label}</h2>`);

/* Interaction/motion: disclosure-first media, reversible motion, keyboard-safe navigation. */
function bindEditorial(root){root.querySelectorAll('[data-eco]').forEach(b=>b.onclick=()=>{store.set('ecosystem',b.dataset.eco);root.querySelectorAll('[data-eco]').forEach(x=>x.setAttribute('aria-pressed',x===b));root.querySelector('.ecosystem-answer').textContent=ecosystemText[b.dataset.eco];});root.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{const id=b.dataset.preview;if(!/^[A-Za-z0-9_-]{11}$/.test(id))return;const img=new Image();img.src=`https://i.ytimg.com/vi/${id}/hqdefault.jpg`;img.alt='YouTube preview for the linked review';img.className='review-thumb';b.replaceWith(img);});root.querySelectorAll('.reveal').forEach(el=>{el.classList.remove('in');el.classList.add('pending');visualObserver.observe(el);});}
const visualObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');e.target.classList.remove('pending');visualObserver.unobserve(e.target);}}),{threshold:.06});
const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');let paused=store.get('motionPaused',false);
function syncMotion(){const enabled=!motionQuery.matches&&!paused;document.body.classList.toggle('motion-enabled',enabled);document.body.classList.toggle('motion-paused',!enabled);document.getElementById('motionToggle').textContent=motionQuery.matches?'Reduced motion enabled':paused?'Resume motion':'Pause motion';document.getElementById('motionToggle').setAttribute('aria-pressed',paused||motionQuery.matches);document.getElementById('motionToggle').disabled=motionQuery.matches;if(!enabled)document.querySelectorAll('[data-parallax]').forEach(e=>e.style.setProperty('--parallax','0px'));}
document.getElementById('motionToggle').onclick=()=>{paused=!paused;store.set('motionPaused',paused);syncMotion();};motionQuery.addEventListener('change',syncMotion);syncMotion();
let scrollFrame=0;window.addEventListener('scroll',()=>{if(scrollFrame||paused||motionQuery.matches)return;scrollFrame=requestAnimationFrame(()=>{scrollFrame=0;document.querySelectorAll('.page.active [data-parallax]').forEach(el=>{const r=el.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight)el.style.setProperty('--parallax',Math.max(-10,Math.min(10,(r.top-innerHeight*.3)*-.025))+'px');});});},{passive:true});
document.addEventListener('pointermove',e=>{if(paused||motionQuery.matches||e.pointerType==='touch')return;const el=e.target.closest('[data-depth]');if(!el)return;const r=el.getBoundingClientRect();el.style.transform=`perspective(700px) rotateX(${((.5-(e.clientY-r.top)/r.height)*2).toFixed(2)}deg) rotateY(${(((e.clientX-r.left)/r.width-.5)*3).toFixed(2)}deg) translateY(-2px)`;});document.addEventListener('pointerout',e=>{const el=e.target.closest('[data-depth]');if(el&&!el.contains(e.relatedTarget))el.style.transform='';});
const drawer=document.getElementById('drawer'),more=document.getElementById('moreBtn');drawer.setAttribute('role','dialog');drawer.setAttribute('aria-modal','true');more.setAttribute('aria-controls','drawer');more.setAttribute('aria-expanded','false');
function closeDrawer(){drawer.classList.remove('open');main.inert=false;document.getElementById('mobilebar').inert=false;more.setAttribute('aria-expanded','false');more.focus();}
more.onclick=()=>{drawer.classList.add('open');main.inert=true;document.getElementById('mobilebar').inert=true;more.setAttribute('aria-expanded','true');document.getElementById('drawerClose').focus();};document.getElementById('drawerClose').onclick=closeDrawer;drawer.onclick=e=>{if(e.target.closest('a'))closeDrawer();};drawer.onkeydown=e=>{if(e.key==='Escape')closeDrawer();if(e.key==='Tab'){const ls=[...drawer.querySelectorAll('a,button')];if(e.shiftKey&&document.activeElement===ls[0]){e.preventDefault();ls.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===ls.at(-1)){e.preventDefault();ls[0].focus();}}};
const originalRoute=route;let previousRoute='';route=function(){originalRoute();const active=document.querySelector('.page.active');const id=active.id.replace('page-','');const nav=document.querySelector(`#railnav [data-nav="${id}"]`);if(nav){const tracer=document.querySelector('.nav-tracer');tracer.style.transform=`translateY(${nav.offsetTop}px)`;tracer.style.height=nav.offsetHeight+'px';}const top=document.querySelector('.topbar');top.style.display=id==='home'?'none':'';if(id!=='test'){const a=document.getElementById('micPlayback');a.pause();if(a.getAttribute('src'))URL.revokeObjectURL(a.src);a.removeAttribute('src');a.style.display='none';}if(previousRoute&&id!==previousRoute){const h=active.querySelector('h1');h?.focus({preventScroll:true});}previousRoute=id;document.querySelector('.route-loading')?.remove();if(!paused&&!motionQuery.matches){const tracer=document.createElement('i');tracer.className='route-loading';document.body.append(tracer);tracer.addEventListener('animationend',()=>tracer.remove(),{once:true});}bindEditorial(active);renderChecklist();};
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopCam();stopMic();}});window.addEventListener('pagehide',()=>{stopCam();stopMic();if(faceURL)URL.revokeObjectURL(faceURL);});
renderChecklist();renderKitCount();route();
