import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {createRecordingsService,createRecordingTranscription} from '../../server/recordings.mjs';
import {AppError} from '../../server/errors.mjs';
const owner='11111111-1111-4111-8111-111111111111',interview='22222222-2222-4222-8222-222222222222',recording='33333333-3333-4333-8333-333333333333';
const actor={id:owner,wpUserId:9,role:'student',eligible:true};
const audio=Buffer.concat([Buffer.from('1a45dfa3','hex'),Buffer.alloc(40,1)]);
const input=(changes={})=>({segmentId:randomUUID(),seq:0,contentType:'audio/webm;codecs=opus',audioBase64:audio.toString('base64'),durationMs:4000,...changes});
function fixture({providerError=false,valid=true,revalidation=null}={}){
  let row={id:recording,owner_id:owner,interview_id:interview,status:'listening',next_sequence:0},chunks=[],calls=[],providerCalls=0,putCalls=0;
  const objects=new Map();
  function owned(a,id){if(a.id!==row.owner_id||id!==row.id)throw new AppError(404,'not_found','Unavailable');}
  const store={
    async create(a,data){calls.push('create');row={...row,client_session_key:data.requestId,mime_type:data.mimeType};return {...row};},
    async reserve(a,id,data){owned(a,id);calls.push('reserve');const prior=chunks.find(x=>x.sequence===data.seq||x.client_segment_key===data.segmentId);if(prior){if(prior.sha256!==data.sha256||prior.client_segment_key!==data.segmentId)throw new AppError(409,'recording_segment_reused','Different input');return {chunk:{...prior},created:false};}const chunk={id:randomUUID(),owner_id:a.id,interview_id:interview,recording_session_id:id,sequence:data.seq,client_segment_key:data.segmentId,sha256:data.sha256,mime_type:data.mimeType,byte_count:data.byteCount,duration_ms:data.durationMs,object_key:data.objectKey,status:'pending',provider_attempts:0,version:1};chunks.push(chunk);row.next_sequence++;return {chunk:{...chunk},created:true};},
    async claim(a,id,seq){owned(a,id);const chunk=chunks.find(x=>x.sequence===seq);if(!chunk||chunk.status==='complete')return null;calls.push('claim');chunk.status='transcribing';chunk.version++;chunk.provider_attempts++;return {...chunk};},
    async claimValid(a,claim){calls.push('context');return valid&&row.status!=='abandoned'&&chunks.some(x=>x.id===claim.id&&x.version===claim.version);},
    async complete(a,claim,result){calls.push('complete');const chunk=chunks.find(x=>x.id===claim.id&&x.version===claim.version);if(!chunk||!valid)return false;chunk.status='complete';chunk.transcript=result.text;return true;},
    async fail(a,claim,code){calls.push('failed');const chunk=chunks.find(x=>x.id===claim.id&&x.version===claim.version);if(chunk){chunk.status='failed';chunk.last_error_code=code;}},
    async status(a,id){owned(a,id);return {session:{...row},chunks:chunks.map(x=>({...x}))};},
    async transition(a,id,name){owned(a,id);calls.push(name);if(name==='finish'&&chunks.some(x=>x.status!=='complete'))throw new AppError(409,'recording_pending','Pending segments');row.status={pause:'paused',resume:'listening',cancel:'abandoned',finish:'completed'}[name];return {...row};}
  };
  const storage={configured:true,prefix:'interviewiq-recordings',async put({objectKey,body}){putCalls++;calls.push('put');objects.set(objectKey,Buffer.from(body));},async get({objectKey}){calls.push('get');if(!objects.has(objectKey))throw Error('Missing object');return objects.get(objectKey);}};
  const transcription={async transcribeSegment(data){providerCalls++;calls.push('provider');if(providerError)throw Object.assign(Error('provider secret/raw body must not escape'),{code:'transcribe_timeout'});return {text:'I did not say yes. José joined at 10:30.',providerId:'openai',modelId:'gpt-4o-transcribe',latencyMs:10,flaggedTerms:[]};}};
  const bootstrap=async()=>({actor,state:{debriefs:{edited:'MY_EDITED_ACCOUNT'}},version:chunks.length});
  const service=createRecordingsService({store,storage,transcription,bootstrap});
  return {service,store,storage,calls,chunks,objects,getRow:()=>row,providerCalls:()=>providerCalls,putCalls:()=>putCalls,setProviderError:v=>providerError=v,setValid:v=>valid=v};
}
test('metadata is durable before private object/provider; raw transcript preserves words',async()=>{const x=fixture(),data=input(),r=await x.service.segment(actor,recording,data);assert.deepEqual(x.calls.slice(0,5),['reserve','put','claim','get','context']);assert.ok(x.calls.indexOf('provider')>x.calls.indexOf('context'));assert.ok(x.calls.indexOf('complete')>x.calls.indexOf('provider'));assert.equal(r.segment.text,'I did not say yes. José joined at 10:30.');assert.equal(r.bootstrap.state.debriefs.edited,'MY_EDITED_ACCOUNT');assert.equal(r.segment.status,'complete');assert.doesNotMatch(JSON.stringify(r),/object_key|audioBase64|sha256|version.*claim/);});
test('completed segment replay does not re-upload, re-transcribe or duplicate',async()=>{const x=fixture(),data=input();await x.service.segment(actor,recording,data);const again=await x.service.segment(actor,recording,data);assert.equal(x.providerCalls(),1);assert.equal(x.putCalls(),1);assert.equal(x.chunks.length,1);assert.equal(again.segments.length,1);});
test('segment replay with different bytes is rejected',async()=>{const x=fixture(),data=input();await x.service.segment(actor,recording,data);const different=Buffer.from(audio);different[15]=2;await assert.rejects(x.service.segment(actor,recording,{...data,audioBase64:different.toString('base64')}),e=>e.code==='recording_segment_reused');assert.equal(x.providerCalls(),1);});
test('mentor/admin and different owner cannot start provider work',async()=>{const x=fixture();for(const role of ['mentor','admin'])await assert.rejects(x.service.segment({...actor,role},recording,input()),e=>e.status===403);await assert.rejects(x.service.segment({...actor,id:'44444444-4444-4444-8444-444444444444'},recording,input()),e=>e.status===404);assert.equal(x.providerCalls(),0);assert.equal(x.putCalls(),0);});
test('oversized, continuation-only and malformed audio are rejected before metadata',async()=>{const x=fixture();for(const data of [input({audioBase64:Buffer.alloc(1048577).toString('base64')}),input({audioBase64:Buffer.alloc(44).toString('base64')}),input({audioBase64:'abc%'}),input({seq:-1}),input({durationMs:0}),input({contentType:'text/html'})])await assert.rejects(x.service.segment(actor,recording,data));assert.deepEqual(x.calls,[]);});
test('provider outage retains durable object and failed metadata; retry succeeds without edited text mutation',async()=>{const x=fixture({providerError:true});await assert.rejects(x.service.segment(actor,recording,input()),e=>e.code==='transcribe_timeout'&&!e.message.includes('secret'));assert.equal(x.objects.size,1);assert.equal(x.chunks[0].status,'failed');x.setProviderError(false);const result=await x.service.action(actor,recording,'retry',{requestId:randomUUID()});assert.equal(result.segments[0].status,'complete');assert.equal(result.bootstrap.state.debriefs.edited,'MY_EDITED_ACCOUNT');assert.equal(x.putCalls(),1);});
test('vanished or cancelled context blocks provider use even after storage read',async()=>{const x=fixture({valid:false});await assert.rejects(x.service.segment(actor,recording,input()),e=>e.code==='recording_context_unavailable');assert.equal(x.providerCalls(),0);assert.equal(x.chunks[0].status,'failed');});
test('fresh owner revalidation mismatch fails before provider claim',async()=>{const x=fixture();await assert.rejects(x.service.segment(actor,recording,input(),{revalidateActor:async()=>({...actor,id:'44444444-4444-4444-8444-444444444444'})}),e=>e.code==='recording_identity_changed');assert.equal(x.providerCalls(),0);assert.equal(x.calls.includes('claim'),false);});
test('logout during provider work prevents transcript commit',async()=>{const x=fixture();let n=0;await assert.rejects(x.service.segment(actor,recording,input(),{revalidateActor:async()=>{n++;if(n>=3)throw new AppError(401,'session_unavailable','Session ended');return actor;}}),e=>e.status===401);assert.equal(x.providerCalls(),1);assert.equal(x.calls.includes('complete'),false);assert.equal(x.chunks[0].status,'failed');});
test('finish waits for all transcripts, and action names are bounded',async()=>{const x=fixture({providerError:true});await assert.rejects(x.service.segment(actor,recording,input()));await assert.rejects(x.service.action(actor,recording,'finish',{requestId:randomUUID()}),e=>e.code==='recording_pending');await assert.rejects(x.service.action(actor,recording,'grant-access',{requestId:randomUUID()}));const stopped=await x.service.action(actor,recording,'cancel',{requestId:randomUUID()});assert.equal(stopped.status,'abandoned');});
test('primary transient failure invokes fixed whisper fallback with new authorization check',async()=>{const models=[],checks=[];const driver=createRecordingTranscription({apiKey:'test-only',fetchImpl:async(url,options)=>{models.push(options.body.get('model'));return models.length===1?{ok:false,status:503}:{ok:true,json:async()=>({text:'Exact provider words'})};}});const r=await driver.transcribeSegment({buffer:audio,mimeType:'audio/webm',seq:0},{beforeAttempt:async()=>checks.push(true)});assert.deepEqual(models,['gpt-4o-transcribe','whisper-1']);assert.equal(checks.length,1);assert.equal(r.modelId,'whisper-1');assert.equal(r.text,'Exact provider words');});
test('hard provider authentication failure does not launch fallback',async()=>{let n=0;const driver=createRecordingTranscription({apiKey:'test-only',fetchImpl:async()=>{n++;return {ok:false,status:401};}});await assert.rejects(driver.transcribeSegment({buffer:audio,mimeType:'audio/webm',seq:0}));assert.equal(n,1);});
test('unconfigured service does not pretend voice is available',async()=>{const x=fixture(),service=createRecordingsService({store:x.store,storage:null,transcription:null,bootstrap:async()=>({})});assert.equal(service.available,false);await assert.rejects(service.create(actor,{interviewId:interview,requestId:randomUUID(),mimeType:'audio/webm'}),e=>e.code==='speech_unavailable');assert.equal(x.calls.length,0);});
