import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {createHash} from 'node:crypto';
import {audioObjectKey,assertAudioSignature,createPrivateAudioStorage} from '../../server/storage.mjs';
const ownerId='11111111-1111-4111-8111-111111111111',recordingId='22222222-2222-4222-8222-222222222222',segmentId='33333333-3333-4333-8333-333333333333';
const bytes=Buffer.concat([Buffer.from('1a45dfa3','hex'),Buffer.alloc(40,1)]),sha256=createHash('sha256').update(bytes).digest('hex');
const objectKey=audioObjectKey({prefix:'interviewiq-recordings',ownerId,recordingId,segmentId,seq:0,contentType:'audio/webm'});
function commands(){class PutObjectCommand{constructor(input){this.input=input;}}class HeadObjectCommand{constructor(input){this.input=input;}}class GetObjectCommand{constructor(input){this.input=input;}}return {PutObjectCommand,HeadObjectCommand,GetObjectCommand};}
async function fixture(options={}){const sdk=commands(),calls=[],objects=new Map();const client={async send(command){calls.push(command);const data=command.input;if(command instanceof sdk.PutObjectCommand){if(objects.has(data.Key))throw Object.assign(Error('exists'),{name:'PreconditionFailed',$metadata:{httpStatusCode:412}});objects.set(data.Key,data);return {};}
  if(command instanceof sdk.HeadObjectCommand){const item=objects.get(data.Key);return {Metadata:item.Metadata,ContentLength:item.ContentLength,ContentType:item.ContentType};}
  const item=objects.get(data.Key);return {ContentLength:item.ContentLength,ContentType:item.ContentType,Body:Readable.from([item.Body])};}};
const storage=await createPrivateAudioStorage({endpoint:'https://test-account.r2.cloudflarestorage.com',bucket:'interviewiq-private-test',prefix:'interviewiq-recordings',accessKeyId:'test-only',secretAccessKey:'test-only',sdk,client,...options});return {storage,calls,objects,sdk};}
test('dedicated prefix and owner identities determine every object key',()=>{assert.match(objectKey,/^interviewiq-recordings\/11111111/);for(const prefix of ['storyforge-audio','../interviewiq','interviewiq/../other','',undefined])assert.throws(()=>audioObjectKey({prefix,ownerId,recordingId,segmentId,seq:0,contentType:'audio/webm'}));});
test('private put has no public ACL or signed URL and is immutable on replay',async()=>{const x=await fixture(),input={objectKey,ownerId,recordingId,body:bytes,contentType:'audio/webm',sha256};await x.storage.put(input);await x.storage.put(input);const put=x.calls[0].input;assert.equal(put.IfNoneMatch,'*');assert.equal(put.ACL,undefined);assert.equal(put.CacheControl,'private, no-store');assert.equal(x.objects.size,1);assert.deepEqual(await x.storage.get(input),bytes);});
test('changed bytes cannot replace an existing object',async()=>{const x=await fixture();await x.storage.put({objectKey,ownerId,recordingId,body:bytes,contentType:'audio/webm',sha256});const changed=Buffer.from(bytes);changed[12]=7;await assert.rejects(x.storage.put({objectKey,ownerId,recordingId,body:changed,contentType:'audio/webm',sha256:createHash('sha256').update(changed).digest('hex')}),e=>e.code==='audio_replay_conflict');assert.deepEqual(x.objects.get(objectKey).Body,bytes);});
test('cross-owner keys and traversal fail before storage access',async()=>{const x=await fixture();for(const key of [objectKey.replace(ownerId,segmentId),objectKey+'/../../secret','https://example.com/private'])await assert.rejects(x.storage.get({objectKey:key,ownerId,recordingId}));assert.equal(x.calls.length,0);});
test('endpoint and missing bucket configuration fail closed',async()=>{for(const options of [{endpoint:'http://localhost/'},{endpoint:'https://evil.example/'},{bucket:''},{prefix:'storyforge-audio'}])await assert.rejects(fixture(options));});
test('audio type is verified against the complete container signature',()=>{assert.equal(assertAudioSignature(bytes,'audio/webm;codecs=opus'),'audio/webm');assert.throws(()=>assertAudioSignature(bytes,'audio/mp4'));assert.throws(()=>assertAudioSignature(Buffer.alloc(1048577),'audio/webm'));});
