import fs from 'node:fs';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
if(process.env.MR_ECOSYSTEM_LEASE_ACTIVE!=='1')throw Error('Exact-path heartbeat lease required');
const base='wp-content/mu-plugins/missionmed-mr-alternate-assets';
const runtime='/www/theresidencyacademy_209/public';
const custody='/www/theresidencyacademy_209/private/mr-matrix-ecosystem-0930';
const files=['media/ecosystem-matrix-720.webp','media/ecosystem-matrix-1080.webp','media/ecosystem-matrix-1440.webp','media/ecosystem-oncall-720.webp','media/ecosystem-oncall-1080.webp','media/ecosystem-oncall-1440.webp','alternate.css','page.php'];
const old={'page.php':'5bd1094fa1e4584088165b09d16f503a3825a703de2f3ba261eaad7ecaa7af66','alternate.css':'625608f3bd2964104a299c1b149672a5558c82323052405b6a8bac1bbddd5da7'};
const hashes=Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(`${base}/${f}`)).digest('hex')]));
const q=s=>`'${s.replaceAll("'","'\\''")}'`;
const ssh=s=>execFileSync('ssh',['missionmed-kinsta',`set -eu; cd ${q(runtime)}; ${s}`],{encoding:'utf8',timeout:25000});
const guard=Object.entries(old).map(([f,h])=>`test "$(sha256sum ${q(base+'/'+f)} | cut -d' ' -f1)" = ${q(h)}`).join('; ');
const absent=files.filter(f=>!old[f]).map(f=>`test ! -e ${q(base+'/'+f)}`).join('; ');
const protect=`sha256sum wp-content/mu-plugins/missionmed-mr*.php ${q(base+'/alternate.js')} ${q(base+'/match-day-media.json')} ${q(base+'/match-day-player.php')}`;
const protectedBefore=ssh(protect);
console.log(ssh(`${guard}; ${absent}; test ! -e ${q(custody)}; umask 077; mkdir -p ${q(custody+'/preimage')} ${q(custody+'/candidate/media')}; cp -p ${q(base+'/page.php')} ${q(base+'/alternate.css')} ${q(custody+'/preimage/')}; sha256sum ${q(custody+'/preimage/')}*`));
for(const f of files)execFileSync('scp',[`${base}/${f}`,`missionmed-kinsta:${custody}/candidate/${f}`],{timeout:25000});
const verify=files.map(f=>`test "$(sha256sum ${q(custody+'/candidate/'+f)} | cut -d' ' -f1)" = ${q(hashes[f])}`).join('; ');
const install=files.map(f=>`install -m 644 ${q(custody+'/candidate/'+f)} ${q(base+'/'+f+'.ecosystem-next')}; mv ${q(base+'/'+f+'.ecosystem-next')} ${q(base+'/'+f)}`).join('; ');
console.log(ssh(`${guard}; ${absent}; ${verify}; php -l ${q(custody+'/candidate/page.php')}; ${install}; sha256sum ${files.map(f=>q(base+'/'+f)).join(' ')}`));
const protectedAfter=ssh(protect);if(protectedBefore!==protectedAfter)throw Error('Unrelated runtime drift: inspect before further mutation');
const receipt={at:new Date().toISOString(),source:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),custody,files,preimages:old,absentBefore:files.filter(f=>!old[f]),deployed:hashes,protectedBefore,protectedAfter,protectedUnchanged:true};
fs.writeFileSync(new URL('./qa/deployment.json',import.meta.url),JSON.stringify(receipt,null,2));console.log(JSON.stringify({deployed:files.length,protectedUnchanged:true,custody}));
