import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync, statSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {dirname, join, resolve} from 'node:path';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const read=path=>readFileSync(join(root,path),'utf8');
const php=read('wp-content/mu-plugins/missionmed-mr-p0.php');
const heroJs=read('wp-content/mu-plugins/missionmed-mr-0912-assets/premium-hero/hero.js');
const heroCss=read('wp-content/mu-plugins/missionmed-mr-0912-assets/premium-hero/hero.css');
const mrJs=read('wp-content/mu-plugins/missionmed-mr-0912-assets/b-immersive/scripts/site.js');
const mrHtml=read('wp-content/mu-plugins/missionmed-mr-0912-assets/b-immersive/index.html');
const mrCss=read('wp-content/mu-plugins/missionmed-mr-0912-assets/b-immersive/styles/site.css');
const base='a860765556b025c14177d7044fbf2bf5948b4a6d';
const acceptedZelle='2a43b20018865c465df3c9f81e836de066315aae';

test('homepage frame order and final Founder message are exact',()=>{
 const block=php.slice(php.indexOf('function mm_mr_0929_home_hero_frames'),php.indexOf('function mm_mr_0929_home_hero_markup'));
 assert.deepEqual([...block.matchAll(/'id'=>'([^']+)'/g)].map(m=>m[1]),['mr-application','exam-live','mr-communication','usce-fit','mr-ranking','exam-reasoning','mr-story','usce-pathway']);
 for(const text of ['YOU BUILT THE APPLICATION','that earned the interview.',"NOW LET'S TURN THE INTERVIEW",'INTO A MATCH.','Build the communication, story and connection skills that matter when programs meet you.','Explore Interview Bootcamp Week'])assert.ok(block.includes(text),text);
 assert.ok(php.includes("preg_replace('~<section\\b[^>]*\\bid="),'legacy hero removal accepts attributes before id');
 assert.ok(php.includes("ob_start('mm_mr_0929_filter_homepage_output')"),'final output removes legacy hero injected outside main content');
});

test('rotation is bounded, controllable and motion-aware',()=>{
 for(const token of ['12000','prefers-reduced-motion','max-width: 760px','IntersectionObserver','visibilitychange','data-pause','data-prev','data-next','mm_home_hero_cta','utm_source','utm_medium','utm_campaign','carry(frame.href)','Still','mountMobileNav'])assert.ok(heroJs.includes(token),token);
 assert.ok(heroCss.includes('min-width:44px'));assert.ok(heroCss.includes(':focus-visible'));
 assert.equal((php.match(/data-slide=/g)||[]).length,1,'dots are generated by one bounded loop');
});

test('Round 2 visual geometry is full bleed and contrast-safe',()=>{
 for(const token of ['height:880px','position:absolute;inset:0;z-index:0','left:54%;right:4.45%','--ph-accent:#9b412e','linear-gradient(90deg,rgba(3,14,24,.14)'])assert.ok(heroCss.includes(token),token);
 assert.ok(!/\.mm-ph\{[^}]*display:grid/.test(heroCss),'homepage hero must not return to split-grid geometry');
 for(const token of ['background:#eee7d9','linear-gradient(90deg,transparent 33%,#eee7d9 60%)','left:53%;right:4.45%','height:884px'])assert.ok(mrCss.includes(token),token);
 assert.ok(!mrJs.includes("$('.hero-scene').style"),'removed hero-scene runtime error');
 assert.ok(mrJs.includes('scrollIntoView({block:\'start\'})'),'deep links restore after async render');
});

test('dedicated Mission Residency hero is static and both paths are explicit',()=>{
 const hero=mrJs.slice(mrJs.indexOf('function hero()'),mrJs.indexOf('function paths()'));
 for(const text of ['brian-studio-aaa.jpg','YOU BUILT THE APPLICATION','that earned the interview.',"NOW LET'S TURN THE INTERVIEW",'INTO A MATCH.','Explore Interview Bootcamp Week','Explore IV Prep Complete',"here('#dates')","here('#compare')"])assert.ok(hero.includes(text),text);
 assert.ok(mrJs.includes('carry(location.pathname+hash)'));
 assert.ok(!/carousel|setInterval|setTimeout/.test(hero));
 for(const text of ['October 8–18, 2026','October through final February interviews','small-group training','groups are small and personalized'])assert.ok(mrJs.includes(text),text);
 assert.ok(mrHtml.includes('brian-studio-aaa.jpg'));
});

test('ranking evidence and quote interpretation stay bounded',()=>{
 for(const text of ['NRMP Program Director Survey / 2024','89%','87%','76%','18% (N=1,150)','not a Match-rate or outcome promise'])assert.ok(mrJs.includes(text),text);
 assert.equal((mrJs.match(/You made me fall in love with my own story and believe that my dreams are valid against all Odds\./g)||[]).length,1);
});

test('stale headlines are absent from current presentation source',()=>{
 for(const source of [php,heroJs,heroCss,mrJs,mrHtml]){assert.ok(!source.includes('Your application got you here'));assert.ok(!source.includes('Now they meet you'));}
});

test('initial and deferred image budgets are bounded',()=>{
 const dir=join(root,'wp-content/mu-plugins/missionmed-mr-0912-assets/premium-hero/assets');
 for(const name of ['mr-application.webp','exam-live.webp','mr-communication.webp','usce-operating.webp','mr-ranking.webp','mr-community.webp','usce-clinical.webp'])assert.ok(statSync(join(dir,name)).size<140000,`${name} exceeds 140 KB`);
 assert.equal((php.match(/fetchpriority="high"/g)||[]).length,2,'one preload and one initial image only');
});

test('accepted Zelle implementation stays byte-identical',()=>{
 execFileSync('git',['diff','--quiet',acceptedZelle,'--','wp-content/mu-plugins/missionmed-mr-zelle-verifier.php','wp-content/mu-plugins/missionmed-mr-0912-assets/media/missionmed-zelle-qr.png'],{cwd:root});
 for(const token of ["const MM_MR_0912_IW_CARD_PRICE = 549.0","const MM_MR_0912_IW_ZELLE_PRICE = 499.0","return $now <= mm_mr_0912_complete_early_deadline_timestamp() ? 3099.0 : 3499.0"])assert.ok(php.includes(token),token);
});
