import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url));
const read=p=>readFile(`${root}/${p}`,'utf8');
test('invitation and ordinary branded login use distinct fixed server-side returns',async()=>{for(const p of ['wordpress/missionmed-missionaccounts-sso/missionmed-missionaccounts-sso.php','infra/wordpress/missionmed-missionaccounts-sso.php']){const s=await read(p);assert.match(s,/hash_equals\( 'missionaccounts_onboarding'/);assert.match(s,/home_url\( '\/my-account\/'/);assert.match(s,/home_url\( '\/missionaccounts\/#\/'/);assert.match(s,/home_url\( '\/member-dashboard\/'/);assert.match(s,/woocommerce_login_redirect/);assert.match(s,/add_action\( 'wp_login', 'mma_onboarding_invitation_mark_login'/);assert.match(s,/set_transient\( mma_onboarding_invitation_return_key\( \$user->ID \), 1, 5 \* MINUTE_IN_SECONDS \)/);assert.match(s,/set_transient\( mma_matrix_login_return_key\( \$user->ID \), 1, 5 \* MINUTE_IN_SECONDS \)/);assert.match(s,/! user_can\( \$user, 'manage_options' \)/);assert.match(s,/delete_transient\( \$return_key \)/);assert.match(s,/delete_transient\( \$matrix_key \)/);assert.doesNotMatch(s,/HTTP_REFERER/);}});
test('completion experience is persistent and routes to canonical destinations',async()=>{const s=await read('public/index.production.html');assert.match(s,/if\(data\.status==='COMPLETE'\) return/);assert.match(s,/Go to MyMissionMed Account/);assert.match(s,/href="#\/me"/);assert.match(s,/href="\/member-dashboard\/"/);assert.match(s,/onboarding\?\.status==='COMPLETE'/);});
test('email v4 uses full brand, safe intent and only verified live benefits',async()=>{const h=await read('emails/onboarding-launch-v4.html'),t=await read('emails/onboarding-launch-v4.txt'),m=JSON.parse(await read('emails/onboarding-launch-v4.manifest.json'));assert.match(h,/608a69b125647f6e63b56f87b823b1e60dbdaebf4916b1d5d5edcc408b8ab3fe\.png/);assert.match(h,/width=\"800\"/);assert.match(h,/Hi \{\{first_name\}\},/);assert.match(m.cta_url,/missionmed_intent=missionaccounts_onboarding/);assert.equal(m.pilot_send_authorized,false);for(const s of [h,t]){for(const forbidden of ['payment method','card','billing authorization','Stripe','invoice','Join Classroom','upcoming schedule','replays','notes'])assert.equal(s.toLowerCase().includes(forbidden.toLowerCase()),false,forbidden);}});
