<?php
define('MMDRJ_ONBOARDING_LAUNCH_TEST',true);$GLOBALS['options']=array();$GLOBALS['user_meta']=array();$GLOBALS['mail_count']=0;$GLOBALS['meta_fail']=false;
function esc_html($v){return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}function esc_url($v){return str_replace('&','&#038;',(string)$v);}function esc_url_raw($v){return(string)$v;}function sanitize_text_field($v){return trim(strip_tags((string)$v));}function sanitize_email($v){return(string)$v;}function absint($v){return abs((int)$v);}function wp_json_encode($v,$f=0){return json_encode($v,$f);}function get_option($k,$d=false){return$GLOBALS['options'][$k]??$d;}function add_option($k,$v,$d='',$a=false){if(array_key_exists($k,$GLOBALS['options']))return false;$GLOBALS['options'][$k]=$v;return true;}function wp_cache_delete(){return true;}function update_user_meta($u,$k,$v){if($GLOBALS['meta_fail'])return false;$GLOBALS['user_meta'][$u][$k]=$v;return 1;}function get_user_meta($u,$k,$s=true){return$GLOBALS['user_meta'][$u][$k]??'';}function user_can(){return false;}function sfwd_lms_has_access(){return true;}function add_action(){return true;}function get_password_reset_key(){return'reset-key';}function is_wp_error(){return false;}function network_site_url($p){return'https://missionmedinstitute.com/'.$p;}function wp_mail(){++$GLOBALS['mail_count'];return true;}
class HarnessUser{public $roles=array('subscriber');}class HarnessWpdb{public $options='wp_options';function update($t,$d,$w){$k=$w['option_name'];if(($GLOBALS['options'][$k]??null)!==$w['option_value'])return 0;$GLOBALS['options'][$k]=$d['option_value'];return 1;}}$GLOBALS['wpdb']=new HarnessWpdb();
require dirname(__DIR__).'/scripts/onboarding-launch/wp_onboarding_pilot.php';
$merged=mmdrj_launch_merge_text('{{password_setup_url}}',array('first_name'=>'A','username'=>'u','account_url'=>'https://x','password_setup_url'=>'https://x/?action=rp&key=k&login=u','support_email'=>'support@example.invalid'));$plain_url_ok=$merged==='https://x/?action=rp&key=k&login=u';
$first=add_option('_claim','{"state":"sending"}','','no');$second=add_option('_claim','{"state":"sending"}','','no');$atomic_claim_ok=$first===true&&$second===false;
$GLOBALS['meta_fail']=true;$mirror_failure_blocks=mmdrj_launch_mirror_ledger(1,'ledger','x')===false&&$GLOBALS['mail_count']===0;
$outsider_blocked=false;$payload=array('schema_version'=>'missionaccounts-onboarding-pilot-send-v1','template_version'=>'examprep-onboarding-email-2026-09-17-v3r1','provider'=>'wordpress_wp_mail','subject'=>'Your MyMissionMed Account is ready','cta_url'=>'https://missionmedinstitute.com/missionaccounts/#/me/onboarding','template_html_sha256'=>hash('sha256','h'),'template_text_sha256'=>hash('sha256','t'),'external_send_authorized'=>false,'authority_commit'=>null,'items'=>array(array('display_name'=>'Outsider','pilot_status'=>'READY','wp_user_id'=>999,'student_id'=>'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','eligibility_basis'=>'learndash_course_6357','username_sha256'=>str_repeat('b',64),'email_sha256'=>str_repeat('a',64)),array('display_name'=>'Subani Dias','pilot_status'=>'READY'),array('display_name'=>'Neshmaidy Negrón Zeda','pilot_status'=>'READY')));
try{mmdrj_launch_process($payload,'h','t','dry-run');}catch(RuntimeException $e){$outsider_blocked=$e->getMessage()==='onboarding_pilot_exact_cohort_required';}echo json_encode(compact('plain_url_ok','atomic_claim_ok','mirror_failure_blocks','outsider_blocked'));
