import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url));
const header='display_name,wp_user_id,username,email,student_id,sponsor_type,onboarding_eligible,prior_send_state,pilot_status,eligibility_basis\n';
const rows=['Raghav Gupta,114,student-alpha,raghav@example.invalid,5171c2ec-5046-59e0-a22a-7362404bf9ec,DIRECT,true,not_sent,READY,learndash_course_6357','Subani Dias,9,student-beta,subani@example.invalid,142b08bb-9643-550c-acac-29a8030c7e02,DIRECT,true,not_sent,READY,learndash_course_6357','Neshmaidy Negrón Zeda,89,student-gamma,neshmaidy@example.invalid,c6843e4d-f163-5f57-b1bd-61d566700444,DIRECT,true,not_sent,READY,drj_drills_student_role'];
async function build(values=rows){const d=await mkdtemp(join(tmpdir(),'ma-launch-v3r1-')),c=join(d,'c.csv'),o=join(d,'m.json');await writeFile(c,header+values.join('\n')+'\n');const r=spawnSync('python3',[join(root,'scripts/onboarding-launch/build_pilot_manifest.py'),'--cohort-csv',c,'--html',join(root,'emails/onboarding-launch-v3.html'),'--text',join(root,'emails/onboarding-launch-v3.txt'),'--output',o],{encoding:'utf8'});return{r,o};}
test('corrected builder seals the exact three recipients without source addresses or usernames',async()=>{const{r,o}=await build();assert.equal(r.status,0,r.stderr);const m=JSON.parse(await readFile(o,'utf8'));assert.deepEqual(m.items.map(x=>x.display_name),['Raghav Gupta','Subani Dias','Neshmaidy Negrón Zeda']);assert.equal(m.template_version,'examprep-onboarding-email-2026-09-17-v3r1');assert.equal(m.external_send_authorized,false);assert.equal(JSON.stringify(m).includes('@example.invalid'),false);assert.equal('username' in m.items[0],false);assert.match(m.items[2].username_sha256,/^[0-9a-f]{64}$/);});
test('corrected builder rejects reordered, extra, held, sponsored, drifted, or prior-sent rows',async()=>{for(const bad of [[rows[1],rows[0],rows[2]],[...rows,'Ana Torres,353,a,a@example.invalid,b2a9e055-d55e-5bfc-8c0c-bd38f3b14b5c,DIRECT,true,not_sent,READY,learndash_course_6357'],rows.map(x=>x.replace('DIRECT','UCC')),rows.map(x=>x.replace('not_sent','sent')),rows.map(x=>x.replace('READY','HELD'))]){const{r}=await build(bad);assert.notEqual(r.status,0);}});
test('controller harness proves atomic claim, WP-CLI arguments, raw plain reset URL, mirror fail closed, outsider denial, and exact result population',async()=>{const r=spawnSync('php',[join(root,'tests/onboarding-launch-harness.php')],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);const p=JSON.parse(r.stdout);assert.deepEqual(p,{plain_url_ok:true,atomic_claim_ok:true,mirror_failure_blocks:true,cli_args_ok:true,outsider_blocked:true});const source=await readFile(join(root,'scripts/onboarding-launch/wp_onboarding_pilot.php'),'utf8');assert.match(source,/'population'=>count\(\$cohort\)/);assert.equal(rows.length,3);});
test('migration registers corrected manifest with external sending disabled',async()=>{const sql=await readFile(join(root,'supabase/migrations/20260917190000_onboarding_email_pilot_recipient_correction.sql'),'utf8');assert.match(sql,/examprep-onboarding-email-2026-09-17-v3r1/);assert.match(sql,/false/);assert.match(sql,/6a73d3d1e04a3bc6d733b47ada12f8d7d068fa47ff169c2587b763727f0076f8/);});
