import test from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import { PartnerLedger } from '../src/partner-cost-sharing/ledger.mjs';
import { allocateExpenses, PARTNERS, digest } from '../src/partner-cost-sharing/domain.mjs';
import { proposeExpense, classifyExpenseCandidates, assessAIProposal, authenticateReceiptEnvelope, matchChaseReceipt } from '../src/partner-cost-sharing/ingestion.mjs';
import { partnerStatement, statementToCsv, annualSummary } from '../src/partner-cost-sharing/statements.mjs';
import { PartnerStripeAdapter, PartnerGmailAdapter, PartnerVendorAdapter } from '../src/partner-cost-sharing/providers.mjs';
import { environmentPartnerConfig, PartnerRestStore } from '../src/partner-cost-sharing/store.mjs';
import { invoicePackage, privateZip, crc32 } from '../src/partner-cost-sharing/archive.mjs';
import { createHash } from 'node:crypto';
const actors=Object.fromEntries(PARTNERS.map(key=>[key,{key,active:true}]));
const proof='a'.repeat(64), stamp='2026-10-04T22:00:00.000Z';
const candidate=(amountCents=300)=>({vendor:'Hosting',invoiceNumber:'INV-1',amountCents,currency:'USD',periodStart:'2026-09-01',periodEnd:'2026-09-30',evidenceSha256:proof,assetId:'private:fixture',source:'fixture',category:'Hosting',description:'Hosting service'});
async function fixture(openingBalances={brian:0,drj:0,phil:0}) {
 const ledger=new PartnerLedger({now:()=>stamp});
 const {expense}=await ledger.ingest(actors.brian,'ingest-1',candidate());
 await ledger.reviewExpense(actors.brian,'review-1',{expenseId:expense.id,decision:'approve',evidenceSha256:proof,reason:'Original custody verified',expectedRevision:0});
 const {period}=await ledger.certifyPeriod(actors.brian,'certify-1',{expenseIds:[expense.id],openingBalances,expectedRevision:1,coverageCutoff:'2026-09-30',periodStart:'2026-09-01',periodEnd:'2026-09-30',allocationRuleVersion:'equal-third-brian-residual-v1',certificationEvidenceSha256:proof});
 return {ledger,period,o:ledger.state.obligations.find(x=>x.partner==='drj')};
}
const payment=(o,amountCents=100)=>({partner:'drj',obligationId:o.id,amountCents,expectedRevision:o.revision,snapshotHash:o.snapshotHash,fingerprint:'b'.repeat(64),evidenceSha256:proof,method:'authorized_admin',attestation:'Fixture original receipt assigned to this exact obligation',receivedAt:stamp});
const method={partner:'drj',providerVerified:true,domain:'partner_cost_sharing',reference:'pm_fixture',customerReference:'cus_fixture',brand:'visa',last4:'4242'};
async function setup(ledger,period){await ledger.setMethod(actors.drj,'method-1',method);await ledger.consent(actors.drj,'consent-1',{action:'authorize',termsVersion:'fixture-v1',termsSha256:proof,maxAmountCents:1000,periodId:period.id});}

test('seeded 10,000 allocation batches preserve every source cent and batch target',()=>{
 let seed=127;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed;};
 for(let n=0;n<10000;n++){const rows=Array.from({length:1+rand()%30},(_,i)=>({id:String(i),amountCents:rand()%1000000}));const result=allocateExpenses(rows);assert.equal(PARTNERS.reduce((s,p)=>s+result.shares[p],0),result.totalCents);for(const row of result.expenses)assert.equal(PARTNERS.reduce((s,p)=>s+row.shares[p],0),row.amountCents);for(const p of PARTNERS)assert.equal(result.expenses.reduce((s,x)=>s+x.shares[p],0),result.shares[p]);}
});
test('generic role, inactive membership and cross-partner claims fail closed',async()=>{
 const {ledger,o}=await fixture();assert.throws(()=>ledger.view({role:'founder'}));assert.throws(()=>ledger.view({key:'drj',active:false}));await assert.rejects(ledger.reportSent(actors.phil,'claim-x',{obligationId:o.id,amountCents:50}));await assert.rejects(ledger.ingest(actors.drj,'ingest-x',candidate()));
});
test('historical proposals alone never create a certified balance',async()=>{const ledger=new PartnerLedger();await ledger.ingest(actors.brian,'proposal-only',candidate());assert.equal(ledger.view(actors.drj).currentBalanceCents,null);assert.equal(ledger.state.expenses[0].included,false);});
test('expense approval requires exact custody and current revision',async()=>{const l=new PartnerLedger();const {expense}=await l.ingest(actors.brian,'ingest',candidate());for(const omitted of ['expectedRevision','evidenceSha256']){const p={expenseId:expense.id,decision:'approve',reason:'Original checked',expectedRevision:0,evidenceSha256:proof};delete p[omitted];await assert.rejects(l.reviewExpense(actors.brian,'bad-'+omitted,p));}assert.equal(l.state.revision,0);});
test('dedup, conflicting evidence and same-key changed payload remain atomic',async()=>{const l=new PartnerLedger();await l.ingest(actors.brian,'ingest',candidate());assert.equal((await l.ingest(actors.brian,'second',candidate())).duplicate,true);await assert.rejects(l.ingest(actors.brian,'different',candidate(301)));await assert.rejects(l.ingest(actors.brian,'ingest',candidate(302)));assert.equal(l.state.expenses.length,1);});
test('reporting sent remains pending and does not change balance',async()=>{const {ledger,o}=await fixture();const before=ledger.view(actors.drj).currentBalanceCents;await ledger.reportSent(actors.drj,'claim',{obligationId:o.id,amountCents:50});assert.equal(ledger.view(actors.drj).currentBalanceCents,before);assert.equal(ledger.state.claims[0].state,'PENDING_VERIFICATION');});
test('completion reconciles one exact claim and atomically posts receipt/statement',async()=>{const {ledger,o}=await fixture();await ledger.reportSent(actors.drj,'small',{obligationId:o.id,amountCents:25});await ledger.reportSent(actors.drj,'large',{obligationId:o.id,amountCents:50});const result=await ledger.markPartnerPaymentVerifiedAndComplete(actors.brian,'verified',payment(o,50));assert.equal(result.remainingCents,50);assert.equal(result.obligation.status,'PARTIAL');assert.equal(result.receiptState,'READY');assert.equal(result.statementState,'POSTED');assert.deepEqual(ledger.state.claims.map(x=>x.state),['PENDING_VERIFICATION','RECONCILED']);assert.equal(ledger.view(actors.drj).currentBalanceCents,50);});
test('duplicate completion and competing requests cannot double apply a receipt',async()=>{const {ledger,o}=await fixture();const results=await Promise.all(['a','b'].map(k=>ledger.markPartnerPaymentVerifiedAndComplete(actors.brian,k,payment(o))));assert.equal(results.filter(x=>x.duplicate).length,1);assert.equal(ledger.state.payments.length,1);assert.equal(ledger.view(actors.drj).currentBalanceCents,0);});
test('excess, stale revision, wrong partner and unauthenticated receipt roll back',async()=>{const {ledger,o}=await fixture();for(const changes of [{amountCents:101},{expectedRevision:99},{partner:'phil'},{method:'authenticated_chase_gmail',transportVerified:false},{receivedAt:'2026-01-01T00:00:00Z'}])await assert.rejects(ledger.markPartnerPaymentVerifiedAndComplete(actors.brian,digest(changes),{...payment(o),...changes}));assert.equal(ledger.state.payments.length,0);assert.equal(ledger.state.obligations.find(x=>x.id===o.id).appliedCents,0);});
test('partner projection excludes other contributions and method provider references',async()=>{const {ledger,period}=await fixture();await setup(ledger,period);await ledger.markPartnerPaymentVerifiedAndComplete(actors.brian,'done',payment(ledger.state.obligations.find(x=>x.partner==='drj')));const view=ledger.view(actors.phil);assert.equal(view.payments.length,0);assert.equal(view.admin,undefined);assert.equal(view.periods[0].openingBalances,undefined);assert.ok(view.obligations.every(x=>x.partner==='phil'));assert.equal(JSON.stringify(ledger.view(actors.drj)).includes('pm_fixture'),false);});
test('saving, replacing and removing cards requires new affirmative consent',async()=>{const {ledger,period,o}=await fixture();await ledger.setMethod(actors.drj,'method-1',method);assert.throws(()=>ledger.collectionProposal(actors.drj,o.id));await ledger.consent(actors.drj,'consent-1',{action:'authorize',termsVersion:'v1',termsSha256:proof,maxAmountCents:100,periodId:period.id});assert.equal(ledger.collectionProposal(actors.drj,o.id).moneyMoved,false);await ledger.setMethod(actors.drj,'replace',{...method,reference:'pm_other'});assert.throws(()=>ledger.collectionProposal(actors.drj,o.id));await ledger.removeMethod(actors.drj,'remove');assert.equal(ledger.view(actors.drj).methods.at(-1).state,'REMOVED');});
test('opening credits and adjustments cannot be ignored during collection',async()=>{const {ledger,period,o}=await fixture({brian:0,drj:-200,phil:0});assert.equal(ledger.view(actors.drj).currentBalanceCents,-100);assert.throws(()=>ledger.collectionProposal(actors.drj,o.id));const second=await fixture();await setup(second.ledger,second.period);await second.ledger.adjustment(actors.brian,'credit',{partner:'drj',amountCents:-25,evidenceSha256:proof,reason:'Fixture certified credit',expectedRevision:2});assert.equal(second.ledger.view(actors.drj).currentBalanceCents,75);assert.throws(()=>second.ledger.collectionProposal(actors.drj,second.o.id));});
test('calendar validation rejects rollover and annual export is own-only',async()=>{const {ledger}=await fixture();assert.throws(()=>partnerStatement(ledger.view(actors.drj),{start:'2026-02-30',end:'2026-12-31'}));const annual=annualSummary(ledger.view(actors.drj),2026);assert.equal(annual.closingBalanceCents,100);assert.equal(annual.allocatedExpenses.length,1);assert.equal(annual.allocatedExpenses[0].amountCents,100);assert.match(statementToCsv(annual),/"Opening cents","0"/);});
test('CSV neutralizes spreadsheet formula injection',async()=>{const {ledger}=await fixture();ledger.state.obligations.find(x=>x.partner==='drj').lines[0].vendor='=HYPERLINK("https://bad")';const csv=statementToCsv(annualSummary(ledger.view(actors.drj),2026));assert.ok(csv.includes("'=HYPERLINK"));});
test('AI cannot post, invent provenance, change exact amounts or add control fields',()=>{const input=candidate(),source={sha256:proof,extractedAmountCents:300,currency:'USD',invoiceNumber:'INV-1',assetId:'private:fixture'};const proposal={sourceSha256:proof,...Object.fromEntries(Object.entries(input).filter(([k])=>['vendor','invoiceNumber','amountCents','currency','periodStart','periodEnd','category','description'].includes(k)))};assert.equal(assessAIProposal(proposal,[source]).aiMayPost,false);assert.throws(()=>assessAIProposal({...proposal,amountCents:301},[source]));assert.throws(()=>assessAIProposal({...proposal,approved:true},[source]));const p=proposeExpense(input,{sourceSha256:proof,assetId:source.assetId,sourceKind:'fixture'});assert.equal(classifyExpenseCandidates([p,p]).held[0].reason,'DUPLICATE');assert.equal(classifyExpenseCandidates([{...p,amountCents:1}],[p]).held[0].reason,'CONFLICTING_EVIDENCE');});
test('receipt transport requires fresh server HMAC; sender text is insufficient',()=>{const raw='[]',secret='fixture-secret-not-a-provider-key'.repeat(2),nonce='fixture-nonce-123456',timestamp=Date.now();const signature=createHmac('sha256',secret).update(timestamp+'\n'+nonce+'\n'+raw).digest('hex');assert.deepEqual(authenticateReceiptEnvelope(raw,{timestamp,nonce,signature},secret),[]);assert.throws(()=>authenticateReceiptEnvelope(raw,{timestamp,nonce,signature:'0'.repeat(64)},secret));assert.throws(()=>authenticateReceiptEnvelope(raw,{timestamp:timestamp-400000,nonce,signature},secret));});
test('duplicate amount across periods, aliases, consumed receipts and destination mismatch queue review',async()=>{const {o}=await fixture();const receipt={protocolVersion:2,transportVerified:true,authentication:'gmail_chase_dkim_dmarc_pass',recipient:'Mission Global Group LLC',destination:'info@missionmedinstitute.com',currency:'USD',payer:'Dr J',amountCents:100,fingerprint:'b'.repeat(64),messageFingerprint:'c'.repeat(64),evidenceSha256:proof,receivedAt:stamp};const options={aliases:{drj:['Dr J']}};assert.equal(matchChaseReceipt(receipt,[o],options).matched,true);assert.equal(matchChaseReceipt(receipt,[o,{...o,id:'other'}],options).reason,'MULTIPLE_ELIGIBLE_OBLIGATIONS');assert.equal(matchChaseReceipt(receipt,[o],{aliases:{drj:['Dr J'],phil:['Dr J']}}).matched,false);assert.equal(matchChaseReceipt({...receipt,destination:'old@example.com'},[o],options).matched,false);assert.equal(matchChaseReceipt(receipt,[o],{...options,consumedFingerprints:[receipt.fingerprint]}).matched,false);});
test('default provider gates and shadow collection move no money',async()=>{const {ledger,period,o}=await fixture();await setup(ledger,period);let calls=0;const gateway={assertMutationAllowed(){calls++;},request(){calls++;}};const adapter=new PartnerStripeAdapter({gateway});assert.equal((await adapter.collect(ledger.collectionProposal(actors.drj,o.id))).state,'SHADOW_ONLY');assert.equal(calls,0);await assert.rejects(adapter.collect(ledger.collectionProposal(actors.drj,o.id),{shadow:false}));assert.equal(calls,0);assert.equal((await new PartnerGmailAdapter().receipts({})).state,'DISABLED');assert.equal((await new PartnerVendorAdapter().discover()).state,'DISABLED');assert.equal(environmentPartnerConfig({}).enabled,false);});
test('invalid money authorization expiry fails closed even in Test Mode',async()=>{const {ledger,period,o}=await fixture();await setup(ledger,period);const p=ledger.collectionProposal(actors.drj,o.id);let requests=0;const adapter=new PartnerStripeAdapter({mode:'test',gateway:{assertMutationAllowed(){},request(){requests++;}},moneyAuthorization:{...p,expiresAt:'not-a-date'}});await assert.rejects(adapter.collect(p,{shadow:false}));assert.equal(requests,0);});
test('private REST store rejects unknown operations without network and does not leak upstream errors',async()=>{let calls=0;const store=new PartnerRestStore({url:'https://fixture.example',serviceKey:'fixture-only',fetchImpl:async()=>{calls++;return {ok:false,status:500,json:async()=>({code:'XX',message:'private upstream value'})};}});await assert.rejects(store.rpc('other',{}));assert.equal(calls,0);await assert.rejects(store.rpc('partner_view',{}),e=>!e.message.includes('private upstream'));assert.equal(await store.memberForPrincipal('bad',0),null);});
test('historical receipts require certified coverage assignment and excess credit is never inferred',async()=>{const {ledger,o,period}=await fixture();const evidence={...payment(o,114),receivedAt:'2026-09-20T12:00:00Z',historicalAssignment:{certificationEvidenceSha256:period.certificationEvidenceSha256,reason:'Fixture historical obligation coverage explicitly matched'}};await assert.rejects(ledger.markPartnerPaymentVerifiedAndComplete(actors.brian,'hist-without-credit',evidence));const result=await ledger.markPartnerPaymentVerifiedAndComplete(actors.brian,'hist-certified',{...evidence,excessTreatment:{action:'certified_credit',evidenceSha256:proof,reason:'Fixture excess contribution certified as a credit'}});assert.equal(result.payment.amountAppliedCents,100);assert.equal(result.payment.excessCreditCents,14);assert.equal(ledger.view(actors.drj).currentBalanceCents,-14);assert.equal(ledger.state.adjustments.length,1);assert.equal(result.obligation.status,'PAID');});
test('certified credit allocation changes collectible amount once, without double counting balance',async()=>{const {ledger,period,o}=await fixture();await setup(ledger,period);const {adjustment}=await ledger.adjustment(actors.brian,'refund',{partner:'drj',amountCents:-25,evidenceSha256:proof,reason:'Verified fixture refund',expectedRevision:2});const payload={obligationId:o.id,sourceKind:'adjustment',sourceId:adjustment.id,amountCents:25,evidenceSha256:proof,reason:'Apply verified fixture refund to own obligation',expectedRevision:3};await assert.rejects(ledger.applySettlement(actors.brian,'cross-credit',{...payload,obligationId:ledger.state.obligations.find(x=>x.partner==='phil').id}));const result=await ledger.applySettlement(actors.brian,'apply-credit',payload);assert.equal(result.remainingCents,75);assert.equal(ledger.view(actors.drj).currentBalanceCents,75);assert.equal(ledger.collectionProposal(actors.drj,o.id).amountCents,75);await assert.rejects(ledger.applySettlement(actors.brian,'apply-twice',{...payload,expectedRevision:4}));await assert.rejects(ledger.markPartnerPaymentVerifiedAndComplete(actors.brian,'old-settlement',payment(o,75)));const settled=ledger.state.obligations.find(x=>x.id===o.id);await ledger.markPartnerPaymentVerifiedAndComplete(actors.brian,'net-payment',{...payment(settled,75),expectedSettlementRevision:settled.settlementRevision});assert.equal(ledger.view(actors.drj).currentBalanceCents,0);assert.equal(ledger.state.obligations.find(x=>x.id===o.id).status,'PAID');});
test('positive adjustment stays held until exact obligation allocation',async()=>{const {ledger,period,o}=await fixture();await setup(ledger,period);const {adjustment}=await ledger.adjustment(actors.brian,'debit',{partner:'drj',amountCents:10,evidenceSha256:proof,reason:'Verified fixture correction',expectedRevision:2});assert.throws(()=>ledger.collectionProposal(actors.drj,o.id));await ledger.applySettlement(actors.brian,'apply-debit',{obligationId:o.id,sourceKind:'adjustment',sourceId:adjustment.id,amountCents:10,evidenceSha256:proof,reason:'Allocate correction explicitly',expectedRevision:3});assert.equal(ledger.view(actors.drj).currentBalanceCents,110);assert.equal(ledger.collectionProposal(actors.drj,o.id).amountCents,110);});
test('invoice package validates every original hash and rejects unsafe paths or partial custody',async()=>{const {ledger}=await fixture();const bytes=Buffer.from('%PDF-fixture'),sha=createHash('sha256').update(bytes).digest('hex'),record=annualSummary(ledger.view(actors.drj),2026);record.invoicePackageManifest[0].sha256=sha;const exported=await invoicePackage(record,async()=>({bytes,type:'application/pdf'}));assert.equal(exported.originalCount,1);assert.equal(Buffer.from(exported.base64,'base64').readUInt32LE(0),0x04034b50);assert.equal(crc32(Buffer.from('123456789')),0xcbf43926);await assert.rejects(invoicePackage(record,async()=>({bytes:Buffer.from('wrong'),type:'application/pdf'})));await assert.rejects(invoicePackage(record,async()=>null));assert.throws(()=>privateZip([{name:'../private',bytes}]));assert.throws(()=>privateZip([{name:'a',bytes},{name:'a',bytes}]));});
test('collection revalidates current consent and ownership before any mock dispatch',async()=>{const {ledger,period,o}=await fixture();await setup(ledger,period);const proposal=ledger.collectionProposal(actors.drj,o.id);let calls=0;const gateway={assertMutationAllowed(){},retrievePaymentMethod:async()=>({id:'pm_fixture',customer:'cus_fixture',type:'card'}),retrieve:async()=>({metadata:{domain:'partner_cost_sharing',partner:'drj'}}),request:async()=>{calls++;return{id:'pi_fixture'};}};const moneyAuthorization={...proposal,expiresAt:new Date(Date.now()+60000).toISOString()};const adapter=new PartnerStripeAdapter({mode:'test',gateway,moneyAuthorization,revalidate:()=>ledger.collectionProposal(actors.drj,o.id),reserveDispatch:async p=>({...p,dispatchId:'fixture-only',state:'DISPATCHING'}),recordDispatch:async()=>({fixture:true})});await adapter.collect(proposal,{shadow:false});assert.equal(calls,1);await ledger.consent(actors.drj,'revoke',{action:'revoke'});await assert.rejects(adapter.collect(proposal,{shadow:false}));assert.equal(calls,1);await assert.rejects(adapter.collect({...proposal,methodReference:'pm_wrong'},{shadow:false}));assert.equal(calls,1);});

test('historical payment date is independent of certified expense coverage cutoff',async()=>{const {ledger,o,period}=await fixture();const result=await ledger.markPartnerPaymentVerifiedAndComplete(actors.brian,'after-service-period',{...payment(o),receivedAt:'2026-10-01T00:00:00Z',historicalAssignment:{certificationEvidenceSha256:period.certificationEvidenceSha256,reason:'Fixture original payment settles September coverage after period end'}});assert.equal(result.obligation.status,'PAID');});
test('consent revoked during provider ownership lookup cannot reach dispatch',async()=>{const {ledger,period,o}=await fixture();await setup(ledger,period);const p=ledger.collectionProposal(actors.drj,o.id);let calls=0;const gateway={assertMutationAllowed(){},retrievePaymentMethod:async()=>{await ledger.consent(actors.drj,'during-lookup',{action:'revoke'});return {id:'pm_fixture',customer:'cus_fixture',type:'card'};},retrieve:async()=>({metadata:{domain:'partner_cost_sharing',partner:'drj'}}),request:async()=>{calls++;return {id:'pi_fixture'};}};const adapter=new PartnerStripeAdapter({mode:'test',gateway,moneyAuthorization:{...p,expiresAt:new Date(Date.now()+60000).toISOString()},revalidate:()=>ledger.collectionProposal(actors.drj,o.id),reserveDispatch:async p=>({...p,dispatchId:'fixture',state:'DISPATCHING'}),recordDispatch:async()=>({})});await assert.rejects(adapter.collect(p,{shadow:false}));assert.equal(calls,0);});

test('private custodian is disabled by default, rejects mismatched readback and stages exact originals only',async()=>{const {PartnerEvidenceCustodian}=await import('../src/partner-cost-sharing/custody.mjs');let registrations=0;const bytes=Buffer.from('%PDF-1.4 fixture original'),objects=new Map();assert.equal((await new PartnerEvidenceCustodian().preserve(bytes,{sourceId:'fixture'})).state,'DISABLED');await assert.rejects(new PartnerEvidenceCustodian({mode:'local'}).preserve(bytes,{sourceId:'fixture'}));const options={mode:'local',privateWriteApproved:true,put:async(k,b)=>objects.set(k,b),read:async k=>objects.get(k),register:async()=>registrations++};const result=await new PartnerEvidenceCustodian(options).preserve(bytes,{sourceId:'fixture-original'});assert.equal(result.sha256,createHash('sha256').update(bytes).digest('hex'));assert.equal(registrations,1);await assert.rejects(new PartnerEvidenceCustodian({...options,read:async()=>Buffer.from('corrupt')}).preserve(bytes,{sourceId:'fixture-corrupt'}));assert.equal(registrations,1);});

test('setup and removal enforce own partner customer before provider mutation',async()=>{let mutations=0;const gateway={assertMutationAllowed(){},retrieve:async()=>({metadata:{domain:'partner_cost_sharing',partner:'phil'}}),retrievePaymentMethod:async()=>({id:'pm_fixture',customer:'cus_fixture',type:'card'}),request:async()=>{mutations++;},detachPaymentMethod:async()=>{mutations++;}};const adapter=new PartnerStripeAdapter({mode:'test',gateway});await assert.rejects(adapter.createSetupIntent({partner:'drj',customerReference:'cus_fixture'},'fixture-request'));await assert.rejects(adapter.removeMethod({partner:'drj',customerReference:'cus_fixture',methodReference:'pm_fixture'},'fixture-request'));assert.equal(mutations,0);});
test('custody retries read the exact existing private original without overwriting',async()=>{const {PartnerEvidenceCustodian}=await import('../src/partner-cost-sharing/custody.mjs');const originals=new Map();let writes=0;const c=new PartnerEvidenceCustodian({mode:'local',privateWriteApproved:true,read:async k=>originals.get(k),put:async(k,b)=>{writes++;originals.set(k,b);},register:async()=>{}}),bytes=Buffer.from('%PDF-1.4 fixture');const a=await c.preserve(bytes,{sourceId:'fixture'}),b=await c.preserve(bytes,{sourceId:'fixture'});assert.equal(a.sha256,b.sha256);assert.equal(writes,1);});

test('partial canonical payment advances the generation for a distinct remaining collection',async()=>{const {ledger,period,o}=await fixture();await setup(ledger,period);const before=ledger.collectionProposal(actors.drj,o.id);await ledger.markPartnerPaymentVerifiedAndComplete(actors.brian,'partial-generation',payment(o,40));const after=ledger.collectionProposal(actors.drj,o.id);assert.equal(after.amountCents,60);assert.notEqual(after.idempotencyKey,before.idempotencyKey);assert.ok(after.settlementRevision>before.settlementRevision);});
