import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {buildAccountingReview,projectAccountingReview,accountingReviewCsv} from '../src/partner-cost-sharing/accounting-review.mjs';
import {createPartnerCostRouter} from '../src/partner-cost-sharing/router.mjs';
const fixture=()=>({schema:'pcs-private-accounting-review-v1',asOf:'2026-10-04',rows:[],contributions:[{partner:'drj',amountCents:89300,receivedAt:'2026-05-09',state:'FOUNDER_ATTESTED_UNASSIGNED'},{partner:'phil',amountCents:90000,receivedAt:'2026-07-02',state:'SOURCE_AUTHENTICATED_UNASSIGNED'}],workspace:{paymentTodayCents:31997,totalNetChargesCents:74932,totalPaymentsCents:74592,vendorOutstandingCents:340}});
const row=(id,changes={})=>({id,vendor:'Fixture hosting',invoiceNumber:id,recordedAt:'2026-07-24',dateBasis:'BILLING_HISTORY',paidAt:'2026-07-24',periodStart:'2026-07-24',periodEnd:'2026-08-24',amountCents:5000,status:'PAID',purpose:'SHARED',legacy:'NOT_IN_OLD_HTML',description:'Synthetic invoice fixture',evidenceKind:'PROVIDER_METADATA',evidenceSha256:'a'.repeat(64),originalSha256:null,...changes});
test('review separates settled annual costs, forecasts, attribution, accruals and credits from paid candidates',()=>{
 const f=fixture();f.rows=[row('new'),row('covered-annual',{legacy:'INCLUDED',amountCents:47800,periodStart:'2026-01-12',periodEnd:'2027-01-12'}),row('accrual',{status:'ACCRUED',paidAt:null,amountCents:340}),row('forecast',{status:'FORECAST',recordedAt:'2026-10-23',paidAt:null}),row('personal',{purpose:'PENDING'}),row('credit-conflict',{status:'QUARANTINED'}),row('late-prior-period',{recordedAt:'2026-07-01',periodStart:'2026-06-01',periodEnd:'2026-06-30'})];
 const r=buildAccountingReview(f),v=projectAccountingReview(r,{key:'drj',prototype:true});assert.equal(v.scenarios[1].totalCents,5000);assert.equal(v.scenarios[1].ownShareCents,1667);assert.equal(v.currentBalanceCents,null);assert.equal(v.certified,false);assert.equal(v.collectionEnabled,false);assert.equal(v.outstandingCostCents,340);assert.equal(v.pendingPurposeCents,null);assert.equal(projectAccountingReview(r,{key:'brian',prototype:true}).pendingPurposeCents,5000);assert.deepEqual(v.scenarios[1].invoiceIds,['new']);assert.ok(!v.rows.some(r=>['personal','credit-conflict','forecast'].includes(r.id)));assert.ok(!accountingReviewCsv(v,'drj').includes('personal'));assert.equal(v.workspace.paymentTodayCents,undefined);
});
test('cutoff alternatives share one census, flag boundary uncertainty and allocate exact cents without subtracting receipts',()=>{
 const f=fixture();f.rows=[row('june',{recordedAt:'2026-06-24',paidAt:'2026-06-24',periodStart:null,periodEnd:null}),row('july',{amountCents:5001,periodStart:'2026-06-29'})];const r=buildAccountingReview(f);
 const views=['brian','drj','phil'].map(key=>projectAccountingReview(r,{key,prototype:true}));assert.equal(views[0].scenarios[0].totalCents,10001);assert.equal(views[0].scenarios[1].totalCents,5001);assert.equal(views[0].scenarios[1].unresolvedEarlierCents,5000);assert.equal(views[0].scenarios[1].unresolvedEarlierCount,1);for(let i=0;i<2;i++)assert.equal(views.reduce((s,v)=>s+v.scenarios[i].ownShareCents,0),views[0].scenarios[i].totalCents);assert.equal(views[0].scenarios[1].boundaryInvoiceCount,1);assert.equal(r.rows.length,2);assert.equal(r.contributions.length,2);
});
test('review rejects duplicate invoices, fractional/future paid amounts, private fields and unreconciled vendor payments',()=>{
 let f=fixture();f.rows=[row('duplicate'),row('duplicate')];assert.throws(()=>buildAccountingReview(f),/Duplicate/);
 f=fixture();f.rows=[row('same-id'),row('same-id',{vendor:'Other vendor',invoiceNumber:'other-invoice'})];assert.throws(()=>buildAccountingReview(f),/Duplicate review row identity/);
 for(const changes of [{amountCents:1.5},{recordedAt:'2026-10-23'},{sourceUrl:'https://private.invalid'},{invoiceNumber:'../../private'},{evidenceKind:'ORIGINAL_HASHED'},{periodStart:'2026-08-25',periodEnd:'2026-08-24'}]){f=fixture();f.rows=[row('bad',changes)];assert.throws(()=>buildAccountingReview(f));}
 f=fixture();f.workspace.totalPaymentsCents=0;assert.throws(()=>buildAccountingReview(f),/do not reconcile/);
});
test('partner projections and exports redact other contributions and evidence hashes; real workpapers cannot activate production',()=>{
 const f=fixture();f.rows=[row('safe')];const r=buildAccountingReview(f);const drj=projectAccountingReview(r,{key:'drj',prototype:true}),brian=projectAccountingReview(r,{key:'brian',prototype:true});assert.deepEqual(drj.contributions.map(x=>x.partner),['drj']);assert.equal(drj.rows[0].evidenceSha256,undefined);assert.equal(brian.contributions.length,2);const csv=accountingReviewCsv(drj,'drj');assert.ok(!csv.includes('Phil'));assert.ok(!csv.includes('90000'));assert.match(csv,/NOT CERTIFIED OR PAYABLE/);assert.match(csv,/UNKNOWN/);assert.throws(()=>projectAccountingReview(r,{key:'phil',prototype:false}));assert.throws(()=>createPartnerCostRouter({config:{partnerCostSharing:{enabled:true,accountingReview:r}},authenticate:()=>null}),/isolated local/);
});
test('HTTP review bootstrap and CSV are own-only, private, read-only and disabled by default',async()=>{
 const f=fixture();f.rows=[row('safe')];const r=buildAccountingReview(f);
 const route=createPartnerCostRouter({config:{localAuth:true,production:false,partnerCostSharing:{enabled:true,prototype:true,accountingReview:r}},authenticate:()=>null});
 const server=createServer(async(req,res)=>{try{if(!await route(req,res,new URL(req.url,'http://fixture'))){res.writeHead(404);res.end();}}catch(e){res.writeHead(e.status||500);res.end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port+'/api/partner-cost-sharing/';
 try{for(const key of ['drj','phil']){const headers={cookie:'pcs_prototype_lens='+key};const response=await fetch(url+'bootstrap',{headers});const v=await response.json();assert.equal(response.headers.get('cache-control'),'no-store, private');assert.equal(v.currentBalanceCents,null);assert.deepEqual(v.accountingReview.contributions.map(x=>x.partner),[key]);const exported=await fetch(url+'accounting-review-export',{headers});const csv=(await exported.json()).csv;assert.ok(!csv.includes(key==='drj'?'Phil':'Dr J'));assert.match(csv,/UNKNOWN/);}const posted=await fetch(url+'accounting-review-export',{method:'POST'});assert.equal(posted.status,404);assert.equal(r.certified,false);}finally{await new Promise(resolve=>server.close(resolve));}
});

test('production private draft uses signed exact membership, ignores prototype cookies, redacts own exports and holds every command',async()=>{
 const f=fixture();f.rows=[row('shared'),row('pending',{purpose:'PENDING'})];
 const identities={brian:{userId:'10000000-0000-4000-8000-000000000001',wpUserId:101},drj:{userId:'10000000-0000-4000-8000-000000000002',wpUserId:102},phil:{userId:'10000000-0000-4000-8000-000000000003',wpUserId:103},other:{userId:'10000000-0000-4000-8000-000000000004',wpUserId:104}};
 let executeCount=0,missing=false,originalReads=0;
 const memberStore={memberForPrincipal:async(p,w)=>{const key=Object.keys(identities).find(k=>k!=='other'&&identities[k].userId===p&&identities[k].wpUserId===w);return key?{key,active:true}:null;},accountingReview:async()=>missing?null:f,readReviewOriginal:async()=>{originalReads++;return {bytes:Buffer.from('fixture'),sha256:'b'.repeat(64),type:'application/pdf',filename:'fixture.pdf'};},view:()=>{throw Error('Draft must not consult certified journal');},execute:()=>{executeCount++;}};
 const settings={enabled:true,prototype:false,readOnly:true,brianOnly:false};
 const route=createPartnerCostRouter({config:{production:true,partnerCostSharing:settings},authenticate:async req=>{const key=String(req.headers.authorization||'').replace('Bearer ','');if(!identities[key])throw Object.assign(Error('Authentication required'),{status:401});return identities[key];},memberStore});
 const server=createServer(async(req,res)=>{try{if(!await route(req,res,new URL(req.url,'http://fixture'))){res.writeHead(404);res.end();}}catch(e){res.writeHead(e.status||500);res.end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port+'/api/partner-cost-sharing/';
 try{
  assert.equal((await fetch(url+'bootstrap',{headers:{cookie:'pcs_prototype_lens=brian'}})).status,401);
  assert.equal((await fetch(url+'bootstrap',{headers:{authorization:'Bearer other',cookie:'pcs_prototype_lens=brian'}})).status,404);
  for(const key of ['brian','drj','phil']){const headers={authorization:'Bearer '+key,cookie:'pcs_prototype_lens=brian'};const response=await fetch(url+'bootstrap',{headers});assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store, private');const v=await response.json();assert.equal(v.partner.key,key);assert.equal(v.prototype,false);assert.equal(v.certified,false);assert.equal(v.currentBalanceCents,null);assert.equal(v.accountingReview.collectionEnabled,false);assert.equal(v.accountingReview.rows.length,key==='brian'?2:1);assert.equal(v.ledger,undefined);if(key!=='brian'){assert.deepEqual(v.accountingReview.contributions.map(p=>p.partner),[key]);assert.equal(v.accountingReview.rows[0].evidenceSha256,undefined);assert.equal((await fetch(url+'admin',{headers})).status,403);}const csv=(await (await fetch(url+'accounting-review-export',{headers})).json()).csv;assert.match(csv,/UNKNOWN/);if(key!=='brian')assert.ok(!csv.includes(key==='drj'?'Phil':'Dr J'));}
  let headers={authorization:'Bearer drj'};
  assert.equal((await fetch(url+'invoices/pending/document',{headers})).status,404);assert.equal((await fetch(url+'invoices/unknown/document',{headers})).status,404);assert.equal(originalReads,0);
  f.rows[0].originalSha256='a'.repeat(64);assert.equal((await fetch(url+'invoices/shared/document',{headers})).status,409);assert.equal(originalReads,1);
  f.rows[0].status='QUARANTINED';assert.equal((await fetch(url+'invoices/shared/document',{headers})).status,404);assert.equal(originalReads,1);
  assert.equal((await fetch(url+'statement-export',{headers})).status,200);assert.equal((await fetch(url+'statement-export?year=2026',{headers})).status,409);
  settings.brianOnly=true;assert.equal((await fetch(url+'bootstrap',{headers:{authorization:'Bearer drj'}})).status,404);settings.brianOnly=false;
  for(const command of ['ingest','reviewExpense','certifyPeriod','reportSent','verifyPayment','adjustment','applySettlement','consent','method'])assert.equal((await fetch(url+'commands/'+command,{method:'POST',headers:{authorization:'Bearer brian'},body:'{}'})).status,409);
  missing=true;assert.equal((await fetch(url+'bootstrap',{headers:{authorization:'Bearer brian'}})).status,503);assert.equal((await fetch(url+'commands/certifyPeriod',{method:'POST',headers:{authorization:'Bearer brian'},body:'{}'})).status,409);assert.equal(executeCount,0);
  settings.enabled=false;assert.equal((await fetch(url+'bootstrap',{headers:{authorization:'Bearer brian'}})).status,404);
 }finally{await new Promise(resolve=>server.close(resolve));}
});
