import fs from 'node:fs';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
if(process.env.MR_V2_LEASE_ACTIVE!=='1')throw Error('Heartbeat-protected exact-path lease required');
const base='wp-content/mu-plugins/missionmed-mr-alternate-assets',runtime='/www/theresidencyacademy_209/public';
const custody='/www/theresidencyacademy_209/private/mr-landing-page-versions-20260930';
const files=['alternate.css','alternate.js','page.php'];
const manifest=JSON.parse(fs.readFileSync(new URL('./MR-LANDING-PAGE-V1.json',import.meta.url)));
const old=Object.fromEntries(files.map(f=>[f,manifest.assetHashes.find(x=>x.path===base+'/'+f).sha256]));
const hashes=Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(base+'/'+f)).digest('hex')]));
const q=s=>`'${s.replaceAll("'","'\\''")}'`;
const ssh=s=>execFileSync('ssh',['missionmed-kinsta',`set -eu; cd ${q(runtime)}; ${s}`],{encoding:'utf8',timeout:25000});
const guard=Object.entries(old).map(([f,h])=>`test "$(sha256sum ${q(base+'/'+f)} | cut -d' ' -f1)" = ${q(h)}; test "$(sha256sum ${q(custody+'/MR-LANDING-PAGE-V1/'+f)} | cut -d' ' -f1)" = ${q(h)}`).join('; ');
const protect=`sha256sum wp-content/mu-plugins/missionmed-mr*.php ${q(base+'/match-day-media.json')} ${q(base+'/match-day-player.php')}`;
const protectedBefore=ssh(protect);
console.log(ssh(`${guard}; test ! -e ${q(custody+'/MR-LANDING-PAGE-V2')}; umask 077; mkdir ${q(custody+'/MR-LANDING-PAGE-V2')}`));
for(const f of files)execFileSync('scp',[base+'/'+f,`missionmed-kinsta:${custody}/MR-LANDING-PAGE-V2/${f}`],{timeout:25000});
const verify=files.map(f=>`test "$(sha256sum ${q(custody+'/MR-LANDING-PAGE-V2/'+f)} | cut -d' ' -f1)" = ${q(hashes[f])}`).join('; ');
const install=files.map(f=>`install -m 644 ${q(custody+'/MR-LANDING-PAGE-V2/'+f)} ${q(base+'/'+f+'.v2-next')}; mv ${q(base+'/'+f+'.v2-next')} ${q(base+'/'+f)}`).join('; ');
console.log(ssh(`${guard}; ${verify}; php -l ${q(custody+'/MR-LANDING-PAGE-V2/page.php')}; ${install}; sha256sum ${files.map(f=>q(base+'/'+f)).join(' ')}`));
const protectedAfter=ssh(protect);if(protectedBefore!==protectedAfter)throw Error('Unrelated runtime drift - stop');
const receipt={at:new Date().toISOString(),source:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),custody,files,preimages:old,deployed:hashes,protectedBefore,protectedAfter,protectedUnchanged:true};
fs.writeFileSync(new URL('./qa/deployment.json',import.meta.url),JSON.stringify(receipt,null,2));console.log(JSON.stringify({deployed:3,protectedUnchanged:true,custody}));
