#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/../../../.." && pwd)"
commerce="$root/wp-content/mu-plugins/missionmed-drj-examprep-commerce.php"
access="$root/wp-content/mu-plugins/missionmed-drj-drills-access.php"
bridge="$root/wp-content/mu-plugins/missionmed-drills-oncall-enrollment.php"

php -l "$commerce"
php -l "$access"
php -l "$bridge"
rg -q "MMDRJ_VERSION[[:space:]]*=[[:space:]]*'1\.2\.0'" "$commerce"
rg -q "MMDRJ_ARENA_PRO_PRODUCT_ID[[:space:]]*=[[:space:]]*9017" "$commerce"
rg -q "set_discount_type\( 'recurring_fee' \)" "$commerce"
rg -q "set_amount\( '50\.00' \)" "$commerce"
rg -q "'amount_cents' => 4999" "$commerce"
! rg -q "recurring_product|set_amount\( '60\.00' \)|'amount_cents' => 3999" "$commerce"
rg -q "mmdrj_reconcile_daily_rounds_user" "$commerce"
rg -q "missionmed_access_drj_drills" "$commerce"
rg -q "ExamPrep: Arena Pro is coming soon" "$commerce"
rg -q 'aria-disabled="true"' "$commerce"
rg -q "mmdrj_examprep_payment_gateways" "$commerce"
rg -q "unset.*bacs" "$commerce"
rg -q "mmdoc_drills_oncall_product_ids" "$bridge"
rg -q "positive_daily_route_guard" "$access"
rg -q "missionmed_access_arena_pro" "$access"
echo "DRJ_EXAMPREP_0920A_CONTRACT_CHECKS_PASS"
