// Guarded disposable PG18 + real HTTP/RLS. Auth and RISE responses are synthetic trusted seams.
import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{execFileSync}from'node:child_process';import{randomUUID,randomInt,createHash}from'node:crypto';import{createServer}from'node:http';import{once}from'node:events';
import{initializeHarness,localToolEnvironment,assertDisposableTarget,qualifyDisposableConnection}from'../../scripts/disposable-db-guard.mjs';import{migrate}from'../../scripts/migrate.mjs';import{createDatabase}from'../../server/db.mjs';import{createCommands}from'../../server/commands.mjs';import{createHandler}from'../../server/http.mjs';import{MRX_AREAS}from'../../server/research-standard.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex');
test('LOI append-only owner lifecycle, current evidence, HTTP and real RLS',async t=>{
 const bin='/opt/homebrew/opt/postgresql@18/bin/',env=localToolEnvironment(),dir=fs.mkdtempSync('/tmp/iiq-pg18.');fs.chmodSync(dir,0o700);const marker=initializeHarness(dir);fs.mkdirSync(dir+'/socket',{mode:0o700});let started=false,database,server;
 const pg=(name,args)=>execFileSync(bin+name,args,{env,stdio:['ignore','pipe','pipe']});
 try{
  pg('initdb',['-D',dir+'/data','-A','trust','--no-locale','-U','iiq_test_admin']);pg('pg_ctl',['-D',dir+'/data','-l',dir+'/server.log','-o',`-k ${dir}/socket -h '' -p 55432 -c cluster_name=${marker}`,'-w','start']);started=true;
  pg('createdb',['-h',dir+'/socket','-p','55432','-U','iiq_test_admin','iiq_test']);const url=role=>`postgresql://${role}@localhost/iiq_test?host=${dir}/socket&port=55432`,adminUrl=url('iiq_test_admin');await migrate({connectionString:adminUrl,local:true,bootstrap:true,log:()=>{}});
  pg('psql',['-h',dir+'/socket','-p','55432','-U','iiq_test_admin','-d','iiq_test','-v','ON_ERROR_STOP=1','-c','CREATE ROLE iiq_runtime_test LOGIN NOINHERIT NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE; GRANT iiq_authenticated TO iiq_runtime_test WITH INHERIT FALSE, SET TRUE;']);
  assertDisposableTarget(url('iiq_runtime_test'),{role:'iiq_runtime_test'});database=createDatabase({databaseUrl:url('iiq_runtime_test')});await qualifyDisposableConnection(database.pool,url('iiq_runtime_test'),{role:'iiq_runtime_test'});await database.verifyRuntimeRole();
  const base=randomInt(1000000,100000000),make=(role,i)=>({id:randomUUID(),wpUserId:base+i,role,tier:role==='student'?'360':role,eligible:true,displayName:'SYNTHETIC LOI '+role,firstName:'Synthetic',zone:'America/New_York',assignments:[]});const a=make('student',1),b=make('student',2),admin=make('admin',3),mentor=make('mentor',4),actors={a,b,admin,mentor};
  let now=Date.now(),bad='',dispatches=0;const program={id:'synthetic-loi-program',name:'Synthetic Program',track:'Preliminary',registryReleaseId:'synthetic_registry_v1'},second={...program,id:'synthetic-second-program',name:'Synthetic Second Program',track:'Categorical'},programs=[program,second],detail='The curriculum includes supervised continuity care',motivation='I value continuity and careful follow-up.';
  function research(p=program){const coverage={programId:p.id,registryReleaseId:p.registryReleaseId,observedAt:new Date(now-(bad==='stale'?300001:0)).toISOString(),fields:Object.entries(MRX_AREAS).flatMap(([area,fields])=>fields.map(field=>({area,field,state:field==='research.curriculum'?(bad==='conflicted'?'CONFLICTED':'SUPPORTED'):'UNKNOWN'}))).sort((a,b)=>a.field.localeCompare(b.field,'en'))};coverage.receipt={sha256:hash(JSON.stringify(coverage)),publicRef:'rise-coverage-v1'};const body={schema:'rise-interviewiq-research-results-v1',coverage,facts:[{area:'curriculum_training',field:'research.curriculum',state:'SUPPORTED',claimRef:'rise-claim:'+hash('synthetic curriculum'),value:bad==='changed'?'Changed verified detail':detail,retrievedAt:new Date(now-10000).toISOString(),asOf:{kind:'historical',label:'2026 Preliminary'},sources:[{claimRef:'rise-claim:'+hash('synthetic source'),reviewRef:null,urls:['https://hospital.edu/curriculum'],retrievedAt:new Date(now-10000).toISOString(),reviewedAt:null}]}]};return{...body,receipt:{sha256:hash(JSON.stringify(body)),publicRef:'rise-results-v1'}};}
  const owners={async context(){return{};},async getProgram(actor,id){const p=programs.find(p=>p.id===id);assert.ok(p,'qualified registry ID');return{...p};},async searchPrograms(){return{registryReleaseId:program.registryReleaseId,programs:programs.map(p=>({...p})),page:1,total:programs.length};},async getProgramResearch(actor,id){if(bad==='unavailable')throw Error('SYNTHETIC_UNAVAILABLE');return research(programs.find(p=>p.id===id));},async storyConsent(){},async validateBasis(){return{};}};
  const config={enabled:true,coreOnly:true,publicOrigin:'https://missionmed.test',maxBodyBytes:262144,gatewaySecret:'synthetic-private-gateway-key-'.repeat(2),loi:{enabled:true,ownerId:a.id,programId:program.id}},factory=c=>createCommands({database,owners,config:c,clock:()=>new Date(now),researchTransport:async()=>{dispatches++;throw Error('UNEXPECTED_RESEARCH_DISPATCH');}}),commands=factory(config),full=factory({...config,coreOnly:false});
  const envelope=async(who,command,data={},interviewId=null,c=commands)=>({command,data,interviewId,expectedVersion:(await (who.role==='mentor'?full:c).bootstrap(who)).version,requestId:randomUUID()});
  const run=async(who,command,data={},interviewId=null,c=commands)=>c.execute(who,await envelope(who,command,data,interviewId,c));
  for(const actor of Object.values(actors))await (actor.role==='mentor'?full:commands).bootstrap(actor);
  const iid=(await run(a,'interview.create',{program:program.id,programName:program.name,schedule:{date:'2026-11-01',time:'01:30',zone:'America/New_York',fold:0,duration:45}},null,full)).interviewId;
  const other=(await run(b,'interview.create',{program:program.id,programName:program.name},null,full)).interviewId;
  const old=[null,'legacy',{unknown:'retain exactly'}];await database.withActor(a,db=>db.query(`INSERT INTO iiq.preparation(owner_id,interview_id,why_program,questions,basis,anchors) VALUES($1,$2,'Old Why Program','[{"text":"Old question"}]','{"edited":true}',$3::jsonb)`,[a.id,iid,JSON.stringify(old)]),{write:true});
  const prep=()=>database.withActor(a,async db=>(await db.query('SELECT * FROM iiq.preparation WHERE owner_id=$1 AND interview_id=$2',[a.id,iid])).rows[0]);const baseline=await database.withActor(a,async db=>(await db.query('SELECT to_jsonb(i) AS row FROM iiq.interviews i WHERE id=$1',[iid])).rows[0].row);
  const logs=[];server=createServer(createHandler({config,database,commands,owners,authorize:async req=>{const actor=actors[req.headers['x-synthetic-actor']];if(!actor)throw Error('deny');return actor;},logger:x=>logs.push(x)}));server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;
  const http=async(who,body)=>{const r=await fetch(origin+'/api/commands',{method:'POST',headers:{'content-type':'application/json',origin:config.publicOrigin,'x-synthetic-actor':who,'x-mmed-iiq-gateway':config.gatewaySecret},body:JSON.stringify(body)});return{status:r.status,body:await r.json()};};
  const send=async(command,data={},id=iid)=>{const req=await envelope(a,command,data,id),r=await http('a',req);assert.equal(r.status,200,r.body.error?.code);return{req,r:r.body};};
  const saveData={letterId:null,expectedHead:null,expectedLetterVersion:0,text:`Dear ${program.name},\n${motivation}\n${detail}`,context:{whyNow:'Following my interview',applicationState:'Applied',interviewState:'Completed'},motivations:[{id:randomUUID(),text:motivation,confirmed:true}],facts:[],storyRefs:[],selectedEvidence:[{field:'research.curriculum',claimRef:'rise-claim:'+hash('synthetic curriculum')}],studentFactualConfirmation:true,studentSpecificityConfirmation:true};let head;
  const current=async()=>{const r=await commands.bootstrap(a);return r.state.loi[iid].current;};const saveHead=x=>({letterId:x.letterId,expectedHead:x.revisionId,expectedLetterVersion:x.letterVersion});const headData=x=>({letterId:x.letterId,expectedHead:x.revisionId,expectedLetterVersion:x.letterVersion,contentHash:x.contentHash});
  await t.test('readonly evidence/export consume no workspace revision; missing/unknown fields denied',async()=>{const v=(await commands.bootstrap(a)).version;const e=await send('loi.evidence');assert.equal(e.r.research.facts[0].asOf.label,'2026 Preliminary');await send('loi.export');assert.equal((await commands.bootstrap(a)).version,v);const req=await envelope(a,'loi.evidence',{ownerId:b.id},iid);assert.equal((await http('a',req)).status,422);});
  await t.test('save/replay append once preserving old preparation and Calendar',async()=>{const {req}=await send('loi.save',saveData);assert.equal((await http('a',req)).body.replayed,true);head=await current();assert.equal(head.letterVersion,1);const p=await prep();assert.deepEqual(p.anchors.slice(0,3),old);assert.equal(p.anchors.length,4);assert.equal(p.why_program,'Old Why Program');assert.equal(p.questions[0].text,'Old question');assert.deepEqual((await database.withActor(a,async db=>(await db.query('SELECT to_jsonb(i) AS row FROM iiq.interviews i WHERE id=$1',[iid])).rows[0].row)),baseline);});
  await t.test('owner B/admin/mentor cannot read/export/evidence/write; RLS denies B private rows',async()=>{for(const who of ['b','admin','mentor'])for(const cmd of ['loi.export','loi.evidence','loi.save','loi.mark_sent'])assert.equal((await http(who,await envelope(actors[who],cmd,{},iid))).status,403);assert.equal((await database.withActor(b,db=>db.query('SELECT anchors FROM iiq.preparation WHERE interview_id=$1',[iid]))).rowCount,0);assert.equal((await http('a',await envelope(a,'loi.export',{},other))).status,404);const preview=await commands.bootstrap(admin);assert.deepEqual(Object.keys(preview.state.loi),[]);assert.equal(preview.capabilities.loi,false);});
  await t.test('stale/conflicted/changed evidence and invented approval fail without append',async()=>{const n=(await prep()).anchors.length;for(const mode of ['stale','conflicted','changed']){bad=mode;assert.notEqual((await http('a',await envelope(a,'loi.approve',{...headData(head),studentFactualConfirmation:true,studentSpecificityConfirmation:true},iid))).status,200);}bad='';assert.equal((await http('a',await envelope(a,'loi.approve',{...headData(head),approval:{approved:true},studentFactualConfirmation:true,studentSpecificityConfirmation:true},iid))).status,422);assert.equal((await prep()).anchors.length,n);});
  let handoff;
  await t.test('approve immutable child, compose exact approved bytes, replay and self-reported sent persist',async()=>{await send('loi.approve',{...headData(head),studentFactualConfirmation:true,studentSpecificityConfirmation:true});const approved=await current();assert.equal(approved.state,'approved');assert.equal(approved.text,head.text);assert.equal(approved.parentRevisionId,head.revisionId);head=approved;const {req,r}=await send('loi.handoff',{...headData(head),recipient:'program@hospital.edu',subject:'Letter & Interest',channel:'gmail',recipientConfirmed:true});handoff=r.handoff;assert.equal(new URL(handoff.gmailUrl).searchParams.get('body'),head.text);assert.equal((await http('a',req)).body.handoff.gmailUrl,handoff.gmailUrl);const n=(await prep()).anchors.length;const sent=await send('loi.mark_sent',{...headData(head),handoffId:handoff.handoffId,confirmed:true});await http('a',sent.req);assert.equal((await prep()).anchors.length,n+1);const e=(await send('loi.export')).r.export;assert.equal(e.history.at(-1).state,'self_reported_sent');assert.equal(e.history.at(-1).verified,undefined);assert.equal((await http('a',await envelope(a,'loi.mark_sent',{...headData(head),handoffId:handoff.handoffId,confirmed:true},iid))).status,409);});
  await t.test('parallel prep.save/version and head conflicts preserve approved bytes; edit creates draft child',async()=>{const before=(await prep()).anchors;const req=await envelope(a,'loi.save',{...saveData,...saveHead(head),text:head.text+'\nEdited draft'},iid),prepReq=await envelope(a,'prep.save',{why:{text:'Updated own Why Program',edited:true}},iid,full);const outcomes=await Promise.allSettled([commands.execute(a,req),full.execute(a,prepReq)]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal(outcomes.filter(x=>x.status==='rejected')[0].reason.code,'version_conflict');assert.deepEqual((await prep()).anchors.slice(0,before.length),before);head=await current();if(head.state==='approved'){await send('loi.save',{...saveData,...saveHead(head),text:head.text+'\nEdited draft'});head=await current();}assert.equal(head.state,'draft');const n=(await prep()).anchors.length;assert.equal((await http('a',await envelope(a,'loi.save',saveData,iid))).status,409);assert.equal((await prep()).anchors.length,n);});
  await t.test('consent revoke prevents approval; future schemas and retarget history fail closed',async()=>{await run(a,'story.consent',{storyId:'synthetic-story',consent:true},null,full);await send('loi.save',{...saveData,...saveHead(head),storyRefs:[{id:'synthetic-story'}]});head=await current();const before=(await prep()).anchors;await run(a,'story.consent',{storyId:'synthetic-story',consent:false},null,full);assert.deepEqual((await prep()).anchors,before);assert.equal((await commands.bootstrap(a)).state.loi[iid].currentConsentValid,false);assert.equal((await http('a',await envelope(a,'loi.approve',{...headData(head),studentFactualConfirmation:true,studentSpecificityConfirmation:true},iid))).status,409);await database.withActor(a,db=>db.query('UPDATE iiq.preparation SET anchors=anchors||$3::jsonb WHERE owner_id=$1 AND interview_id=$2',[a.id,iid,JSON.stringify([{type:'iiq.loi.revision',schemaVersion:99}])]),{write:true});assert.equal((await http('a',await envelope(a,'loi.save',{...saveData,...saveHead(head)},iid))).status,409);const retained=(await prep()).anchors;await run(a,'interview.identity',{programName:'Retargeted manual',track:'Categorical'},iid,full);assert.equal((await commands.bootstrap(a)).state.loi[iid],undefined);assert.deepEqual((await prep()).anchors,retained);assert.equal((await http('a',await envelope(a,'loi.handoff',{...headData(head),recipient:'program@hospital.edu',subject:'Interest',channel:'copy',recipientConfirmed:true},iid))).status,403);});
  await t.test('eligible A/B canonical lookup and attachment support owned LOI without research effects',async()=>{
   b.tier='ivprep_complete';const eligibleConfig={...config,loi:{enabled:true,mode:'ELIGIBLE'}},eligible=factory(eligibleConfig),eligibleFull=factory({...eligibleConfig,coreOnly:false});let s;
   const noResearch=who=>database.withActor(who,async db=>({demands:(await db.query('SELECT count(*)::int AS n FROM iiq.research_demands WHERE owner_id=$1',[who.id])).rows[0].n,grants:(await db.query('SELECT count(*)::int AS n FROM iiq.research_job_grants WHERE owner_id=$1',[who.id])).rows[0].n}));
   const priorA=await noResearch(a),priorB=await noResearch(b);
   const call=async(who,path,body)=>{const r=await fetch(`http://127.0.0.1:${s.address().port}`+path,{method:body?'POST':'GET',headers:{origin:config.publicOrigin,'x-synthetic-actor':who,'x-mmed-iiq-gateway':config.gatewaySecret,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return{status:r.status,body:await r.json()};};
   const sendAs=async(who,command,data={},id=null)=>call(who,'/api/commands',await envelope(actors[who],command,data,id,eligible));
   try{
    s=createServer(createHandler({config:eligibleConfig,database,commands:eligible,owners,authorize:async req=>actors[req.headers['x-synthetic-actor']]}));s.listen(0,'127.0.0.1');await once(s,'listening');
    for(const who of ['a','b']){const read=await call(who,'/api/bootstrap');assert.equal(read.body.capabilities.loi,true);assert.equal(read.body.capabilities.loiCanonicalLookup,true);assert.equal(read.body.capabilities.deepResearch,false);assert.equal((await call(who,'/api/programs?q=synthetic')).body.programs.length,2);}
    const createdA=await sendAs('a','interview.create',{program:program.id,programName:'Untrusted browser label'});assert.equal(createdA.status,200);const aid=createdA.body.interviewId;assert.equal(createdA.body.bootstrap.state.interviews.find(i=>i.id===aid).programName,program.name);assert.equal(createdA.body.researchBinding,undefined);
    const createdB=await sendAs('b','interview.create',{programName:'Invitation details',track:'Supplied track'});assert.equal(createdB.status,200);const bid=createdB.body.interviewId;assert.equal((await sendAs('b','loi.evidence',{},bid)).status,403);
    const attached=await sendAs('b','interview.identity',{program:second.id,programName:'Invented name'},bid);assert.equal(attached.status,200);assert.equal(attached.body.bootstrap.state.interviews.find(i=>i.id===bid).programName,second.name);assert.equal(attached.body.researchBinding,undefined);
    for(const [who,id,p] of [['a',aid,program],['b',bid,second]]){
     const evidence=await sendAs(who,'loi.evidence',{},id);assert.equal(evidence.status,200);assert.equal(evidence.body.program.id,p.id);
     const draft=await sendAs(who,'loi.save',{...saveData,text:`Dear ${p.name},\n${motivation}\n${detail}`},id);assert.equal(draft.status,200);const d=draft.body.bootstrap.state.loi[id].current;
     const approved=await sendAs(who,'loi.approve',{...headData(d),studentFactualConfirmation:true,studentSpecificityConfirmation:true},id);assert.equal(approved.status,200);const approvedHead=approved.body.bootstrap.state.loi[id].current;
     const prepared=await sendAs(who,'loi.handoff',{...headData(approvedHead),recipient:'program@hospital.edu',subject:'Interest',channel:'copy',recipientConfirmed:true},id);assert.equal(prepared.status,200);
     assert.equal((await sendAs(who,'loi.mark_sent',{...headData(approvedHead),handoffId:prepared.body.handoff.handoffId,confirmed:true},id)).status,200);
     assert.equal((await sendAs(who,'loi.export',{},id)).body.export.history.at(-1).state,'self_reported_sent');
     assert.equal((await eligibleFull.bootstrap(actors[who])).state.loi[id].current.state,'approved');
    }
    for(const [who,id] of [['a',bid],['b',aid]])for(const command of ['loi.export','loi.evidence','loi.save','interview.identity'])assert.equal((await sendAs(who,command,command==='interview.identity'?{program:program.id}:{},id)).status,404);
    assert.equal((await database.withActor(b,db=>db.query('SELECT anchors FROM iiq.preparation WHERE interview_id=$1',[aid]))).rowCount,0);
    for(const who of ['admin','mentor']){assert.notEqual((await call(who,'/api/programs?q=synthetic')).status,200);assert.equal((await sendAs(who,'loi.export',{},aid)).status,403);}
    for(const override of [{eligible:false},{tier:'mission_residency'}]){const deniedExport=await envelope(b,'loi.export',{},bid,eligible),original={eligible:b.eligible,tier:b.tier};Object.assign(b,override);assert.notEqual((await call('b','/api/programs?q=synthetic')).status,200);assert.equal((await call('b','/api/commands',deniedExport)).status,403);Object.assign(b,original);}
    for(const command of ['research.check','research.refresh','mission.create'])assert.equal((await sendAs('a',command,{},aid)).status,503);
    const stored=await database.withActor(b,async db=>(await db.query('SELECT anchors FROM iiq.preparation WHERE owner_id=$1 AND interview_id=$2',[b.id,bid])).rows[0].anchors);
    assert.equal((await sendAs('b','interview.identity',{program:program.id},bid)).status,200);assert.equal((await eligible.bootstrap(b)).state.loi[bid].currentBindingValid,false);assert.deepEqual((await database.withActor(b,async db=>(await db.query('SELECT anchors FROM iiq.preparation WHERE owner_id=$1 AND interview_id=$2',[b.id,bid])).rows[0].anchors)),stored);
    eligibleConfig.loi.programId=second.id;assert.equal((await call('a','/api/programs?q=synthetic')).body.programs[0].id,second.id);assert.equal((await call('a','/api/programs?q=synthetic')).body.total,1);assert.equal((await sendAs('a','interview.create',{program:program.id,programName:program.name})).status,503);assert.equal((await sendAs('b','interview.identity',{program:program.id},bid)).status,503);
    assert.equal((await eligible.bootstrap(a)).state.loi[aid],undefined);assert.equal((await eligibleFull.bootstrap(a)).state.loi[aid],undefined);for(const command of ['loi.export','loi.evidence','loi.save','loi.handoff'])assert.equal((await sendAs('a',command,{},aid)).status,403);
    eligibleConfig.loi.ownerId=a.id;assert.notEqual((await call('b','/api/programs?q=synthetic')).status,200);assert.equal((await eligible.bootstrap(b)).capabilities.loi,false);assert.deepEqual(Object.keys((await eligible.bootstrap(b)).state.loi),[]);
    eligibleConfig.loi.enabled=false;assert.notEqual((await call('a','/api/programs?q=synthetic')).status,200);assert.equal((await sendAs('a','interview.create',{program:second.id,programName:second.name})).status,503);assert.equal((await sendAs('a','interview.create',{programName:'Still manual'})).status,200);
    assert.deepEqual(await noResearch(a),priorA);assert.deepEqual(await noResearch(b),priorB);assert.equal(dispatches,0);
   }finally{if(s){s.closeAllConnections();await new Promise(r=>s.close(r));}}
  });
  await t.test('shared audit/logs exclude prose, recipient, references and history remains owner-only',async()=>{const audit=await database.withActor(a,db=>db.query("SELECT metadata FROM iiq.audit_events WHERE owner_id=$1 AND event_type LIKE 'loi.%'",[a.id]));const serialized=JSON.stringify([audit.rows,logs]);for(const value of [motivation,detail,'program@hospital.edu','synthetic-story'])assert.equal(serialized.includes(value),false);});
 }finally{if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}await database?.close();if(started)pg('pg_ctl',['-D',dir+'/data','-m','immediate','-w','stop']);}
});
