// Local synthetic owner seams + actual HTTP/SQL/RLS. No provider credentials or production target.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {execFileSync} from 'node:child_process';import {randomUUID,randomInt,createHash} from 'node:crypto';import {createServer} from 'node:http';import {once} from 'node:events';
import {initializeHarness,localToolEnvironment,assertDisposableTarget,qualifyDisposableConnection} from '../../scripts/disposable-db-guard.mjs';import {migrate} from '../../scripts/migrate.mjs';import {createDatabase} from '../../server/db.mjs';import {createCommands} from '../../server/commands.mjs';import {createHandler} from '../../server/http.mjs';import {MRX_AREAS} from '../../server/research-standard.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex');
test('Three-Box real private lifecycle, HTTP, idempotency, preservation and RLS',async t=>{
 const bin='/opt/homebrew/opt/postgresql@18/bin/',env=localToolEnvironment(),dir=fs.mkdtempSync('/tmp/iiq-pg18.');fs.chmodSync(dir,0o700);const marker=initializeHarness(dir);fs.mkdirSync(dir+'/socket',{mode:0o700});let started=false,database,server,browserId=null,stopBrowser=null;
 const pg=(name,args)=>execFileSync(bin+name,args,{env,stdio:['ignore','pipe','pipe']});
 try{
  pg('initdb',['-D',dir+'/data','-A','trust','--no-locale','-U','iiq_test_admin']);pg('pg_ctl',['-D',dir+'/data','-l',dir+'/server.log','-o',`-k ${dir}/socket -h '' -p 55432 -c cluster_name=${marker}`,'-w','start']);started=true;pg('createdb',['-h',dir+'/socket','-p','55432','-U','iiq_test_admin','iiq_test']);
  const url=role=>`postgresql://${role}@localhost/iiq_test?host=${dir}/socket&port=55432`;await migrate({connectionString:url('iiq_test_admin'),local:true,bootstrap:true,log:()=>{}});
  pg('psql',['-h',dir+'/socket','-p','55432','-U','iiq_test_admin','-d','iiq_test','-v','ON_ERROR_STOP=1','-c','CREATE ROLE iiq_runtime_test LOGIN NOINHERIT NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE; GRANT iiq_authenticated TO iiq_runtime_test WITH INHERIT FALSE, SET TRUE;']);
  assertDisposableTarget(url('iiq_runtime_test'),{role:'iiq_runtime_test'});database=createDatabase({databaseUrl:url('iiq_runtime_test')});await qualifyDisposableConnection(database.pool,url('iiq_runtime_test'),{role:'iiq_runtime_test'});await database.verifyRuntimeRole();
  const base=randomInt(1000000,100000000),actor=(role,n)=>({id:randomUUID(),wpUserId:base+n,role,tier:role==='student'?'360':role,eligible:true,displayName:'SYNTHETIC Three-Box '+role,firstName:'Synthetic',zone:'America/New_York',assignments:[]}),a=actor('student',1),b=actor('student',2),admin=actor('admin',3),mentor=actor('mentor',4),actors={a,b,admin,mentor};mentor.assignments=[a.id];
  let now=Date.now(),mode='';const program={id:'synthetic-river-program',name:'SYNTHETIC River General Program',track:'Categorical',registryReleaseId:'synthetic-registry-v1'};
  const definitions=[['curriculum_training','research.curriculum','River Hospital continuity clinic meets each Tuesday.'],['research_scholarly','research.research_opportunities','Dr Example leads the published continuity study.'],['facilities_patient_population','research.facilities_patient_population','Training occurs at River Hospital and West Community Clinic.']];
  const fixture=()=>{const coverage={programId:program.id,registryReleaseId:program.registryReleaseId,observedAt:new Date(now-(mode==='stale'?300001:0)).toISOString(),fields:Object.entries(MRX_AREAS).flatMap(([area,fields])=>fields.map(field=>({area,field,state:definitions.some(x=>x[1]===field)?(mode==='conflict'?'CONFLICTED':'SUPPORTED'):'UNKNOWN'}))).sort((a,b)=>a.field.localeCompare(b.field,'en'))};coverage.receipt={sha256:hash(JSON.stringify(coverage)),publicRef:'rise-coverage-v1'};const body={schema:'rise-interviewiq-research-results-v1',coverage,facts:definitions.map(([area,field,value],n)=>({area,field,state:'SUPPORTED',claimRef:'rise-claim:'+hash(field),value:mode==='changed'&&n===0?'River Hospital changed its clinic to Wednesday.':value,retrievedAt:new Date(now-10000).toISOString(),asOf:{kind:'current-season',label:'Synthetic 2026 teaching fixture'},sources:[{claimRef:'rise-claim:'+hash('source '+field),reviewRef:null,urls:['https://hospital.edu/'+field.replaceAll('.','/')],retrievedAt:new Date(now-10000).toISOString(),reviewedAt:null}]}))};return {...body,receipt:{sha256:hash(JSON.stringify(body)),publicRef:'rise-results-v1'}};};
  const owners={async context(){return{};},async getProgram(_actor,id){assert.equal(id,program.id);return {...program,...(mode==='identity'?{registryReleaseId:'changed-registry'}:{})};},async getProgramResearch(){if(mode==='outage')throw Error('SYNTHETIC_OWNER_UNAVAILABLE');return fixture();},async validateBasis(){return{};}};
  const config={enabled:true,coreOnly:true,publicOrigin:'https://missionmed.test',gatewaySecret:'SYNTHETIC-LOCAL-ONLY-GATEWAY'.repeat(2),maxBodyBytes:262144,threebox:{enabled:true}},factory=c=>createCommands({database,owners,config:c,clock:()=>new Date(now)}),commands=factory(config),full=factory({...config,coreOnly:false}),disabled=factory({...config,threebox:{enabled:false}});
  const envelope=async(who,command,data={},interviewId=null,c=commands)=>({command,data,interviewId,expectedVersion:(await (who.role==='mentor'?full:c).bootstrap(who)).version,requestId:randomUUID()});const run=async(who,command,data={},iid=null,c=commands)=>c.execute(who,await envelope(who,command,data,iid,c));
  for(const who of Object.values(actors))await (who.role==='mentor'?full:commands).bootstrap(who);
  const iid=(await run(a,'interview.create',{program:program.id,programName:program.name,schedule:{date:'2026-11-01',time:'01:30',zone:'America/New_York',fold:1,duration:45}},null,full)).interviewId,other=(await run(b,'interview.create',{program:program.id,programName:program.name},null,full)).interviewId;
  const old=[null,'legacy',{type:'iiq.loi.revision',schemaVersion:1,revisionId:randomUUID(),letterVersion:1,text:'PRIVATE LOI approval remains',state:'approved',program:{id:program.id,name:program.name,track:program.track},interviewId:iid},{type:'iiq.loi.outreach',schemaVersion:1,state:'self_reported_sent',text:'PRIVATE outreach'},{unknown:'retain exact'}];await database.withActor(a,db=>db.query(`INSERT INTO iiq.preparation(owner_id,interview_id,why_program,questions,basis,anchors) VALUES($1,$2,'PRIVATE original Why','[{"text":"PRIVATE original question"}]','{"edited":true}',$3::jsonb)`,[a.id,iid,JSON.stringify(old)]),{write:true});
  const prep=()=>database.withActor(a,async db=>(await db.query('SELECT * FROM iiq.preparation WHERE owner_id=$1 AND interview_id=$2',[a.id,iid])).rows[0]),baseline=await database.withActor(a,async db=>(await db.query('SELECT to_jsonb(i) AS row FROM iiq.interviews i WHERE id=$1',[iid])).rows[0].row),head=async()=>((await commands.bootstrap(a)).state.why[iid].threebox.current),logs=[];
  const api=createHandler({config,database,commands,owners,authorize:async req=>actors[req.headers['x-synthetic-actor']||'a'],logger:x=>logs.push(x)}),publicRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../public');
  server=createServer((req,res)=>{const u=new URL(req.url,'http://127.0.0.1');if(u.pathname==='/__qa/stop'&&stopBrowser){res.end('Synthetic browser harness stopped');stopBrowser();return;}if(u.pathname==='/wp-admin/admin-ajax.php'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(u.searchParams.get('action')==='missionmed_interviewiq_bootstrap'?{nonce:'synthetic-only',token_endpoint:'/wp-admin/admin-ajax.php?action=token',api_base:'/interviewiq/api'}:{token:'SYNTHETIC-LOCAL-ONLY',ttl_seconds:60}));return;}if(u.pathname.startsWith('/interviewiq/api/')){req.url=req.url.replace('/interviewiq/api/','/api/');req.headers.origin=config.publicOrigin;req.headers['x-mmed-iiq-gateway']=config.gatewaySecret;return api(req,res);}if(['/interviewiq/','/interviewiq/app.js','/interviewiq/styles.css'].includes(u.pathname)){const name=u.pathname==='/interviewiq/'?'index.html':u.pathname.split('/').at(-1);let bytes=fs.readFileSync(path.join(publicRoot,name));if(name==='app.js'&&browserId)bytes=Buffer.from(bytes.toString().replace('void boot();',`void boot().then(async()=>{S.ui.route='interviews';S.ui.open=${JSON.stringify(browserId)};S.ui.section='why';render();await A['threebox-evidence']({dataset:{id:${JSON.stringify(browserId)}}});window.__threeboxLayout={width:innerWidth,scrollWidth:document.documentElement.scrollWidth,boxes:[...document.querySelectorAll('.tbBoxes>section')].map(e=>({title:e.querySelector('h3').textContent,width:e.getBoundingClientRect().width,left:e.getBoundingClientRect().left})),buttons:[...document.querySelectorAll('.tbBuilder button')].map(e=>({text:e.textContent,height:e.getBoundingClientRect().height,width:e.getBoundingClientRect().width})),textarea:!!document.querySelector('[data-tb-field="editedAnswer"]')};document.body.dataset.threeboxLayout=JSON.stringify(window.__threeboxLayout);});`));res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(bytes);return;}return api(req,res);});server.listen(0,'127.0.0.1');await once(server,'listening');const origin=`http://127.0.0.1:${server.address().port}`;
  const http=async(who,body)=>{const r=await fetch(origin+'/api/commands',{method:'POST',headers:{'content-type':'application/json',origin:config.publicOrigin,'x-synthetic-actor':who,'x-mmed-iiq-gateway':config.gatewaySecret},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};const send=async(command,data={},who='a',id=iid)=>{const req=await envelope(actors[who],command,data,id),r=await http(who,req);assert.equal(r.status,200,r.body.error?.code+' '+r.body.error?.message);return {req,r:r.body};};
  const evidence=(await send('threebox.evidence')).r,reason=(n,personal=false)=>({id:randomUUID(),general:{category:['Didactics','Research','Exposure'][n]},details:[evidence.evidenceBindings[n]],personal:{enabled:personal,text:personal?'I want to build continuity skills.':'',confirmed:personal},selected:true,rank:n+1,followUpDefense:'I can explain this published detail and ask about supervision.',intel:[]}),reasons=[reason(0,true),reason(1),reason(2)];
  const data=async(extra={})=>{const h=await head();return {expectedHead:h?.revisionId??null,expectedAnswerVersion:h?.answerVersion??0,reasons,delivery:'STANDARD',factualConfirmed:true,specificityConfirmed:true,locationException:false,...extra};};
  await t.test('read/evidence do not consume revision and return canonical proof rather than browser values',async()=>{const v=(await commands.bootstrap(a)).version;await send('threebox.read');await send('threebox.evidence');assert.equal((await commands.bootstrap(a)).version,v);assert.equal(evidence.evidenceBindings.length,3);assert.equal(evidence.program.id,program.id);assert.equal((await http('a',await envelope(a,'threebox.evidence',{ownerId:b.id},iid))).status,422);});
  await t.test('incomplete worksheet saves/replays once while original prose, LOI/history/questions/basis/calendar survive',async()=>{const {req}=await send('threebox.save',await data({reasons:[],factualConfirmed:false,specificityConfirmed:false}));assert.equal((await http('a',req)).body.replayed,true);const p=await prep();assert.deepEqual(p.anchors.slice(0,old.length),old);assert.equal(p.anchors.length,old.length+1);assert.equal(p.why_program,'PRIVATE original Why');assert.equal(p.questions[0].text,'PRIVATE original question');assert.deepEqual(p.basis,{edited:true});assert.deepEqual(await database.withActor(a,async db=>(await db.query('SELECT to_jsonb(i) AS row FROM iiq.interviews i WHERE id=$1',[iid])).rows[0].row),baseline);});
  await t.test('assembly yields taught worksheet/three forms, saved exact text and a parent-linked version',async()=>{const previous=await head();await send('threebox.assemble',await data());const h=await head();assert.equal(h.state,'assembled');assert.equal(h.parentRevisionId,previous.revisionId);assert.equal(h.answerVersion,2);assert.match(h.text,/River Hospital/);assert.match(h.answers.concise,/Dr Example/);assert.match(h.answers.bullets,/Didactics →/);assert.equal((await prep()).why_program,h.text);assert.equal((await commands.bootstrap(a)).state.why[iid].threebox.ready,true);assert.equal(h.reasons[1].personal.enabled,false);});
  await t.test('cross-student and mentor/admin reads/commands are denied; private row never leaks through bootstrap/RLS',async()=>{for(const who of ['b','admin','mentor'])for(const command of ['threebox.read','threebox.evidence','threebox.save','threebox.assemble'])assert.notEqual((await http(who,await envelope(actors[who],command,{},iid))).status,200);for(const who of [b,admin,mentor]){assert.equal((await database.withActor(who,db=>db.query('SELECT anchors FROM iiq.preparation WHERE interview_id=$1',[iid]))).rowCount,0);assert.equal((await (who.role==='mentor'?full:commands).bootstrap(who)).state.why[iid],undefined);}assert.equal((await http('a',await envelope(a,'threebox.read',{},other))).status,404);});
  await t.test('stale coverage, conflict, changed exact evidence and registry change fail without appending',async()=>{const n=(await prep()).anchors.length;for(const bad of ['stale','conflict','changed','identity']){mode=bad;assert.notEqual((await http('a',await envelope(a,'threebox.assemble',await data(),iid))).status,200);}mode='';assert.equal((await prep()).anchors.length,n);});
  await t.test('client cannot invent provenance, verified status, personal confirmation or freshness',async()=>{const d=await data();d.reasons=structuredClone(reasons);d.reasons[0].details[0].value='Invented board pass rate 100%';assert.equal((await http('a',await envelope(a,'threebox.assemble',d,iid))).status,422);const x=await data();x.reasons=structuredClone(reasons);x.reasons[0].personal.confirmed=false;assert.equal((await http('a',await envelope(a,'threebox.assemble',x,iid))).status,422);assert.equal((await http('a',await envelope(a,'threebox.assemble',await data({specificityConfirmed:false}),iid))).status,422);});
  await t.test('first explicit clearing retains preexisting Why prose and legacy-client edits remain recoverable',async()=>{
    const fresh=(await run(a,'interview.create',{program:program.id,programName:program.name},null,full)).interviewId;
    await database.withActor(a,db=>db.query('INSERT INTO iiq.preparation(owner_id,interview_id,why_program) VALUES($1,$2,$3)',[a.id,fresh,'PRIVATE previous answer']),{write:true});
    const draft={expectedHead:null,expectedAnswerVersion:0,reasons:[],delivery:'STANDARD',factualConfirmed:false,specificityConfirmed:false,locationException:false,editedAnswer:''};
    await run(a,'threebox.save',draft,fresh);let saved=(await commands.bootstrap(a)).state.why[fresh];assert.equal(saved.text,'');assert.equal(saved.threebox.current.legacyText,'PRIVATE previous answer');
    await run(a,'prep.save',{why:{text:'PRIVATE old-client revision',edited:true}},fresh,full);
    await run(a,'threebox.save',{...draft,expectedHead:saved.threebox.current.revisionId,expectedAnswerVersion:1},fresh);
    saved=(await commands.bootstrap(a)).state.why[fresh];assert.equal(saved.text,'');assert.equal(saved.threebox.current.legacyText,'PRIVATE old-client revision');assert.equal(saved.threebox.history[0].legacyText,'PRIVATE previous answer');
  });
  await t.test('provider unavailable still permits an unfinished private draft but cannot assemble',async()=>{mode='outage';await send('threebox.save',await data());assert.equal((await head()).state,'draft');assert.notEqual((await http('a',await envelope(a,'threebox.assemble',await data(),iid))).status,200);mode='';});
  await t.test('edited wording is private draft history, never silently certified as evidence-bound prose',async()=>{const h=await head();await send('threebox.save',await data({editedAnswer:'PRIVATE student edited voice'}));const current=await head();assert.equal(current.text,'PRIVATE student edited voice');assert.equal(current.parentRevisionId,h.revisionId);assert.equal(current.state,'draft');assert.equal(current.checks.ready,false);assert.equal((await commands.bootstrap(a)).state.why[iid].threebox.ready,false);});
  await t.test('legacy prep client changes preserve anchors and mark divergent head instead of claiming readiness',async()=>{await send('threebox.assemble',await data());const before=(await prep()).anchors;await run(a,'prep.save',{why:{text:'PRIVATE legacy client edit',edited:true}},iid,full);assert.deepEqual((await prep()).anchors,before);const w=(await commands.bootstrap(a)).state.why[iid];assert.equal(w.text,'PRIVATE legacy client edit');assert.equal(w.threebox.manualEdit,true);assert.equal(w.threebox.ready,false);});
  await t.test('workspace/head concurrency and request replay do not overwrite newer content or duplicate history',async()=>{const d=await data(),one=await envelope(a,'threebox.save',d,iid),two={...one,requestId:randomUUID(),data:{...d,editedAnswer:'PRIVATE concurrent edit'}};const r=await Promise.all([http('a',one),http('a',two)]);assert.deepEqual(r.map(x=>x.status).sort(),[200,409]);const winner=r[0].status===200?one:two,n=(await prep()).anchors.length;assert.equal((await http('a',winner)).body.replayed,true);assert.equal((await prep()).anchors.length,n);assert.equal((await http('a',{...winner,data:{...winner.data,editedAnswer:'DIFFERENT BODY'}})).status,409);assert.equal((await http('a',await envelope(a,'threebox.save',d,iid))).status,409);});
  await t.test('default-off feature and scoped owner/program deny command execution without broad preparation activation',async()=>{await assert.rejects(run(a,'threebox.read',{},iid,disabled),{code:'threebox_unavailable'});assert.equal(Object.keys((await disabled.bootstrap(a)).state.why).length,0);for(const command of ['prep.save','practice.start','debrief.save'])assert.equal((await http('a',await envelope(a,command,{},iid))).status,503);const scoped=factory({...config,threebox:{enabled:true,ownerId:b.id}});await assert.rejects(run(a,'threebox.read',{},iid,scoped),{code:'threebox_unavailable'});const otherScope=factory({...config,threebox:{enabled:true,programId:'unrelated'}});await assert.rejects(run(a,'threebox.read',{},iid,otherScope),{code:'threebox_scope'});});
  await t.test('unknown future answer schema blocks editing but preserves history, old runtime and private state',async()=>{await database.withActor(a,db=>db.query('UPDATE iiq.preparation SET anchors=anchors||$3::jsonb WHERE owner_id=$1 AND interview_id=$2',[a.id,iid,JSON.stringify([{type:'iiq.threebox.revision',schemaVersion:99,preserve:'FUTURE_BYTES'}])]),{write:true});const p=await prep();assert.equal((await http('a',await envelope(a,'threebox.save',await data(),iid))).status,409);assert.deepEqual((await prep()).anchors,p.anchors);assert.equal((await full.bootstrap(a)).state.why[iid].text,p.why_program);});
  await t.test('audit/log receipts exclude private text and application schema/runtime custody remains unchanged',async()=>{const r=await database.withActor(a,db=>db.query("SELECT metadata FROM iiq.audit_events WHERE owner_id=$1 AND event_type LIKE 'threebox.%'",[a.id]));assert.doesNotMatch(JSON.stringify([r.rows,logs]),/PRIVATE|continuity skills|River Hospital|Dr Example/);await database.verifyRuntimeRole();assert.equal(pg('psql',['-h',dir+'/socket','-p','55432','-U','iiq_test_admin','-d','iiq_test','-At','-c','SELECT count(*) FROM iiq_migrations.applied']).toString().trim(),'5');});
  if(process.env.IIQ_THREEBOX_BROWSER_QA==='1'){
    browserId=(await run(a,'interview.create',{program:program.id,programName:program.name,schedule:{date:'2026-11-10',time:'10:00',zone:'America/New_York',duration:45}},null,full)).interviewId;
    await run(a,'threebox.assemble',{expectedHead:null,expectedAnswerVersion:0,reasons,delivery:'STANDARD',factualConfirmed:true,specificityConfirmed:true,locationException:false},browserId);
    process.stdout.write(JSON.stringify({event:'threebox-browser-ready',url:origin+'/interviewiq/',syntheticOnly:true,privateDatabase:dir})+'\n');await new Promise(resolve=>{stopBrowser=resolve;process.once('SIGTERM',resolve);process.once('SIGINT',resolve);});
  }
 }finally{if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}await database?.close();if(started)pg('pg_ctl',['-D',dir+'/data','-m','immediate','-w','stop']);}
});
