import {eventsForScope,mediaForScope} from "./timeline-canvas-renderer.js";

function esc(value){return String(value==null?"":value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function label(value){return String(value||"").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,(letter)=>letter.toUpperCase());}
function date(value){if(!value)return "Not recorded";const [year,month]=String(value).split("-").map(Number);return Number.isFinite(year)&&Number.isFinite(month)?new Intl.DateTimeFormat("en-US",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(year,month-1,1))):String(value);}

function accessibleEvents(document,scope){return eventsForScope(document,scope).slice().sort((a,b)=>String(a.startDate).localeCompare(String(b.startDate))||String(a.endDate||a.startDate).localeCompare(String(b.endDate||b.startDate))||String(a.title).localeCompare(String(b.title)));}

export function buildAccessibleTextSummary(document,{scope="INTERVIEWER_SAFE"}={}){
  const categories=Object.fromEntries((document.categories||[]).map((item)=>[item.id,item.label])),events=accessibleEvents(document,scope),profile=document.studentProfile||{};
  const lines=[document.title||"Mission Timeline",`Audience: ${label(scope)}`,`Student: ${profile.name||"Not recorded"}`,`Specialty goal: ${profile.specialtyGoal||"Not recorded"}`,`Medical school country: ${profile.medicalSchoolCountry||"Not recorded"}`,"","Chronology"];
  events.forEach((event,index)=>{const range=event.eventType==="milestone"?date(event.startDate):`${date(event.startDate)} to ${event.endDate?date(event.endDate):"Present"}`;lines.push(`${index+1}. ${event.title}. ${range}. Category: ${categories[event.categoryId]||event.categoryId||"Uncategorized"}.${event.siteName||event.location?` Site: ${event.siteName||event.location}.`:""}`);});
  if(!events.length)lines.push("No events are visible in this audience scope.");
  if(scope==="ADVISOR_PACKET"){
    lines.push("","Advisor review",`Status: ${document.advisorReview?.status||"Unreviewed"}`);
    (document.advisorReview?.comments||[]).forEach((item,index)=>lines.push(`Comment ${index+1}: ${item.body}`));
    (document.advisorReview?.changeRequests||[]).forEach((item,index)=>lines.push(`Change request ${index+1}: ${item.state}. ${item.body}`));
  }
  lines.push("","Accessibility note: The visual PDF is untagged. Use the semantic HTML or this text summary for searchable text and linear reading order.");
  return lines.join("\n");
}

export function buildAccessibleTimelineHtml(document,{scope="INTERVIEWER_SAFE"}={}){
  const categories=Object.fromEntries((document.categories||[]).map((item)=>[item.id,item])),events=accessibleEvents(document,scope),media=mediaForScope(document,scope),profile=document.studentProfile||{},summary=buildAccessibleTextSummary(document,{scope});
  const eventRows=events.map((event,index)=>{const category=categories[event.categoryId];return `<tr><th scope="row">${index+1}</th><td>${esc(event.title)}</td><td>${esc(event.eventType==="milestone"?date(event.startDate):date(event.startDate)+" to "+(event.endDate?date(event.endDate):"Present"))}</td><td>${esc(category?.label||event.categoryId||"Uncategorized")}</td><td>${esc(event.siteName||event.location||"")}</td></tr>`;}).join("");
  const legend=Object.values(categories).map((item)=>`<li><span class="swatch" style="background:${esc(item.color)}"></span>${esc(item.label)}</li>`).join("");
  const mediaList=media.length?`<ul>${media.map((item)=>`<li>${esc(label(item.type))}: ${esc(item.altText||item.sourceFilename||"No alt description supplied")}</li>`).join("")}</ul>`:"<p>No media is included in this audience scope.</p>";
  const advisor=scope==="ADVISOR_PACKET"?`<section aria-labelledby="advisor-heading"><h2 id="advisor-heading">Advisor review</h2><p><strong>Status:</strong> ${esc(document.advisorReview?.status||"Unreviewed")}</p><h3>Comments</h3><ol>${(document.advisorReview?.comments||[]).map((item)=>`<li>${esc(item.body)} (${esc(item.resolved?"resolved":"open")})</li>`).join("")||"<li>None recorded.</li>"}</ol><h3>Change requests</h3><ol>${(document.advisorReview?.changeRequests||[]).map((item)=>`<li>${esc(item.body)} (${esc(item.state||"open")})</li>`).join("")||"<li>None recorded.</li>"}</ol></section>`:"";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(document.title||"Mission Timeline")} | ${esc(label(scope))}</title><style>body{font-family:Arial,sans-serif;line-height:1.5;color:#17130f;background:#fff;max-width:1100px;margin:0 auto;padding:32px}header{border-bottom:5px solid #d96b2b;margin-bottom:24px}h1{font-size:2rem}h2{margin-top:2rem}table{border-collapse:collapse;width:100%}th,td{border:1px solid #777;padding:9px;text-align:left;vertical-align:top}thead{background:#171d26;color:#fff}.legend{display:flex;flex-wrap:wrap;gap:12px;list-style:none;padding:0}.swatch{display:inline-block;width:18px;height:12px;margin-right:6px;border:1px solid #333}.note{border-left:5px solid #297f9e;padding:12px;background:#eef8fb}@media print{body{padding:0}.note{break-inside:avoid}tr{break-inside:avoid}}</style></head><body><header><p>MissionMed Timeline Builder</p><h1>${esc(document.title||"Mission Timeline")}</h1><p><strong>Audience:</strong> ${esc(label(scope))}</p></header><main><section aria-labelledby="profile-heading"><h2 id="profile-heading">Student profile</h2><dl><dt>Name</dt><dd>${esc(profile.name||"Not recorded")}</dd><dt>Specialty goal</dt><dd>${esc(profile.specialtyGoal||"Not recorded")}</dd><dt>Medical school country</dt><dd>${esc(profile.medicalSchoolCountry||"Not recorded")}</dd></dl></section><section aria-labelledby="legend-heading"><h2 id="legend-heading">Category key</h2><ul class="legend">${legend}</ul></section><section aria-labelledby="chronology-heading"><h2 id="chronology-heading">Chronology</h2><table><caption>${events.length} visible timeline events, ordered by start date</caption><thead><tr><th scope="col">#</th><th scope="col">Event</th><th scope="col">Dates</th><th scope="col">Category</th><th scope="col">Site or location</th></tr></thead><tbody>${eventRows||'<tr><td colspan="5">No events are visible in this audience scope.</td></tr>'}</tbody></table></section><section aria-labelledby="media-heading"><h2 id="media-heading">Media descriptions</h2>${mediaList}</section>${advisor}<section class="note" aria-labelledby="limits-heading"><h2 id="limits-heading">Accessible format note</h2><p>This semantic HTML is the accessible companion to the visual timeline and untagged visual PDF. It provides searchable text, headings, tables, and linear reading order. No PDF/UA claim is made.</p></section><details><summary>Plain text summary</summary><pre>${esc(summary)}</pre></details></main></body></html>`;
}
