import {randomUUID} from 'node:crypto';
import {requireValue,notFound} from './errors.mjs';
import * as v from './validation.mjs';
import {syncActor,revision,writeInterview} from './records.mjs';
import {requireCalendar,admittedTarget,bindCalendar} from './calendar-admission.mjs';
import {syncCalendarProjection} from './calendar-cohort.mjs';
export async function resolveAdminTarget({database,actor,config,admit,eventRef,action}){
 requireCalendar(config,actor);requireValue(actor.role==='admin'&&actor.tier==='admin','admin_required','Use your current administrator workspace.',403);v.uuid(eventRef,'Calendar event');await admit(actor,[],action);
 const row=await database.withActor(actor,async db=>{await db.query('SET TRANSACTION READ ONLY');await bindCalendar(db,actor);return(await db.query("SELECT * FROM iiq.calendar_candidates(current_date,current_date,NULL,NULL,$1)",[eventRef])).rows[0];});if(!row)throw notFound();
 const pair={subject:row.owner_id,wp_user_id:Number(row.wp_user_id)},grant=await admit(actor,[pair],action),target=admittedTarget(actor,pair,grant);return {target,row,pair};
}
export async function lockActors(db,actor,owner){for(const id of [...new Set([actor.id,owner])].sort())await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[id]);}
export async function auditLogistics(db,actor,owner,event,id,metadata={}){await db.query('INSERT INTO iiq.audit_events(owner_id,actor_id,event_type,object_type,object_id,metadata) VALUES($1,$2,$3,\'logistics\',$4,$5::jsonb)',[owner,actor.id,event,id,JSON.stringify(metadata)]);}
export async function readAdminLogistics(ctx){const {database,actor,eventRef,admit}=ctx,action='GET /api/calendar/admin/'+eventRef,scope=await resolveAdminTarget({...ctx,action});admittedTarget(actor,scope.pair,await admit(actor,[scope.pair],action));return database.withActor(actor,async db=>{await bindCalendar(db,actor,scope.target);await lockActors(db,actor,scope.target.ownerId);await syncActor(db,actor);const i=(await db.query('SELECT * FROM iiq.interviews WHERE owner_id=$1 AND id=$2',[scope.target.ownerId,scope.row.interview_id])).rows[0];if(!i)throw notFound();const {rows:e}=await db.query('SELECT id,kind,title,local_date,local_time,timezone,fold,all_day,status,version,duration_minutes,note FROM iiq.related_events WHERE owner_id=$1 AND interview_id=$2',[scope.target.ownerId,i.id]);await auditLogistics(db,actor,i.owner_id,'admin.logistics.read',i.id,{eventRef});return {eventRef,interview:{id:i.id,version:Number(i.version),program:i.program_id,programName:i.program_name,track:i.program_track,status:i.status,date:i.local_date,time:i.local_time,zone:i.timezone,fold:i.fold,format:i.format,joining:i.joining,duration:i.duration_minutes,travel_minutes:i.travel_minutes,deadline:i.deadline_date},events:e,version:await revision(db,{id:i.owner_id})};});}
export async function writeAdminLogistics(ctx,body){const {database,actor,eventRef,admit,config,owners}=ctx;v.onlyKeys(body,['command','requestId','expectedVersion','expectedInterviewVersion','data']);v.uuid(body.requestId,'Request');v.integer(body.expectedVersion,'Workspace version',0,Number.MAX_SAFE_INTEGER);v.integer(body.expectedInterviewVersion,'Interview version',1,Number.MAX_SAFE_INTEGER);v.onlyKeys(body.data??{},Object.keys(body.data??{}));
 const commands={'admin.logistics.create':'interview.create','admin.logistics.update':'interview.schedule','admin.logistics.identity':'interview.identity','admin.logistics.lifecycle':'interview.lifecycle','admin.logistics.event_create':'event.create','admin.logistics.event_update':'event.update'};requireValue(commands[body.command],'admin_operation','Choose a logistics action.');const action='POST /api/calendar/admin/'+eventRef,scope=await resolveAdminTarget({...ctx,action});admittedTarget(actor,scope.pair,await admit(actor,[scope.pair],action));const digest=v.digest({eventRef,...body});
 return database.withActor(actor,async db=>{await bindCalendar(db,actor,scope.target);await lockActors(db,actor,scope.target.ownerId);await syncActor(db,actor);
 const {rows:[prior]}=await db.query('SELECT * FROM iiq.calendar_admin_receipts WHERE actor_id=$1 AND owner_id=$2 AND request_id=$3',[actor.id,scope.target.ownerId,body.requestId]);if(prior){requireValue(prior.digest===digest,'request_reused','Request already used for another action.',409);return{replayed:true,interviewId:prior.result_id,version:Number(prior.after_revision)};}
 const row=(await db.query('SELECT * FROM iiq.interviews WHERE owner_id=$1 AND id=$2 FOR UPDATE',[scope.target.ownerId,scope.row.interview_id])).rows[0];if(!row)throw notFound();const before=await revision(db,{id:scope.target.ownerId});requireValue(before===body.expectedVersion&&Number(row.version)===body.expectedInterviewVersion,'version_conflict','Logistics changed. Keep your draft and reload current details.',409);
 admittedTarget(actor,scope.pair,await admit(actor,[scope.pair],action));
 const result=await writeInterview({db,actor,target:scope.target,interviewId:row.id,command:commands[body.command],data:body.data,owners,config:{...config,coreOnly:true,deepResearch:{enabled:false}}});await syncCalendarProjection({db,actor,target:scope.target,config,owners,interviewId:result.interviewId});
 const next=before+1;await db.query('INSERT INTO iiq.revisions(owner_id,revision,reason,request_key) VALUES($1,$2,$3,$4)',[scope.target.ownerId,next,body.command,body.requestId]);await db.query('INSERT INTO iiq.calendar_admin_receipts(actor_id,owner_id,request_id,digest,result_id,before_revision,after_revision) VALUES($1,$2,$3,$4,$5,$6,$7)',[actor.id,scope.target.ownerId,body.requestId,digest,result.interviewId,before,next]);await auditLogistics(db,actor,scope.target.ownerId,body.command,result.interviewId,{requestId:body.requestId,eventRef,beforeRevision:before,afterRevision:next,changedFields:Object.keys(body.data).sort()});return{interviewId:result.interviewId,resultId:result.id,version:next};
 });
}
