import * as v from './validation.mjs';
import {requireValue,notFound} from './errors.mjs';
import {interview,history,writeInterview,scheduleColumns} from './records.mjs';
import {validDate} from './time.mjs';
export const intakeCommands=new Set(['intake.create','intake.update','intake.read']);
export const POSITION_TYPES=['CATEGORICAL','PRELIMINARY','TRANSITIONAL_YEAR','ADVANCED','RESERVED','OTHER','UNKNOWN'];
export const EXPERIENCE_TYPES=['CLERKSHIP','SUB_INTERNSHIP','ELECTIVE','EXTERNSHIP','OBSERVERSHIP','RESEARCH','EMPLOYMENT','VOLUNTEER','AWAY_ROTATION','OTHER'];
export const EVENT_TYPES=['MEET_GREET','DINNER','SOCIAL','OVERVIEW','SECOND_LOOK','OTHER'];
export function intakeEnabled(config,actor){return config.intake?.enabled===true&&actor?.role==='student'&&['360','ivprep_complete'].includes(actor.tier)&&actor.eligible!==false;}
export function requireIntake(config,actor){requireValue(intakeEnabled(config,actor),'intake_unavailable','The new interview intake is not available for this workspace.',403);}
const text=(x,label,max)=>x===undefined||x===null||x===''?null:v.text(x,label,max,{empty:false});
const choice=(x,values,label)=>x===undefined||x===null||x===''?null:v.choice(x,values,label);
const date=(x,label)=>{if(x===undefined||x===null||x==='')return null;requireValue(validDate(x),'invalid_date','Enter a valid '+label+'.');return x;};
const FIELDS={invitationSource:['ERAS','THALAMUS','INTERVIEW_BROKER','EMAIL','PHONE','OTHER','UNKNOWN'],platform:['ZOOM','WEBEX','TEAMS','THALAMUS','OTHER','UNKNOWN'],itineraryState:['RECEIVED','NOT_YET','UNKNOWN'],pgy1Applied:['YES','NO','UNSURE'],relationshipState:['YES','NO','UNKNOWN'],applicationState:['APPLIED','NOT_APPLIED','UNSURE'],signalState:['YES','NO','NA','UNSURE'],loiTemporal:['AFTER_LOI','NO','NOT_SENT','UNSURE'],priority:['HIGH','INTERESTED','EXPLORING','PREFER_NOT'],structure:['ONE_TO_ONE','PANEL','GROUP','MMI','OTHER','UNKNOWN']};
const TEXT_FIELDS={location:1000,coordinatorName:200,coordinatorContact:500,structureNotes:2000,privateNotes:2000};
function details(input={}){
 v.onlyKeys(input,[...Object.keys(FIELDS),...Object.keys(TEXT_FIELDS),'matchCycle','interviewCount','prelimTargetId','advancedFactConfirmed','invitationReceivedDate','statusDetail']);const out={};
 for(const [key,values]of Object.entries(FIELDS))out[key]=choice(input[key],values,key);
 for(const [key,max]of Object.entries(TEXT_FIELDS))out[key]=text(input[key],key,max);
 out.invitationReceivedDate=date(input.invitationReceivedDate,'invitation received date');out.statusDetail=choice(input.statusDetail,['WAITLISTED','PROGRAM_CANCELLED','STUDENT_CANCELLED','DECLINED'],'status detail');
 out.matchCycle=input.matchCycle==null||input.matchCycle===''?null:v.integer(input.matchCycle,'Match cycle',2000,2100);
 out.interviewCount=input.interviewCount==null||input.interviewCount===''?null:v.integer(input.interviewCount,'Interview count',1,30);
 out.prelimTargetId=input.prelimTargetId==null||input.prelimTargetId===''?null:v.uuid(input.prelimTargetId,'Preliminary letter target');
 out.advancedFactConfirmed=input.advancedFactConfirmed===undefined?false:v.boolean(input.advancedFactConfirmed,'Advanced interview context');
 requireValue(!out.advancedFactConfirmed||out.prelimTargetId,'intake_prelim_target','Choose an existing own preliminary or transitional letter target.');return out;
}
function experiences(input=[]){return v.array(input,'Prior experiences',20).map(e=>{v.onlyKeys(e,['kind','department','startDate','endDate','description','contact','confirmed']);const out={kind:v.choice(e.kind,EXPERIENCE_TYPES,'experience type'),department:text(e.department,'Department',300),startDate:date(e.startDate,'experience start date'),endDate:date(e.endDate,'experience end date'),description:v.text(e.description,'Experience',2000,{empty:false}),contact:text(e.contact,'Student supplied contact',500),confirmed:v.boolean(e.confirmed,'Experience is your confirmed account')};requireValue(out.confirmed===true,'intake_experience_confirmation','Confirm only your actual experience.');requireValue(!out.startDate||!out.endDate||out.startDate<=out.endDate,'intake_experience_dates','Experience dates must be ordered.');return out;});}
export function parseIntake(data,update=false){
 v.onlyKeys(data,update?['expectedIntakeVersion','positionType','track','details','experiences']:['identity','positionType','track','deadline','schedule','details','experiences','events']);
 if(update){v.onlyKeys(data.details??{},[...Object.keys(FIELDS),...Object.keys(TEXT_FIELDS),'matchCycle','interviewCount','prelimTargetId','advancedFactConfirmed','invitationReceivedDate','statusDetail']);if(data.experiences!==undefined)v.array(data.experiences,'Prior experiences',20);return{positionType:data.positionType===undefined?undefined:v.choice(data.positionType,POSITION_TYPES,'position type'),track:data.track===undefined?undefined:v.text(data.track,'Program-specific track',200),detailsInput:data.details??{},experiencesInput:data.experiences,expectedIntakeVersion:v.integer(data.expectedIntakeVersion,'Intake version',0,Number.MAX_SAFE_INTEGER)};}
 const d=details(data.details),x=experiences(data.experiences);requireValue(d.relationshipState==='YES'||x.length===0,'intake_relationship','Confirm a prior connection before adding experiences.');
 v.onlyKeys(data.identity,['programId','registryReleaseId','confirmed','provisionalConfirmed','invitationLabel']);const i=data.identity;
 const identity={programId:text(i.programId,'RISE program ID',180),registryReleaseId:text(i.registryReleaseId,'Registry release',180),invitationLabel:v.text(i.invitationLabel,'Invitation label',500,{empty:false}),confirmed:i.confirmed===true,provisionalConfirmed:i.provisionalConfirmed===true};
 requireValue(identity.programId?identity.confirmed&&identity.registryReleaseId:identity.provisionalConfirmed&&!identity.registryReleaseId,'intake_identity_confirmation','Confirm the exact program, or explicitly retain an unresolved invitation.');
 const positionType=v.choice(data.positionType??'UNKNOWN',POSITION_TYPES,'position type'),track=v.text(data.track??'','Program-specific track',200),schedule=data.schedule??{zone:'UTC'};
 v.onlyKeys(schedule,['date','time','zone','allDay','fold','duration','travel_minutes','format','joining']);scheduleColumns(schedule);
 const events=v.array(data.events??[],'Related events',12).map(e=>{v.onlyKeys(e,['clientKey','kind','schedule','required','location','note']);const clientKey=v.uuid(e.clientKey,'Event request key'),kind=v.choice(e.kind,EVENT_TYPES,'event type');v.onlyKeys(e.schedule,['date','time','zone','allDay','fold','duration','format','joining']);const s=scheduleColumns(e.schedule);requireValue(s.date,'date_required','Each related event needs a date; its time can remain unknown.');return{clientKey,kind,schedule:e.schedule,required:choice(e.required,['REQUIRED','OPTIONAL','UNKNOWN'],'event requirement'),location:text(e.location,'Event location',1000),note:v.text(e.note??'','Event note',2000)};});
 requireValue(new Set(events.map(e=>e.clientKey)).size===events.length,'intake_duplicate_event','Each event needs a distinct request key.');requireValue(!d.advancedFactConfirmed||positionType==='ADVANCED','intake_advanced_context','Confirm advanced context only for an Advanced position.');
 return{identity,positionType,track,schedule,deadline:date(data.deadline,'scheduling deadline'),details:d,experiences:x,events};
}
const columns={invitationSource:'invitation_source',platform:'platform',itineraryState:'itinerary_state',pgy1Applied:'pgy1_applied',relationshipState:'relationship_state',applicationState:'application_state',signalState:'signal_state',loiTemporal:'loi_temporal',priority:'priority',structure:'structure',location:'location',coordinatorName:'coordinator_name',coordinatorContact:'coordinator_contact',structureNotes:'structure_notes',privateNotes:'private_notes',matchCycle:'match_cycle',interviewCount:'interview_count',prelimTargetId:'prelim_target_id',advancedFactConfirmed:'advanced_fact_confirmed'};
async function validatePrelim(ctx,d,positionType){
 if(!d.prelimTargetId)return;requireValue(positionType==='ADVANCED'&&d.pgy1Applied==='YES','intake_prelim_context','Associate a PGY-1 target only after confirming your application.');
 const {rows:[t]}=await ctx.db.query('SELECT id,program_id,program_name,target_choice FROM iiq.loi_targets WHERE owner_id=$1 AND id=$2',[ctx.actor.id,d.prelimTargetId]);if(!t)throw notFound();
 requireValue(t.target_choice==='CREATE_LETTER'&&t.program_id,'intake_prelim_target','Use an existing verified own letter target with Create Letter selected.');
 // A target label alone never verifies its PGY-1 position type. Require a current own intake/application fact.
 const {rows:[known]}=await ctx.db.query("SELECT d.interview_id FROM iiq.interview_intake_details d JOIN iiq.interviews i ON i.id=d.interview_id AND i.owner_id=d.owner_id WHERE d.owner_id=$1 AND i.program_id=$2 AND d.position_type IN ('PRELIMINARY','TRANSITIONAL_YEAR') AND d.application_state='APPLIED' AND NOT EXISTS(SELECT 1 FROM iiq.interview_intake_details n WHERE n.owner_id=d.owner_id AND n.interview_id=d.interview_id AND n.intake_version>d.intake_version) LIMIT 1",[ctx.actor.id,t.program_id]);
 requireValue(known,'intake_prelim_unverified','Confirm an existing preliminary or transitional application fact first.');
}
async function appendDetails(ctx,row,p,version){
 requireValue(!p.details.advancedFactConfirmed||row.program_id,'intake_advanced_identity','Confirm the actual Advanced program before using this fact in a letter.');await validatePrelim(ctx,p.details,p.positionType);const selectedColumns={...columns,...(ctx.config.calendar?.enabled?{invitationReceivedDate:'invitation_received_date',statusDetail:'status_detail'}:{})},keys=Object.keys(selectedColumns),names=['owner_id','interview_id','intake_version','registry_release_id','specialty','acgme_id','position_type','student_track',...keys.map(k=>selectedColumns[k])],values=[ctx.actor.id,row.id,version,p.program?.registryReleaseId??null,p.program?.specialty??null,p.program?.acgmeId??null,p.positionType,p.track,...keys.map(k=>p.details[k])];
 await ctx.db.query(`INSERT INTO iiq.interview_intake_details(${names.join(',')}) VALUES(${values.map((_,i)=>'$'+(i+1)).join(',')})`,values);
 for(let k=0;k<p.experiences.length;k++){const e=p.experiences[k];await ctx.db.query('INSERT INTO iiq.interview_experiences(owner_id,interview_id,intake_version,ordinal,kind,department,start_date,end_date,description,contact,confirmed) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,true)',[ctx.actor.id,row.id,version,k,e.kind,e.department,e.startDate,e.endDate,e.description,e.contact]);}
}
export async function writeIntake(ctx){
 requireIntake(ctx.config,ctx.actor);if(!ctx.config.calendar?.enabled)requireValue(!ctx.data.details?.invitationReceivedDate&&!ctx.data.details?.statusDetail&&!['PHONE'].includes(ctx.data.details?.invitationSource)&&ctx.data.details?.structure!=='MMI','calendar_unavailable','These additional intake fields are not active.',403);const p=parseIntake(ctx.data,ctx.command==='intake.update');
 if(ctx.command==='intake.update'){
  const row=await interview(ctx.db,ctx.actor,ctx.interviewId,{lock:true}),old=(await ctx.db.query('SELECT * FROM iiq.interview_intake_details WHERE owner_id=$1 AND interview_id=$2 ORDER BY intake_version DESC LIMIT 1',[ctx.actor.id,row.id])).rows[0];
  requireValue(Number(old?.intake_version??0)===p.expectedIntakeVersion,'intake_version_conflict','Your intake details changed. Keep your draft and review the current version.',409);
  const oldExperiences=old?(await ctx.db.query('SELECT * FROM iiq.interview_experiences WHERE owner_id=$1 AND interview_id=$2 AND intake_version=$3 ORDER BY ordinal',[ctx.actor.id,row.id,old.intake_version])).rows:[];p.details=details({...(ctx.config.calendar?.enabled?{invitationReceivedDate:old?.invitation_received_date??undefined,statusDetail:old?.status_detail??undefined}:{}),...Object.fromEntries(Object.entries(columns).map(([k,c])=>[k,old?.[c]??undefined])),...p.detailsInput});p.experiences=experiences(p.experiencesInput===undefined?(old?view(old,oldExperiences).experiences:[]):p.experiencesInput);requireValue(p.details.relationshipState==='YES'||p.experiences.length===0,'intake_relationship','Confirm a prior connection before adding experiences.');
  const next=p.expectedIntakeVersion+1;await appendDetails(ctx,row,{...p,program:old?{registryReleaseId:old.registry_release_id,specialty:old.specialty,acgmeId:old.acgme_id}:null,positionType:p.positionType??old?.position_type??'UNKNOWN',track:p.track??old?.student_track??row.program_track},next);
  await history(ctx.db,row,'Intake details updated',{from:p.expectedIntakeVersion,to:next,studentReported:true});return{type:'interview',id:row.id,interviewId:row.id,intakeVersion:next};
 }
 requireValue(!ctx.interviewId,'intake_create_subject','A new intake cannot reuse an existing interview identifier.');
 let program=null;
 if(p.identity.programId){requireValue(typeof ctx.owners.getIntakeProgram==='function','intake_owner_unavailable','Current RISE identity is unavailable; retain an unresolved invitation instead.',503);program=await ctx.owners.getIntakeProgram(ctx.actor,p.identity.programId);requireValue(program?.id===p.identity.programId&&program.registryReleaseId===p.identity.registryReleaseId,'intake_registry_changed','RISE identity changed. Confirm the current exact program again.',409);}
 // Reuse the existing schedule/interview persistence without returning a research dispatch binding.
 const owner={...ctx.owners,getProgram:async()=>program},saved=await writeInterview({...ctx,command:'interview.create',data:{unresolved_input:p.identity.invitationLabel,program:program?.id??null,programName:program?.name??p.identity.invitationLabel,track:program?.track??p.track,deadline:p.deadline,schedule:p.schedule},owners:owner,config:{...ctx.config,coreOnly:true,deepResearch:{...ctx.config.deepResearch,enabled:false}}}),row=await interview(ctx.db,ctx.actor,saved.id,{lock:true});
 await appendDetails(ctx,row,{...p,program},1);
 for(const e of p.events){const result=await writeInterview({...ctx,command:'event.create',interviewId:row.id,data:{kind:e.kind.replaceAll('_',' '),date:e.schedule.date,time:e.schedule.time,zone:e.schedule.zone,fold:e.schedule.fold,duration_minutes:e.schedule.duration,note:e.note}});const s=scheduleColumns(e.schedule);await ctx.db.query('INSERT INTO iiq.interview_event_details(owner_id,interview_id,event_id,client_key,event_kind,format,joining,location,requirement) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[ctx.actor.id,row.id,result.id,e.clientKey,e.kind,s.format,s.joining,e.location,e.required]);}
 await history(ctx.db,row,'Intake saved',{intakeVersion:1,relatedEventCount:p.events.length,identity:program?'CANONICAL':'PROVISIONAL',studentReported:true});return{type:'interview',id:row.id,interviewId:row.id,intakeVersion:1,relatedEventCount:p.events.length};
}
function view(d,x){const out={version:Number(d.intake_version),registryReleaseId:d.registry_release_id,specialty:d.specialty,acgmeId:d.acgme_id,positionType:d.position_type,track:d.student_track,details:{},experiences:x.map(e=>({kind:e.kind,department:e.department,startDate:e.start_date instanceof Date?e.start_date.toISOString().slice(0,10):e.start_date,endDate:e.end_date instanceof Date?e.end_date.toISOString().slice(0,10):e.end_date,description:e.description,contact:e.contact,confirmed:e.confirmed})),itineraryUpload:{status:'PENDING_SEPARATE_INTEGRATION',attachment:null},sharedCalendar:{status:'PENDING_SEPARATE_POLICY'}};for(const [k,c]of Object.entries(columns))out.details[k]=d[c];if(Object.hasOwn(d,'invitation_received_date')){out.details.invitationReceivedDate=d.invitation_received_date;out.details.statusDetail=d.status_detail;}return out;}
export async function readIntake(ctx){requireIntake(ctx.config,ctx.actor);await interview(ctx.db,ctx.actor,ctx.interviewId);const{rows:[d]}=await ctx.db.query('SELECT * FROM iiq.interview_intake_details WHERE owner_id=$1 AND interview_id=$2 ORDER BY intake_version DESC LIMIT 1',[ctx.actor.id,ctx.interviewId]);if(!d)return null;const{rows:x}=await ctx.db.query('SELECT * FROM iiq.interview_experiences WHERE owner_id=$1 AND interview_id=$2 AND intake_version=$3 ORDER BY ordinal',[ctx.actor.id,ctx.interviewId,d.intake_version]);return view(d,x);}
export async function attachIntake(db,actor,config,state){if(!intakeEnabled(config,actor))return;const{rows:d}=await db.query('SELECT DISTINCT ON (interview_id) * FROM iiq.interview_intake_details WHERE owner_id=$1 ORDER BY interview_id,intake_version DESC',[actor.id]);const{rows:x}=await db.query('SELECT * FROM iiq.interview_experiences WHERE owner_id=$1 ORDER BY intake_version,ordinal',[actor.id]);const{rows:events}=await db.query('SELECT * FROM iiq.interview_event_details WHERE owner_id=$1',[actor.id]);for(const i of state.interviews){if(i.owner!==actor.id)continue;const detail=d.find(t=>t.interview_id===i.id);i.intake=detail?view(detail,x.filter(e=>e.interview_id===i.id&&e.intake_version===detail.intake_version)):null;for(const e of i.related??[]){const meta=events.find(m=>m.event_id===e.id);if(meta)e.intake={kind:meta.event_kind,format:meta.format,joining:meta.joining,location:meta.location,required:meta.requirement};}}}
