const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test'),path=require('node:path');
const root=fs.existsSync(path.join(__dirname,'matrix-v2-iiq-1203.js'))?__dirname:path.join(__dirname,'../../infra/wordpress/matrix-v2-discovery/iiq-1203-v1'),js=fs.readFileSync(path.join(root,'matrix-v2-iiq-1203.js'),'utf8');
function renderer(eligible=true){const cfg={experience:'matrix2',apps:{},defaults:{},interviewiq_art:{pencil:'p.svg',cinematic:'c.svg'}};for(const id of ['homebase','calendar','scheduler','storyforge','ivprep','rise','ranklist','lor'])cfg.apps[id]={name:id};if(eligible)cfg.apps.interviewiq={id:'interviewiq',name:'INTERVIEWIQ',sub:'Add your scheduled interviews. Prepare smarter for every program.',cat:'Match tools',launch:'https://missionmedinstitute.com/interviewiq/?iiq_entry=calendar'};const window={MMED_OS:{render:{},access:{apps:{}}},mmedDashboardV2:cfg,location:{search:'',hash:''},addEventListener(){}};const document={addEventListener(){}};const ctx={window,document,URLSearchParams};vm.createContext(ctx);vm.runInContext(js.replace(/\}\)\(\);\s*$/, 'window.test={FEATURED,state,cardHTML,lockedArtURL,merchFor};})();'),ctx);return window.test;}
test('eligible card second; all original cards remain ordered',()=>assert.deepEqual(Array.from(renderer().FEATURED),['homebase','interviewiq','calendar','scheduler','storyforge','ivprep','rise','ranklist','lor']));
test('ineligible server payload leaves original collection intact',()=>assert.equal(renderer(false).FEATURED.includes('interviewiq'),false));
test('approved paired art uses family morph markup',()=>{const r=renderer();const s=r.cardHTML(r.state.apps.interviewiq,'test',false);assert.match(s,/data-morph-app="interviewiq"/);assert.match(s,/src="p.svg"/);assert.match(s,/data-src="c.svg"/);});
test('admin edit mode does not expose unsupported card editor',()=>{const r=renderer();r.state.editMode=true;assert.doesNotMatch(r.cardHTML(r.state.apps.interviewiq,'t',true),/data-editapp/);assert.match(r.cardHTML({...r.state.apps.homebase,id:'homebase'},'t',true),/data-editapp="homebase"/);});
test('exact Founder CTA and promise; no premature integration claims',()=>{const r=renderer();const m=r.merchFor(r.state.apps.interviewiq);assert.equal(m.cta,'ADD YOUR SCHEDULED INTERVIEW');assert.equal(m.promise,'Add your scheduled interviews. Prepare smarter for every program.');});
test('live HTTPS query launch (no duplicate internal route)',()=>assert.equal(renderer().state.apps.interviewiq.launch,'https://missionmedinstitute.com/interviewiq/?iiq_entry=calendar'));
