import assert from 'node:assert/strict';
import {test} from 'node:test';
import fs from 'node:fs';
import {createRequire} from 'node:module';
const {JSDOM}=createRequire(import.meta.url)('/Users/brianb/MissionMed/node_modules/jsdom');
const html=fs.readFileSync(new URL('../../LIVE/usce_admin.html',import.meta.url),'utf8');
const CASE='11111111-1111-4111-8111-111111111111',MSG='22222222-2222-4222-8222-222222222222',DIS='33333333-3333-4333-8333-333333333333';
function harness(url='https://synthetic.invalid/'){
 const dom=new JSDOM(html,{url,runScripts:'outside-only'}),w=dom.window;w.confirm=()=>true;w.fetch=()=>{throw Error('Network forbidden')};w.setInterval=()=>0;
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};Object.defineProperty(w.crypto,'randomUUID',{value:()=>DIS});
 const r={id:CASE,name:'Synthetic Student',email:'student@example.test',status:'NEW',program:'Synthetic program',school:'Synthetic school',specialties:['Internal Medicine'],locations:['New York'],months:['Oct 2026'],length:'4 weeks',comms:[],audit:[],offerHistory:[],submittedAt:Date.now()};
 const calls=[],sender={ready:true,from_email:'clinicals@missionmedinstitute.com',reply_to:'clinicals@missionmedinstitute.com'};let saved,revision=0,custom;
 w.MOCK=async(path,vars,options={})=>{calls.push({path,options});if(custom){const result=await custom(path,vars,options);if(result!==undefined)return result;}if(path.endsWith('/config'))return{ok:true,sender};if(path.includes('/drafts')&&options.method==='POST'){saved={...options.body,id:MSG,state:'draft',revision:++revision,to_email:r.email,from_email:sender.from_email};return{ok:true,item:saved};}if(path.endsWith('/preview'))return{ok:true,preview:{message_id:MSG,revision:saved.revision,to_email:saved.to_email,from_email:sender.from_email,reply_to:sender.reply_to,subject:saved.subject,body_text:saved.body_text,preview_hash:'a'.repeat(64)}};if(path.endsWith('/send'))return{ok:true,outcome:'provider_accepted',dispatch_id:DIS};if(path.endsWith('/messages/'+MSG))return{ok:true,item:{id:MSG,intake_request_id:CASE,state:'received',direction:'IN',unread:true,subject:'Synthetic reply',body_text:'<img src=x onerror=bad()>',from_email:r.email,to_email:sender.from_email,created_at:'2026-10-09T12:00:00Z',revision:1}};if(path.endsWith('/thread'))return{ok:true,items:[{id:MSG,intake_request_id:CASE,state:'received',direction:'IN',unread:true,subject:'Synthetic reply',body_text:'<img src=x onerror=bad()>',from_email:r.email,to_email:sender.from_email,created_at:'2026-10-09T12:00:00Z',revision:1}],has_more:false};return{ok:true,items:[],counts:{inbox:0,sent:0,drafts:0,unread:0,unassigned:0},has_more:false,sync:{backfill_complete:true}};};
 let source=w.document.querySelector('script').textContent;source=source.replace("renderRequestList(); switchView('hq'); loadLiveQueue();","adminFetch=window.MOCK;loadCaseActivity=async()=>{};loadLiveComms=()=>{};window.MAILTEST={state,mail,setV3Workspace,startMailComposer,saveMailDraft,reviewMailDraft,sendReviewedMail,loadMailConfig,loadCaseMail,openMailThread,selectRequest,loadMailDispatches};state.adapter='live';state.requests=window.REQS;");w.REQS=[r];w.eval(source);w.eval(w.document.querySelector('#usce-foundation-navigation').textContent);
 const a=w.MAILTEST,$=id=>w.document.getElementById(id);const input=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new w.Event('input',{bubbles:true}));};const compose=async()=>{await a.loadMailConfig();a.startMailComposer(CASE);input('mmMailSubject','Synthetic subject');input('mmMailBody','Synthetic body');};
 return{dom,w,a,$,calls,sender,r,input,compose,override(fn){custom=fn;}};
}
function check(name,fn){test(name,async()=>{const h=harness();try{await fn(h)}finally{h.dom.window.close()}})}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
check('general Communications is available without selecting a case; folders use the same endpoint',async({w,a,$,calls})=>{w.document.querySelector('[data-sf-nav="comms"]').click();await tick();assert.equal($('mmCx').dataset.workspace,'communications');assert.equal($('mmCommunications').hidden,false);assert.equal(w.document.querySelectorAll('[data-mail-folder]').length,5);assert.ok(calls.some(c=>c.path.includes('folder=inbox')));w.document.querySelector('[data-mail-folder="unassigned"]').click();await tick();assert.ok(calls.some(c=>c.path.includes('folder=unassigned')));a.startMailComposer(null);assert.equal($('mmMailCase').value,'');assert.equal($('mmMailTo').textContent,'Choose a student case');});
check('sender not ready permits draft saving and blocks review and send',async({a,$,sender,compose,calls})=>{sender.ready=false;await compose();assert.equal($('mmMailPreview').disabled,true);assert.equal($('mmMailSend').disabled,true);await a.saveMailDraft();await assert.rejects(a.reviewMailDraft(),/sender is not ready/);await assert.rejects(a.sendReviewedMail(),/Review and approve/);assert.equal(calls.filter(c=>c.path.endsWith('/send')).length,0);});
check('exact generic preview approval is invalidated by edits; recipient and sender remain verified',async({a,$,w,compose,input,calls})=>{await compose();await a.reviewMailDraft();assert.equal($('mmMailApproval').checked,false);$('mmMailApproval').checked=true;$('mmMailApproval').dispatchEvent(new w.Event('change'));assert.equal(a.mail.preview.from_email,'clinicals@missionmedinstitute.com');input('mmMailBody','Changed text');assert.equal(a.mail.preview,null);assert.equal($('mmMailApproval').checked,false);await assert.rejects(a.sendReviewedMail());assert.equal(calls.filter(c=>c.path.endsWith('/send')).length,0);});
check('ambiguous send is attempted once and held for reconciliation; generic mail never calls Offer APIs',async({a,$,compose,override,calls})=>{await compose();await a.reviewMailDraft();$('mmMailApproval').checked=true;override(path=>path.endsWith('/send')?{ok:true,outcome:'ambiguous',dispatch_id:DIS}:undefined);await a.sendReviewedMail();await assert.rejects(a.sendReviewedMail());assert.equal(calls.filter(c=>c.path.endsWith('/send')).length,1);assert.equal($('mmMailReconcile').hidden,false);assert.match($('mmMailSendOutcome').textContent,/Do not resend/);assert.ok(calls.every(c=>c.path.startsWith('/api/usce/admin/communications')));});
check('case history and unified thread share message records and render inbound body as text',async({a,$,calls,override})=>{a.state.selectedRequestId=CASE;override(path=>path.includes('folder=all')?{ok:true,items:[{id:MSG,subject:'Synthetic reply',state:'received',created_at:'2026-10-09T12:00:00Z'}],has_more:false}:undefined);await a.loadCaseMail(CASE);assert.equal($('mmCaseMailHistory').querySelector('button').textContent.startsWith('Synthetic reply'),true);await a.openMailThread(MSG);assert.ok(calls.some(c=>c.path.includes('folder=all')&&c.path.includes('intake_request_id='+CASE)));assert.ok(calls.some(c=>c.path.endsWith('/messages/'+MSG+'/thread')));assert.ok(calls.some(c=>c.path.endsWith('/messages/'+MSG+'/read')));assert.equal($('mmMailThreadMessages').querySelector('img'),null);assert.match($('mmMailThreadMessages').textContent,/<img/);assert.equal(a.mail.selected,MSG);});
check('template uses recorded preferences and never claims confirmed availability',async({a,$,compose,r})=>{await compose();$('mmMailTemplate').value='preferences';$('mmMailUseTemplate').click();assert.match($('mmMailBody').value,/Internal Medicine/);assert.match($('mmMailBody').value,/New York/);assert.match($('mmMailBody').value,/Preferences do not confirm rotation availability/);assert.equal(a.state.liveOffersByRequest[r.id],undefined);});
check('mismatched server recipient proof prevents sending and retains composer text',async({a,$,compose,override,calls})=>{await compose();override(path=>path.endsWith('/preview')?{ok:true,preview:{message_id:MSG,revision:1,to_email:'different@example.test',from_email:'clinicals@missionmedinstitute.com',reply_to:'clinicals@missionmedinstitute.com',subject:'Synthetic subject',body_text:'Synthetic body',preview_hash:'b'.repeat(64)}}:undefined);await assert.rejects(a.reviewMailDraft(),/did not match/);assert.equal($('mmMailBody').value,'Synthetic body');assert.equal(calls.filter(c=>c.path.endsWith('/send')).length,0);});
test('canonical message deep link opens the unified conversation through authenticated API',async()=>{const h=harness('https://synthetic.invalid/?conversation='+MSG);try{await tick();await tick();assert.equal(h.$('mmCx').dataset.workspace,'communications');assert.ok(h.calls.some(c=>c.path.endsWith('/messages/'+MSG+'/thread')));}finally{h.dom.window.close();}});

check('exact older deep-linked message remains the reply target outside newest thread page',async({a,$,calls,override})=>{
 const newest='44444444-4444-4444-8444-444444444444';override(path=>path.endsWith('/thread')?{ok:true,items:[{id:newest,intake_request_id:CASE,state:'received',direction:'IN',subject:'Newer message',created_at:'2026-10-10T12:00:00Z',body_text:'Newer body'}],has_more:true,next_cursor:{before:'2026-10-10T12:00:00Z',before_id:newest}}:undefined);
 await a.openMailThread(MSG);assert.equal(a.mail.selectedItem.id,MSG);assert.equal($('mmMailThreadTitle').textContent,'Synthetic reply');$('mmMailReply').click();assert.equal(a.mail.reply.id,MSG);assert.ok(calls.some(c=>c.path.endsWith('/messages/'+MSG)));
});

check('delivery attention offers readback for ambiguous and retry only for confirmed-unsent failure',async({a,w,$,calls,override})=>{
 const failed='55555555-5555-4555-8555-555555555555';override(path=>path.endsWith('/dispatches')?{ok:true,items:[{id:DIS,entity_id:MSG,action:'usce_v3_notify',state:'ambiguous',attempts:1,can_reconcile:true,can_retry:false},{id:failed,entity_id:MSG,action:'usce_v3_correspondence',state:'failed',attempts:1,can_reconcile:false,can_retry:true}],has_more:false}:undefined);
 await a.loadMailDispatches();assert.equal(w.document.querySelectorAll('[data-dispatch-retry]').length,1);assert.equal(w.document.querySelector('[data-dispatch-retry]').dataset.dispatchRetry,failed);assert.equal(w.document.querySelector('[data-dispatch-reconcile]').dataset.dispatchReconcile,DIS);
 w.confirm=()=>false;w.document.querySelector('[data-dispatch-retry]').click();await tick();assert.equal(calls.filter(c=>c.path.endsWith('/retry')).length,0);
 w.confirm=()=>true;w.document.querySelector('[data-dispatch-retry]').click();await tick();const retry=calls.find(c=>c.path.endsWith('/retry'));assert.equal(retry.options.body.confirm_retry,true);assert.match(retry.path,new RegExp(failed));
});
check('unavailable inbound body is marked incomplete and links to Clinicals Gmail',async({a,$,override})=>{
 override(path=>path.endsWith('/messages/'+MSG)?{ok:true,item:{id:MSG,intake_request_id:CASE,state:'received',subject:'Large reply',body_unavailable:true,created_at:'2026-10-09T12:00:00Z'}}:path.endsWith('/thread')?{ok:true,items:[{id:MSG,intake_request_id:CASE,state:'received',subject:'Large reply',body_unavailable:true,created_at:'2026-10-09T12:00:00Z'}],has_more:false}:undefined);
 await a.openMailThread(MSG);assert.match($('mmMailThreadMessages').textContent,/full body could not be retrieved/);assert.match($('mmMailThreadMessages').querySelector('a').href,/mail.google.com/);
});

check('linked reply and draft outside filtered queue use current trusted recipient without inventing preferences',async({a,$,r,override,compose})=>{
 a.state.requests=[];const dto={id:MSG,intake_request_id:CASE,state:'received',subject:'Linked reply',from_email:'historical@example.test',body_text:'Historical message',needs_triage:false};
 await a.loadMailConfig();a.startMailComposer(CASE,dto);assert.equal($('mmMailCompose').open,true);assert.equal($('mmMailTo').textContent,'Recipient verified when draft is saved');assert.equal(a.state.requests.length,0);$('mmMailTemplate').value='preferences';$('mmMailUseTemplate').click();assert.doesNotMatch($('mmMailBody').value,/Internal Medicine|New York|Oct 2026/);await a.reviewMailDraft();assert.equal(a.mail.preview.to_email,r.email);
 $('mmMailCompose').close();a.startMailComposer(CASE,null,{...dto,state:'draft',revision:1,to_email:'historical@example.test',subject:'Saved draft',body_text:'Saved body'});assert.equal($('mmMailBody').value,'Saved body');assert.equal($('mmMailTo').textContent,'Recipient verified when draft is saved');assert.equal(a.state.requests.length,0);await a.reviewMailDraft();assert.equal($('mmMailTo').textContent,r.email);assert.equal(a.mail.preview.to_email,r.email);assert.notEqual(a.mail.preview.to_email,'historical@example.test');
});
check('archived linked case permits correspondence without reopening case or changing Offer',async({a,$,r,compose})=>{
 r.status='ARCHIVED';await compose();await a.reviewMailDraft();assert.equal(r.status,'ARCHIVED');assert.equal(a.state.liveOffersByRequest[CASE],undefined);assert.equal(a.mail.preview.to_email,r.email);
});
check('draft save conflict remains actionable inside composer after finally and preserves text',async({a,w,$,compose,override,input})=>{
 await compose();override(path=>{if(path.endsWith('/drafts')){const e=new Error('Conflict');e.status=409;e.payload={error:'stale_revision'};throw e;}});$('mmMailSave').click();await tick();
 assert.equal($('mmMailCompose').open,true);assert.match($('mmMailComposeStatus').textContent,/draft changed/);assert.match($('mmMailComposeStatus').textContent,/text is retained/);assert.equal($('mmMailBody').value,'Synthetic body');assert.equal($('mmMailSubject').value,'Synthetic subject');
 await a.loadMailConfig();assert.match($('mmMailComposeStatus').textContent,/draft changed/);input('mmMailBody','Meaningful edit');assert.doesNotMatch($('mmMailComposeStatus').textContent,/draft changed/);
});
