import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeGmailMessage,hydrateTextBodies,syncMailboxOnce,startUsceMailWorker,createGmailReader} from '../lib/usce-mail-sync.mjs';
const message=(id='abc001',extra={})=>({id,threadId:'def001',internalDate:'1791547200000',labelIds:['INBOX'],payload:{mimeType:'multipart/mixed',headers:[{name:'From',value:'Synthetic Student <student@example.invalid>'},{name:'To',value:'clinicals@missionmedinstitute.com'},{name:'Subject',value:'Synthetic reply'},{name:'Message-ID',value:'<synthetic@example.invalid>'},{name:'In-Reply-To',value:'<known@example.invalid>'}],parts:[{mimeType:'text/plain',body:{data:Buffer.from('Line one\nLine two').toString('base64url')}},{mimeType:'application/pdf',filename:'paperwork.pdf',body:{attachmentId:'private'}}]},...extra});
function fixture(state={}){const calls=[];let current={generation:1,baseline_history_id:'100',history_id:'100',baseline_at:'2026-10-09T11:00:00Z',backfill_complete:true,...state};return {calls,get state(){return current},rpc:async(name,p)=>{calls.push({name,...p});if(name==='usce_mail_ingest')return {ok:true};if(p.p_action==='claim')return {ok:true,claimed:true,state:current};if(p.p_action==='initialize'){current={...current,baseline_history_id:p.p_data.history_id,history_id:p.p_data.history_id};return {ok:true,state:current};}if(p.p_action==='checkpoint')current={...current,...p.p_data};return {ok:true,state:current};}};}
test('parser preserves plain text and never fetches or embeds attachments',()=>{const m=normalizeGmailMessage(message());assert.equal(m.body_text,'Line one\nLine two');assert.equal(m.attachment_count,1);assert.equal(m.from_email,'student@example.invalid');assert.equal(m.in_reply_to,'<known@example.invalid>');assert.equal(m.automatic,false);assert.doesNotMatch(JSON.stringify(m),/paperwork\.pdf|private/);});
test('HTML fallback removes executable markup and is still plain text',()=>{const m=message();m.payload.parts=[{mimeType:'text/html',body:{data:Buffer.from('<script>secret()</script><p>Hello &amp; welcome</p>').toString('base64url')}}];assert.equal(normalizeGmailMessage(m).body_text,'Hello & welcome\n');});
test('large body is explicitly flagged as truncated',()=>{const m=message();m.payload.parts=[{mimeType:'text/plain',body:{data:Buffer.from('x'.repeat(100001)).toString('base64url')}}];const p=normalizeGmailMessage(m);assert.equal(p.body_text.length,100000);assert.equal(p.body_truncated,true);});
test('automatic messages are classified to prevent personal notification loops',()=>{const m=message();m.payload.headers.push({name:'Auto-Submitted',value:'auto-replied'});assert.equal(normalizeGmailMessage(m).automatic,true);});
test('baseline is persisted before historical listing and import cannot notify via history phase',async()=>{const f=fixture({baseline_history_id:null,history_id:null,backfill_complete:false});const order=[];const rpc=async(n,p)=>{order.push(p.p_action||n);return f.rpc(n,p)};const r=await syncMailboxOnce({rpc,gmail:async(path)=>{order.push(path);return {ok:true,data:path==='profile'?{historyId:'123'}:path==='messages'?{messages:[{id:'abc001'}],nextPageToken:'next'}:message()}}});assert.equal(r.ok,true);assert.ok(order.indexOf('initialize')<order.indexOf('messages'));assert.equal(f.calls.find(c=>c.name==='usce_mail_ingest').p_phase,'backfill');assert.equal(f.state.history_id,'123');assert.equal(f.state.backfill_page_token,'next');assert.equal(f.state.backfill_complete,false);});
test('history duplicates are ingested once per page and cursor advances after persistence',async()=>{const f=fixture();const r=await syncMailboxOnce({rpc:f.rpc,gmail:async path=>({ok:true,data:path==='history'?{history:[{messagesAdded:[{message:{id:'abc001'}},{message:{id:'abc001'}}]}],historyId:'200'}:message()})});assert.equal(r.ok,true);assert.equal(f.calls.filter(c=>c.name==='usce_mail_ingest').length,1);assert.equal(f.state.history_id,'200');assert.ok(f.calls.findIndex(c=>c.name==='usce_mail_ingest')<f.calls.findIndex(c=>c.p_action==='checkpoint'));});
test('partial history page preserves starting cursor and persists continuation',async()=>{const f=fixture();await syncMailboxOnce({rpc:f.rpc,gmail:async()=>({ok:true,data:{history:[],historyId:'200',nextPageToken:'page2'}})});assert.equal(f.state.history_id,'100');assert.equal(f.state.history_page_token,'page2');});
test('storage failure prevents advancing cursor and releases sync lease',async()=>{const f=fixture();const r=await syncMailboxOnce({rpc:async(n,p)=>n==='usce_mail_ingest'?{ok:false,error:'storage_failed'}:f.rpc(n,p),gmail:async path=>({ok:true,data:path==='history'?{history:[{messagesAdded:[{message:{id:'abc001'}}]}],historyId:'200'}:message()})});assert.equal(r.ok,false);assert.equal(f.state.history_id,'100');assert.equal(f.calls.some(c=>c.p_action==='checkpoint'),false);assert.equal(f.calls.at(-1).p_action,'release');});
test('expired history triggers explicit recovery baseline rather than claiming current',async()=>{const f=fixture();const r=await syncMailboxOnce({rpc:f.rpc,gmail:async path=>path==='history'?{ok:false,status:404,error:'gmail_history_expired'}:{ok:true,data:{historyId:'999'}}});assert.equal(r.recovering,true);assert.equal(f.calls.find(c=>c.p_action==='recover').p_data.history_id,'999');assert.equal(f.calls.some(c=>c.p_action==='checkpoint'),false);});
test('draft/spam/trash Gmail events do not become incoming messages or sent copies',async()=>{const f=fixture();await syncMailboxOnce({rpc:f.rpc,gmail:async path=>({ok:true,data:path==='history'?{history:[{messagesAdded:[{message:{id:'abc001'}}]}],historyId:'200'}:message('abc001',{labelIds:['DRAFT']})})});assert.equal(f.calls.some(c=>c.name==='usce_mail_ingest'),false);});
test('no concurrent worker operates when durable claim is unavailable',async()=>{let read=0;const r=await syncMailboxOnce({rpc:async()=>({ok:true,claimed:false}),gmail:async()=>{read++}});assert.equal(r.claimed,false);assert.equal(read,0);});
test('background worker cannot start in shared HQ or when disabled',()=>{for(const env of [{USCE_MAIL_SYNC_ENABLED:'true'},{MMHQ_USCE_GATEWAY_CHILD:'1'},{MMHQ_USCE_GATEWAY_CHILD:'0',USCE_MAIL_SYNC_ENABLED:'true'}])assert.equal(startUsceMailWorker({env}).started,false);});
test('Gmail reader pins actual Clinicals mailbox and only reads',async()=>{let url,method;const gmail=createGmailReader({config:()=>({ok:true,credentials:{},scopes:['readonly']}),mint:async p=>{assert.equal(p.mailbox,'clinicals@missionmedinstitute.com');return {ok:true,accessToken:'synthetic'}},fetchImpl:async(u,o)=>{url=String(u);method=o.method;return {ok:true,json:async()=>({historyId:'1'})}}});assert.equal((await gmail('profile')).ok,true);assert.match(url,/users\/clinicals%40missionmedinstitute.com\/profile$/);assert.equal(method,undefined);});

test('unnamed text body attachmentId is fetched while named student documents never are',async()=>{const m=message();m.payload.parts.unshift({mimeType:'text/plain',body:{attachmentId:'body-id',size:24}});let calls=[];await hydrateTextBodies(m,async path=>{calls.push(path);return {ok:true,data:{data:Buffer.from('Remote plain message body').toString('base64url')}}});const value=normalizeGmailMessage(m);assert.deepEqual(calls,['messages/abc001/attachments/body-id']);assert.match(value.body_text,/Remote plain message body/);assert.equal(value.body_unavailable,false);assert.equal(value.attachment_count,1);});
test('oversized or unavailable text bodies are explicitly incomplete rather than empty-complete',async()=>{const m=message();m.payload.parts=[{mimeType:'text/plain',body:{attachmentId:'large-body',size:256001}}];let calls=0;await hydrateTextBodies(m,async()=>{calls++});const value=normalizeGmailMessage(m);assert.equal(calls,0);assert.equal(value.body_unavailable,true);assert.equal(value.attachment_count,0);});
test('body-part read failure prevents cursor advance',async()=>{const f=fixture();const m=message();m.payload.parts=[{mimeType:'text/plain',body:{attachmentId:'body',size:10}}];const result=await syncMailboxOnce({rpc:f.rpc,gmail:async path=>path==='history'?{ok:true,data:{history:[{messagesAdded:[{message:{id:'abc001'}}]}],historyId:'200'}}:path.includes('/attachments/')?{ok:false,status:503}:{ok:true,data:m}});assert.equal(result.ok,false);assert.equal(f.state.history_id,'100');assert.equal(f.calls.some(c=>c.p_action==='checkpoint'),false);});

test('machine classification uses headers or corroborated report/system signals; ordinary student terms do not trigger it',()=>{
 const parse=(from,subject,extra=[],body='I am interested in a clinical rotation')=>{
  const m=message();m.payload.headers=m.payload.headers.filter(h=>!['From','Subject','In-Reply-To'].includes(h.name));
  m.payload.headers.push({name:'From',value:from},{name:'Subject',value:subject},...extra);
  m.payload.parts=[{mimeType:'text/plain',body:{data:Buffer.from(body).toString('base64url')}}];return normalizeGmailMessage(m);
 };
 assert.equal(parse('student@example.invalid','My DMARC class and clinical rotation').automatic,false);
 assert.equal(parse('reports@example.invalid','Report Domain: missionmedinstitute.com Submitter: example Report-ID: 123').automatic,false);
 const report=message();report.payload.headers.push({name:'Subject',value:'ignored duplicate'});
 report.payload.headers=report.payload.headers.filter(h=>h.name!=='Subject');report.payload.headers.push({name:'Subject',value:'Report Domain: missionmedinstitute.com Submitter: example Report-ID: 123'});
 assert.equal(normalizeGmailMessage(report).automation_reason,'dmarc_report'); // corroborated attachment
 assert.equal(parse('student@example.invalid','Clinical rotation',[]).automatic,false);
 assert.equal(parse('noreply@example.invalid','Security alert').automation_reason,'system_alert');
 assert.equal(parse('newsletter@example.invalid','Clinical offers',[{name:'List-Unsubscribe',value:'<mailto:unsubscribe@example.invalid>'}]).automation_reason,'mailing_list');
 assert.equal(parse('sender@example.invalid','Report',[{name:'Content-Type',value:'multipart/report; report-type=feedback-report'}]).automatic,true);
});
test('sender authentication accepts only Gmail authentication result authority and stores no full headers',()=>{
 const m=message();m.payload.headers.push({name:'Authentication-Results',value:'attacker.invalid; dmarc=pass'});
 assert.equal(normalizeGmailMessage(m).sender_authentication,'unknown');
 m.payload.headers=m.payload.headers.filter(h=>h.name!=='Authentication-Results');
 m.payload.headers.push({name:'Authentication-Results',value:'mx.google.com; dmarc=pass header.from=example.invalid'});
 assert.equal(normalizeGmailMessage(m).sender_authentication,'passed');
 assert.doesNotMatch(JSON.stringify(normalizeGmailMessage(m)),/header.from|mx.google.com/);
 m.payload.headers.at(-1).value='mx.google.com; dmarc=fail';
 assert.equal(normalizeGmailMessage(m).sender_authentication,'failed');
});
