import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {getMailSender,previewMessage,submitMail,sendDraft,notificationMessage,reconcileDispatch,dispatchNextNotification,retryDispatch,makeMailRpc,sha256} from '../lib/usce-mail-dispatch.mjs';
import {handleUsceCommunicationsRoute} from '../routes/usce-communications.mjs';
const ID='11111111-1111-4111-8111-111111111111',DIS='22222222-2222-4222-8222-222222222222',PROVIDER='33333333-3333-4333-8333-333333333333';
const env={POSTMARK_SERVER_TOKEN:'synthetic-token',USCE_POSTMARK_FROM_EMAIL:'clinicals@missionmedinstitute.com',USCE_POSTMARK_REPLY_TO_EMAIL:'clinicals@missionmedinstitute.com',USCE_POSTMARK_LIVE_SEND_ENABLED:'true',USCE_POSTMARK_DRY_RUN:'false'};
const item={id:ID,revision:1,state:'draft',to_email:'student@example.invalid',subject:'Synthetic correspondence',body_text:'Synthetic message',references_ids:['<parent@example.invalid>'],in_reply_to:'<parent@example.invalid>'};
const payload=()=>({...previewMessage(item,getMailSender(env)).preview,rfc_message_id:'<usce-mail-'+ID+'@missionmedinstitute.com>',text_sha256:sha256(item.body_text)});
const response=(status,value)=>({ok:status>=200&&status<300,status,json:async()=>value});
async function route(path,method='GET',body=null,context={authorizedUsceAdmin:true},dependencies={}){let code,result;const req=Readable.from(body===null?[]:[typeof body==='string'?body:JSON.stringify(body)]);req.method=method;const res={writeHead(c){code=c},end(v){result=JSON.parse(v)}};await handleUsceCommunicationsRoute(req,res,new URL('http://local.invalid/api/usce/admin/communications'+path),context,{env,...dependencies});return {code,result};}

test('Clinicals sender is fail closed until dedicated config matches',()=>{assert.equal(getMailSender(env).ok,true);for(const change of [{USCE_POSTMARK_FROM_EMAIL:'info@missionmedinstitute.com'},{USCE_POSTMARK_DRY_RUN:'true'},{USCE_POSTMARK_LIVE_SEND_ENABLED:'false'},{POSTMARK_SERVER_TOKEN:''}])assert.equal(getMailSender({...env,...change}).ok,false);});
test('preview binds sender, exact text, revision and reply headers',()=>{const p=previewMessage(item,getMailSender(env));assert.equal(p.ok,true);for(const change of [{body_text:'Changed'},{subject:'Changed'},{revision:2},{in_reply_to:'<other@example.invalid>'}])assert.notEqual(previewMessage({...item,...change},getMailSender(env)).preview.preview_hash,p.preview.preview_hash);});
test('generic correspondence cannot carry secure Offer link around approved Offer path',()=>{assert.equal(previewMessage({...item,body_text:'https://cdn.missionmedinstitute.com/html-system/LIVE/usce_offer.html?offer=synthetic'},getMailSender(env)).error,'use_offer_journey');});
test('Postmark send uses Clinicals sender, bound reply references and durable dispatch metadata',async()=>{let body;const result=await submitMail(payload(),DIS,{env,fetchImpl:async(_u,o)=>{body=JSON.parse(o.body);return response(200,{ErrorCode:0,MessageID:PROVIDER})}});assert.equal(result.outcome,'provider_accepted');assert.equal(body.ReplyTo,'clinicals@missionmedinstitute.com');assert.equal(body.Headers.find(h=>h.Name==='In-Reply-To').Value,'<parent@example.invalid>');assert.equal(body.Metadata.usce_dispatch_id,DIS);assert.equal(body.Headers.find(h=>h.Name==='Message-ID').Value,payload().rfc_message_id);});
for(const [name,fetchImpl] of [['timeout',async()=>{throw new Error('timeout')}],['server failure',async()=>response(503,{})],['invalid successful response',async()=>response(200,{ErrorCode:0})]])test(name+' holds uncertain outcome after exactly one attempt',async()=>{let calls=0;const r=await submitMail(payload(),DIS,{env,fetchImpl:async(...a)=>{calls++;return fetchImpl(...a)}});assert.equal(r.outcome,'ambiguous');assert.equal(calls,1);});
test('explicit provider rejection is failed, not delivered',async()=>{const r=await submitMail(payload(),DIS,{env,fetchImpl:async()=>response(422,{ErrorCode:300})});assert.equal(r.outcome,'failed');});
test('header injection is blocked before provider attempt',async()=>{let calls=0;const r=await submitMail({...payload(),in_reply_to:'x\r\nBcc: victim@example.invalid'},DIS,{env,fetchImpl:async()=>{calls++}});assert.equal(r.attempted,false);assert.equal(calls,0);});
test('stale preview cannot claim or send',async()=>{let claims=0;const r=await sendDraft({id:ID,revision:1,preview_hash:'stale',idempotency_key:'test-key'},{env,rpc:async n=>{if(n!=='usce_mail_read')claims++;return {ok:true,item}}});assert.equal(r.error,'stale_preview');assert.equal(claims,0);});
test('duplicate claimed dispatch cannot hit provider again',async()=>{let calls=0;const proof=previewMessage(item,getMailSender(env));const r=await sendDraft({id:ID,revision:1,preview_hash:proof.preview.preview_hash,idempotency_key:'test-key'},{env,rpc:async n=>n==='usce_mail_read'?{ok:true,item}:{ok:true,claimed:false,dispatch:{id:DIS,state:'claimed'}},fetchImpl:async()=>{calls++}});assert.equal(calls,0);assert.equal(r.ok,false);assert.equal(r.error,'send_requires_reconciliation');});
test('failure recording accepted attempt reports reconciliation, never blind retry',async()=>{let calls=0;const proof=previewMessage(item,getMailSender(env));const r=await sendDraft({id:ID,revision:1,preview_hash:proof.preview.preview_hash,idempotency_key:'test-key'},{env,rpc:async n=>n==='usce_mail_read'?{ok:true,item}:n==='usce_mail_claim_send'?{ok:true,claimed:true,dispatch:{id:DIS,attempt_id:ID,action:'usce_v3_correspondence',payload:payload()}}:{ok:false},fetchImpl:async()=>{calls++;return response(200,{ErrorCode:0,MessageID:PROVIDER})}});assert.equal(calls,1);assert.equal(r.error,'send_requires_reconciliation');});
test('notification is fixed recipient and contains secure entry link, no student body',()=>{const n=notificationMessage({id:DIS,payload:{message_id:ID,student_name:'Synthetic Student',received_at:'2026-10-09T12:00:00Z',body_text:'PRIVATE_PAPERWORK'}});assert.equal(n.to_email,'philaperri@gmail.com');assert.match(n.body_text,/usce-admin\/\?conversation=/);assert.match(n.body_text,/mail.google.com/);assert.doesNotMatch(n.body_text,/PRIVATE_PAPERWORK/);assert.match(n.rfc_message_id,/usce-notify-/);});
test('notification waits for configured sender without consuming a claim',async()=>{let calls=0;const r=await dispatchNextNotification({env:{},rpc:async()=>{calls++}});assert.equal(r.error,'clinicals_sender_not_ready');assert.equal(calls,0);});
test('provider reconciliation rejects ambiguous search and mismatched content',async()=>{const rpc=async()=>({ok:true,dispatch:{id:DIS,attempt_id:ID,dispatch_state:'ambiguous',payload:payload()}});assert.equal((await reconcileDispatch(DIS,{env,rpc,fetchImpl:async()=>response(200,{TotalCount:2,Messages:[]})})).error,'provider_outcome_unresolved');let c=0;const r=await reconcileDispatch(DIS,{env,rpc,fetchImpl:async()=>++c===1?response(200,{TotalCount:1,Messages:[{MessageID:PROVIDER}]}):response(200,{MessageID:PROVIDER,Metadata:{usce_dispatch_id:DIS},Status:'Sent',Sandboxed:false,To:[{Email:item.to_email}],Subject:item.subject,TextBody:'Wrong'})});assert.equal(r.error,'provider_evidence_mismatch');});
test('RPC target cannot leave pinned USCE project',async()=>{let calls=0;const rpc=makeMailRpc({env:{MMHQ_SUPABASE_URL:'https://other.supabase.co',MMHQ_SUPABASE_SERVICE_ROLE_KEY:'synthetic'},fetchImpl:async()=>{calls++}});assert.equal((await rpc('usce_mail_read',{})).error,'mail_storage_not_configured');assert.equal(calls,0);});
test('route refuses absent admin gate before storage access',async()=>{let calls=0;const r=await route('', 'GET',null,{}, {rpc:async()=>{calls++}});assert.equal(r.code,403);assert.equal(calls,0);});
test('composer draft strips client recipient, sender and arbitrary provider fields',async()=>{let input;const r=await route('/drafts','POST',{intake_request_id:ID,subject:'Hello',body_text:'Message',to_email:'attacker@example.invalid',from_email:'attacker@example.invalid',raw_json:{a:1}},undefined,{rpc:async(_n,p)=>{input=p;return {ok:true}}});assert.equal(r.code,200);assert.equal(input.p_data.to_email,undefined);assert.equal(input.p_data.from_email,undefined);assert.equal(input.p_data.raw_json,undefined);});
test('send route requires explicit reviewed confirmation',async()=>{let calls=0;const r=await route('/messages/'+ID+'/send','POST',{revision:1,preview_hash:'a'.repeat(64),idempotency_key:'test-key'},undefined,{rpc:async()=>{calls++}});assert.equal(r.code,400);assert.equal(calls,0);});
test('malformed input and oversized JSON are bounded',async()=>{assert.equal((await route('/drafts','POST','{')).code,400);assert.equal((await route('/drafts','POST','x'.repeat(66000))).result.error,'payload_too_large');});

test('matching provider evidence is recorded against the same held attempt only',async()=>{let finish;let calls=0;const rpc=async(n,p)=>{if(p.p_action==='get')return {ok:true,dispatch:{id:DIS,attempt_id:ID,dispatch_state:'ambiguous',payload:payload()}};finish=p;return {ok:true}};const r=await reconcileDispatch(DIS,{env,rpc,fetchImpl:async()=>++calls===1?response(200,{TotalCount:1,Messages:[{MessageID:PROVIDER}]}):response(200,{MessageID:PROVIDER,Metadata:{usce_dispatch_id:DIS},Status:'Sent',Sandboxed:false,From:'MissionMed Clinicals <clinicals@missionmedinstitute.com>',To:[{Email:item.to_email}],Subject:item.subject,TextBody:item.body_text})});assert.equal(r.ok,true);assert.equal(finish.p_id,DIS);assert.equal(finish.p_attempt_id,ID);assert.equal(finish.p_data.evidence_source,'postmark_authenticated_readback');});

test('definite Postmark rejection is distinguished from an ambiguous provider outage for retry',async()=>{const rejected=await submitMail(payload(),DIS,{env,fetchImpl:async()=>response(422,{ErrorCode:300})});assert.equal(rejected.proven_unsent,true);const uncertain=await submitMail(payload(),DIS,{env,fetchImpl:async()=>response(503,{ErrorCode:500})});assert.equal(uncertain.proven_unsent,false);assert.equal(uncertain.outcome,'ambiguous');});
test('retry never reaches provider unless database proves prior non-acceptance',async()=>{let calls=0;const r=await retryDispatch(DIS,{env,rpc:async()=>({ok:false,error:'retry_requires_proven_unsent'}),fetchImpl:async()=>{calls++}});assert.equal(r.error,'retry_requires_proven_unsent');assert.equal(calls,0);});
test('dispatch recovery routes require explicit retry confirmation and expose only RPC projection',async()=>{let called;const deps={rpc:async(n,p)=>{called=p;return {ok:true,items:[]}}};assert.equal((await route('/dispatches','GET',null,undefined,deps)).code,200);assert.equal(called.p_action,'list');called=null;const r=await route('/dispatches/'+DIS+'/retry','POST',{},undefined,deps);assert.equal(r.code,400);assert.equal(called,null);});

test('unexpected 4xx/3xx without explicit Postmark rejection remains reconcilable ambiguity',async()=>{for(const status of [302,400,422,429]){let calls=0;const r=await submitMail(payload(),DIS,{env,fetchImpl:async()=>{calls++;return response(status,{})}});assert.equal(r.outcome,'ambiguous');assert.equal(r.proven_unsent,false);assert.equal(calls,1);}});
