import {createHash,randomUUID} from 'node:crypto';
import {mrxParse} from '../adapters/interviewiq-mrx-contract.mjs';
export const MEDIA_SCHEMA='iiq-program-media-candidate-v1',MEDIA_READ_SCHEMA='rise-program-media-v1';
export const MEDIA_STATES=['CANDIDATE','UNDER_REVIEW','APPROVED','REJECTED','WITHDRAWN'];
export const MEDIA_TRANSITIONS={CANDIDATE:['UNDER_REVIEW','REJECTED','WITHDRAWN'],UNDER_REVIEW:['APPROVED','REJECTED','WITHDRAWN'],APPROVED:['WITHDRAWN','REJECTED'],REJECTED:['UNDER_REVIEW'],WITHDRAWN:[]};
export const mediaNeed=(x,code='MEDIA_INVALID',status=422)=>{if(!x)throw Object.assign(Error(code),{code,status});};
export const mediaSha=x=>createHash('sha256').update(typeof x==='string'||Buffer.isBuffer(x)?x:JSON.stringify(mediaStable(x))).digest('hex');
export const mediaStable=x=>Array.isArray(x)?x.map(mediaStable):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,mediaStable(x[k])])):x;
export const mediaExact=(x,keys)=>mediaNeed(x&&Object.getPrototypeOf(x)===Object.prototype&&Object.keys(x).length===keys.length&&Object.keys(x).every(k=>keys.includes(k)));
export function mediaText(x,max=300,empty=false){mediaNeed(typeof x==='string'&&x.length<=max&&(empty||x.trim())&&!/[\u0000-\u001f\u007f]/.test(x));return x;}
export function mediaId(x){mediaNeed(typeof x==='string'&&/^rise_[A-Za-z0-9._:-]{1,174}$/.test(x));return x;}
export function mediaInstant(x){mediaNeed(typeof x==='string'&&Number.isFinite(Date.parse(x))&&new Date(x).toISOString()===x);return x;}
export function mediaUrl(x,{asset=false}={}){mediaText(x,2048);let u;try{u=new URL(x);}catch{mediaNeed(false);}mediaNeed(u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash&&!u.port&&u.hostname.includes('.')&&!/[\[\]:]/.test(u.hostname)&&!/^\d[\d.]*$/.test(u.hostname)&&!/(^|\.)(localhost|internal|local|private|invalid|test|example|lan|home|home\.arpa)$/.test(u.hostname));if(asset)mediaNeed(u.origin==='https://upload.wikimedia.org'&&/^\/wikipedia\/commons\/[a-f0-9]\/[a-f0-9]{2}\/[A-Za-z0-9_().%+,-]+\.(?:jpe?g|png|webp)$/i.test(u.pathname)&&!/%(?:2f|5c|00|2e)/i.test(u.pathname));return u.href;}
const candidateKeys=['schema','sourceUrl','publisher','assetRef','programId','registryReleaseId','category','caption','alt','verifiedAt','identityConfidence','licenseState','approvalState','discoveredBy','notes'];
const provenanceKeys=['institution','discoveryMission','assetSha256','assetBytes','licenseUrl','attribution','changes','pageRevision','pageReportedDate','exifReportedDate','dateConflict','observedAt'];
export function validateMediaInput(input,now=Date.now()){
 mediaExact(input,['candidate','provenance']);const c=input.candidate,p=input.provenance;mediaExact(c,candidateKeys);mediaExact(p,provenanceKeys);mediaNeed(c.schema===MEDIA_SCHEMA&&c.approvalState==='CANDIDATE');mediaId(c.programId);mediaText(c.registryReleaseId,180);mediaUrl(c.sourceUrl);mediaUrl(c.assetRef,{asset:true});mediaText(c.publisher,200);mediaText(c.caption,300,true);mediaText(c.alt,300);mediaText(c.notes,2000,true);mediaNeed(['INSTITUTION_EXTERIOR','CAMPUS','DEPARTMENT','LOGO','OTHER'].includes(c.category)&&['VERIFIED','HIGH','MEDIUM','LOW','UNKNOWN'].includes(c.identityConfidence)&&['PUBLISHER_TERMS','CREATIVE_COMMONS','PUBLIC_DOMAIN','PERMISSION_GRANTED','UNKNOWN','NOT_PERMITTED'].includes(c.licenseState)&&['RESEARCH','STUDENT','ADMIN','IMPORT'].includes(c.discoveredBy));
 mediaNeed(/^\d{4}-\d\d-\d\d$/.test(c.verifiedAt)&&new Date(c.verifiedAt).toISOString().slice(0,10)===c.verifiedAt&&Date.parse(c.verifiedAt)<=now);mediaText(p.institution,300);mediaText(p.discoveryMission,200);mediaNeed(/^[a-f0-9]{64}$/.test(p.assetSha256)&&Number.isSafeInteger(p.assetBytes)&&p.assetBytes>0&&p.assetBytes<=2000000);mediaUrl(p.licenseUrl);mediaText(p.attribution,500);mediaText(p.changes,300);mediaNeed(p.pageRevision===null||Number.isSafeInteger(p.pageRevision)&&p.pageRevision>0);
 for(const k of ['pageReportedDate','exifReportedDate'])mediaNeed(p[k]===null||/^\d{4}-\d\d-\d\d$/.test(p[k])&&new Date(p[k]).toISOString().slice(0,10)===p[k]);mediaText(p.dateConflict,500,true);if(p.dateConflict)mediaNeed(c.caption.length<=245&&!/\b(current|today|recent|latest)\b/i.test(c.caption));mediaInstant(p.observedAt);mediaNeed(Date.parse(p.observedAt)<=now&&Date.parse(p.observedAt)>=now-366*86400000);if(p.pageReportedDate&&p.exifReportedDate&&p.pageReportedDate!==p.exifReportedDate)mediaNeed(p.dateConflict.trim());return structuredClone(input);
}
const grants=new WeakSet();export function mediaAuthority(session,now=Date.now()) {mediaNeed(session?.role==='admin'&&session.capabilities?.includes('rise:admin')&&session.preview!==true&&session.audience==='rise'&&typeof session.issuer==='string'&&session.issuer.startsWith('https://')&&typeof session.subject==='string'&&/^wp:\d+$/.test(session.subject)&&Date.parse(session.expiresAt)>now,'MEDIA_ADMIN_REQUIRED',403);const grant=Object.freeze({actor:mediaSha('rise-program-media-admin-v1\0'+session.subject),expiresAt:Math.min(Date.parse(session.expiresAt),now+30000),nonce:randomUUID()});grants.add(grant);return grant;}
export function assertMediaAuthority(grant,now=Date.now()){mediaNeed(grants.has(grant)&&grant.expiresAt>now,'MEDIA_ADMIN_REQUIRED',403);return grant.actor;}
export function validateMediaDecision(input,now=Date.now()){
 mediaExact(input,['requestId','expectedCandidateVersion','expectedProgramVersion','state','reason','review']);mediaNeed(/^[a-f0-9-]{36}$/.test(input.requestId)&&Number.isSafeInteger(input.expectedCandidateVersion)&&input.expectedCandidateVersion>=0&&Number.isSafeInteger(input.expectedProgramVersion)&&input.expectedProgramVersion>=0&&MEDIA_STATES.includes(input.state)&&input.state!=='CANDIDATE');mediaText(input.reason,1000);const r=input.review;
 if(input.state==='APPROVED'){mediaExact(r,['explicitHumanApproval','institutionVerified','rightsVerified','checksumVerified','historicalPhotoAcknowledged','authorityRef','validThrough','replacesCandidateId']);for(const k of ['explicitHumanApproval','institutionVerified','rightsVerified','checksumVerified'])mediaNeed(r[k]===true);mediaNeed(typeof r.historicalPhotoAcknowledged==='boolean');mediaText(r.authorityRef,200);mediaNeed(r.replacesCandidateId===null||/^[a-f0-9-]{36}$/.test(r.replacesCandidateId));mediaInstant(r.validThrough);mediaNeed(Date.parse(r.validThrough)>now&&Date.parse(r.validThrough)<=now+366*86400000);}else mediaNeed(r===null);return structuredClone(input);
}
export function publicMedia(candidate,decision,revision,now=Date.now()){
 if(!candidate||!decision||revision?.state!=='APPROVED'||decision.state!=='APPROVED'||Date.parse(decision.review?.validThrough)<=now)return null;
 const {candidate:c,provenance:p}=validateMediaInput(candidate.payload,now);mediaNeed(c.category==='INSTITUTION_EXTERIOR'&&['VERIFIED','HIGH'].includes(c.identityConfidence)&&!['UNKNOWN','NOT_PERMITTED'].includes(c.licenseState));if(p.dateConflict)mediaNeed(decision.review.historicalPhotoAcknowledged===true);
 return {mediaId:candidate.id,revision:Number(revision.version),programId:c.programId,registryReleaseId:c.registryReleaseId,url:c.assetRef,sourceUrl:c.sourceUrl,publisher:c.publisher,category:c.category,caption:p.dateConflict?`${c.caption} Historical photograph; source dates differ.`.trim():c.caption,alt:c.alt,verifiedAt:c.verifiedAt,identityConfidence:c.identityConfidence,licenseState:c.licenseState,approvalState:'APPROVED',assetSha256:p.assetSha256,assetBytes:p.assetBytes,licenseUrl:p.licenseUrl,attribution:p.attribution,changes:p.changes,institution:p.institution,validThrough:decision.review.validThrough,dateConflict:p.dateConflict,photoDates:{page:p.pageReportedDate,exif:p.exifReportedDate}};
}
export async function readMediaBody(request){
 const raw=request.rawHeaders||[];const seen=new Set();for(let i=0;i<raw.length;i+=2){const k=raw[i].toLowerCase();mediaNeed(!seen.has(k));seen.add(k);}
 mediaNeed(/^application\/json(?:;\s*charset=utf-8)?$/i.test(request.headers?.['content-type']||''));mediaNeed(!request.headers?.['content-encoding']);let bytes=0;const chunks=[];const timer=setTimeout(()=>request.destroy(),5000);try{for await(const chunk of request){bytes+=chunk.length;mediaNeed(bytes<=40000);chunks.push(chunk);}return parseMediaJson(Buffer.concat(chunks));}finally{clearTimeout(timer);}
}
export async function mediaRoute(request,url,{session,store,readBody}={}){
 const prefix='/api/rise/v1/operator/program-media',match=url.pathname.match(/^\/api\/rise\/v1\/operator\/program-media\/candidates\/([a-f0-9-]{36})(\/decisions)?$/);if(url.pathname!==prefix+'/candidates'&&!match)return null;
 try{mediaNeed(store?.enabled===true,'MEDIA_UNAVAILABLE',503);const grant=mediaAuthority(session);mediaNeed(!url.search,'MEDIA_INVALID');if(request.method==='POST'&&url.pathname===prefix+'/candidates'){const b=await readMediaBody(request);mediaExact(b,['requestId','input']);return {status:200,body:await store.record({grant,...b})};}if(match&&request.method==='GET'&&!match[2])return {status:200,body:await store.audit({grant,id:match[1]})};if(match&&request.method==='POST'&&match[2])return {status:200,body:await store.decide({grant,id:match[1],input:await readMediaBody(request)})};return {status:405,body:{error:'MEDIA_METHOD_NOT_ALLOWED'}};}catch(e){return {status:e.status||503,body:{error:e.code||'MEDIA_UNAVAILABLE'}};}
}
// Same bounded duplicate-key rejecting parser already accepted for the MRX owner boundary.
export const parseMediaJson=bytes=>{try{return mrxParse(bytes,40000);}catch{mediaNeed(false,'MEDIA_INVALID',422);}};
