import test from 'node:test';
import assert from 'node:assert/strict';
import {runInterviewiqResearchWorkerOnce} from '../tools/start-interviewiq-research-worker.mjs';
function fixture(mode='SEND') {const calls=[];const claim={mode,job:{providerKey:'OPENAI_TERRA',modelKey:'gpt-5.6-terra'},receipt:{status:'COMPLETED'}};const store={async claim({proof}){calls.push('claim:'+proof);return claim;},async heartbeat(){calls.push('heartbeat');},async captureRaw(_h,r){calls.push('raw:'+r.sha256);},async complete(_h,{proof}){calls.push('complete:'+proof);return {status:'PARTIAL'};},async quarantine(_h,{code}){calls.push('quarantine:'+code);}};const provider={providerKey:'OPENAI_TERRA',modelKey:'gpt-5.6-terra',async execute({recovery}){calls.push('provider');await recovery.checkpointResponse({sha256:'synthetic'});}};return {calls,store,provider,getProof:async phase=>phase,heartbeatMs:10};}
test('one fresh intent permits exactly one provider call and checkpoints before completion',async()=>{const f=fixture();assert.deepEqual(await runInterviewiqResearchWorkerOnce(f),{status:'PARTIAL'});assert.deepEqual(f.calls,['claim:start','heartbeat','provider','raw:synthetic','complete:publish']);});
for(const mode of ['BUSY','RECONCILIATION_REQUIRED','COMPLETED'])test(mode+' never dispatches or adds followup',async()=>{const f=fixture(mode);await runInterviewiqResearchWorkerOnce(f);assert.deepEqual(f.calls,['claim:start']);});
test('raw recovery uses no provider or API credential',async()=>{const f=fixture('RECOVER');delete f.provider;assert.deepEqual(await runInterviewiqResearchWorkerOnce(f),{status:'PARTIAL'});assert.deepEqual(f.calls,['claim:start','heartbeat','complete:publish']);});
test('ambiguous intent commit makes zero provider calls',async()=>{const f=fixture();f.store.claim=async()=>{throw Error('commit acknowledgement lost');};await assert.rejects(runInterviewiqResearchWorkerOnce(f));assert.deepEqual(f.calls,[]);});
test('provider mismatch does not send',async()=>{const f=fixture();f.provider.modelKey='other';await assert.rejects(runInterviewiqResearchWorkerOnce(f),{code:'IIQ_PROVIDER_MISMATCH'});assert.ok(!f.calls.includes('provider'));});
test('provider error is quarantined without private text, refund or redispatch',async()=>{const f=fixture();f.provider.execute=async()=>{f.calls.push('provider');throw Object.assign(Error('PRIVATE_RAW_SECRET'),{code:'OPENAI_PROVIDER_HTTP_ERROR',httpStatus:429});};await assert.rejects(runInterviewiqResearchWorkerOnce(f),e=>e.code==='OPENAI_PROVIDER_HTTP_ERROR'&&e.httpStatus===429&&!e.message.includes('PRIVATE'));assert.equal(f.calls.filter(x=>x==='provider').length,1);assert.ok(f.calls.includes('quarantine:OPENAI_PROVIDER_HTTP_ERROR'));assert.ok(!f.calls.some(x=>x.startsWith('complete')));});
test('heartbeat failure aborts in-flight provider and prohibits completion',async()=>{const f=fixture();let count=0;f.store.heartbeat=async()=>{if(++count>1)throw Object.assign(Error('lost'),{code:'IIQ_EXECUTION_LEASE_LOST'});};let aborted=false;f.provider.execute=async({recovery})=>new Promise((_,reject)=>{recovery.signal.addEventListener('abort',()=>{aborted=true;reject(Object.assign(Error('aborted'),{code:'IIQ_EXECUTION_LEASE_LOST'}));});});await assert.rejects(runInterviewiqResearchWorkerOnce(f),{code:'IIQ_EXECUTION_LEASE_LOST'});assert.equal(aborted,true);assert.ok(!f.calls.some(x=>x.startsWith('complete')));});
test('lost checkpoint acknowledgement never produces a second provider call',async()=>{const f=fixture();f.store.captureRaw=async()=>{throw Error('ack lost');};await assert.rejects(runInterviewiqResearchWorkerOnce(f));assert.equal(f.calls.filter(x=>x==='provider').length,1);assert.ok(!f.calls.some(x=>x.startsWith('complete')));});
test('revoked publish proof does not invoke publication',async()=>{const f=fixture();f.getProof=async phase=>{if(phase==='publish')throw Error('revoked');return phase;};await assert.rejects(runInterviewiqResearchWorkerOnce(f));assert.ok(!f.calls.some(x=>x.startsWith('complete')));});

for(const [name,code] of [['number',123],['object',{private:'PRIVATE_CANARY',toString(){return 'SYNTHETIC_ERROR';}}]])test(name+' provider code cannot escape as private error data',async()=>{const f=fixture();let quarantined;f.store.quarantine=async(_h,value)=>{quarantined=value;};f.provider.execute=async()=>{throw Object.assign(Error('PRIVATE_CANARY'),{code});};await assert.rejects(runInterviewiqResearchWorkerOnce(f),e=>e.code==='IIQ_EXECUTION_FAILED'&&!JSON.stringify(e).includes('PRIVATE_CANARY'));assert.deepEqual(quarantined,{code:'IIQ_EXECUTION_FAILED'});});
