import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {randomUUID,createHash} from 'node:crypto';
import pg from 'pg';
import {qualifyLocalHarness} from '../tools/migrate-interviewiq-owner.mjs';
import {ingestProviderRecordTransaction,applyCorpusTransaction,completeJobTransaction,createRiseCanonicalEvidenceStore,createRiseEvidenceReviewStore,createRiseResearchStore} from '../adapters/postgres-runtime.mjs';
import {createCanonicalEvidenceClaim} from '../src/evidence.mjs';
import {reviewResearchCorpus} from '../src/research-review.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex');
const subject='d'.repeat(64),acgme='1854831078',worker='synthetic-a13',time='2026-10-04T12:00:00.000Z';
const files=['005_rights_safe_runtime.sql','007_canonical_evidence_bridge.sql','008_on_demand_research.sql','009_research_provider_provenance.sql','010_full_evidence_promotion.sql','011_provider_benchmark_on_demand_canary.sql','012_deep_research_dossier_v2.sql','013_application_intelligence_preferences.sql','014_six_specialty_research_scope.sql'];
function ingest(run){const url='https://example.edu/residency/visa';const claim=createCanonicalEvidenceClaim({subjectId:'synthetic-identity',field:'research.visa',value:{j1:true},provider:'OPENAI',providerRunId:run,sourceType:'openai_responses_web_search',sourceUrl:url,sourceLocator:'synthetic:'+run,retrievedAt:time,publicationState:'REVIEW_REQUIRED',reviewState:'PENDING'});return {provider:'OPENAI',providerRunId:run,campaignId:'IIQ-1204-SYNTHETIC',acgmeId:acgme,idempotencyKey:sha(run),sourceFile:'synthetic:'+run,sourceFileSha256:sha('raw:'+run),stagedAt:time,newSpendUsd:0.02,providerKey:'OPENAI_TERRA',modelKey:'gpt-5.6-terra',claims:[{...claim,provider:'OPENAI',sourceUrls:[url],directSourceUrls:[url]}]};}
test('shared PostgreSQL publication and accounting commit together and preserve generic wrappers',async t=>{
 for(const name of ['DATABASE_URL','RISE_DATABASE_URL','PGHOST','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGOPTIONS','RAILWAY_ENVIRONMENT_ID'])assert.ok(!process.env[name],`Refuse ${name}`);
 const bin='/opt/homebrew/opt/postgresql@18/bin/',directory=fs.mkdtempSync('/tmp/iiq-rise-test-');fs.chmodSync(directory,0o700);
 const socket=directory+'/socket';fs.mkdirSync(socket,{mode:0o700});const marker='iiq-test-'+randomUUID();
 const env={PATH:process.env.PATH,LANG:'C',LC_ALL:'C',PGHOST:socket,PGPORT:'55440',PGUSER:'postgres',PGDATABASE:'iiq_owner_synthetic'};
 const run=(cmd,args)=>execFileSync(bin+cmd,args,{env,stdio:['ignore','pipe','pipe'],timeout:30000});
 let started=false,admin,pool;
 try {
  run('initdb',['-D',directory+'/data','-A','trust','--no-locale','--encoding=UTF8','-U','postgres']);
  run('pg_ctl',['-D',directory+'/data','-l',directory+'/server.log','-o',`-k ${socket} -h '' -p 55440 -c cluster_name=${marker}`,'-w','start']);started=true;run('createdb',['iiq_owner_synthetic']);
  const harness=directory+'/harness.json';fs.writeFileSync(harness,JSON.stringify({directory,host:socket,port:55440,database:'iiq_owner_synthetic',user:'postgres',marker,pid:Number(fs.readFileSync(directory+'/data/postmaster.pid','utf8').split('\n')[0]),createdAt:Date.now()}),{mode:0o600,flag:'wx'});
  const {connection}=qualifyLocalHarness(harness);admin=new pg.Client(connection);await admin.connect();
  assert.equal((await admin.query('SELECT inet_server_addr() AS address')).rows[0].address,null);
  for(const file of files)await admin.query(fs.readFileSync(new URL('../sql/'+file,import.meta.url),'utf8'));
  await admin.query('CREATE ROLE rise_app_login LOGIN; GRANT rise_app_runtime TO rise_app_login');
  await admin.query(`INSERT INTO rise_runtime.canonical_evidence_sources(source_id,provider,provider_run_id,source_type,retrieved_at,rights_state,exposure_state) VALUES('synthetic-source','MISSIONMED_REVIEW','synthetic-source','test',now(),'APPROVED','PRIVATE_BETA')`);
  await admin.query(`INSERT INTO rise_runtime.canonical_program_identities(program_identity_id,acgme_id,program_specialty_id,program_name,institution,state,specialty,reconciliation_status,exposure_state,source_id,content_sha256) VALUES('synthetic-identity',$1,'synthetic-program','Synthetic','Synthetic','TX','Child Neurology','EXACT_ACGME_MATCH','PRIVATE_BETA','synthetic-source',$2)`,[acgme,sha('identity')]);
  await admin.query(`INSERT INTO rise_runtime.research_quota_ledgers(subject_key,window_start,window_end,quota_limit) VALUES($1,current_date,current_date+7,100)`,[subject]);
  await admin.query(`UPDATE rise_runtime.research_router_settings SET budget_cap_usd=12,actual_spend_usd=0,reserved_spend_usd=0`);
  await admin.query(`UPDATE rise_runtime.research_provider_routes SET budget_cap_usd=6,actual_spend_usd=0,reserved_spend_usd=0 WHERE provider_key='OPENAI_TERRA'`);
  pool=new pg.Pool({...connection,user:'rise_app_login',max:4});
  const begin=async()=>{const c=await pool.connect();await c.query('BEGIN');await c.query("SELECT set_config('rise.subject_key',$1,true),set_config('rise.is_admin','true',true)",[subject]);return c;};
  async function seed(){const id=randomUUID(),leaseToken=randomUUID();await admin.query(`UPDATE rise_runtime.research_quota_ledgers SET reserved_count=reserved_count+1 WHERE subject_key=$1`,[subject]);await admin.query(`UPDATE rise_runtime.research_router_settings SET reserved_spend_usd=reserved_spend_usd+0.3`);await admin.query(`UPDATE rise_runtime.research_provider_routes SET reserved_spend_usd=reserved_spend_usd+0.3 WHERE provider_key='OPENAI_TERRA'`);await admin.query(`INSERT INTO rise_runtime.research_jobs(job_id,dedupe_key,release_id,program_specialty_id,acgme_id,specialty,state_code,requester_subject_key,request_source,status,provider_key,model_key,router_revision,quota_window_start,estimated_cost_usd,attempt_count,worker_id,lease_token,lease_expires_at) VALUES($1,$2,'synthetic-release','synthetic-program',$3,'Child Neurology','TX',$4,'STUDENT','RUNNING','OPENAI_TERRA','gpt-5.6-terra',1,current_date,0.3,1,$5,$6,now()+interval '3 minutes')`,[id,sha(id),acgme,subject,worker,leaseToken]);return {jobId:id,leaseToken,workerId:worker,status:'COMPLETED',actualCostUsd:0.02,providerResponseId:'resp_'+id.replaceAll('-',''),usage:{input_tokens:100,output_tokens:30}};}
  async function snapshot(){const names=['provider_ingest_runs','canonical_evidence_sources','canonical_evidence_claims','evidence_claim_review_events','canonical_claim_promotion_lineage','research_jobs','research_quota_ledgers','research_spend_ledger','research_router_settings','research_provider_routes'];const result={};for(const name of names)result[name]=(await admin.query(`SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]') AS rows FROM rise_runtime.${name} t`)).rows[0].rows;return result;}
  async function perform(c,args,stop=0){const data=ingest(args.jobId),receipt=await ingestProviderRecordTransaction(c,{ingest:data});if(stop===1)throw Error('SYNTHETIC_AFTER_INGEST');const review=reviewResearchCorpus([data],{resolvedAcgmeIds:new Set([acgme]),allowedCanaryAcgmeIds:new Set([acgme])});assert.equal(review.promotions.length,1);const reviewed=await applyCorpusTransaction(c,{review,actorSubject:'IIQ-1204',reviewedAt:time,ticket:'IIQ-1204',promotionSourceId:'synthetic-promotion'});if(stop===2)throw Error('SYNTHETIC_AFTER_REVIEW');const completed=await completeJobTransaction(c,{...args,canonicalIngestRunId:receipt.ingestRunId,resultSummary:{canonicalPromotion:'PROMOTED'}});if(stop===3)throw Error('SYNTHETIC_AFTER_ACCOUNTING');return {receipt,reviewed,completed};}
  for(const stage of [1,2,3])await t.test('rollback after stage '+stage+' preserves all claims, lineage, job, quota and spend',async()=>{const args=await seed(),before=await snapshot(),c=await begin();try{await assert.rejects(perform(c,args,stage),/SYNTHETIC_AFTER_/);await c.query('ROLLBACK');}finally{c.release();}assert.deepEqual(await snapshot(),before);});
  await t.test('single transaction is invisible externally until all publication/accounting commit',async()=>{const args=await seed(),before=await snapshot(),c=await begin();try{const result=await perform(c,args);assert.equal(result.completed.status,'COMPLETED');assert.deepEqual(await snapshot(),before);await c.query('COMMIT');}finally{c.release();}const after=await snapshot();assert.equal(after.research_spend_ledger.length,before.research_spend_ledger.length+1);assert.equal(after.research_quota_ledgers[0].consumed_count,before.research_quota_ledgers[0].consumed_count+1);const current=(await admin.query('SELECT count(*)::int AS n FROM rise_runtime.canonical_current_facts')).rows[0].n;assert.ok(current>0);});
  await t.test('two concurrent completers account once and second fails lease guard',async()=>{const args=await seed(),c1=await begin(),c2=await begin();try{await completeJobTransaction(c1,args);const pending=completeJobTransaction(c2,args).then(()=>({ok:true}),error=>({error}));await c1.query('COMMIT');const result=await pending;assert.equal(result.error?.code,'RESEARCH_JOB_LEASE_LOST');await c2.query('ROLLBACK');assert.equal((await admin.query('SELECT count(*)::int AS n FROM rise_runtime.research_spend_ledger WHERE job_id=$1',[args.jobId])).rows[0].n,1);}finally{c1.release();c2.release();}});
  await t.test('stale or wrong completion lease makes no accounting mutation',async()=>{const args=await seed(),before=await snapshot(),c=await begin();try{await assert.rejects(completeJobTransaction(c,{...args,leaseToken:randomUUID()}),{code:'RESEARCH_JOB_LEASE_LOST'});await c.query('ROLLBACK');}finally{c.release();}assert.deepEqual(await snapshot(),before);});
  await t.test('generic wrappers keep independent transactions and compatible results',async()=>{const args=await seed(),data=ingest(args.jobId),canonical=await createRiseCanonicalEvidenceStore({pool}),reviews=await createRiseEvidenceReviewStore({pool}),jobs=await createRiseResearchStore({pool,subjectHmacKey:'synthetic-only-subject-hmac-key-long-enough'});const ingested=await canonical.ingestProviderRecord({ingest:data});const review=reviewResearchCorpus([data],{resolvedAcgmeIds:new Set([acgme]),allowedCanaryAcgmeIds:new Set([acgme])});await reviews.applyCorpus({review,reviewedAt:time,ticket:'IIQ-1204-GENERIC',promotionSourceId:'synthetic-generic-promotion'});assert.equal((await jobs.completeJob({...args,canonicalIngestRunId:ingested.ingestRunId})).status,'COMPLETED');});
 } finally {if(pool)await pool.end();if(admin)await admin.end();if(started)run('pg_ctl',['-D',directory+'/data','-m','fast','-w','stop']);t.diagnostic(JSON.stringify({localCluster:directory,stopped:true}));}
});
