import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {randomUUID,createHash,createHmac} from 'node:crypto';
import pg from 'pg';
import {qualifyLocalHarness} from '../tools/migrate-interviewiq-owner.mjs';
import {createCommittedResearchProof} from '../adapters/interviewiq-job-auth.mjs';
import {createInterviewiqResearchAcceptance} from '../adapters/interviewiq-research-store.mjs';
import {createInterviewiqResearchWorkerStore,executionCatalog,EXECUTION_SCHEMA_SHA} from '../adapters/interviewiq-research-worker-store.mjs';
import {DEEP_RESEARCH_DOMAIN_KEYS} from '../src/research-router.mjs';
import {subjectKey} from '../adapters/postgres-runtime.mjs';
import {INTERVIEWIQ_IDENTITY_RELATIONSHIP as REL} from '../adapters/interviewiq-program-identity.mjs';
import {createInterviewiqCoverageReader} from '../adapters/interviewiq-coverage.mjs';
import {createInterviewiqResearchResultsReader} from '../adapters/interviewiq-research-results.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex');
const files=['005_rights_safe_runtime.sql','007_canonical_evidence_bridge.sql','008_on_demand_research.sql','009_research_provider_provenance.sql','010_full_evidence_promotion.sql','011_provider_benchmark_on_demand_canary.sql','012_deep_research_dossier_v2.sql','013_application_intelligence_preferences.sql','014_six_specialty_research_scope.sql'];
const SECRET='synthetic-proof-never-production-1234567890',HMAC='synthetic-subject-never-production-1234567890',INDEX='a'.repeat(64),RIGHTS='b'.repeat(64),RELEASE='synthetic-worker-release';
const subject=subjectKey('wp:90001',HMAC);
const retainedIdentity={"program_identity_id":"rise_prg_e652e785-e2cd-5654-96dd-226055a61008","program_specialty_id":"rise_ps_60a68ad0-4593-58ce-8b4c-2fb3e34f9ae8","acgme_id":"1401611122","reconciliation_status":"EXACT_ACGME_MATCH","exposure_state":"PRIVATE_BETA","source_id":"rise_src_soap_2026","content_sha256":"3eab6658ca36a65d12be6e8d652c83dd52a75d166149861b25fb6c17d4c59399","program_name":"Ascension St Joseph-IL","institution":"Ascension St Joseph-IL","city":null,"state":"Illinois","specialty":"Internal Medicine"},retainedSource={"source_id":"rise_src_soap_2026","provider":"NRMP_SOAP_CLOSURE","provider_run_id":"P1_RISE_SOAP_2026_CLOSURE_006","source_type":"historical_match_cycle_result","source_file_sha256":"af7215525bb3b974bc5092f18bd6b42f19c3c397d259ea60ab32dd89418b68ac","rights_state":"APPROVED","exposure_state":"PRIVATE_BETA"},currentProgram={"id":"rise_prg_134107c0-e949-57b8-a54f-7d9a19b97fcb","programSpecialtyId":"rise_ps_d0382fec-f389-5cf8-8b25-ac0e256f710e","designation":"Internal Medicine","entryFormat":"unknown","display":{"state":"IL","city":"Chicago","programName":"Ascension Illinois/Saint Joseph (Chicago) Program"},"identifiers":[{"namespace":"ACGME_PROGRAM","value":"1401611122"},{"namespace":"FREIDA_PROGRAM","value":"1401611122"}]};
const registry=()=>({registryReleaseId:REL.registryReleaseId,activationStatus:'active',activationReceipt:{verified:true,apiIndexSha256:REL.registrySha256},releaseGate:{sourceRightsApproved:true},programs:[structuredClone(currentProgram)]});
const context=()=>({registryIndex:registry(),registrySha256:REL.registrySha256,programId:REL.programId,registryReleaseId:REL.registryReleaseId});

async function proof(config,phase,wpUserId=90001) {return createCommittedResearchProof({enabled:true,requestSecret:HMAC,proofSecret:SECRET},{fetchImpl:async(_url,o)=>{const r=JSON.parse(o.body),payload=JSON.stringify({...r,allowed:true,reason:'current_committed_demand',wpUserId,role:'student',tier:'360',exp:r.iat+30});return new Response(JSON.stringify({payload,signature:createHmac('sha256',SECRET).update(`iiq-job-proof-v1\nresponse\n${payload}`).digest('hex')}),{headers:{'Content-Type':'application/json'}});}})({binding:config.binding,bodyHash:config.bodyHash,phase});}
function raw(config){const url='https://example.edu/visa',p=config.registryIndex.programs[0],acgme=p.identifiers[0].value;const payload={id:'resp_'+config.jobId.replaceAll('-',''),status:'completed',model:'gpt-5.6-terra',usage:{input_tokens:100,output_tokens:30},output:[{type:'web_search_call',action:{sources:[{url}]}},{type:'message',content:[{type:'output_text',text:JSON.stringify({program_identity:{acgme_id:acgme,program_name:'Synthetic',institution:'Synthetic',specialty:p.designation,state:p.display.state},findings:[{field:'visa',status:'FOUND',summary:'Published J1',value_json:'{"j1":true}',source_urls:[url]}],completion_matrix:Object.fromEntries(DEEP_RESEARCH_DOMAIN_KEYS.map(d=>[d,d==='visa'?{state:'VERIFIED',summary:'Published',source_urls:[url]}:{state:'RESEARCHED_NOT_FOUND',summary:'Not found after synthetic search',source_urls:[]}])),research_summary:'Synthetic'})}]}]};const bytes=Buffer.from(' \n'+JSON.stringify(payload)+'\n');return {rawBodyBase64:bytes.toString('base64'),sha256:sha(bytes),httpStatus:200,receivedAt:'2026-10-04T12:00:00.000Z',providerKey:'OPENAI_TERRA',modelKey:'gpt-5.6-terra'};}
test('durable one-job execution preserves raw output, fencing, privacy and accounting',async t=>{
 for(const name of ['DATABASE_URL','RISE_DATABASE_URL','PGHOST','PGHOSTADDR','PGSERVICE','PGSERVICEFILE','PGOPTIONS','RAILWAY_ENVIRONMENT_ID'])assert.ok(!process.env[name],`Refuse ${name}`);
 const bin='/opt/homebrew/opt/postgresql@18/bin/',directory=fs.mkdtempSync('/tmp/iiq-rise-test-');fs.chmodSync(directory,0o700);
 const socket=directory+'/socket';fs.mkdirSync(socket,{mode:0o700});const marker='iiq-test-'+randomUUID();
 const env={PATH:process.env.PATH,LANG:'C',LC_ALL:'C',PGHOST:socket,PGPORT:'55440',PGUSER:'postgres',PGDATABASE:'iiq_owner_synthetic'};
 const run=(cmd,args)=>execFileSync(bin+cmd,args,{env,stdio:['ignore','pipe','pipe'],timeout:30000});
 let started=false,admin,pool;
 try {
  run('initdb',['-D',directory+'/data','-A','trust','--no-locale','--encoding=UTF8','-U','postgres']);
  run('pg_ctl',['-D',directory+'/data','-l',directory+'/server.log','-o',`-k ${socket} -h '' -p 55440 -c cluster_name=${marker}`,'-w','start']);started=true;run('createdb',['iiq_owner_synthetic']);
  const harness=directory+'/harness.json';fs.writeFileSync(harness,JSON.stringify({directory,host:socket,port:55440,database:'iiq_owner_synthetic',user:'postgres',marker,pid:Number(fs.readFileSync(directory+'/data/postmaster.pid','utf8').split('\n')[0]),createdAt:Date.now()}),{mode:0o600,flag:'wx'});
  const {connection}=qualifyLocalHarness(harness);admin=new pg.Client(connection);await admin.connect();
  assert.equal((await admin.query('SELECT inet_server_addr() AS address')).rows[0].address,null);
  for(const file of files)await admin.query(fs.readFileSync(new URL('../sql/'+file,import.meta.url),'utf8'));
  await admin.query('CREATE ROLE rise_app_login LOGIN; GRANT rise_app_runtime TO rise_app_login');

  for(const file of ['20261004085448_iiq_1204_research_job_links.sql','20261004094448_iiq_1204_research_origin.sql','20261004123000_iiq_1204_research_execution.sql'])await admin.query(fs.readFileSync(new URL('../sql/'+file,import.meta.url),'utf8'));
  const catalogHash=sha(JSON.stringify(await executionCatalog(admin)));t.diagnostic('EXECUTION_CATALOG_SHA='+catalogHash);assert.equal(catalogHash,EXECUTION_SCHEMA_SHA);
  await admin.query(`INSERT INTO rise_runtime.registry_releases(release_id,projection,api_index_sha256,index_manifest_sha256,program_count,rights_blocked_field_count,active) VALUES($1,'STUDENT_RIGHTS_SAFE_RISE',$2,$2,20,0,true)`,[RELEASE,INDEX]);
  await admin.query(`INSERT INTO rise_runtime.source_authorizations VALUES($1,'TEST',$2,$2,'government_public_domain_factual_projection','SYNTHETIC',current_date+1,NULL)`,[RELEASE,RIGHTS]);
  await admin.query(`UPDATE rise_runtime.research_router_settings SET global_enabled=true,student_enabled=true,emergency_kill_switch=false,default_quota=100,primary_provider='OPENAI_TERRA',budget_cap_usd=12,actual_spend_usd=0,reserved_spend_usd=0,subject_allowlist_hashes=$1`,[[subject]]);
  await admin.query(`UPDATE rise_runtime.research_provider_routes SET enabled=true,network_allowed=true,spend_allowed=true,state='PRODUCTION_APPROVED',budget_cap_usd=6,actual_spend_usd=0,reserved_spend_usd=0,configuration='{"reservationUsd":0.3}' WHERE provider_key='OPENAI_TERRA'`);
  await admin.query(`INSERT INTO rise_runtime.canonical_evidence_sources(source_id,provider,provider_run_id,source_type,retrieved_at,rights_state,exposure_state) VALUES('synthetic-source','MISSIONMED_REVIEW','synthetic-source','test',now(),'APPROVED','PRIVATE_BETA')`);
  pool=new pg.Pool({...connection,user:'rise_app_login',max:6});let serial=0;
  async function seed(){const n=++serial,acgme=String(1854831000+n),p={programSpecialtyId:'synthetic-'+n,designation:'Child Neurology',display:{state:'TX',programName:'Synthetic'},identifiers:[{namespace:'ACGME_PROGRAM',value:acgme}]};await admin.query('UPDATE rise_runtime.research_router_settings SET canary_acgme_ids=$1',[[acgme]]);await admin.query(`INSERT INTO rise_runtime.canonical_program_identities(program_identity_id,acgme_id,program_specialty_id,program_name,institution,state,specialty,reconciliation_status,exposure_state,source_id,content_sha256) VALUES($1,$2,$1,'Synthetic','Synthetic','TX','Child Neurology','EXACT_ACGME_MATCH','PRIVATE_BETA','synthetic-source',$3)`,[p.programSpecialtyId,acgme,sha(acgme)]);const binding={requestId:randomUUID(),ownerId:randomUUID(),demandId:randomUUID(),interviewId:randomUUID(),programId:p.programSpecialtyId,registryReleaseId:RELEASE};const config={enabled:true,binding,bodyHash:sha(JSON.stringify({...binding,kind:'program-gaps'})),registryIndex:{registryReleaseId:RELEASE,programs:[p]},registrySha256:INDEX,authorizationSha256s:[RIGHTS],subjectHmacKey:HMAC,expectedSubjectKey:subject,providerKey:'OPENAI_TERRA',modelKey:'gpt-5.6-terra'};const accepted=await createInterviewiqResearchAcceptance(config,{pool}).acceptJob({ownerId:binding.ownerId,requestId:binding.requestId,binding,bodyHash:config.bodyHash,proof:await proof(config,'reserve')});config.jobId=accepted.jobId;return {config,store:createInterviewiqResearchWorkerStore(config,{pool})};}
  const claim=async f=>f.store.claim({proof:await proof(f.config,'start'),workerId:'synthetic-worker'});
  const expire=async f=>{await admin.query("UPDATE rise_runtime.research_jobs SET lease_expires_at=now()-interval '1 second' WHERE job_id=$1",[f.config.jobId]);await admin.query("UPDATE rise_runtime.iiq_research_executions SET lease_until=now()-interval '1 second' WHERE job_id=$1",[f.config.jobId]);};
  let first,firstClaim;
  await t.test('two competing claims yield one SEND and one BUSY with one durable dispatch',async()=>{first=await seed();const outcomes=await Promise.all([claim(first),claim(first)]);assert.deepEqual(outcomes.map(x=>x.mode).sort(),['BUSY','SEND']);firstClaim=outcomes.find(x=>x.mode==='SEND');assert.equal((await admin.query('SELECT count(*)::int AS n FROM rise_runtime.iiq_research_executions')).rows[0].n,1);});
  await t.test('original bytes capture is immutable and identical replay is idempotent',async()=>{const r=raw(first.config);await first.store.captureRaw(firstClaim,r);await first.store.captureRaw(firstClaim,r);await assert.rejects(first.store.captureRaw(firstClaim,{...r,receivedAt:'2026-10-04T12:00:01.000Z'}),{code:'IIQ_EXECUTION_RAW_CONFLICT'});assert.equal((await admin.query('SELECT raw_sha256 FROM rise_runtime.iiq_research_executions')).rows[0].raw_sha256,r.sha256);});
  await t.test('raw cannot steal a still-active lease',async()=>{assert.equal((await claim(first)).mode,'BUSY');});
  await t.test('generic admin context and different owner cannot read raw',async()=>{const q=await pool.connect();try{await q.query('BEGIN');await q.query("SELECT set_config('rise.is_admin','true',true),set_config('rise.subject_key',$1,true),set_config('rise.iiq_owner_id',$2,true),set_config('rise.iiq_job_id',$3,true)",[subject,randomUUID(),first.config.jobId]);assert.equal((await q.query('SELECT raw_body FROM rise_runtime.iiq_research_executions')).rowCount,0);await q.query('ROLLBACK');}finally{q.release();}});
  await t.test('expired raw recovers with new fence, no SEND and stale holder cannot publish',async()=>{await expire(first);const recovered=await claim(first);assert.equal(recovered.mode,'RECOVER');assert.equal(recovered.fence,firstClaim.fence+1);await assert.rejects(first.store.heartbeat(firstClaim),{code:'IIQ_EXECUTION_LEASE_LOST'});await assert.rejects(first.store.complete(firstClaim,{proof:await proof(first.config,'publish')}),{code:'IIQ_EXECUTION_LEASE_LOST'});firstClaim=recovered;});
  await t.test('missing falsy and fabricated publish proofs cannot publish or account',async()=>{for(const proof of [undefined,null,false,0,'',{}, {assertFresh(){}}])await assert.rejects(first.store.complete(firstClaim,{proof}));assert.equal((await admin.query("SELECT count(*)::int AS n FROM rise_runtime.research_spend_ledger WHERE job_id=$1 AND event_type='RECONCILE'",[first.config.jobId])).rows[0].n,0);});
  await t.test('publication and replay account exactly once with retained raw/provenance',async()=>{const a=await first.store.complete(firstClaim,{proof:await proof(first.config,'publish')}),b=await first.store.complete(firstClaim,{proof:await proof(first.config,'publish')});assert.deepEqual(a,b);assert.equal(a.status,'PARTIAL');assert.equal(a.rawSha256,raw(first.config).sha256);assert.equal((await admin.query("SELECT count(*)::int AS n FROM rise_runtime.research_spend_ledger WHERE job_id=$1 AND event_type='RECONCILE'",[first.config.jobId])).rows[0].n,1);assert.equal((await claim(first)).mode,'COMPLETED');});
  await t.test('completed original, raw and final receipt cannot be rewritten',async()=>{for(const sql of ["UPDATE rise_runtime.iiq_research_executions SET request_sha256=repeat('f',64) WHERE job_id=$1","UPDATE rise_runtime.iiq_research_executions SET completion_receipt='{}' WHERE job_id=$1","UPDATE rise_runtime.iiq_research_executions SET raw_body='x' WHERE job_id=$1"])await assert.rejects(admin.query(sql,[first.config.jobId]));});
  await t.test('crash after intent and before response quarantines without refund or redispatch',async()=>{const f=await seed();await claim(f);await expire(f);const before=(await admin.query('SELECT reserved_spend_usd FROM rise_runtime.research_router_settings')).rows;assert.equal((await claim(f)).mode,'RECONCILIATION_REQUIRED');assert.equal((await claim(f)).mode,'RECONCILIATION_REQUIRED');assert.deepEqual((await admin.query('SELECT reserved_spend_usd FROM rise_runtime.research_router_settings')).rows,before);assert.equal((await admin.query('SELECT state,error_code FROM rise_runtime.iiq_research_executions WHERE job_id=$1',[f.config.jobId])).rows[0].error_code,'RECONCILIATION_REQUIRED');});
  await t.test('late exact raw custody preserves bytes but does not restore old publication authority',async()=>{const f=await seed(),h=await claim(f);await expire(f);await f.store.captureRaw(h,raw(f.config));await assert.rejects(f.store.complete(h,{proof:await proof(f.config,'publish')}),{code:'IIQ_EXECUTION_LEASE_LOST'});assert.equal((await claim(f)).mode,'RECOVER');await expire(f);});
  await t.test('wrong student and reserve-phase proof cannot claim work',async()=>{const f=await seed();await assert.rejects(f.store.claim({proof:await proof(f.config,'start',90002),workerId:'synthetic'}));await assert.rejects(f.store.claim({proof:await proof(f.config,'reserve'),workerId:'synthetic'}));assert.equal((await admin.query('SELECT count(*)::int AS n FROM rise_runtime.iiq_research_executions WHERE job_id=$1',[f.config.jobId])).rows[0].n,0);});
  await t.test('missing falsy and fabricated start proofs cannot persist intent',async()=>{const f=await seed();for(const proof of [undefined,null,false,0,'',{}, {assertFresh(){}}])await assert.rejects(f.store.claim({proof,workerId:'synthetic'}));assert.equal((await admin.query('SELECT count(*)::int AS n FROM rise_runtime.iiq_research_executions WHERE job_id=$1',[f.config.jobId])).rows[0].n,0);});
  await t.test('rights authority body and ACL drift fail closed before dispatch',async()=>{const f=await seed(),definition=(await admin.query("SELECT pg_get_functiondef('rise_runtime.iiq_lock_research_rights(text,text,text[])'::regprocedure) AS definition")).rows[0].definition;try{await admin.query("CREATE OR REPLACE FUNCTION rise_runtime.iiq_lock_research_rights(wanted_release text,wanted_index text,wanted_rights text[]) RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS 'SELECT true'");await assert.rejects(claim(f),{code:'IIQ_EXECUTION_RIGHTS_SCHEMA_DRIFT'});}finally{await admin.query(definition);}try{await admin.query('GRANT EXECUTE ON FUNCTION rise_runtime.iiq_lock_research_rights(text,text,text[]) TO PUBLIC');await assert.rejects(claim(f),{code:'IIQ_EXECUTION_RIGHTS_SCHEMA_DRIFT'});}finally{await admin.query('REVOKE EXECUTE ON FUNCTION rise_runtime.iiq_lock_research_rights(text,text,text[]) FROM PUBLIC');}assert.equal((await admin.query('SELECT count(*)::int AS n FROM rise_runtime.iiq_research_executions WHERE job_id=$1',[f.config.jobId])).rows[0].n,0);});
  await t.test('kill switch blocks new dispatch intent',async()=>{const f=await seed();await admin.query('UPDATE rise_runtime.research_router_settings SET emergency_kill_switch=true');await assert.rejects(claim(f),{code:'IIQ_EXECUTION_PAUSED'});await admin.query('UPDATE rise_runtime.research_router_settings SET emergency_kill_switch=false');});
  await t.test('ambiguous intent COMMIT cannot issue SEND on restart',async()=>{const f=await seed();let lose=true;const wrapped={async connect(){const q=await pool.connect();return {async query(...args){const out=await q.query(...args),sql=typeof args[0]==='string'?args[0]:args[0].text;if(sql==='COMMIT'&&lose){lose=false;throw Error('synthetic lost acknowledgement');}return out;},release:b=>q.release(b)};}};const uncertain=createInterviewiqResearchWorkerStore(f.config,{pool:wrapped});await assert.rejects(uncertain.claim({proof:await proof(f.config,'start'),workerId:'synthetic'}));assert.equal((await claim(f)).mode,'BUSY');await expire(f);assert.equal((await claim(f)).mode,'RECONCILIATION_REQUIRED');});
  await t.test('ambiguous completion COMMIT resolves immutable receipt without re-accounting',async()=>{const f=await seed();let lose=false;const wrapped={async connect(){const q=await pool.connect();return {async query(...args){const out=await q.query(...args),sql=typeof args[0]==='string'?args[0]:args[0].text;if(sql==='COMMIT'&&lose){lose=false;throw Error('synthetic lost acknowledgement');}return out;},release:b=>q.release(b)};}};const store=createInterviewiqResearchWorkerStore(f.config,{pool:wrapped}),h=await store.claim({proof:await proof(f.config,'start'),workerId:'synthetic'});await store.captureRaw(h,raw(f.config));lose=true;const result=await store.complete(h,{proof:await proof(f.config,'publish')});assert.equal(result.status,'PARTIAL');assert.equal((await admin.query("SELECT count(*)::int AS n FROM rise_runtime.research_spend_ledger WHERE job_id=$1 AND event_type='RECONCILE'",[f.config.jobId])).rows[0].n,1);});
  await t.test('revoked rights prevent publication without erasing paid raw or reservation',async()=>{const f=await seed(),h=await claim(f);await f.store.captureRaw(h,raw(f.config));await admin.query('UPDATE rise_runtime.source_authorizations SET revoked_at=now() WHERE release_id=$1',[RELEASE]);await assert.rejects(f.store.complete(h,{proof:await proof(f.config,'publish')}),{code:'IIQ_EXECUTION_RIGHTS_REVOKED'});assert.equal((await admin.query('SELECT raw_sha256 FROM rise_runtime.iiq_research_executions WHERE job_id=$1',[f.config.jobId])).rows[0].raw_sha256,raw(f.config).sha256);assert.equal((await admin.query("SELECT count(*)::int AS n FROM rise_runtime.research_spend_ledger WHERE job_id=$1 AND event_type='RECONCILE'",[f.config.jobId])).rows[0].n,0);await admin.query('UPDATE rise_runtime.source_authorizations SET revoked_at=NULL WHERE release_id=$1',[RELEASE]);await expire(f);});
  await t.test('current model and subject envelope drift prevents dispatch',async()=>{const f=await seed();await admin.query("UPDATE rise_runtime.research_provider_routes SET model_key='different-model' WHERE provider_key='OPENAI_TERRA'");await assert.rejects(claim(f),{code:'IIQ_EXECUTION_PAUSED'});await admin.query("UPDATE rise_runtime.research_provider_routes SET model_key='gpt-5.6-terra' WHERE provider_key='OPENAI_TERRA'");await admin.query('UPDATE rise_runtime.research_router_settings SET subject_allowlist_hashes=ARRAY[]::text[]');await assert.rejects(claim(f),{code:'IIQ_EXECUTION_ENVELOPE_CHANGED'});await admin.query('UPDATE rise_runtime.research_router_settings SET subject_allowlist_hashes=$1',[[subject]]);});
  await t.test('raw has no DELETE or TRUNCATE runtime privileges',async()=>{const q=await pool.connect();try{assert.deepEqual((await q.query("SELECT has_table_privilege(current_user,'rise_runtime.iiq_research_executions','DELETE') AS delete,has_table_privilege(current_user,'rise_runtime.iiq_research_executions','TRUNCATE') AS truncate")).rows[0],{delete:false,truncate:false});}finally{q.release();}});

  let aliasSeeded=false;
  async function seedAlias(){
   if(!aliasSeeded){
    await admin.query('UPDATE rise_runtime.registry_releases SET active=false WHERE release_id=$1',[RELEASE]);
    await admin.query(`INSERT INTO rise_runtime.registry_releases(release_id,projection,api_index_sha256,index_manifest_sha256,program_count,rights_blocked_field_count,active) VALUES($1,'STUDENT_RIGHTS_SAFE_RISE',$2,$2,1,0,true)`,[REL.registryReleaseId,REL.registrySha256]);
    await admin.query(`INSERT INTO rise_runtime.source_authorizations VALUES($1,'TEST',$2,$2,'government_public_domain_factual_projection','SYNTHETIC',current_date+1,NULL)`,[REL.registryReleaseId,RIGHTS]);
    await admin.query(`INSERT INTO rise_runtime.canonical_evidence_sources(source_id,provider,provider_run_id,source_type,source_file_sha256,retrieved_at,rights_state,exposure_state) VALUES($1,$2,$3,$4,$5,'2026-08-29',$6,$7)`,[retainedSource.source_id,retainedSource.provider,retainedSource.provider_run_id,retainedSource.source_type,retainedSource.source_file_sha256,retainedSource.rights_state,retainedSource.exposure_state]);
    const i=retainedIdentity;
    await admin.query(`INSERT INTO rise_runtime.canonical_program_identities(program_identity_id,acgme_id,program_specialty_id,program_name,institution,city,state,specialty,reconciliation_status,exposure_state,source_id,content_sha256) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[i.program_identity_id,i.acgme_id,i.program_specialty_id,i.program_name,i.institution,i.city,i.state,i.specialty,i.reconciliation_status,i.exposure_state,i.source_id,i.content_sha256]);
    await admin.query(`INSERT INTO rise_runtime.canonical_evidence_claims(claim_id,subject_id,field,knowledge,canonical_value,assertion_class,publication_state,review_state,conflict_state,source_id,observed_period,retrieved_at,content_sha256) VALUES('synthetic-historical',$1,'SOAP_2026_APPEARANCE','{"state":"known"}','{"availablePositions":2,"programType":"Preliminary","programTypeCode":"P","nrmpProgramCode":"1405140P0"}','historical_cycle_fact','PRIVATE_BETA','APPROVED','NONE',$2,'{"kind":"match_cycle","label":"2026"}','2026-08-29',$3)`,[i.program_specialty_id,i.source_id,sha('synthetic-historical')]);
    aliasSeeded=true;
   }
   await admin.query('UPDATE rise_runtime.research_router_settings SET canary_acgme_ids=$1',[[REL.acgmeId]]);
   const binding={requestId:randomUUID(),ownerId:randomUUID(),demandId:randomUUID(),interviewId:randomUUID(),programId:REL.programId,registryReleaseId:REL.registryReleaseId};
   const config={enabled:true,binding,bodyHash:sha(JSON.stringify({...binding,kind:'program-gaps'})),registryIndex:registry(),registrySha256:REL.registrySha256,authorizationSha256s:[RIGHTS],subjectHmacKey:HMAC,expectedSubjectKey:subject,providerKey:'OPENAI_TERRA',modelKey:'gpt-5.6-terra'};
   const accepted=await createInterviewiqResearchAcceptance(config,{pool}).acceptJob({ownerId:binding.ownerId,requestId:binding.requestId,binding,bodyHash:config.bodyHash,proof:await proof(config,'reserve')});config.jobId=accepted.jobId;
   return {config,store:createInterviewiqResearchWorkerStore(config,{pool})};
  }
  await t.test('approved namespace publishes to retained subject and both readers return current program without changing historical record',async()=>{
   const f=await seedAlias(),before=(await admin.query("SELECT row_to_json(c) AS row FROM rise_runtime.canonical_evidence_claims c WHERE claim_id='synthetic-historical'")).rows;
   const invalid=structuredClone(f.config);invalid.registryIndex.activationReceipt.verified=false;await assert.rejects(createInterviewiqResearchWorkerStore(invalid,{pool}).claim({proof:await proof(invalid,'start'),workerId:'synthetic'}),{code:'IIQ_EXECUTION_IDENTITY_CHANGED'});assert.equal((await admin.query('SELECT count(*)::int AS n FROM rise_runtime.iiq_research_executions WHERE job_id=$1',[f.config.jobId])).rows[0].n,0);
   let armed=false,locked=false,checked=0,deny=false;
   const wrapped={async connect(){const q=await pool.connect();return {async query(...args){const sql=typeof args[0]==='string'?args[0]:args[0].text;
    if(sql==='COMMIT'&&armed&&locked){await admin.query("SET lock_timeout='50ms'");try{await assert.rejects(admin.query('UPDATE rise_runtime.canonical_program_identities SET content_sha256=content_sha256 WHERE program_identity_id=$1',[retainedIdentity.program_identity_id]),{code:'55P03'});await assert.rejects(admin.query('UPDATE rise_runtime.canonical_evidence_sources SET rights_state=rights_state WHERE source_id=$1',[retainedSource.source_id]),{code:'P0001'});checked++;}finally{await admin.query('SET lock_timeout=0');}}
    const out=await q.query(...args);if(deny&&sql.includes('pg_trigger t ON t.tgrelid'))out.rows[0].replication_role='replica';if(armed&&sql.includes('FOR SHARE OF i'))locked=true;return out;},release:b=>q.release(b)};}};
   const store=createInterviewiqResearchWorkerStore(f.config,{pool:wrapped}),h=await store.claim({proof:await proof(f.config,'start'),workerId:'synthetic-alias'});assert.equal(h.mode,'SEND');await store.captureRaw(h,raw(f.config));const beforeIngest=(await admin.query('SELECT count(*)::int AS n FROM rise_runtime.provider_ingest_runs')).rows;deny=true;await assert.rejects(store.complete(h,{proof:await proof(f.config,'publish')}),{code:'IIQ_EXECUTION_IDENTITY_CHANGED'});assert.deepEqual((await admin.query('SELECT count(*)::int AS n FROM rise_runtime.provider_ingest_runs')).rows,beforeIngest);assert.equal((await admin.query("SELECT count(*)::int AS n FROM rise_runtime.research_spend_ledger WHERE job_id=$1 AND event_type='RECONCILE'",[f.config.jobId])).rows[0].n,0);deny=false;armed=true;const result=await store.complete(h,{proof:await proof(f.config,'publish')});assert.equal(result.status,'PARTIAL');assert.equal(checked,1);
   const rows=(await admin.query(`SELECT c.subject_id FROM rise_runtime.canonical_evidence_claims c JOIN rise_runtime.canonical_evidence_sources s USING(source_id) WHERE s.provider_run_id=$1`,[result.providerResponseId])).rows;
   assert.ok(rows.length>0);assert.ok(rows.every(r=>r.subject_id===retainedIdentity.program_identity_id));
   const readConfig={enabled:true,pool:{options:{connectionTimeoutMillis:5000},connect:()=>pool.connect()},registryIndex:registry(),registrySha256:REL.registrySha256},binding={programId:REL.programId,registryReleaseId:REL.registryReleaseId};
   const coverage=await createInterviewiqCoverageReader(readConfig)(binding),facts=await createInterviewiqResearchResultsReader(readConfig)(binding);
   assert.equal(coverage.fields.find(x=>x.field==='research.visa').state,'SUPPORTED');assert.equal(facts.coverage.programId,REL.programId);assert.equal(facts.facts.find(x=>x.field==='research.visa').value.j1,true);
   assert.deepEqual((await admin.query("SELECT row_to_json(c) AS row FROM rise_runtime.canonical_evidence_claims c WHERE claim_id='synthetic-historical'")).rows,before);
  });
 } finally {if(pool)await pool.end();if(admin)await admin.end();if(started)run('pg_ctl',['-D',directory+'/data','-m','fast','-w','stop']);t.diagnostic(JSON.stringify({localCluster:directory,stopped:true}));}
});
