import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {PassThrough} from 'node:stream';
import {createHash,createHmac,randomUUID} from 'node:crypto';
import {createRiseServer} from '../server.mjs';
import {createInterviewiqRuntime,readInterviewiqRuntimeConfig,isInterviewiqNamespace,readEmptyInterviewiqBody} from '../adapters/interviewiq-runtime.mjs';

// Public trust certificate only; no private key or production credential.
const CA=`-----BEGIN CERTIFICATE-----
MIIDBTCCAe2gAwIBAgIUXQ4MoAMmNRTSsEJbBuv8dplXPq0wDQYJKoZIhvcNAQEL
BQAwEjEQMA4GA1UEAwwHcm9vdC1jYTAeFw0yNjA4MjgwODExMTBaFw0yODExMjUw
ODExMTBaMBIxEDAOBgNVBAMMB3Jvb3QtY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQCIyvYLH2CvKbOIeBoAMuvRxPUvrxltcvwgn63O7zKkscykFs1F
75KdWTyoQNBjRAFNUmXCpg4mNIea/v290ljj195Iuh+LQ/HgEe0VS+4PbNz5qdlY
Nw7eq9AhLrzqrLllDZDpJ+EQPSJEBsERT88tWSpERpQt5Gtz0VMRaxCVYfPae7hX
zbkYACmYzSy1oIVFq7x/TcdACh7i2RafEK8nuVA3QOul+PtpotFBCanT39T0K61E
WSwYuucGuZRJNUFBgcSVUOICXBvsI/n7MAcoGGFgLWjlNM1Ym/MmHLHTIfVWfgjh
NA0XM2aG8HP6SUfQaeMvpQbBwXnmY4U5SrzPAgMBAAGjUzBRMB0GA1UdDgQWBBSd
wFTTAJPV/MU+lddGOG9qMSWKgjAfBgNVHSMEGDAWgBSdwFTTAJPV/MU+lddGOG9q
MSWKgjAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQADetM8+BcH
a72rrUJLvF/R0QI4jlaBqcYCktaqAjvAKLmnSl1uAmcUuh9EEDYGKQt7q9eWl2rx
gQnkHIxo6ap4pSC7R4BkgZj4XdSzICCqKLv8EvUInImDJZ6NkM43eSCUydwlrlAS
qDUefex+g6UX7dUpuu7/S8alR3N2KnQbQdNVwTiRGTcg+CygvZCxKnyLJt/i0cop
+8Tx6DPU/jiOHXkPXCGn9Ny5oOCdMWbNC6qYKw0H4Hbokz8TiqcVBrFZg6Jou5gV
k+IPxEc0ELE32HtLY9z1XKikFZE4ArAvqMSbjYYJOIngU/nELw/EfJSd9m9/SbqS
uwjAidCdVSjg
-----END CERTIFICATE-----
`;
const SECRET='synthetic-request-secret-00000000000001',PROOF='synthetic-proof-secret-000000000000002';
const ENV={RISE_IIQ_ENABLED:'true',RISE_IIQ_OWNER_REQUEST_SECRET:SECRET,RISE_IIQ_OWNER_PROOF_SECRET:PROOF,
  RISE_IIQ_DATABASE_CA_PEM:CA,RISE_DATABASE_URL:'postgresql://rise_app_login:synthetic-only@postgres.railway.internal:5432/railway?sslmode=require'};
const RIGHT='a'.repeat(64),PATH='/api/rise/v1/interviewiq/programs?q=&page=1&pageSize=20';
const INDEX={registryReleaseId:'synthetic-release',activationStatus:'active',activationReceipt:{verified:true},
  releaseGate:{sourceRightsApproved:true,sourceRights:[{sha256:RIGHT}]},programs:[{programSpecialtyId:'synthetic:im',display:{programName:'Synthetic Residency'},facts:['MUST_NOT_ESCAPE']}]};
const sha=x=>createHash('sha256').update(x).digest('hex'),mac=(key,x)=>createHmac('sha256',key).update(x).digest('hex');
function signed(path=PATH) {
  const actor=JSON.stringify({subject:'11111111-1111-4111-8111-111111111111',wp_user_id:123,session_verifier:'b'.repeat(64),auth_role:'student',auth_tier:'360'});
  const time=String(Math.floor(Date.now()/1000)),nonce=randomUUID();
  return {'X-MMED-IIQ-Owner':'rise','X-MMED-IIQ-Timestamp':time,'X-MMED-IIQ-Nonce':nonce,
    'X-MMED-IIQ-Actor':Buffer.from(actor).toString('base64url'),'X-MMED-IIQ-Signature':mac(SECRET,`iiq-owner-v1\nrise\n${time}\n${nonce}\nGET\n${path}\n${sha('')}\n${sha(actor)}`)};
}
// Public schema metadata independently regenerated by the A4 PG18 verifier.
const CATALOG=[
  {
    "name": "iiq_owner_migrations",
    "kind": "r",
    "owner": "postgres",
    "rls": true,
    "force_rls": true,
    "columns": [
      {
        "name": "name",
        "type": "text",
        "default": null,
        "notNull": true,
        "identity": "",
        "generated": ""
      },
      {
        "name": "sql_sha256",
        "type": "text",
        "default": null,
        "notNull": true,
        "identity": "",
        "generated": ""
      },
      {
        "name": "schema_sha256",
        "type": "text",
        "default": null,
        "notNull": true,
        "identity": "",
        "generated": ""
      },
      {
        "name": "applied_at",
        "type": "timestamp with time zone",
        "default": "clock_timestamp()",
        "notNull": true,
        "identity": "",
        "generated": ""
      }
    ],
    "acl": [
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "DELETE"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "INSERT"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "MAINTAIN"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "REFERENCES"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "SELECT"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "TRIGGER"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "TRUNCATE"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "UPDATE"
      }
    ],
    "constraints": [
      {
        "name": "iiq_owner_migrations_applied_at_not_null",
        "type": "n",
        "validated": true,
        "definition": "NOT NULL applied_at"
      },
      {
        "name": "iiq_owner_migrations_name_check",
        "type": "c",
        "validated": true,
        "definition": "CHECK ((name ~ '^[0-9]{14}_[a-z0-9_]+\\.sql$'::text))"
      },
      {
        "name": "iiq_owner_migrations_name_not_null",
        "type": "n",
        "validated": true,
        "definition": "NOT NULL name"
      },
      {
        "name": "iiq_owner_migrations_pkey",
        "type": "p",
        "validated": true,
        "definition": "PRIMARY KEY (name)"
      },
      {
        "name": "iiq_owner_migrations_schema_sha256_check",
        "type": "c",
        "validated": true,
        "definition": "CHECK ((schema_sha256 ~ '^[a-f0-9]{64}$'::text))"
      },
      {
        "name": "iiq_owner_migrations_schema_sha256_not_null",
        "type": "n",
        "validated": true,
        "definition": "NOT NULL schema_sha256"
      },
      {
        "name": "iiq_owner_migrations_sql_sha256_check",
        "type": "c",
        "validated": true,
        "definition": "CHECK ((sql_sha256 ~ '^[a-f0-9]{64}$'::text))"
      },
      {
        "name": "iiq_owner_migrations_sql_sha256_not_null",
        "type": "n",
        "validated": true,
        "definition": "NOT NULL sql_sha256"
      }
    ],
    "indexes": [
      "CREATE UNIQUE INDEX iiq_owner_migrations_pkey ON rise_runtime.iiq_owner_migrations USING btree (name)"
    ],
    "policies": null,
    "triggers": null
  },
  {
    "name": "iiq_owner_request_nonces",
    "kind": "r",
    "owner": "postgres",
    "rls": true,
    "force_rls": true,
    "columns": [
      {
        "name": "issuer",
        "type": "text",
        "default": null,
        "notNull": true,
        "identity": "",
        "generated": ""
      },
      {
        "name": "nonce",
        "type": "uuid",
        "default": null,
        "notNull": true,
        "identity": "",
        "generated": ""
      },
      {
        "name": "request_sha256",
        "type": "text",
        "default": null,
        "notNull": true,
        "identity": "",
        "generated": ""
      },
      {
        "name": "created_at",
        "type": "timestamp with time zone",
        "default": null,
        "notNull": true,
        "identity": "",
        "generated": ""
      },
      {
        "name": "expires_at",
        "type": "timestamp with time zone",
        "default": null,
        "notNull": true,
        "identity": "",
        "generated": ""
      }
    ],
    "acl": [
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "DELETE"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "INSERT"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "MAINTAIN"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "REFERENCES"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "SELECT"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "TRIGGER"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "TRUNCATE"
      },
      {
        "grantee": "postgres",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "UPDATE"
      },
      {
        "grantee": "rise_app_runtime",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "INSERT"
      },
      {
        "grantee": "rise_app_runtime",
        "grantor": "postgres",
        "grantable": false,
        "privilege": "SELECT"
      }
    ],
    "constraints": [
      {
        "name": "iiq_owner_request_nonces_check",
        "type": "c",
        "validated": true,
        "definition": "CHECK ((expires_at >= (created_at + '00:01:30'::interval)))"
      },
      {
        "name": "iiq_owner_request_nonces_created_at_not_null",
        "type": "n",
        "validated": true,
        "definition": "NOT NULL created_at"
      },
      {
        "name": "iiq_owner_request_nonces_expires_at_not_null",
        "type": "n",
        "validated": true,
        "definition": "NOT NULL expires_at"
      },
      {
        "name": "iiq_owner_request_nonces_issuer_check",
        "type": "c",
        "validated": true,
        "definition": "CHECK ((issuer = 'interviewiq'::text))"
      },
      {
        "name": "iiq_owner_request_nonces_issuer_not_null",
        "type": "n",
        "validated": true,
        "definition": "NOT NULL issuer"
      },
      {
        "name": "iiq_owner_request_nonces_nonce_not_null",
        "type": "n",
        "validated": true,
        "definition": "NOT NULL nonce"
      },
      {
        "name": "iiq_owner_request_nonces_pkey",
        "type": "p",
        "validated": true,
        "definition": "PRIMARY KEY (issuer, nonce)"
      },
      {
        "name": "iiq_owner_request_nonces_request_sha256_check",
        "type": "c",
        "validated": true,
        "definition": "CHECK ((request_sha256 ~ '^[a-f0-9]{64}$'::text))"
      },
      {
        "name": "iiq_owner_request_nonces_request_sha256_not_null",
        "type": "n",
        "validated": true,
        "definition": "NOT NULL request_sha256"
      }
    ],
    "indexes": [
      "CREATE UNIQUE INDEX iiq_owner_request_nonces_pkey ON rise_runtime.iiq_owner_request_nonces USING btree (issuer, nonce)"
    ],
    "policies": [
      {
        "name": "iiq_owner_nonce_insert",
        "check": "(issuer = 'interviewiq'::text)",
        "roles": [
          "rise_app_runtime"
        ],
        "using": null,
        "command": "a",
        "permissive": true
      },
      {
        "name": "iiq_owner_nonce_read",
        "check": null,
        "roles": [
          "rise_app_runtime"
        ],
        "using": "(issuer = 'interviewiq'::text)",
        "command": "r",
        "permissive": true
      }
    ],
    "triggers": null
  }
];
function fixture() {
  // Protocol-composition doubles only. A4 supplies separate real-PG tests;
  // these fixtures are never production database or WordPress evidence.
  const state={created:0,closed:0,proofs:0,current:true,authorized:true,encrypted:true,nonces:new Set(),discarded:0,role:'rise_app_login'};
  class Pool {
    constructor(options){state.created++;assert.equal(options.ssl.rejectUnauthorized,true);assert.equal(options.max,4);}
    on(){}
    async end(){state.closed++;}
    async connect(){return {connection:{stream:{encrypted:state.encrypted,authorized:state.authorized}},release:discard=>{if(discard)state.discarded++;},query:async({text,values})=>{
      if(text.includes('pg_get_indexdef')){const rows=structuredClone(CATALOG);if(state.schemaDrift)rows[1].columns[1].type='text';return {rows};}
      if(text.includes('session_user'))return {rows:[{database:'railway',role:state.role,session:state.role,major:18}]};
      if(text.includes('rolsuper'))return {rows:['rise_app_login','rise_app_runtime'].map(rolname=>({rolname,rolsuper:false,rolbypassrls:false,rolcreaterole:false,rolcreatedb:false,rolreplication:false,rolinherit:true,rolcanlogin:rolname==='rise_app_login'}))};
      if(text.includes('pg_auth_members'))return {rows:[{parent:'rise_app_runtime',child:'rise_app_login',admin_option:false,inherit_option:true,set_option:true}]};
      if(text.includes('AS schema_owner'))return {rows:['iiq_owner_migrations','iiq_owner_request_nonces'].map(name=>({name,kind:'r',owner:'postgres',schema_owner:'postgres',rls:true,forced:true,triggers:0}))};
      if(text.includes('has_table_privilege'))return {rows:['iiq_owner_request_nonces','iiq_owner_migrations'].flatMap(name=>['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER','MAINTAIN'].map(privilege=>({name,privilege,allowed:name==='iiq_owner_request_nonces'&&['SELECT','INSERT'].includes(privilege)})))};
      if(text.includes('aclexplode'))return {rows:['INSERT','SELECT'].map(privilege=>({name:'iiq_owner_request_nonces',grantee:'rise_app_runtime',privilege,grantable:false}))};
      if(text.includes("to_regclass('rise_runtime.release_source_rights')"))return {rows:[{relation:'rise_runtime.release_source_rights'}]};
      if(text.includes('FROM rise_runtime.registry_releases r'))return {rows:state.current?[{authorization_sha256:RIGHT,decision_record_id:'synthetic-only'}]:[]};
      if(text.includes('INSERT INTO rise_runtime.iiq_owner_request_nonces')){const prior=state.nonces.has(values[0]);state.nonces.add(values[0]);return {rowCount:prior?0:1,rows:[]};}
      if(text==='BEGIN'||text==='COMMIT'||text==='ROLLBACK'||text.startsWith('SET LOCAL')||text.includes('SELECT 1 FROM rise_runtime.source_authorizations'))return {rows:[],rowCount:0};
      throw Error('Unhandled synthetic query');
    }};}
  }
  const fetchImpl=async(url,options)=>{
    assert.equal(url,'https://missionmedinstitute.com/wp-json/missionmed/v1/interviewiq-owner/rise/introspect');state.proofs++;
    assert.equal(options.headers['X-MMED-IIQ-Owner-Proof'],mac(PROOF,`iiq-owner-proof-v1\nrequest\n${options.body}`));
    const p=JSON.parse(options.body),now=Math.floor(Date.now()/1000);
    const raw=JSON.stringify({audience:p.audience,nonce:p.nonce,request_sha256:p.request_sha256,subject:p.subject,wp_user_id:p.wp_user_id,
      session_verifier:p.session_verifier,allowed:true,role:'student',tier:'360',iat:now,exp:now+30});
    if(state.revokeDuringProof)state.current=false;
    return new Response(raw,{headers:{'Content-Type':'application/json','X-MMED-IIQ-Owner-Proof':mac(PROOF,`iiq-owner-proof-v1\nresponse\n${raw}`)}});
  };
  return {state,Pool,fetchImpl};
}
async function mounted(runtime) {
  let generic=0;const logs=[];
  const server=createRiseServer({registryIndex:{registryReleaseId:'synthetic-http',dataClassification:'synthetic_test_fixture',programs:[]},
    production:false,authMode:'injected',authIssuer:'https://synthetic.test',authenticator:async()=>{generic++;return null;},
    interviewiqRuntime:runtime,logger:{info:x=>logs.push(x),error:x=>logs.push(x)}});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const request=(path,headers={},method='GET',body)=>new Promise((resolve,reject)=>{
    const req=http.request({hostname:'127.0.0.1',port:server.address().port,path,headers,method},res=>{
      let text='';res.on('data',b=>text+=b);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,text}));
    });req.on('error',reject);req.end(body);
  });
  return {request,logs,get generic(){return generic;},close:()=>new Promise(resolve=>server.close(resolve))};
}

test('default off creates no pool or proof calls',async()=>{
  const f=fixture(),runtime=await createInterviewiqRuntime({env:{}},f);
  const app=await mounted(runtime);
  try{assert.equal((await app.request(PATH,signed())).status,503);assert.equal(app.generic,0);assert.equal(f.state.created,0);assert.equal(f.state.proofs,0);}
  finally{await app.close();}
});
test('strict pool config preserves original URL and prevents URL TLS override',()=>{
  const before=ENV.RISE_DATABASE_URL,c=readInterviewiqRuntimeConfig(ENV);
  assert.equal(ENV.RISE_DATABASE_URL,before);assert.equal(new URL(c.pool.connectionString).search,'');assert.equal(c.pool.ssl.rejectUnauthorized,true);
  assert.equal(c.pool.ssl.ca.toString(),CA);assert.ok(c.pool.ssl.checkServerIdentity('postgres.railway.internal',{fingerprint256:'WRONG'}));
});
for(const [name,edit] of Object.entries({
  host:e=>e.RISE_DATABASE_URL=e.RISE_DATABASE_URL.replace('postgres.railway.internal','other.invalid'),
  port:e=>e.RISE_DATABASE_URL=e.RISE_DATABASE_URL.replace(':5432',':5433'),
  role:e=>e.RISE_DATABASE_URL=e.RISE_DATABASE_URL.replace('rise_app_login','postgres'),
  fragment:e=>e.RISE_DATABASE_URL+='#unsafe',
  duplicateSSL:e=>e.RISE_DATABASE_URL+='&sslmode=require',
  insecureSSL:e=>e.RISE_DATABASE_URL=e.RISE_DATABASE_URL.replace('sslmode=require','sslmode=no-verify'),
  urlOptions:e=>e.RISE_DATABASE_URL+='&options=x',
  ambientHost:e=>e.PGHOST='localhost',ambientService:e=>e.PGSERVICEFILE='/tmp/unused',
  tlsOff:e=>e.NODE_TLS_REJECT_UNAUTHORIZED='0',ca:e=>e.RISE_IIQ_DATABASE_CA_PEM='not a certificate',
  secretReuse:e=>e.RISE_IIQ_OWNER_PROOF_SECRET=SECRET,sharedToken:e=>e.RISE_HQ_IVOC_DELEGATION_TOKEN=SECRET,
  short:e=>e.RISE_IIQ_OWNER_REQUEST_SECRET='short',
}))test(`enabled configuration rejects ${name} before pool construction`,async()=>{const e={...ENV};edit(e);const f=fixture();await assert.rejects(createInterviewiqRuntime({env:e,registryIndex:INDEX},f));assert.equal(f.state.created,0);});
for(const path of ['/api/rise/v1/interviewiq','/api/rise/v1/interviewiq/../programs','/api/rise/v1/%69nterviewiq/programs','/api/rise/v1/interviewiq%2fprograms','/api/rise/v1/interviewiq%252fprograms','/api/rise/x/../v1/interviewiq/programs','//other.test/api/rise/v1/interviewiq/programs'])
  test(`reserved malformed namespace never uses generic auth ${path}`,async()=>{
    assert.equal(isInterviewiqNamespace(path),true);const app=await mounted();try{assert.equal((await app.request(path)).status,503);assert.equal(app.generic,0);}finally{await app.close();}
  });
test('real HTTP mount carries signed request and returns identity only',async()=>{
  const f=fixture(),runtime=await createInterviewiqRuntime({env:ENV,registryIndex:INDEX},f),app=await mounted(runtime),headers=signed();
  try{
    const r=await app.request(PATH,headers);assert.equal(r.status,200);assert.equal(r.headers['cache-control'],'no-store');assert.equal(f.state.proofs,2);assert.equal(app.generic,0);
    const p=JSON.parse(r.text).programs[0];assert.deepEqual(Object.keys(p),['id','name','track','registryReleaseId']);assert.equal(p.id,'synthetic:im');
    assert.doesNotMatch(r.text+JSON.stringify(app.logs),/MUST_NOT_ESCAPE|session_verifier|wp_user_id|synthetic-request-secret/);
    assert.equal((await app.request(PATH,headers)).status,503);assert.equal(f.state.proofs,2);
    assert.equal((await app.request('/api/rise/v1/health')).status,200);
  }finally{await app.close();await new Promise(setImmediate);assert.equal(f.state.closed,1);}
});
for(const [label,change] of Object.entries({plain:c=>c.encrypted=false,untrusted:c=>c.authorized=false,wrongRole:c=>c.role='postgres',schemaDrift:c=>c.schemaDrift=true,missingRights:c=>c.current=false}))
  test(`startup rejects ${label} and closes dedicated pool`,async()=>{const f=fixture();change(f.state);await assert.rejects(createInterviewiqRuntime({env:ENV,registryIndex:INDEX},f));assert.equal(f.state.closed,1);assert.equal(f.state.proofs,0);});
test('rights revoked during proof prevent response without fallback',async()=>{
  const f=fixture(),runtime=await createInterviewiqRuntime({env:ENV,registryIndex:INDEX},f);f.state.revokeDuringProof=true;const app=await mounted(runtime);
  try{assert.equal((await app.request(PATH,signed())).status,503);assert.equal(app.generic,0);}finally{await app.close();}
});
for(const [label,extra,method,body] of [['browser',{Origin:'https://synthetic.test'},'GET'],['override',{'X-HTTP-Method-Override':'POST'},'GET'],['body',{'Content-Length':'1'},'GET','x'],['method',{},'POST']])
  test(`HTTP ${label} rejected before nonce/proof`,async()=>{const f=fixture(),runtime=await createInterviewiqRuntime({env:ENV,registryIndex:INDEX},f),app=await mounted(runtime);
    try{assert.equal((await app.request(PATH,{...signed(),...extra},method,body)).status,503);assert.equal(f.state.nonces.size,0);assert.equal(f.state.proofs,0);assert.equal(app.generic,0);}finally{await app.close();}});
test('empty-body reader is bounded and rejects actual bytes or duplicate framing',async()=>{
  const stream=()=>Object.assign(new PassThrough(),{method:'GET',rawHeaders:[]});
  const duplicate=stream();duplicate.rawHeaders=['Content-Length','0','content-length','0'];await assert.rejects(readEmptyInterviewiqBody(duplicate));duplicate.destroy();
  const bytes=stream(),p=readEmptyInterviewiqBody(bytes);bytes.end('x');await assert.rejects(p);bytes.destroy();
  const stalled=stream(),started=Date.now();await assert.rejects(readEmptyInterviewiqBody(stalled));assert.ok(Date.now()-started<1800);stalled.destroy();
});
