import fs from 'node:fs';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const {chromium}=require('/Users/brianb/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch();const results=[];
for(const [offer,selector,amount] of [['interview_week','a[data-offer="interview_week"]',549],['complete','a[data-offer="complete"]',3099]]){
 const ctx=await browser.newContext({viewport:{width:390,height:844}});const p=await ctx.newPage();const events=[];p.on('request',r=>{if(r.url().includes('google-analytics.com')&&r.url().includes('collect'))events.push({url:r.url(),body:r.postData()});});
 await p.goto('https://missionmedinstitute.com/missionresidency/?utm_source=facebook&utm_medium=paid_social&utm_campaign=alternate_qa',{waitUntil:'networkidle'});
 await p.waitForTimeout(1500); // Let the existing async Google tag finish initialization before the measured interaction.
 await Promise.all([p.waitForURL(/\/product\//),p.locator(selector).last().click()]);await p.getByRole('link',{name:'Continue with card',exact:true}).waitFor();const detailUrl=p.url();const rails=await p.locator('a[href*="checkout"]').evaluateAll(es=>es.map(e=>({text:e.innerText,url:e.href})).filter(x=>x.text));
 await Promise.all([p.waitForURL(/\/checkout\//),p.getByRole('link',{name:'Continue with card',exact:true}).click()]);await p.locator('#payment_method_stripe').waitFor({state:'attached'});
 const checkout=await p.evaluate(()=>({url:location.href,title:document.title,order:document.querySelector('.woocommerce-checkout-review-order')?.innerText||'',stripe:!!document.querySelector('#payment_method_stripe'),zelle:!!document.querySelector('#payment_method_bacs'),fields:[...document.querySelectorAll('input[required]')].map(e=>e.name),overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth)}));
 results.push({offer,amount,detailUrl,rails,checkout,events:events.filter(e=>e.url.includes('mr_product_detail_intent')||e.body?.includes('mr_product_detail_intent')).map(e=>{const u=new URL(e.url);return {event:u.searchParams.get('en'),measurement_id:u.searchParams.get('tid'),page_location:u.searchParams.get('dl')};})});await ctx.close();
}
const ctx=await browser.newContext();const p=await ctx.newPage();const routes=[];for(const route of ['/mission-residency/','/usce/','/my-account/','/cart/','/wp-admin/']){const r=await p.goto('https://missionmedinstitute.com'+route,{waitUntil:'domcontentloaded'});routes.push({route,status:r.status(),destination:p.url(),title:await p.title()});}
await ctx.close();await browser.close();fs.writeFileSync(new URL('./qa/regression.json',import.meta.url),JSON.stringify({results,routes},null,2));console.log(JSON.stringify({results:results.map(({events,...x})=>({...x,eventCount:events.length})),routes},null,2));
