import assert from 'node:assert/strict';
import {test} from 'node:test';
import fs from 'node:fs';
import {createRequire} from 'node:module';
const {JSDOM}=createRequire(import.meta.url)('/Users/brianb/MissionMed/node_modules/jsdom');
const html=fs.readFileSync(new URL('./page_5979_wrapper.html',import.meta.url),'utf8'),ID='22222222-2222-4222-8222-222222222222';
function harness(query){const dom=new JSDOM(html,{url:'https://missionmedinstitute.com/usce-admin/'+query,runScripts:'outside-only'}),w=dom.window,frame=w.document.querySelector('iframe'),calls=[],src=frame.src;frame.contentWindow.postMessage=(...args)=>calls.push(args);w.eval(w.document.querySelector('script').textContent);return{dom,w,frame,calls,src};}
test('wrapper only accepts exact CDN origin and exact child window; does not replace relay/cachebuster source',()=>{const h=harness('?conversation='+ID+'&url=https://attacker.invalid');try{const data={type:'mm-usce-conversation-ready'};for(const [origin,source,d] of [['https://attacker.invalid',h.frame.contentWindow,data],['https://cdn.missionmedinstitute.com',{},data],['https://cdn.missionmedinstitute.com',h.frame.contentWindow,{type:'other'}],['https://cdn.missionmedinstitute.com',h.frame.contentWindow,[data]]])h.w.dispatchEvent(new h.w.MessageEvent('message',{origin,source,data:d}));assert.equal(h.calls.length,0);h.frame.src=h.src+'?v=cachebuster';h.frame.contentWindow.postMessage=(...args)=>h.calls.push(args);h.w.dispatchEvent(new h.w.MessageEvent('message',{origin:'https://cdn.missionmedinstitute.com',source:h.frame.contentWindow,data}));assert.equal(h.calls.length,1);assert.equal(h.calls[0][0].type,'mm-usce-conversation');assert.equal(h.calls[0][0].conversation,ID);assert.equal(Object.keys(h.calls[0][0]).length,2);assert.equal(h.calls[0][1],'https://cdn.missionmedinstitute.com');assert.equal(h.frame.src,h.src+'?v=cachebuster');h.frame.dispatchEvent(new h.w.Event('load'));assert.equal(h.calls.length,2);}finally{h.dom.window.close();}});
for(const query of ['?conversation=https://attacker.invalid','?conversation='+ID+'&conversation='+ID,'?conversation=bad',''])test('wrapper rejects malformed/multiple/missing canonical query '+query,()=>{const h=harness(query);try{h.w.dispatchEvent(new h.w.MessageEvent('message',{origin:'https://cdn.missionmedinstitute.com',source:h.frame.contentWindow,data:{type:'mm-usce-conversation-ready'}}));h.frame.dispatchEvent(new h.w.Event('load'));assert.equal(h.calls.length,0);assert.equal(h.frame.src,h.src);}finally{h.dom.window.close();}});
