import test from 'node:test';
import assert from 'node:assert/strict';
import {BehaviorIntelligenceRuntime} from '../../public/live-analytics/behavior-intelligence-runtime.mjs';
import {invalidateDeviceCalibration} from '../../public/studio-fable/app/adapters/engine-adapter.mjs';

for (const state of ['LISTENING','ANSWERING','NOTES']) test(`device calibration invalidation preserves the active ${state} conversation and turn evidence`,()=>{
  let now=1000;
  const behavior=new BehaviorIntelligenceRuntime({now:()=>now});
  behavior.beginInterview(0,{explicitMeasurementStart:true});
  behavior.interviewerTurnStarted({atMs:100,questionId:'CORE-01',source:'REMOTE_VAD'});
  if(state==='ANSWERING')behavior.ingestDiagnostic({modality:'audio',atMs:200,speaking:true,dbfs:-22,loudness:{speechLufsK:-22}});
  if(state==='NOTES')behavior.setNotesActive(true,200);
  behavior.setBaseline({pitchMedianHz:160,speechLufsK:-22});
  behavior.calibration.ingestAudio({atMs:300,speaking:true,loudness:{speechLufsK:-22},pitch:{medianHz:160}});
  const conversation=behavior.conversation.snapshot();
  const turns=behavior.turnMetrics.snapshot(1000),channel=behavior.interviewerChannel;
  const levels=[...behavior.speechLevels],notes=behavior.notes;
  let cancelled=null,cleared=0;
  const clock={sessionMs:()=>now},pipeline={clearPersonalCalibration(){cleared++;}};
  const real={behavior,pipeline,bridge:{sessionClock:clock},cancelFaceBaseline(reason){cancelled=reason;}};
  invalidateDeviceCalibration(real);
  assert.equal(behavior.conversation.state,state);
  assert.deepEqual(behavior.conversation.snapshot(),conversation);
  assert.deepEqual(behavior.turnMetrics.snapshot(1000),turns);
  assert.equal(behavior.interviewerChannel,channel);
  assert.equal(behavior.notes,notes);
  assert.deepEqual(behavior.speechLevels,levels);
  assert.equal(behavior.interviewRequested,true);
  assert.equal(behavior.baseline,null);
  assert.deepEqual(behavior.calibration.pitch,[]);
  assert.deepEqual(behavior.calibration.loudness,[]);
  assert.equal(behavior.calibration.phaseStartedAtMs,now);
  assert.equal(cancelled,'DEVICE_CHANGED_RECALIBRATION_REQUIRED');
  assert.equal(cleared,1);
  assert.equal(real.bridge.sessionClock,clock);
  now=1200;
  behavior.ingestDiagnostic({modality:'audio',atMs:now,speaking:false,dbfs:-65});
  assert.notEqual(behavior.conversation.state,'SETUP','the next real producer observation must remain in the current interview');
});
