import {singleOutput as legacySingleOutput} from '../helpers/loi-single-call.mjs';import {authoredOutput as singleOutput} from '../helpers/loi-authored.mjs';
import {validateAuthoredSingleCallPlans as validateSingleCallPlans,validateSingleCallPlans as validateLegacySingleCallPlans} from '../../server/loi-composition.mjs';
import {proseFixture,proseOutput} from '../helpers/loi-prose.mjs';
import {validateProsePlans} from '../../server/loi-composition.mjs';
import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{createRequire}from'node:module';import{webcrypto}from'node:crypto';const{JSDOM}=createRequire(import.meta.url)('jsdom');
const root=new URL('../../',import.meta.url),html=fs.readFileSync(new URL('public/index.html',root),'utf8'),code=fs.readFileSync(new URL('server/loi-prose-contract.mjs',root),'utf8').replace(/^export /gm,'')+'\n'+['runtime','model','views','shell','roles','actions','opening'].map(n=>fs.readFileSync(new URL('public/source/'+n+'.js',root),'utf8')).join('\n');
const owner='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222',program='program-one';
const head=(state='draft')=>({revisionId:'33333333-3333-4333-8333-333333333333',letterId:'44444444-4444-4444-8444-444444444444',letterVersion:1,state,text:'Example Program\n\nMy genuine reason\n\nSupported detail',context:{whyNow:'My reason',applicationState:'Applied',interviewState:'Invited'},motivations:[{id:'55555555-5555-4555-8555-555555555555',text:'My genuine reason',confirmed:true}],facts:[],selectedEvidence:[{field:'curriculum',claimRef:'rise-claim:'+'a'.repeat(64)}],studentFactualConfirmation:true,studentSpecificityConfirmation:true,contentHash:'a'.repeat(64),checks:{reasons:[]}});
function workspace(state='draft',role='student'){return{actor:{id:owner,role,tier:'ivprep_complete',zone:'UTC'},version:1,capabilities:{coreOnly:true,loi:true},catalog:{programs:[{id:program,name:'Example Program',track:'Categorical',fact_ids:[]}],student_zone:'UTC'},state:{interviews:[{id,owner,program,saved:true,state:'scheduled',programName:'Example Program',zone:'UTC',related:[],history:[]}],loi:{[id]:{current:head(state),history:[head(state)],outreach:[],currentBindingValid:true}}}};}
function setup(initial=workspace(),reply){const dom=new JSDOM(html,{url:'https://missionmed.test/interviewiq/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,calls=[],opened=[];Object.defineProperty(w,'crypto',{value:webcrypto});w.Headers=Headers;w.matchMedia=()=>({matches:true});w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLElement.prototype.scrollTo=()=>{};w.open=(...args)=>{opened.push(args);return{opener:'old'};};w.fetch=async(url,options={})=>{const path=String(url),body=options.body?JSON.parse(options.body):null;calls.push({path,body});let response;if(path.includes('missionmed_interviewiq_bootstrap'))response={nonce:'test',token_endpoint:'/token',api_base:'/interviewiq/api'};else if(path.endsWith('/token'))response={token:'memory-only',ttl_seconds:60};else if(path.endsWith('/commands'))response=await reply?.(body)||{bootstrap:initial};else if(path.includes('/programs?'))response=await reply?.(body,path)||{programs:[]};else response=initial;return{ok:!response.error,status:response.error?409:200,json:async()=>response};};w.eval(code+'\nwindow.h={A,applyBootstrap,render,renderLoi,coreSection,coreCommand,clearPrivateMemory,draftKey,loiExternalURL,getS:()=>S,maps:()=>[loiEvidence,loiHandoffs,loiInputIds,draftValues],getActor:()=>actor,coreAction,scheduleProgramSearch,renderIdentify,getF:()=>F,preview:()=>administratorPreview=true};');w.h.applyBootstrap(initial);w.h.getS().ui.route='interviews';w.h.getS().ui.open=id;w.h.getS().ui.section='loi';w.h.render();return{w,h:w.h,calls,opened,close:()=>w.close()};}
const el={dataset:{id}};
function input(x,k,value){const field=x.w.document.getElementById('loi-'+k+'-'+id);assert.ok(field,k);if(field.type==='checkbox')field.checked=value;else field.value=value;field.dispatchEvent(new x.w.Event('input',{bubbles:true}));return field;}

function composeWorkspace(){const b=workspace();b.capabilities.loiComposition=true;b.state.loiPreferences={defaultApproach:'ACADEMIC_PROGRAM',version:1};return b;}
function generation(b,approaches=['DIRECT_CONCISE'],legacy=false){const input=proseFixture({approaches,program:{id:program,name:'Example Program',track:'',registryReleaseId:'registry-test'}});input.refs[0].text='Example Program';const h=b.state.loi[id].current;return {generationId:'66666666-6666-4666-8666-666666666666',status:'PROPOSED',reason:null,proposals:legacy?validateProsePlans(proseOutput(input),input):validateSingleCallPlans(singleOutput(input),input),approaches,baseHead:{letterId:h.letterId,expectedHead:h.revisionId,expectedLetterVersion:h.letterVersion},subject:{interviewId:id},provenance:{program:input.program,factualSpans:input.refs,evidenceQualification:{contract:'SOURCE_PINNED_CLAIM_REVIEW_V1',claimDigests:['a'.repeat(64)]}},factualGuard:legacy?'PROSE_INDEPENDENT_CHECK_V3':'PROSE_AUTHORED_REVIEW_V5',compositionMode:'prose',currentEvidenceState:'RECHECK_REQUIRED',usage:null,studentReviewRequired:true};}
test('hard handler loads saved traced prose and selection saves edited draft only after explicit review',async()=>{const b=composeWorkspace(),g=generation(b),x=setup(b,body=>body.command==='loi.generation_read'?{bootstrap:b,generation:g}:{bootstrap:b});try{await x.h.A['loi-compose-load'](el);const field=x.w.document.getElementById('loi-composition-proposal-0-'+id);assert.equal(field.value,g.proposals[0].text);assert.equal(x.calls.filter(c=>c.body?.command==='loi.generate').length,0);await assert.rejects(x.h.A['loi-compose-select']({dataset:{id,candidate:'0'}}),/Review this proposal/);const review=x.w.document.getElementById('loi-composition-review-0-'+id);review.checked=true;review.dispatchEvent(new x.w.Event('input',{bubbles:true}));field.value+='\nStudent edited wording';field.dispatchEvent(new x.w.Event('input',{bubbles:true}));await x.h.A['loi-compose-select']({dataset:{id,candidate:'0'}});const selected=x.calls.find(c=>c.body?.command==='loi.generation_select').body;assert.equal(selected.data.studentReviewConfirmed,true);assert.match(selected.data.editedText,/Student edited wording/);assert.equal(x.calls.filter(c=>['loi.approve','loi.handoff'].includes(c.body?.command)).length,0);assert.equal(x.opened.length,0);}finally{x.close();}});
test('hard handler rejects unsupported saved assertion before rendering private prose',async()=>{const b=composeWorkspace(),g=generation(b);g.proposals[0].text+='\n\nI invented an award.';const x=setup(b,()=>({bootstrap:b,generation:g}));try{await assert.rejects(x.h.A['loi-compose-load'](el));assert.equal(x.w.document.body.textContent.includes('invented an award'),false);assert.equal(x.w.document.getElementById('loi-composition-proposal-0-'+id),null);}finally{x.close();}});
test('hard Generate one and SHOW ME 3 handlers send exact requested count/approaches, never auto-approve/send',async()=>{for(const count of [1,3]){const b=composeWorkspace(),x=setup(b,body=>body.command==='loi.generate'?{bootstrap:b,generation:generation(b,body.data.approaches||[body.data.approach])}:{bootstrap:b});try{x.h.maps()[0].set(id,{research:{facts:[{field:'curriculum',state:'SUPPORTED',claimRef:'rise-claim:'+'a'.repeat(64),value:'Supported detail'}]}});x.h.render();input(x,'evidence-0',true);await x.h.A[count===1?'loi-compose-one':'loi-compose-three'](el);const sent=x.calls.filter(c=>c.body?.command==='loi.generate');assert.equal(sent.length,1);assert.equal(sent[0].body.data.count,count);if(count===3){assert.equal(sent[0].body.data.approaches.length,3);assert.equal(new Set(sent[0].body.data.approaches).size,3);}assert.equal(x.w.document.querySelectorAll('[id^="loi-composition-proposal-"]').length,count);assert.equal(x.calls.filter(c=>['loi.approve','loi.handoff'].includes(c.body?.command)).length,0);}finally{x.close();}}});
test('late saved prose after capability revocation cannot restore private DOM',async()=>{const b=composeWorkspace();let release,started;const began=new Promise(r=>started=r),x=setup(b,()=>{started();return new Promise(r=>release=r);});try{const pending=x.h.A['loi-compose-load'](el);await began;const revoked=composeWorkspace();revoked.capabilities.loiComposition=false;x.h.applyBootstrap(revoked);x.h.render();release({bootstrap:b,generation:generation(b)});await assert.rejects(pending,/access changed|letter or writing/i);assert.equal(x.w.document.getElementById('loi-composition-proposal-0-'+id),null);}finally{x.close();}});

test('saved V2 prose remains read-only compatible without new provider generation',async()=>{const b=composeWorkspace(),g=generation(b,['DIRECT_CONCISE'],true);g.factualGuard='PROSE_TRACED_CLAIMS_V2';for(const row of g.proposals)delete row.verification;const x=setup(b,()=>({bootstrap:b,generation:g}));try{await x.h.A['loi-compose-load'](el);assert.equal(x.w.document.getElementById('loi-composition-proposal-0-'+id).value,g.proposals[0].text);assert.equal(x.calls.filter(c=>c.body?.command==='loi.generate').length,0);}finally{x.close();}});

test('saved V3 independent-verdict output remains compatible without generation',async()=>{const b=composeWorkspace(),g=generation(b,['DIRECT_CONCISE'],true),x=setup(b,()=>({bootstrap:b,generation:g}));try{await x.h.A['loi-compose-load'](el);assert.equal(x.w.document.getElementById('loi-composition-proposal-0-'+id).value,g.proposals[0].text);assert.equal(x.calls.filter(c=>c.body?.command==='loi.generate').length,0);}finally{x.close();}});

test('saved V4 local-span proposals remain readable without provider generation',async()=>{const b=composeWorkspace(),g=generation(b),input=proseFixture({program:g.provenance.program});input.refs[0].text=g.provenance.program.name;g.proposals=validateLegacySingleCallPlans(legacySingleOutput(input),input);g.factualGuard='PROSE_LOCAL_SPANS_V4';const x=setup(b,()=>({bootstrap:b,generation:g}));try{await x.h.A['loi-compose-load'](el);assert.equal(x.w.document.getElementById('loi-composition-proposal-0-'+id).value,g.proposals[0].text);assert.equal(x.calls.filter(c=>c.body?.command==='loi.generate').length,0);}finally{x.close();}});
test('authored review is visible and exact saved approval needs explicit governed-source confirmation',async()=>{const b=composeWorkspace(),g=generation(b),row=g.proposals[0],h=b.state.loi[id].current;h.text=row.text;h.authoredComposition={review:row.review};const x=setup(b,()=>({bootstrap:b}));try{assert.match(x.w.document.body.textContent,/Meaning needs your verification/);assert.match(x.w.document.body.textContent,/not factual certification/);assert.throws(()=>x.h.A['loi-approve'](el),/Verify every authored clause/);input(x,'source-verified',true);await x.h.A['loi-approve'](el);const approval=x.calls.find(c=>c.body?.command==='loi.approve');assert.equal(approval.body.data.studentSourceVerification,true);assert.equal(approval.body.data.contentHash,h.contentHash);assert.equal(x.opened.length,0);}finally{x.close();}});
