import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{createRequire}from'node:module';import{webcrypto}from'node:crypto';const{JSDOM}=createRequire(import.meta.url)('jsdom');
const root=new URL('../../',import.meta.url),html=fs.readFileSync(new URL('public/index.html',root),'utf8'),code=['runtime','model','views','shell','roles','actions','opening'].map(n=>fs.readFileSync(new URL('public/source/'+n+'.js',root),'utf8')).join('\n');
const owner='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222',program='program-one';
const head=(state='draft')=>({revisionId:'33333333-3333-4333-8333-333333333333',letterId:'44444444-4444-4444-8444-444444444444',letterVersion:1,state,text:'Example Program\n\nMy genuine reason\n\nSupported detail',context:{whyNow:'My reason',applicationState:'Applied',interviewState:'Invited'},motivations:[{id:'55555555-5555-4555-8555-555555555555',text:'My genuine reason',confirmed:true}],facts:[],selectedEvidence:[{field:'curriculum',claimRef:'rise-claim:'+'a'.repeat(64)}],studentFactualConfirmation:true,studentSpecificityConfirmation:true,contentHash:'a'.repeat(64),checks:{reasons:[]}});
function workspace(state='draft',role='student'){return{actor:{id:owner,role,tier:'ivprep_complete',zone:'UTC'},version:1,capabilities:{coreOnly:true,loi:true},catalog:{programs:[{id:program,name:'Example Program',track:'Categorical',fact_ids:[]}],student_zone:'UTC'},state:{interviews:[{id,owner,program,saved:true,state:'scheduled',programName:'Example Program',zone:'UTC',related:[],history:[]}],loi:{[id]:{current:head(state),history:[head(state)],outreach:[],currentBindingValid:true}}}};}
function setup(initial=workspace(),reply){const dom=new JSDOM(html,{url:'https://missionmed.test/interviewiq/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,calls=[],opened=[];Object.defineProperty(w,'crypto',{value:webcrypto});w.Headers=Headers;w.matchMedia=()=>({matches:true});w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLElement.prototype.scrollTo=()=>{};w.open=(...args)=>{opened.push(args);return{opener:'old'};};w.fetch=async(url,options={})=>{const path=String(url),body=options.body?JSON.parse(options.body):null;calls.push({path,body});let response;if(path.includes('missionmed_interviewiq_bootstrap'))response={nonce:'test',token_endpoint:'/token',api_base:'/interviewiq/api'};else if(path.endsWith('/token'))response={token:'memory-only',ttl_seconds:60};else if(path.endsWith('/commands'))response=await reply?.(body)||{bootstrap:initial};else if(path.includes('/programs?'))response=await reply?.(body,path)||{programs:[]};else response=initial;return{ok:!response.error,status:response.error?409:200,json:async()=>response};};w.eval(code+'\nwindow.h={A,applyBootstrap,render,renderLoi,coreSection,coreCommand,clearPrivateMemory,draftKey,loiExternalURL,getS:()=>S,maps:()=>[loiEvidence,loiHandoffs,loiInputIds,draftValues],getActor:()=>actor,coreAction,scheduleProgramSearch,renderIdentify,getF:()=>F,preview:()=>administratorPreview=true};');w.h.applyBootstrap(initial);w.h.getS().ui.route='interviews';w.h.getS().ui.open=id;w.h.getS().ui.section='loi';w.h.render();return{w,h:w.h,calls,opened,close:()=>w.close()};}
const el={dataset:{id}};
function input(x,k,value){const field=x.w.document.getElementById('loi-'+k+'-'+id);assert.ok(field,k);if(field.type==='checkbox')field.checked=value;else field.value=value;field.dispatchEvent(new x.w.Event('input',{bubbles:true}));return field;}
test('owned attached section, escaped private history and signed capability gates',()=>{const b=workspace();b.state.loi[id].current.text='<img src=x onerror=alert(1)>';b.state.loi[id].history=[b.state.loi[id].current];const x=setup(b);try{assert.equal(x.h.coreSection('loi'),true);assert.equal(x.h.coreCommand('loi.mark_sent'),true);assert.equal(x.w.document.querySelector('img[src=x]'),null);assert.match(x.w.document.getElementById('loi-text-'+id).value,/<img/);x.h.applyBootstrap(workspace('draft','admin'));assert.equal(x.h.coreSection('loi'),false);assert.match(x.h.renderLoi(x.h.getS().interviews[0]),/unavailable/);assert.equal(x.w.localStorage.length,0);}finally{x.close();}});
test('supported evidence/build/save/approve follow server contract, no invented actor or send',async()=>{const x=setup(workspace(),body=>body.command==='loi.evidence'?{type:'loi_evidence',program:{name:'Example Program'},research:{facts:[{field:'curriculum',claimRef:'rise-claim:'+'a'.repeat(64),value:'Supported detail',retrievedAt:'2026-10-04T00:00:00Z',sources:[]}]}}:{bootstrap:workspace()});try{await x.h.A['loi-evidence'](el);input(x,'factual',true);input(x,'specific',true);input(x,'evidence-0',true);x.h.A['loi-build'](el);assert.match(x.w.document.getElementById('loi-text-'+id).value,/Example Program/);await x.h.A['loi-save'](el);const data=x.calls.find(c=>c.body?.command==='loi.save').body.data;assert.equal(data.facts.length,0);assert.equal(data.motivations[0].confirmed,true);assert.equal(data.selectedEvidence[0].field,'curriculum');assert.equal('actor'in data,false);await x.h.A['loi-approve'](el);assert.equal(x.calls.filter(c=>c.body?.command==='loi.approve').length,1);assert.equal(x.opened.length,0);}finally{x.close();}});
test('conflict retains unsaved text and actor switch clears evidence/draft/outreach memory',async()=>{const x=setup(workspace(),body=>body.command==='loi.save'?{error:{message:'Conflict'}}:null);try{input(x,'text','Unsaved student words');await assert.rejects(x.h.A['loi-save'](el),/typed draft is kept/);assert.equal(x.w.document.getElementById('loi-text-'+id).value,'Unsaved student words');await assert.rejects(Promise.resolve().then(()=>x.h.A['loi-approve'](el)),/Save your latest/);for(const m of x.h.maps())m.set('private','words');const b=workspace();b.actor.id='another-owner';b.state.interviews=[];b.state.loi={};x.h.applyBootstrap(b);assert.ok(x.h.maps().every(m=>m.size===0));}finally{x.close();}});
test('server compose handoff opens only explicit click; manual copy and self report persist honestly',async()=>{const recipient='program@example.org',subject='Student letter',text=head().text,gmailUrl='https://mail.google.com/mail/?'+new URLSearchParams({view:'cm',fs:'1',to:recipient,su:subject,body:text}),handoff={handoffId:'66666666-6666-4666-8666-666666666666',recipient,subject,text,gmailUrl,mailtoUrl:'mailto:'+recipient+'?subject=Student%20letter&body='+encodeURIComponent(text)};const b=workspace('approved'),x=setup(b,body=>{if(body.command==='loi.handoff')return{bootstrap:b,handoff};if(body.command==='loi.mark_sent'){const after=workspace('approved');after.state.loi[id].history.push({state:'self_reported_sent',recordedAt:'2026-10-04T00:00:00Z'});return{bootstrap:after};}return{bootstrap:b};});try{input(x,'recipient',recipient);input(x,'subject',subject);input(x,'recipientConfirmed',true);await x.h.A['loi-handoff'](el);assert.equal(x.opened.length,0);x.h.A['loi-gmail'](el);assert.equal(x.opened[0][2],'noopener,noreferrer');assert.equal(new URL(x.opened[0][0]).searchParams.get('body'),text);await x.h.A['loi-copy'](el);assert.equal(x.w.document.activeElement.id,'loi-copyText-'+id);input(x,'sentConfirmed',true);await x.h.A['loi-mark-sent'](el);assert.match(x.w.document.body.textContent,/self_reported_sent/);assert.equal(x.calls.filter(c=>c.body?.command==='loi.mark_sent').length,1);assert.throws(()=>x.h.loiExternalURL('javascript:alert(1)','gmail'));input(x,'text','Edited after approval');assert.throws(()=>x.h.A['loi-gmail'](el),/Save and approve/);}finally{x.close();}});

test('same-owner capability revocation drops late evidence and clears old LOI DOM',async()=>{const b=workspace(),revoked=workspace('draft','admin');revoked.state.interviews=[];revoked.state.loi={};const x=setup(b,()=>({bootstrap:revoked,type:'loi_evidence',program:{name:'Example Program'},research:{facts:[{value:'PRIVATE_LATE'}]}}));try{await assert.rejects(x.h.A['loi-evidence'](el),/account changed/);assert.ok(x.h.maps().every(m=>m.size===0));assert.equal(x.w.document.getElementById('loi-text-'+id),null);assert.equal(x.w.document.body.textContent.includes('PRIVATE_LATE'),false);}finally{x.close();}});

test('derived revoked consent warning preserves history and disables current outreach',()=>{const b=workspace('approved');b.state.loi[id].currentConsentValid=false;b.state.loi[id].consentInvalidRevisionIds=[head().revisionId];const x=setup(b);try{assert.match(x.w.document.body.textContent,/Historical letters are retained/);assert.equal(x.w.document.querySelector('[data-act="loi-handoff"]').disabled,true);assert.throws(()=>x.h.A['loi-gmail'](el),/Save and approve/);assert.match(x.w.document.body.textContent,/historical permission unavailable/);}finally{x.close();}});

const compose=b=>{const recipient='program@example.org',subject='Student letter',text=b.state.loi[id].current.text;return{handoffId:'66666666-6666-4666-8666-666666666666',recipient,subject,text,gmailUrl:'https://mail.google.com/mail/?'+new URLSearchParams({view:'cm',fs:'1',to:recipient,su:subject,body:text}),mailtoUrl:'mailto:'+recipient+'?'+new URLSearchParams({subject,body:text})};};
async function prepare(x){input(x,'recipient','program@example.org');input(x,'subject','Student letter');input(x,'recipientConfirmed',true);await x.h.A['loi-handoff'](el);}
test('cached outreach rejects newer approval, changed evidence, consent, recipient and subject',async()=>{
 for(const change of ['head','evidence','consent','recipient','subject']){
  const b=workspace('approved'),x=setup(b,()=>({bootstrap:b,handoff:compose(b)}));
  try{await prepare(x);if(change==='recipient'||change==='subject')x.w.document.getElementById('loi-'+change+'-'+id).value='changed';
   else{const next=workspace('approved');if(change==='head'){next.state.loi[id].current.revisionId='77777777-7777-4777-8777-777777777777';next.state.loi[id].current.contentHash='b'.repeat(64);next.state.loi[id].current.text='New approved words';}if(change==='evidence')next.state.loi[id].current.evidenceDigest='changed';if(change==='consent')next.state.loi[id].currentConsentValid=false;x.h.applyBootstrap(next);x.h.render();}
   assert.throws(()=>x.h.A['loi-gmail'](el),/Save and approve|Prepare and review/);
   assert.throws(()=>x.h.A['loi-mailto'](el),/Save and approve|Prepare and review/);
   await assert.rejects(x.h.A['loi-copy'](el),/Save and approve|Prepare and review/);
   assert.throws(()=>x.h.A['loi-mark-sent'](el),/Save and approve|Prepare and review/);assert.equal(x.opened.length,0);assert.equal(x.calls.filter(c=>c.body?.command==='loi.mark_sent').length,0);
  }finally{x.close();}
 }
});
test('same student capability loss clears only LOI caches, input and drafts',()=>{
 const b=workspace('approved'),x=setup(b);try{for(const m of x.h.maps().slice(0,3))m.set(id,'private');const drafts=x.h.maps()[3];drafts.set(x.h.draftKey('loi-text-'+id),'private letter');drafts.set(x.h.draftKey('loi-recipient-'+id),'private recipient');const otherKey=x.h.draftKey('why-'+id);drafts.set(otherKey,'legitimate other draft');const next=workspace('approved');next.capabilities.loi=false;x.h.applyBootstrap(next);x.h.render();assert.ok(x.h.maps().slice(0,3).every(m=>m.size===0));assert.equal(drafts.size,1);assert.equal(drafts.get(otherKey),'legitimate other draft');assert.equal(x.w.document.getElementById('loi-text-'+id),null);}finally{x.close();}
});
test('late export after same-student revocation cannot download or restore access',async()=>{
 let release,started;const began=new Promise(r=>started=r),b=workspace('approved'),x=setup(b,()=>{started();return new Promise(r=>release=r);});let downloads=0;x.w.URL.createObjectURL=()=>{downloads++;return'blob:test';};
 try{const pending=x.h.A['loi-export'](el);await began;const revoked=workspace('approved');revoked.capabilities.loi=false;x.h.applyBootstrap(revoked);x.h.render();release({bootstrap:b,export:{history:[{text:'PRIVATE_LATE'}]}});await assert.rejects(pending,/Letter access changed/);assert.equal(downloads,0);assert.equal(x.h.coreSection('loi'),false);assert.equal(x.w.document.body.textContent.includes('PRIVATE_LATE'),false);}finally{x.close();}
});
test('late handoff rejects changed approval or destination before caching',async()=>{
 for(const change of ['head','subject']){
  let release,started;const began=new Promise(r=>started=r),b=workspace('approved'),x=setup(b,()=>{started();return new Promise(r=>release=r);});
  try{input(x,'recipient','program@example.org');input(x,'subject','Student letter');input(x,'recipientConfirmed',true);const pending=x.h.A['loi-handoff'](el);await began;
   const next=workspace('approved');if(change==='head')next.state.loi[id].current.evidenceDigest='new evidence';else x.w.document.getElementById('loi-subject-'+id).value='new subject';
   release({bootstrap:next,handoff:compose(b)});await assert.rejects(pending,/changed/);assert.equal(x.h.maps()[1].size,0);assert.equal(x.opened.length,0);
  }finally{x.close();}
 }
});

const lookupWorkspace=()=>{const b=workspace();b.capabilities.loiCanonicalLookup=true;return b;};
const waitSearch=()=>new Promise(r=>setTimeout(r,350));
test('eligible signed lookup attaches only explicit canonical choice without research',async()=>{
 const b=lookupWorkspace(),x=setup(b,(body,path)=>path?{programs:[{id:'canonical-two',name:'Canonical & Program',track:'Categorical',specialty:'IM'}]}:{bootstrap:b});
 try{x.h.getS().ui.section='identify';x.h.render();assert.match(x.w.document.body.textContent,/Letter of Interest context/);assert.equal(x.w.document.body.textContent.includes('Research remains limited'),false);assert.equal(x.h.coreAction('resolve'),true);assert.equal(x.h.coreAction('research-refresh'),false);assert.equal(x.h.coreCommand('research.check'),false);x.h.scheduleProgramSearch('Canonical','program-search');await waitSearch();const choice=x.w.document.querySelector('[data-act="resolve"]');assert.equal(choice.dataset.program,'canonical-two');assert.match(choice.textContent,/Canonical & Program/);await x.h.A.resolve(choice);const commands=x.calls.filter(c=>c.body?.command);assert.equal(commands.length,1);assert.equal(commands[0].body.command,'interview.identity');assert.equal(commands[0].body.data.program,'canonical-two');assert.equal(x.h.getS().interviews[0].program,program);}finally{x.close();}
});
test('lookup false, admin and preview make no registry request or canonical attachment',async()=>{
 for(const kind of ['false','admin','preview']){const b=lookupWorkspace();if(kind==='false')b.capabilities.loiCanonicalLookup=false;else b.actor.role='admin';const x=setup(b);try{if(kind==='preview')x.h.preview();x.h.scheduleProgramSearch('Canonical','program-search');await waitSearch();assert.equal(x.calls.filter(c=>c.path.includes('/programs?')).length,0);assert.throws(()=>x.h.A.resolve({dataset:{id,program:'canonical-two'}}),/unavailable/);}finally{x.close();}}
});
test('lookup drops late revoked-account and superseded-query results',async()=>{
 for(const kind of ['revoke','account','query']){let release,started;const began=new Promise(r=>started=r),b=lookupWorkspace(),x=setup(b,(_,path)=>{if(path){started();return new Promise(r=>release=r);}return{bootstrap:b};});
 try{x.h.getS().ui.section='identify';x.h.render();x.h.scheduleProgramSearch('Canonical','program-search');await began;if(kind==='query')x.h.scheduleProgramSearch('','program-search');else{const next=lookupWorkspace();if(kind==='revoke')next.capabilities.loiCanonicalLookup=false;else next.actor.id='another-owner';x.h.applyBootstrap(next);x.h.render();}release({programs:[{id:'late-private',name:'LATE_RESULT',track:'Categorical',specialty:'IM'}]});await new Promise(r=>setTimeout(r,10));assert.equal(x.h.getF().programs.some(p=>p.id==='late-private'),false);assert.equal(x.w.document.body.textContent.includes('LATE_RESULT'),false);}finally{x.close();}}
});

test('add-offer copy distinguishes eligible lookup from disabled registry and research',()=>{
 for(const enabled of [true,false]){const b=workspace();b.capabilities.loiCanonicalLookup=enabled;const x=setup(b);try{x.h.A['add-interview']({dataset:{}});const label=x.w.document.querySelector('label[for="ad-program"]').textContent;assert.equal(label.includes('COMING SOON'),!enabled);if(enabled){assert.match(x.w.document.body.textContent,/This does not start research; your schedule saves now/);assert.equal(x.w.document.body.textContent.includes('Research starts only'),false);}else assert.match(x.w.document.body.textContent,/Registry verification and research are coming soon/);assert.ok(x.w.document.getElementById('ad-name'));assert.ok(x.w.document.getElementById('ad-date'));}finally{x.close();}}
});
