import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';import {randomUUID,webcrypto,createHash} from 'node:crypto';
import {publicMedia} from '../../../rise/src/program-media.mjs';import {mediaInput,decision,NOW,PROGRAM} from '../fixtures/program-media.mjs';
const PNG=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aGf8AAAAASUVORK5CYII=','base64'),HASH=createHash('sha256').update(PNG).digest('hex');
const {JSDOM}=createRequire(import.meta.url)('jsdom'),views=fs.readFileSync(new URL('../../public/source/views.js',import.meta.url),'utf8'),actions=fs.readFileSync(new URL('../../public/source/actions.js',import.meta.url),'utf8');
function setup(media){const dom=new JSDOM('<!doctype html><main id="main"></main>',{runScripts:'outside-only',url:'https://synthetic.test'}),w=dom.window;Object.defineProperty(w,'crypto',{value:webcrypto});w.Uint8Array=Uint8Array;w.AbortController=AbortController;w.eval(`const S={programMedia:${JSON.stringify({[PROGRAM]:[media]})}};const now=()=>${JSON.stringify(new Date(NOW).toISOString())};const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));\n`+views+'\n'+actions.slice(actions.indexOf('// Failed approved media'))+'\nwindow.h={heroMedia,programHero,S,loadProgramMedia,verifiedProgramMediaBytes,clearProgramMediaMemory};');w.document.getElementById('main').innerHTML=w.h.heroMedia(PROGRAM,'SYNTHETIC fixture',{compact:true});return {dom,w,close:()=>w.close()};}
const approved=()=>publicMedia({id:randomUUID(),payload:mediaInput()},{state:'APPROVED',review:decision('APPROVED').review},{state:'APPROVED',version:1},NOW);
test('real hero renderer preserves exact program image/source/license/credit and historical disclaimer',()=>{const m=approved(),x=setup(m);try{assert.equal(x.w.document.querySelector('img').dataset.mediaUrl,m.url);assert.equal(x.w.document.querySelector('img').getAttribute('src'),null);assert.equal(x.w.document.querySelector('img').hidden,true);assert.equal(x.w.document.querySelector('img').alt,m.alt);assert.equal(x.w.document.querySelectorAll('figcaption a').length,2);assert.match(x.w.document.body.textContent,/Historical photograph; source dates differ/);assert.match(x.w.document.body.textContent,/SYNTHETIC credit Hied5/);}finally{x.close();}});
for(const [name,change]of Object.entries({wrongProgram:m=>m.programId='rise_wrong',unapproved:m=>m.approvalState='CANDIDATE',retracted:m=>m.approvalState='WITHDRAWN',expired:m=>m.validThrough=new Date(NOW-1).toISOString(),unrelatedAsset:m=>m.url='https://other-hospital.org/a.jpg',unknownRights:m=>m.licenseState='UNKNOWN'}))test('real hero uses fallback for '+name,()=>{const m=approved();change(m);const x=setup(m);try{assert.equal(x.w.document.querySelector('img'),null);assert.ok(x.w.document.querySelector('.heroFallback'));}finally{x.close();}});
test('actual capture error handler replaces a failed approved image with existing fallback',()=>{const x=setup(approved());try{x.w.document.querySelector('img').dispatchEvent(new x.w.Event('error'));assert.equal(x.w.document.querySelector('img'),null);assert.match(x.w.document.body.textContent,/Verified hospital imagery arrives once approved/);assert.ok(x.w.document.querySelector('.heroFallback.compact'));}finally{x.close();}});
test('source captions and alt remain escaped inert text',()=>{const m=approved();m.alt='<img src=x onerror=alert(1)>';m.caption='<script>alert(1)</script>';const x=setup(m);try{assert.equal(x.w.document.querySelector('script'),null);assert.equal(x.w.document.querySelectorAll('img').length,1);assert.equal(x.w.document.querySelector('img').alt,m.alt);}finally{x.close();}});

function validBytes(m=approved()){return {...m,assetBytes:PNG.length,assetSha256:HASH};}
const flush=()=>new Promise(r=>setTimeout(r,20));
test('checksum loader displays only verified raster data and caches across repeated renders',async()=>{const m=validBytes(),x=setup(m);try{let calls=0;x.w.fetch=async(url,o)=>{calls++;assert.equal(url,m.url);assert.equal(o.credentials,'omit');assert.equal(o.referrerPolicy,'no-referrer');assert.equal(o.redirect,'error');return new Response(PNG,{headers:{'Content-Type':'image/png'}});};x.w.h.loadProgramMedia();await flush();assert.ok(x.w.document.querySelector('img').src.startsWith('data:image/png;base64,'));assert.equal(x.w.document.querySelector('img').hidden,false);x.w.document.getElementById('main').innerHTML=x.w.h.heroMedia(PROGRAM,'SYNTHETIC');x.w.h.loadProgramMedia();await flush();assert.equal(calls,1);}finally{x.close();}});
for(const name of ['hash mismatch','oversize','SVG type','invalid magic','redirect failure'])test('checksum loader retains fallback on '+name,async()=>{const m=validBytes(),x=setup(m);try{let calls=0;x.w.fetch=async()=>{calls++;if(name==='redirect failure')throw Error('redirect denied');return new Response(name==='invalid magic'?Buffer.alloc(PNG.length):name==='oversize'?Buffer.concat([PNG,Buffer.from('extra')]):PNG,{headers:{'Content-Type':name==='SVG type'?'image/svg+xml':'image/png'}});};if(name==='hash mismatch')x.w.h.S.programMedia[PROGRAM][0].assetSha256='f'.repeat(64);x.w.h.loadProgramMedia();await flush();assert.equal(x.w.document.querySelector('img'),null);assert.ok(x.w.document.querySelector('.heroFallback'));x.w.document.getElementById('main').innerHTML=x.w.h.heroMedia(PROGRAM,'SYNTHETIC rerender');x.w.h.loadProgramMedia();await flush();assert.equal(calls,1);}finally{x.close();}});
test('shared in-flight fetch and late route/retraction/account change cannot display a prior image',async()=>{const x=setup(validBytes());try{let calls=0,release;x.w.fetch=async()=>{calls++;await new Promise(r=>release=r);return new Response(PNG,{headers:{'Content-Type':'image/png'}});};x.w.h.loadProgramMedia();x.w.document.getElementById('main').innerHTML=x.w.h.heroMedia(PROGRAM,'SYNTHETIC next render');x.w.h.loadProgramMedia();assert.equal(calls,1);x.w.h.S.programMedia={};x.w.h.clearProgramMediaMemory();release();await flush();assert.equal(x.w.document.querySelector('img')?.getAttribute('src')??null,null);assert.ok(x.w.document.querySelector('.heroFallback'));}finally{x.close();}});
