import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {webcrypto} from 'node:crypto';
const require=createRequire(import.meta.url);
const {JSDOM}=require('jsdom');
const publicURL=new URL('../../public/',import.meta.url);
const html=fs.readFileSync(new URL('index.html',publicURL),'utf8');
const source=fs.readFileSync(new URL('app.js',publicURL),'utf8').replace(/void boot\(\);\s*$/,'');
const plain=x=>JSON.parse(JSON.stringify(x));
function workspace(role='student',populated=false){
  const actor={id:role==='student'?'owner-one':role,role,displayName:'Test Account',firstName:'Test',zone:'America/New_York',tier:'enrolled_360'};
  const interview={id:'interview-one',owner:'owner-one',saved:true,program:'program-one',unresolved_input:'Example Program',deadline:null,state:'scheduled',date:'2026-10-20',wall:'2026-10-20T10:00',zone:'America/New_York',instant:'2026-10-20T14:00:00.000Z',duration:null,travel_minutes:null,format:'virtual',joining:'See invitation',joinVerified:null,related:[],history:[]};
  return {actor,capabilities:{research:true,contributions:true},catalog:{programs:[{id:'program-one',name:'Example Program',specialty:'Internal Medicine',track:'Categorical',zone:'America/New_York',fact_ids:[]}],profiles:[actor]},version:1,server_time:'2026-10-03T12:00:00Z',integrations:{speech:{available:false}},state:{interviews:populated?[interview]:[],mentorAssigned:role==='mentor'?['owner-one']:[]}};
}
function harness(initial=workspace(), responder=null){
  const dom=new JSDOM(html,{url:'https://missionmed.test/interviewiq/',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,calls=[];
  Object.defineProperty(w,'crypto',{value:webcrypto});w.Headers=Headers;w.matchMedia=()=>({matches:true});w.HTMLElement.prototype.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};
  let current=plain(initial);
  w.fetch=async(url,options={})=>{const path=String(url),body=options.body?JSON.parse(options.body):null;calls.push({path,options,body});
    const response=async(status,data)=>({ok:status>=200&&status<300,status,json:async()=>data});
    if(responder){const custom=await responder({path,options,body,current,calls});if(custom){if(custom.current)current=custom.current;return response(custom.status??200,custom.body);}}
    if(path.includes('missionmed_interviewiq_bootstrap'))return response(200,{nonce:'test-nonce',token_endpoint:'/wp-admin/admin-ajax.php?action=token',api_base:'/interviewiq/api'});
    if(path.includes('action=token'))return response(200,{token:'memory-only-test-token',nonce:'test-nonce',ttl_seconds:60});
    if(path.endsWith('/bootstrap'))return response(200,current);
    if(path.endsWith('/commands')){current={...current,version:current.version+1};return response(200,{bootstrap:current});}
    if(path.includes('/programs?'))return response(200,{programs:[]});
    throw Error('Unexpected endpoint '+path);
  };
  w.eval(source+`\nwindow.h={applyBootstrap,refreshWorkspace,render,renderDrawer,openDrawer,closeDrawer,boot,A,command,apiFetch,validateSchedule,renderMe,renderMentor,renderDebrief,renderShareControls,getDebrief,scheduleRelation,scheduleWarnings,calendarItems,structuredDebriefFields,dispatchAction,runCommand,speechStart,speechFinish,speechPause,getS:()=>S,getActor:()=>actor,getVersion:()=>version,getSession:()=>session,getDrafts:()=>draftValues,getPendingAudio:()=>pendingAudio,draftKey,getCapture:()=>speechCapture};`);
  w.h.applyBootstrap(initial);w.h.render();
  return {w,h:w.h,calls,dom,close:()=>w.close(),setCurrent:b=>current=plain(b)};
}
function field(w,id,value){const e=w.document.getElementById(id);assert.ok(e,'field '+id+' exists');e.value=value;return e;}
function el(data){return {dataset:data};}
const settle=()=>new Promise(resolve=>setTimeout(resolve,15));

test('production bundle has no fixture engine or local domain persistence',()=>{
  assert.doesNotMatch(source,/Student-[ABC]|Mentor-A|Admin-A|Program-P0|raw_simulated_segments|localStorage|F\.submission|F\.debrief|load2\(|synthetic clock/);
  assert.doesNotMatch(html,/<script(?![^>]*src=)[^>]*>/);
  assert.match(html,/script-src 'self'/);assert.doesNotMatch(html,/token|test-nonce/);
});
test('every student destination renders empty canonical state',()=>{const x=harness();try{for(const route of ['home','calendar','interviews','prepare','intel','debriefs','growth','settings','contribute']){x.h.getS().ui.route=route;assert.doesNotThrow(()=>x.h.render(),route);assert.ok(x.w.document.getElementById('main').textContent.trim());}assert.equal(x.w.document.getElementById('persona'),null);}finally{x.close();}});
test('populated private interview renders all approved sections',()=>{const b=workspace('student',true),x=harness(b);try{for(const section of ['identify','brief','why','rehearse','day','debrief','learned','schedule']){x.h.getS().ui={...x.h.getS().ui,route:'interviews',open:'interview-one',section};assert.doesNotThrow(()=>x.h.render(),section);}for(const route of ['home','calendar','prepare','intel','debriefs','growth']){x.h.getS().ui.route=route;assert.doesNotThrow(()=>x.h.render(),route);}}finally{x.close();}});
test('mentor and administrator destinations render minimized state',()=>{for(const role of ['mentor','admin']){const x=harness(workspace(role,true));try{for(const route of role==='mentor'?['home','mentor','mentorcal','settings']:['home','review','policy','settings']){x.h.getS().ui.route=route;assert.doesNotThrow(()=>x.h.render(),role+route);}assert.throws(()=>x.h.A['open-interview'](el({id:'interview-one'})),/cannot change/);}finally{x.close();}}});
test('signed WP bootstrap keeps token in memory and attaches nonce only to mutations',async()=>{const x=harness();try{await x.h.refreshWorkspace();await x.h.command('learning.propose',null,{goal:'Own observation',source:'student-entered'});assert.match(x.calls[0].path,/missionmed_interviewiq_bootstrap/);assert.equal(x.calls[1].options.headers['X-IIQ-Nonce'],'test-nonce');const get=x.calls.find(c=>c.path.endsWith('/bootstrap'));assert.equal(get.options.headers.get('Authorization'),'Bearer memory-only-test-token');assert.equal(get.options.headers.get('X-IIQ-Nonce'),null);const post=x.calls.find(c=>c.path.endsWith('/commands'));assert.equal(post.options.headers.get('X-IIQ-Nonce'),'test-nonce');assert.match(post.body.requestId,/^[0-9a-f-]{36}$/);assert.equal(post.body.expectedVersion,1);assert.equal('actor'in post.body,false);assert.equal(x.w.localStorage.length,0);assert.equal(x.w.sessionStorage.length,0);}finally{x.close();}});
test('failed offer create leaves canonical state unchanged and form editable',async()=>{const x=harness(workspace(),({path})=>path.endsWith('/commands')?{status:503,body:{error:{message:'Save unavailable'}}}:null);try{x.h.A['add-interview'](el({}));field(x.w,'ad-name','My actual offer');await assert.rejects(x.h.A['add-interview-save'](el({})),/Save unavailable/);assert.equal(x.h.getS().interviews.length,0);assert.equal(x.w.document.getElementById('ad-name').value,'My actual offer');assert.equal(x.h.getS().ui.drawer.kind,'add');}finally{x.close();}});
test('DST gap and fold are validated before creating any domain record',async()=>{const x=harness();try{x.h.A['add-interview'](el({}));field(x.w,'ad-name','Actual offer');field(x.w,'ad-date','2026-03-08');field(x.w,'ad-time','02:30');field(x.w,'ad-zone','America/New_York');await assert.rejects(x.h.A['add-interview-save'](el({})),/does not exist/);assert.equal(x.calls.length,0);field(x.w,'ad-date','2026-11-01');field(x.w,'ad-time','01:30');await x.h.A['add-interview-save'](el({}));assert.equal(x.calls.length,0);assert.equal(x.h.getS().ui.drawer.overlap.cands.length,2);await x.h.A['add-interview-save'](el({fold:'1'}));const post=x.calls.find(c=>c.path.endsWith('/commands'));assert.equal(post.body.data.schedule.fold,1);assert.equal(post.body.data.schedule.duration,null);assert.equal(post.body.data.schedule.travel_minutes,null);}finally{x.close();}});
test('date-only offer never supplies an invented instant',async()=>{const x=harness();try{x.h.A['add-interview'](el({}));field(x.w,'ad-name','Date only');field(x.w,'ad-date','2026-10-20');await x.h.A['add-interview-save'](el({}));const post=x.calls.find(c=>c.path.endsWith('/commands'));assert.equal(post.body.data.schedule.time,null);assert.equal(post.body.data.schedule.allDay,true);assert.equal('instant'in post.body.data.schedule,false);}finally{x.close();}});
test('409 reload preserves the typed draft and updates version',async()=>{const b=workspace('student',true),x=harness(b,({path,current})=>path.endsWith('/commands')?{status:409,body:{error:{message:'Conflict'}},current:{...current,version:2}}:null);try{x.h.A['open-section'](el({id:'interview-one',section:'why'}));const key=x.h.draftKey('why-interview-one');x.h.getDrafts().set(key,'My unsaved original');field(x.w,'why-interview-one','My unsaved original');await assert.rejects(x.h.A['why-save'](el({id:'interview-one'})),/another tab/);assert.equal(x.h.getVersion(),2);assert.equal(x.w.document.getElementById('why-interview-one').value,'My unsaved original');assert.equal(x.h.getS().why['interview-one'],undefined);}finally{x.close();}});
test('queued commands use the latest acknowledged version',async()=>{const x=harness();try{await Promise.all([x.h.command('learning.propose',null,{goal:'One'}),x.h.command('learning.confirm')]);const posts=x.calls.filter(c=>c.path.endsWith('/commands'));assert.deepEqual(posts.map(c=>c.body.expectedVersion),[1,2]);assert.notEqual(posts[0].body.requestId,posts[1].body.requestId);}finally{x.close();}});
test('drawer traps focus, makes background inert and restores origin',async()=>{const x=harness();try{x.h.getS().ui.route='calendar';x.h.render();const day=x.w.document.querySelector('[data-cal-day][tabindex="0"]');day.focus();x.h.A['cal-day'](el({day:day.dataset.calDay}));await settle();assert.equal(x.w.document.getElementById('main').inert,true);const buttons=[...x.w.document.querySelectorAll('.mcv2-drawer button')],first=buttons[0],last=buttons.at(-1);last.focus();last.dispatchEvent(new x.w.KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true}));assert.equal(x.w.document.activeElement,first);first.dispatchEvent(new x.w.KeyboardEvent('keydown',{key:'Tab',shiftKey:true,bubbles:true,cancelable:true}));assert.equal(x.w.document.activeElement,last);last.dispatchEvent(new x.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));assert.equal(x.w.document.getElementById('main').inert,false);assert.equal(x.w.document.activeElement,day);}finally{x.close();}});
test('calendar boundary arrow preserves exact date and a single roving target',()=>{const x=harness();try{x.h.getS().ui.route='calendar';x.h.getS().ui.cal.ym='2026-10';x.h.render();const last=[...x.w.document.querySelectorAll('[data-cal-day]')].at(-1),expected=new Date(Date.parse(last.dataset.calDay+'T12:00Z')+86400000).toISOString().slice(0,10);last.focus();last.dispatchEvent(new x.w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true}));assert.equal(x.w.document.activeElement.dataset.calDay,expected);assert.equal(x.w.document.querySelectorAll('[data-cal-day][tabindex="0"]').length,1);}finally{x.close();}});
test('review excerpt is exact student-selected text; no automatic speech selection',()=>{const x=harness(workspace('student',true));try{const markup=x.h.renderShareControls(x.h.getS().interviews[0]);assert.match(markup,/exact excerpt/);assert.match(markup,/permitted-interview-one/);assert.match(markup,/deid-interview-one/);assert.doesNotMatch(markup,/selected_shareable|checked/);}finally{x.close();}});
test('account change clears drafts and private state',()=>{const x=harness(workspace('student',true));try{x.h.getDrafts().set('private','Private draft');const next=workspace();next.actor.id='different-owner';x.h.applyBootstrap(next);x.h.render();assert.equal(x.h.getDrafts().size,0);assert.equal(x.h.getS().interviews.length,0);assert.equal(x.h.getS().ui.open,null);assert.doesNotMatch(x.w.document.body.textContent,/Private draft/);}finally{x.close();}});
test('private print selections default off and printable text has explicit contrast',()=>{const x=harness();try{assert.deepEqual(plain(x.h.getS().ui.printSel),{story:false,note:false,points:false,support:false});const css=fs.readFileSync(new URL('styles.css',publicURL),'utf8');assert.match(css,/@media print\{\.skip-link\{display:none!important\}/);assert.match(css,/-webkit-text-fill-color:#000!important/);}finally{x.close();}});
test('debrief preserves unknown structure and speech unavailable has no fake transcript',async()=>{const b=workspace('student',true);b.state.interviews[0].instant='2026-10-01T14:00:00Z';b.state.debriefs={'interview-one':{occurrence:'yes',raw:[],edited:'My own account',fields:{},questions:[],speech:{status:'idle'},latency:[],exits:{},proposed:{individual_count:null,resident_group:null}}};const x=harness(b);try{x.h.A['open-section'](el({id:'interview-one',section:'debrief'}));assert.match(x.w.document.getElementById('main').textContent,/Resident groupunknown/);await assert.rejects(x.h.speechStart(x.h.getS().interviews[0]),/not connected/);assert.equal(x.h.getDebrief(x.h.getS().interviews[0]).raw.length,0);assert.equal(x.w.document.getElementById('edited-interview-one').value,'My own account');}finally{x.close();}});
test('external program text is escaped in visible metadata',()=>{const b=workspace('student',true);b.catalog.programs[0].specialty='<img src=x onerror=alert(1)>';const x=harness(b);try{x.h.A['open-section'](el({id:'interview-one',section:'day'}));assert.equal(x.w.document.querySelector('img[src="x"]'),null);assert.match(x.w.document.getElementById('main').textContent,/<img/);}finally{x.close();}});

test('ambiguous network retry reuses the original request ID and version',async()=>{let failed=false;const x=harness(workspace(),({path})=>{if(path.endsWith('/commands')&&!failed){failed=true;throw Error('Network disconnected after possible commit');}return null;});try{await assert.rejects(x.h.command('interview.create',null,{unresolved_input:'Same offer'}),/Network/);await x.h.command('interview.create',null,{unresolved_input:'Same offer'});const posts=x.calls.filter(c=>c.path.endsWith('/commands'));assert.equal(posts.length,2);assert.equal(posts[0].body.requestId,posts[1].body.requestId);assert.equal(posts[0].body.expectedVersion,posts[1].body.expectedVersion);}finally{x.close();}});
test('expired WordPress session clears private UI and pending drafts',async()=>{const x=harness(workspace('student',true),({path})=>path.includes('missionmed_interviewiq_bootstrap')?{status:401,body:{error:{message:'Login required'}}}:null);try{x.h.getDrafts().set('private','Secret draft');await assert.rejects(x.h.refreshWorkspace(),/Login required/);assert.equal(x.h.getS(),null);assert.equal(x.h.getActor(),null);assert.equal(x.h.getDrafts().size,0);assert.doesNotMatch(x.w.document.body.textContent,/Example Program|Secret draft/);assert.match(x.w.document.body.textContent,/session ended/);}finally{x.close();}});
test('clearing an edited account sends the empty string instead of restoring old text',async()=>{const b=workspace('student',true);b.state.interviews[0].instant='2026-10-01T14:00:00Z';b.state.debriefs={'interview-one':{occurrence:'yes',edited:'Old text',raw:[],fields:{},questions:[],speech:{status:'idle'},latency:[],exits:{}}};const x=harness(b);try{x.h.A['open-section'](el({id:'interview-one',section:'debrief'}));field(x.w,'edited-interview-one','');await x.h.A['debrief-save'](el({id:'interview-one'}));assert.equal(x.calls.find(c=>c.path.endsWith('/commands')).body.data.edited,'');}finally{x.close();}});
function fakeMicrophone(w){
  const stoppedTracks=[],recorders=[];let granted;
  const stream={getTracks:()=>[{stop(){stoppedTracks.push(true);}}]};
  Object.defineProperty(w.navigator,'mediaDevices',{value:{getUserMedia:async()=>stream},configurable:true});
  class Recorder extends w.EventTarget{
    static isTypeSupported(type){return type==='audio/webm;codecs=opus';}
    constructor(input,opts){super();this.state='inactive';this.mimeType=opts.mimeType;recorders.push(this);}
    start(){this.state='recording';}
    stop(){if(this.state!=='recording')return;this.state='inactive';queueMicrotask(()=>{const data=new w.Event('dataavailable');data.data=new w.Blob(['standalone-audio-container'],{type:this.mimeType});this.dispatchEvent(data);this.dispatchEvent(new w.Event('stop'));});}
  }
  w.MediaRecorder=Recorder;return {stream,recorders,stoppedTracks};
}
test('real capture adapter uploads independent segments before pause/finish and never edits the account',async()=>{
  const b=workspace('student',true);b.integrations.speech.available=true;b.state.interviews[0].instant='2026-10-01T14:00:00Z';b.state.debriefs={'interview-one':{occurrence:'yes',raw:[],edited:'My chosen account',fields:{},questions:[],speech:{status:'idle'},latency:[],exits:{}}};let seq=0;
  const x=harness(b,({path,body,current})=>{
    if(path.endsWith('/recordings'))return {body:{recordingId:'recording-one',nextSeq:seq}};
    if(path.endsWith('/segments')){seq=body.seq+1;const next=plain(current);next.version++;next.state.debriefs['interview-one'].raw.push({id:body.segmentId,text:'Provider returned my spoken words',complete:true});return {body:{bootstrap:next,segment:{id:body.segmentId,seq:body.seq,text:'Provider returned my spoken words',status:'complete'}},current:next};}
    if(/\/recordings\/recording-one\/(pause|resume|finish)$/.test(path))return {body:{nextSeq:seq}};
    return null;
  });try{const mic=fakeMicrophone(x.w);x.h.A['open-section'](el({id:'interview-one',section:'debrief'}));await x.h.speechStart(x.h.getS().interviews[0]);assert.equal(mic.recorders.length,1);await x.h.speechPause();assert.equal(mic.stoppedTracks.length,1);const first=x.calls.find(c=>c.path.endsWith('/segments'));assert.equal(first.body.seq,0);assert.match(first.body.segmentId,/^[0-9a-f-]{36}$/);assert.equal(Buffer.from(first.body.audioBase64,'base64').toString(),'standalone-audio-container');assert.equal(first.options.headers.get('X-IIQ-Nonce'),'test-nonce');assert.ok(x.calls.findIndex(c=>c.path.endsWith('/segments'))<x.calls.findIndex(c=>c.path.endsWith('/pause')));assert.equal(x.h.getDebrief(x.h.getS().interviews[0]).edited,'My chosen account');await x.h.speechStart(x.h.getS().interviews[0]);assert.equal(mic.recorders.length,2);assert.equal(x.calls.filter(c=>c.path.endsWith('/recordings')).length,1);await x.h.speechFinish();assert.deepEqual(x.calls.filter(c=>c.path.endsWith('/segments')).map(c=>c.body.seq),[0,1]);assert.equal(x.h.getPendingAudio().size,0);assert.ok(x.calls.at(-1).path.endsWith('/finish'));assert.equal(x.h.getDebrief(x.h.getS().interviews[0]).edited,'My chosen account');}finally{x.close();}
});
test('navigation while permission is pending stops granted microphone before capture starts',async()=>{const b=workspace('student',true);b.integrations.speech.available=true;const x=harness(b);try{const mic=fakeMicrophone(x.w);let resolvePermission;x.w.navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>resolvePermission=resolve);const pending=x.h.speechStart(x.h.getS().interviews[0]);await settle();x.h.A.nav(el({to:'home'}));resolvePermission(mic.stream);await assert.rejects(pending,/workspace changed/);assert.equal(mic.recorders.length,0);assert.equal(mic.stoppedTracks.length,1);assert.equal(x.calls.filter(c=>c.path.endsWith('/recordings')).length,0);}finally{x.close();}});
test('saved offer form clears acknowledged values before a second new offer',async()=>{const x=harness();try{x.h.A['add-interview'](el({}));const input=field(x.w,'ad-name','First invitation');input.dispatchEvent(new x.w.Event('input',{bubbles:true}));await x.h.A['add-interview-save'](el({}));x.h.A['add-interview'](el({}));assert.equal(x.w.document.getElementById('ad-name').value,'');assert.equal(x.h.getDrafts().size,0);}finally{x.close();}});
test('a newer draft is retained while an earlier save is in flight',async()=>{let release;const b=workspace('student',true),x=harness(b,async({path,current})=>{if(path.endsWith('/commands')){await new Promise(resolve=>release=resolve);const next=plain(current);next.version++;next.state.why={'interview-one':{text:'Submitted wording',edited:true,basis:null}};return {body:{bootstrap:next},current:next};}return null;});try{x.h.A['open-section'](el({id:'interview-one',section:'why'}));const key=x.h.draftKey('why-interview-one');x.h.getDrafts().set(key,'Submitted wording');field(x.w,'why-interview-one','Submitted wording');const save=x.h.A['why-save'](el({id:'interview-one'}));await settle();x.h.getDrafts().set(key,'Newer typing');release();await save;assert.equal(x.w.document.getElementById('why-interview-one').value,'Newer typing');assert.equal(x.h.getS().why['interview-one'].text,'Submitted wording');}finally{x.close();}});
test('inactive dispositions preserve their labels and never become debrief prompts',()=>{for(const state of ['cancelled','declined','postponed','no_show']){const b=workspace('student',true);b.state.interviews[0].state=state;b.state.interviews[0].instant='2026-10-01T14:00:00Z';const x=harness(b);try{x.h.A['open-section'](el({id:'interview-one',section:'debrief'}));assert.match(x.w.document.getElementById('main').textContent,/No report for this inactive interview/);assert.doesNotMatch(x.w.document.getElementById('main').textContent,/Did the interview happen\?/);assert.equal(x.h.getS().interviews[0].state,state);}finally{x.close();}}});
test('canonical contribution decisions keep separate positive and negative review actions',async()=>{const b=workspace('admin');b.state.reviewQueue=[{id:'research-review',sourceKind:'research',status:'pending',program:'program-one',excerpt:'Research summary'}];b.state.contrib={submissions:[{id:'submission-one',reviewId:'research-review',student:'owner-one',status:'review',version:1,original:'Original package',decisions:{execution:'unverified',quality:'pending',publication:'unpublished',credit:'none'}}]};const x=harness(b);try{x.h.getS().ui.route='review';x.h.render();const main=x.w.document.getElementById('main');assert.equal(main.querySelector('[data-act="review-approve"]'),null);assert.ok(main.querySelector('[data-k="execution"][data-value="verify"]'));assert.ok(main.querySelector('[data-k="quality"][data-value="repair_requested"]'));assert.equal(main.querySelector('[data-value="grant"]'),null);field(x.w,'decision-reason-submission-one','Missing required source coverage');await x.h.A.decide(el({sub:'submission-one',k:'quality',value:'repair_requested'}));const sent=x.calls.find(c=>c.path.endsWith('/commands')).body;assert.deepEqual(sent.data,{submissionId:'submission-one',decision:'quality',value:'repair_requested',reason:'Missing required source coverage'});const s=x.h.getS().contrib.submissions[0];s.decisions={execution:'verified',quality:'approved',publication:'published',credit:'granted'};x.h.render();assert.ok(main.querySelector('[data-value="retract"]'));assert.ok(main.querySelector('[data-value="revoke"]'));}finally{x.close();}});
test('student receives canonical mentor notes, mission questions, repair request and expired grant',()=>{const b=workspace();b.state.mentorPriority={'owner-one':{text:'Confirm the interview timezone'}};b.state.mentorNudges=[{id:'nudge-one',student:'owner-one',text:'Try your confirmed closing goal aloud',at:'2026-10-02T12:00:00Z'}];b.state.contrib={missions:{'owner-one':{id:'mission-one',program:'program-one',policy:'actual-version',payload:{questions:['Which rotations are published?'],execution_requirement:'Use the filed research standard'}}},submissions:[{id:'submission-one',student:'owner-one',status:'review',version:1,original:'Original package',decisions:{execution:'unverified',quality:'repair_requested',publication:'unpublished',credit:'none'}}],grants:{'owner-one':[{id:'grant-one',program:'program-one',expires:'2026-10-01T12:00:00Z',revoked:false}]}};const x=harness(b);try{x.h.getS().ui.route='growth';x.h.render();assert.match(x.w.document.getElementById('main').textContent,/Confirm the interview timezone/);assert.match(x.w.document.getElementById('main').textContent,/Try your confirmed closing goal aloud/);x.h.getS().ui.route='contribute';x.h.render();const main=x.w.document.getElementById('main');assert.match(main.textContent,/Which rotations are published/);assert.ok(main.querySelector('#repair-submission-one'));assert.match(main.textContent,/expired/);}finally{x.close();}});
test('typed rehearsal clearly labels mechanical wording feedback before and after an attempt',()=>{const b=workspace('student',true),x=harness(b);try{x.h.A['open-section'](el({id:'interview-one',section:'rehearse'}));assert.match(x.w.document.getElementById('main').textContent,/Mechanical wording checks/);x.h.getS().practice['interview-one']=[{id:'attempt-one',question:'General question',draft:'My answer',feedback:true,diagnosis:[],change:'Try one specific action',basis:{},program:'program-one'}];x.h.render();assert.match(x.w.document.getElementById('main').textContent,/Mechanical wording checks/);assert.match(x.w.document.getElementById('main').textContent,/not a factual verification/);}finally{x.close();}});
test('research intake and linked repair preserve exact original package bytes',async()=>{const b=workspace();b.state.contrib={missions:{'owner-one':{id:'mission-one',program:'program-one',payload:{}}},submissions:[{id:'submission-one',student:'owner-one',status:'quarantined',version:1,original:'previous'}]};const x=harness(b);try{x.h.getS().ui.route='contribute';x.h.render();const original='  {"schema":"package"}\n\n';field(x.w,'pkg',original);await x.h.A.upload();assert.equal(x.calls.find(c=>c.body?.command==='submission.upload').body.data.text,original);const repaired='\n {"schema":"repaired"}  ';field(x.w,'repair-submission-one',repaired);await x.h.A.repair(el({sub:'submission-one'}));assert.equal(x.calls.find(c=>c.body?.command==='submission.repair').body.data.text,repaired);}finally{x.close();}});
test('an explicit per-program research denial overrides a general capability',()=>{const b=workspace('student',true);b.capabilities.researchByProgram={'program-one':false};const x=harness(b);try{x.h.A['open-section'](el({id:'interview-one',section:'brief'}));assert.match(x.w.document.getElementById('main').textContent,/Shared research is not available to you/);}finally{x.close();}});
test('session expiry during protected-request refresh clears private state',async()=>{let protectedFailed=false;const x=harness(workspace('student',true),({path})=>{if(path.endsWith('/commands')){protectedFailed=true;return {status:401,body:{error:{message:'Token expired'}}};}if(protectedFailed&&path.includes('missionmed_interviewiq_bootstrap'))return {status:401,body:{error:{message:'WP session expired'}}};return null;});try{await x.h.refreshWorkspace();x.h.getDrafts().set('private','Draft before expiry');await assert.rejects(x.h.command('learning.propose',null,{goal:'Private goal'}),/WP session expired/);assert.equal(x.h.getS(),null);assert.equal(x.h.getActor(),null);assert.equal(x.h.getDrafts().size,0);}finally{x.close();}});
test('late command response cannot restore an account after the UI identity changes',async()=>{let release;const x=harness(workspace('student',true),async({path,current})=>{if(path.endsWith('/commands')){await new Promise(resolve=>release=resolve);return {body:{bootstrap:current}};}return null;});try{const save=x.h.command('learning.propose',null,{goal:'Old account private goal'});await settle();const next=workspace();next.actor.id='new-owner';x.h.applyBootstrap(next);x.h.render();release();await assert.rejects(save,/account changed/);assert.equal(x.h.getActor().id,'new-owner');assert.equal(x.h.getS().interviews.length,0);}finally{x.close();}});
test('late bootstrap cannot restore an account after the UI identity changes',async()=>{let release;const x=harness(workspace('student',true),async({path,current})=>{if(path.endsWith('/bootstrap')){await new Promise(resolve=>release=resolve);return {body:current};}return null;});try{const read=x.h.refreshWorkspace();await settle();const next=workspace();next.actor.id='new-owner';x.h.applyBootstrap(next);x.h.render();release();await assert.rejects(read,/account changed/);assert.equal(x.h.getActor().id,'new-owner');assert.equal(x.h.getS().interviews.length,0);}finally{x.close();}});

test('schedule comparisons use complete durations and a known travel buffer across midnight',()=>{
  const x=harness();try{
    const first={instant:'2026-10-20T23:30:00Z',date:'2026-10-20',duration:120,travel_minutes:0,format:'virtual'};
    const second={instant:'2026-10-21T00:45:00Z',duration:15,travel_minutes:0,format:'virtual'};
    assert.equal(x.h.scheduleRelation(first,second).kind,'overlap');
    assert.equal(x.h.scheduleRelation(second,first).kind,'overlap');
    const later={...second,instant:'2026-10-21T02:00:00Z',duration:null,travel_minutes:45,format:'in person'};
    assert.equal(x.h.scheduleRelation(first,later).kind,'travel');
    assert.equal(x.h.scheduleRelation(first,{...later,travel_minutes:30}).kind,'none');
    assert.equal(x.h.scheduleRelation(first,{...later,travel_minutes:null}).kind,'possible');
    assert.equal(x.h.scheduleRelation({...first,duration:null},later).kind,'possible');
    assert.equal(x.h.scheduleRelation({...first,instant:null,date:'2026-10-20'},second).kind,'possible');
    assert.equal(x.h.scheduleRelation({instant:null,date:'2026-10-21',zone:'Asia/Kolkata',duration:null},{instant:'2026-10-20T20:00:00Z',duration:60}).kind,'possible');
  }finally{x.close();}
});
test('calendar warnings include related events across interviews but exclude cancellation and other students',()=>{
  const b=workspace('student',true),first=b.state.interviews[0];first.duration=60;
  const second={...first,id:'interview-two',unresolved_input:'Second interview',instant:'2026-10-20T17:00:00Z',related:[{id:'event-two',kind:'social',instant:'2026-10-20T13:30:00Z',duration_minutes:90,status:'scheduled'}]};
  b.state.interviews.push(second,{...first,id:'foreign',owner:'other-owner'});const x=harness(b);try{
    const warnings=x.h.scheduleWarnings(x.h.getS().interviews);assert.ok(warnings.some(w=>w.kind==='overlap'&&w.second.key==='rel-interview-two-event-two'));
    assert.equal(warnings.some(w=>w.first.owner!==w.second.owner),false);
    x.h.getS().interviews[1].related[0].status='cancelled';assert.equal(x.h.scheduleWarnings(x.h.getS().interviews).some(w=>w.second.key==='rel-interview-two-event-two'),false);
    x.h.getS().ui.route='calendar';x.h.render();assert.match(x.w.document.getElementById('main').textContent,/Cancelled · social/);
  }finally{x.close();}
});
test('date-only related event remains on its date without a fabricated clock time',()=>{
  const b=workspace('student',true);b.state.interviews[0].related=[{id:'unknown-time',kind:'social',date:'2026-10-20',wall:null,instant:null,zone:'America/New_York',duration_minutes:null,status:'scheduled'}];const x=harness(b);try{
    const event=x.h.calendarItems(x.h.getS().interviews).find(e=>e.id.endsWith('unknown-time'));assert.equal(event.key,'2026-10-20');assert.equal(event.time,'time not set');
    x.h.getS().ui.route='calendar';assert.doesNotThrow(()=>x.h.render());assert.match(x.w.document.getElementById('main').textContent,/Possible conflict/);
  }finally{x.close();}
});
test('related event form changes date and zone and preserves explicit DST fold, then cancels/restores by exact event ID',async()=>{
  const b=workspace('student',true);b.state.interviews[0].related=[{id:'event-one',kind:'social',date:'2026-10-20',wall:'2026-10-20T17:00:00',instant:'2026-10-20T21:00:00Z',zone:'America/New_York',fold:0,duration_minutes:60,status:'scheduled'}];const x=harness(b);try{
    x.h.A['open-section'](el({id:'interview-one',section:'schedule'}));field(x.w,'rel-date-0','2026-11-01');field(x.w,'rel-time-0','01:30');field(x.w,'rel-zone-0','America/Chicago');field(x.w,'rel-dur-0','75');field(x.w,'rel-fold-0','1');
    await x.h.A['related-save'](el({id:'interview-one',k:'0'}));let sent=x.calls.find(c=>c.body?.command==='event.update').body.data;
    assert.equal(sent.date,'2026-11-01');assert.equal(sent.zone,'America/Chicago');assert.equal(sent.fold,1);assert.equal(sent.duration_minutes,75);
    await x.h.A['related-lifecycle'](el({id:'interview-one',k:'0',action:'cancel'}));await x.h.A['related-lifecycle'](el({id:'interview-one',k:'0',action:'restore'}));
    assert.deepEqual(x.calls.filter(c=>c.body?.data?.action).map(c=>c.body.data),[{eventId:'event-one',action:'cancel'},{eventId:'event-one',action:'restore'}]);
  }finally{x.close();}
});
test('postpone/waitlist are exposed and restore replaces a stale cancellation notice',async()=>{
  const x=harness(workspace('student',true));try{x.h.A['open-section'](el({id:'interview-one',section:'schedule'}));assert.ok(x.w.document.querySelector('[data-act="postpone"]'));assert.ok(x.w.document.querySelector('[data-act="waitlist"]'));
    await x.h.A.postpone(el({id:'interview-one'}));await x.h.A.waitlist(el({id:'interview-one'}));await x.h.A.cancel(el({id:'interview-one'}));await x.h.A.restore(el({id:'interview-one'}));
    assert.deepEqual(x.calls.filter(c=>c.body?.command==='interview.lifecycle').map(c=>c.body.data.action),['postpone','waitlist','cancel','restore']);assert.match(x.w.document.getElementById('toast').textContent,/Restored/);
    x.h.getS().interviews[0].state='waitlisted';x.h.A['open-section'](el({id:'interview-one',section:'debrief'}));assert.doesNotMatch(x.w.document.getElementById('main').textContent,/Did the interview happen\?/);
  }finally{x.close();}
});
function encounterWorkspace(){const b=workspace('student',true);b.state.interviews[0].instant='2026-10-01T14:00:00Z';b.state.debriefs={'interview-one':{occurrence:'yes',raw:[],edited:'Private account',fields:{encounters:[{id:'f4c830d0-482d-46a6-a342-df8a4a61ce40',format:'unknown',roles:['unknown'],duration_minutes:null,duration_precision:'unknown'}]},questions:[],speech:{status:'idle'}}};return b;}
test('debrief saves distinct encounter duration, APD/other roles, topics and learned information without sharing',async()=>{
  const x=harness(encounterWorkspace());try{x.h.A['open-section'](el({id:'interview-one',section:'debrief'}));const eid='f4c830d0-482d-46a6-a342-df8a4a61ce40';
    field(x.w,'enc-count-interview-one','1');field(x.w,'enc-count-precision-interview-one','exact');field(x.w,'enc-format-'+eid,'panel');field(x.w,'enc-duration-'+eid,'23');field(x.w,'enc-precision-'+eid,'estimated');
    for(const o of x.w.document.getElementById('enc-roles-'+eid).options)o.selected=['associate program director','other'].includes(o.value);
    field(x.w,'db-emphasized_topics-interview-one','Continuity clinic');field(x.w,'db-emphasized_topics-certainty-interview-one','recalled');field(x.w,'db-program_information-interview-one','My recollection of team supervision');field(x.w,'db-program_information-certainty-interview-one','estimated');
    await x.h.A['debrief-save'](el({id:'interview-one'}));const data=x.calls.find(c=>c.body?.command==='debrief.save').body.data;
    assert.equal(data.fields.encounter_count,1);assert.equal(data.fields.encounters[0].duration_minutes,23);assert.deepEqual(data.fields.encounters[0].roles,['associate program director','other']);assert.equal(data.fields.emphasized_topics.text,'Continuity clinic');assert.equal(data.fields.program_information.certainty,'estimated');assert.equal(x.calls.some(c=>c.body?.command==='share.submit'),false);
  }finally{x.close();}
});
test('structured autosave captures the private form before navigation and keeps multiple role selections',async()=>{
  const x=harness(encounterWorkspace());try{x.h.A['open-section'](el({id:'interview-one',section:'debrief'}));const eid='f4c830d0-482d-46a6-a342-df8a4a61ce40',roles=x.w.document.getElementById('enc-roles-'+eid);
    for(const o of roles.options)o.selected=['faculty','other'].includes(o.value);roles.dispatchEvent(new x.w.Event('input',{bubbles:true}));x.h.render();assert.deepEqual([...x.w.document.getElementById('enc-roles-'+eid).selectedOptions].map(o=>o.value),['faculty','other']);
    x.h.A.nav(el({to:'home'}));await new Promise(r=>setTimeout(r,750));const data=x.calls.find(c=>c.body?.command==='debrief.save').body.data;assert.deepEqual(data.fields.encounters[0].roles,['faculty','other']);assert.equal(data.fields.encounters[0].duration_minutes,null);
  }finally{x.close();}
});
test('suspended grants never render active and restoration sends only the existing grant identity and reason',async()=>{
  const b=workspace('admin');b.state.reviewQueue=[{id:'review-one',status:'pending',sourceKind:'research'}];b.state.contrib={submissions:[{id:'submission-one',reviewId:'review-one',status:'review',decisions:{execution:'verified',quality:'approved',publication:'unpublished',credit:'suspended'}}],grants:{'owner-one':[{id:'grant-one',program:'program-one',expires:'2030-01-01T00:00:00Z',suspended:true,revoked:false,reviewId:'review-one',originalReviewId:'original-review'}]}};
  const x=harness(b);try{x.h.getS().ui.route='review';x.h.render();assert.match(x.w.document.getElementById('main').textContent,/Restore existing credit\/access/);x.h.getS().ui.route='policy';x.h.render();assert.match(x.w.document.getElementById('main').textContent,/suspended pending review/);assert.match(x.w.document.getElementById('main').textContent,/Restore existing grant/);
    field(x.w,'policy-reason','Corrected review was approved');await x.h.A['grant-reinstate'](el({student:'owner-one',grant:'grant-one'}));const data=x.calls.find(c=>c.body?.command==='grant.reinstate').body.data;assert.deepEqual(Object.keys(data).sort(),['grantId','reason','studentId']);assert.equal(data.grantId,'grant-one');
  }finally{x.close();}
});


test('adding an encounter supersedes an older pending structured autosave',async()=>{
  const x=harness(encounterWorkspace(),({path,body,current})=>{if(path.endsWith('/commands')&&body.command==='debrief.save'){const next=plain(current);next.version++;next.state.debriefs['interview-one'].fields=body.data.fields;return {body:{bootstrap:next},current:next};}return null;});try{
    x.h.A['open-section'](el({id:'interview-one',section:'debrief'}));const format=field(x.w,'enc-format-f4c830d0-482d-46a6-a342-df8a4a61ce40','panel');format.dispatchEvent(new x.w.Event('input',{bubbles:true}));
    await x.h.A['encounter-add'](el({id:'interview-one'}));await new Promise(r=>setTimeout(r,750));
    assert.equal(x.calls.filter(c=>c.body?.command==='debrief.save').length,1);assert.equal(x.h.getDebrief(x.h.getS().interviews[0]).fields.encounters.length,2);assert.equal(x.h.getDebrief(x.h.getS().interviews[0]).fields.encounters[0].format,'panel');
  }finally{x.close();}
});

test('new date-only related events submit the chosen named timezone and explicit unknown duration',async()=>{const x=harness(workspace('student',true));try{x.h.A['add-related-pick'](el({day:'2026-10-20'}));field(x.w,'ar-zone','Asia/Kolkata');await x.h.A['add-related-save']();const data=x.calls.find(c=>c.body?.command==='event.create').body.data;assert.equal(data.zone,'Asia/Kolkata');assert.equal(data.time,null);assert.equal(data.duration_minutes,null);assert.equal(data.date,'2026-10-20');}finally{x.close();}});

function coreWorkspace(populated=false){const b=workspace('student',populated);b.capabilities={coreOnly:true,research:false,contributions:false,comingSoon:['RISE research','StoryForge','Voice debrief']};b.catalog.programs=[];if(populated){Object.assign(b.state.interviews[0],{program:null,programName:'Supplied Hospital',track:'Preliminary',resolutionState:'manual'});}return b;}
test('core preserves all advanced navigation with clickable Coming Soon and safe previews',async()=>{const x=harness(coreWorkspace(true));try{for(const route of ['prepare','intel','debriefs','growth','contribute']){const nav=x.w.document.querySelector('[data-act="nav"][data-to="'+route+'"]');assert.ok(nav);assert.match(nav.textContent,/COMING SOON/);assert.equal(nav.disabled,false);await x.h.dispatchAction(nav);assert.match(x.w.document.getElementById('main').textContent,/live integration is not active/);}x.h.A['open-section'](el({id:'interview-one',section:'rehearse'}));assert.match(x.w.document.querySelector('.section').textContent,/COMING SOON/);assert.equal(x.calls.length,0);}finally{x.close();}});
test('core non-core command and endpoint guards make no HTTP or microphone request',async()=>{const x=harness(coreWorkspace(true));try{for(const name of ['research.refresh','ivoc.launch','debrief.save','share.submit','review.approve','submission.upload','privacy.export','grant.reinstate']){const result=await x.h.command(name,'interview-one',{});assert.equal(result.comingSoon,true);}await assert.rejects(x.h.apiFetch('/programs?q=test'),/COMING SOON/);await assert.rejects(x.h.apiFetch('/recordings',{method:'POST',body:'{}'}),/COMING SOON/);let requested=false;Object.defineProperty(x.w.navigator,'mediaDevices',{value:{getUserMedia(){requested=true;throw Error('Must not request microphone');}}});await x.h.speechStart(x.h.getS().interviews[0]);assert.equal(requested,false);assert.equal(x.calls.length,0);}finally{x.close();}});
test('core unsafe buttons stay clickable and open a safe Coming Soon drawer',async()=>{const x=harness(coreWorkspace());try{const button=x.w.document.querySelector('[data-act="eco"][data-app="storyforge"]');assert.equal(button.disabled,false);assert.match(button.textContent,/COMING SOON/);await x.h.dispatchAction(button);assert.match(x.w.document.querySelector('[role="dialog"]').textContent,/live integration is not active/);assert.ok(x.w.document.querySelector('[data-act="drawer-close"]'));assert.equal(x.calls.length,0);}finally{x.close();}});
test('core manual offer payload retains supplied program and track without a RISE query',async()=>{const x=harness(coreWorkspace());try{x.h.A['add-interview'](el({day:'2026-10-20'}));const name=field(x.w,'ad-name','  My Supplied Hospital  ');name.dispatchEvent(new x.w.Event('input',{bubbles:true}));field(x.w,'ad-track',' Preliminary ');field(x.w,'ad-time','10:30');field(x.w,'ad-zone','America/New_York');await x.h.A['add-interview-save'](el({}));const data=x.calls.find(c=>c.body?.command==='interview.create').body.data;assert.equal(data.program,null);assert.equal(data.programName,'My Supplied Hospital');assert.equal(data.unresolved_input,'My Supplied Hospital');assert.equal(data.track,'Preliminary');assert.equal(data.schedule.date,'2026-10-20');assert.equal(data.schedule.time,'10:30');await new Promise(r=>setTimeout(r,350));assert.equal(x.calls.some(c=>c.path.includes('/programs')),false);}finally{x.close();}});
test('core manual identity and schedule remain real while advanced subsections are previews',async()=>{const x=harness(coreWorkspace(true));try{x.h.A['open-section'](el({id:'interview-one',section:'identify'}));assert.equal(x.w.document.getElementById('identity-name').value,'Supplied Hospital');field(x.w,'identity-name','Corrected Hospital');field(x.w,'identity-track','Categorical');await x.h.A['manual-identity-save'](el({id:'interview-one'}));const data=x.calls.find(c=>c.body?.command==='interview.identity').body.data;assert.deepEqual(data,{program:null,programName:'Corrected Hospital',unresolved_input:'Corrected Hospital',track:'Categorical'});x.h.A['open-section'](el({id:'interview-one',section:'schedule'}));assert.ok(x.w.document.getElementById('sd-date'));assert.match(x.w.document.querySelector('.roomHead').textContent,/Supplied Hospital/);assert.match(x.w.document.querySelector('.roomHead').textContent,/Preliminary/);assert.ok(x.w.document.querySelector('[data-section="rehearse"]'));}finally{x.close();}});
test('core Home next scheduled interview and empty state use authenticated records only',()=>{const b=coreWorkspace(true);b.state.interviews.push({...b.state.interviews[0],id:'later',programName:'Later Hospital',instant:'2026-10-25T12:00:00Z'});const x=harness(b);try{const items=[...x.w.document.querySelectorAll('.shortItem')];assert.match(items[0].textContent,/Supplied Hospital/);assert.match(items[0].textContent,/Review interview details/);assert.doesNotMatch(items[0].textContent,/research starts|rehearse|confirm which program/i);x.h.applyBootstrap(coreWorkspace());x.h.render();assert.match(x.w.document.getElementById('main').textContent,/No interviews yet/);assert.doesNotMatch(x.w.document.getElementById('main').textContent,/Supplied Hospital|Later Hospital/);}finally{x.close();}});

test('bounded research opens existing Brief with facts, public sources and actual uncertainty',async()=>{
 const b=workspace('student',true);b.capabilities={coreOnly:true,deepResearch:true};b.state.demands={'interview-one':{requestId:'request-one',programId:'program-one',registryReleaseId:'release-one',version:2,status:'available'}};
 const research={coverage:{fields:[{field:'research.visa',state:'SUPPORTED'},{field:'research.culture',state:'UNKNOWN'}],observedAt:'2026-10-03T12:00:00.000Z'},facts:[{field:'research.visa',value:'<img src=x onerror=alert(1)> supported source text',retrievedAt:'2026-10-03T11:00:00.000Z',asOf:null,sources:[{urls:['https://hospital.edu/residency'],retrievedAt:'2026-10-03T11:00:00.000Z',reviewedAt:null}]}]};
 const x=harness(b,({path,body})=>path.endsWith('/commands')?{body:{bootstrap:b,researchCheck:{interviewId:'interview-one',requestId:'request-one',programId:'program-one',registryReleaseId:'release-one',version:2,research}}}:null);
 try{await x.h.A['open-section'](el({id:'interview-one',section:'brief'}));const text=x.w.document.getElementById('main').textContent;assert.match(text,/supported source text/);assert.match(text,/1 of 2 fields/);assert.match(text,/culture: unknown/);assert.doesNotMatch(text,/14 required areas/);assert.equal(x.w.document.querySelector('img[src=x]'),null);assert.equal(x.w.document.querySelector('a[href="https://hospital.edu/residency"]').rel,'noopener noreferrer');assert.equal(x.calls.find(c=>c.path.endsWith('/commands')).body.command,'research.check');
  x.h.applyBootstrap(b);x.h.render();assert.doesNotMatch(x.w.document.getElementById('main').textContent,/supported source text/);
 }finally{x.close();}
});
test('disabled research keeps Brief coming soon and administrator preview cannot send research',async()=>{
 const b=workspace('student',true);b.capabilities={coreOnly:true};const x=harness(b);try{await x.h.A['open-section'](el({id:'interview-one',section:'brief'}));assert.match(x.w.document.getElementById('main').textContent,/COMING SOON/);assert.equal(x.calls.length,0);}finally{x.close();}
 const a=workspace('admin');a.capabilities={coreOnly:true,deepResearch:true};const y=harness(a);try{await y.h.A['switch-view'](el({view:'student'}));await assert.rejects(y.h.command('research.check','interview-one',{}),/Preview/);assert.equal(y.calls.length,0);}finally{y.close();}
});
test('late research result for a replaced generation never enters Brief',async()=>{
 const b=workspace('student',true);b.capabilities={coreOnly:true,deepResearch:true};b.state.demands={'interview-one':{requestId:'new-request',programId:'program-one',registryReleaseId:'release-one',version:2,status:'queued'}};
 const x=harness(b,({path})=>path.endsWith('/commands')?{body:{bootstrap:b,researchCheck:{interviewId:'interview-one',requestId:'old-request',programId:'program-one',registryReleaseId:'release-one',version:1,research:{facts:[{value:'STALE FACT'}]}}}}:null);
 try{await x.h.A['open-section'](el({id:'interview-one',section:'brief'}));assert.doesNotMatch(x.w.document.getElementById('main').textContent,/STALE FACT/);}finally{x.close();}
});
