/* Shared inline reader for homepage and Mission Residency quote links. */
(() => {
 const config=document.currentScript, api=config.dataset.api||'/testimonials/api/stories', assets=config.dataset.assets||'/wp-content/mu-plugins/missionmed-proof-intelligence-assets/assets/';
 const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const style=document.createElement('style');style.textContent=`.proof-inline-reader{box-sizing:border-box;width:min(900px,calc(100% - 32px));max-height:90dvh;border:1px solid #9e8143;border-radius:18px;padding:0;background:#0d1b35;color:#eef1f6;overscroll-behavior:contain;font:16px/1.8 Inter,system-ui,sans-serif}.proof-inline-reader::backdrop{background:#04081ae8;backdrop-filter:blur(8px)}.proof-inline-reader header{position:sticky;top:0;display:flex;justify-content:space-between;align-items:center;padding:12px 22px;background:#10172a;color:#e6c785;border-bottom:1px solid #354156;z-index:2}.proof-inline-reader button{cursor:pointer;min-height:44px;min-width:44px;color:#e6c785;background:transparent;border:1px solid #9e8143;border-radius:6px;font:inherit}.proof-inline-reader section{padding:26px 32px}.proof-inline-reader h2{font:38px/1.25 Georgia,serif;color:#e6c785;margin:0 0 18px}.proof-inline-reader h3{color:#e6c785}.proof-inline-reader .proof-exact{white-space:pre-wrap;overflow-wrap:anywhere}.proof-inline-reader video{width:100%;max-height:420px;background:#000}.proof-inline-reader :focus-visible{outline:3px solid #e6c785;outline-offset:3px}.proof-inline-reader .proof-note{font-size:13px;color:#b8c7dd}.proof-inline-reader summary{cursor:pointer;color:#e6c785;min-height:44px}.proof-inline-reader a{color:#e6c785}@media(max-width:600px){.proof-inline-reader{width:100%;height:100dvh;max-height:100dvh;max-width:100%;margin:0;border-radius:0}.proof-inline-reader section{padding:24px 20px}.proof-inline-reader h2{font-size:30px}}`;
 document.head.append(style);let modal,origin,y,overflow,request=0;
 function close(){request++;if(!modal?.open)return;modal.querySelectorAll('video').forEach(v=>v.pause());modal.close();document.body.style.overflow=overflow;window.scrollTo({top:y,behavior:'instant'});origin?.focus({preventScroll:true})}
 document.addEventListener('click',async e=>{
 const link=e.target.closest('a[href]');if(!link)return;const url=new URL(link.href,location.href);if(!url.hash.startsWith('#story-')||!(/\/testimonials\/?$/.test(url.pathname)||url.origin===location.origin&&url.pathname==='/'))return;
 e.preventDefault();const token=++request;origin=link;y=scrollY;overflow=document.body.style.overflow;
 if(!modal){modal=document.createElement('dialog');modal.className='proof-inline-reader';modal.setAttribute('aria-labelledby','proof-inline-title');document.body.append(modal);modal.addEventListener('cancel',e=>{e.preventDefault();close()})}
 modal.innerHTML='<header><span>MissionMed / Full testimonial</span><button aria-label="Close testimonial">×</button></header><section><h2 id="proof-inline-title">Student testimonial</h2><p role="status">Loading testimonial…</p></section>';
 modal.querySelector('button').onclick=close;document.body.style.overflow='hidden';modal.showModal();modal.querySelector('button').focus({preventScroll:true});
 try{const id=url.hash.slice(7).split('~')[0],r=await fetch(api+'?'+new URLSearchParams({id,limit:1}));if(!r.ok)throw Error();const d=await r.json(),s=d.stories?.[0];if(!s)throw Error();if(!modal.open||token!==request)return;
 const complete=s.fullTextStatus==='source-matched-complete'&&!!s.full,verified=s.originalVerification==='verified'&&s.fullOriginalVerified===true;
 modal.querySelector('section').innerHTML=`<h2 id="proof-inline-title">${escape(s.name)}</h2><p>${escape([s.specialty,s.program,s.course].filter(Boolean).join(' · '))}</p>${complete?`<h3>${verified?'Full original testimonial':'Archived full testimonial'}</h3><div class="proof-exact">${escape(s.full)}</div>${verified?'':'<p class="proof-note">Original-source verification is pending for this archived record.</p>'}`:'<h3>Full testimonial awaiting source reconciliation</h3><p>The complete original has not been located. The excerpt is not presented as a full testimonial.</p>'}${s.video?`<h3>Associated recording</h3><video controls playsinline preload="none" poster="${assets}frame-${escape(s.video)}-aaa.jpg" src="${assets}${escape(s.video)}.mp4" aria-label="${escape(s.name)} recording"></video><p class="proof-note">The written testimonial and recording are separate sources.</p>`:''}${s.transcript?.verified?`<details><summary>Read transcript</summary><div class="proof-exact">${escape(s.transcript.text)}</div></details>`:''}<details><summary>Source & context</summary><p class="proof-note">${escape(s.sourceDisplay||'MissionMed written testimonial archive')}</p></details>`;
 }catch{if(modal.open&&token===request)modal.querySelector('section').innerHTML='<h2 id="proof-inline-title">Testimonial unavailable</h2><p>Please try again. The complete source has not loaded.</p>'}
 });
})();
