/* Tests execute only added patch bytes in a fake DOM. No product/browser/provider writes. */
'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const lines=fs.readFileSync(__dirname+'/catalog-admin.patch','utf8').split('\n');
function candidate(name){let inside=false,out=[];for(const line of lines){if(line.startsWith('+++ ')){inside=line.slice(4)==='b/interview-ready/'+name;continue;}if(inside&&line.startsWith('--- '))break;if(inside&&line.startsWith('+')&&!line.startsWith('+++'))out.push(line.slice(1));}assert(out.length,'missing candidate '+name);return out.join('\n');}
let n=0;const check=(ok,label)=>{assert(ok,label);n++;};
const copy=v=>JSON.parse(JSON.stringify(v));
class Element {constructor(tag){this.tag=tag;this.children=[];this.attributes={};this.hidden=false;this.textContent='';this.value='';this.disabled=false;}append(...ns){this.children.push(...ns);}insertAdjacentElement(_,n){this.children.push(n);}replaceChildren(...ns){this.children=[...ns];}setAttribute(k,v){this.attributes[k]=v;}querySelector(){return null;}}
const root=new Element('header'),handlers={},requests=[],applied=[];
const document={body:{},visibilityState:'visible',createElement:t=>new Element(t),querySelector:s=>s==='.topbar'?root:null,querySelectorAll:()=>[],addEventListener:(k,f)=>{handlers[k]=f;},dispatchEvent:()=>{}};
const env={window:null,document,location:{origin:'https://missionmedinstitute.com',pathname:'/interview-ready/app/'},URL,JSON,crypto:require('crypto').webcrypto,TextEncoder,AbortController,setTimeout,clearTimeout,queueMicrotask,CustomEvent:class{constructor(t){this.type=t;}},addEventListener:(k,f)=>{handlers[k]=f;}};env.window=env;
let server,denied=false;env.fetch=async(url,options)=>{requests.push({url,options});if(denied)return{status:403,ok:false};const body=options.body&&JSON.parse(options.body);if(body){assert.strictEqual(body.expectedRevision,server.revision);server.revision++;if(body.action==='draft')server.draft=copy(body.catalog);else{assert.strictEqual(body.previewDigest,'a'.repeat(64));server.published=copy(server.draft);server.publishedVersion++;}}return{status:200,ok:true,json:async()=>({subject:'subject',state:copy(server),draftDigest:'a'.repeat(64)})};};
vm.createContext(env);vm.runInContext(candidate('catalog-runtime.js'),env);check(requests.length===0,'default null context produces no public/admin calls');
function p(id,tier,order,primary=true){return{id,category:'webcam',tier,order,primary,enabled:true,archived:false,badges:[],legacyKey:'',editorial:{title:id,verdict:'Verdict',brianTake:'',bestFor:'',notNeeded:'',features:[],pros:[],cons:[],setup:'',ecosystem:'',complexity:'Simple',requiredExtras:'',gainOverBusiness:'',gainOverFirst:'',specs:[]},amazon:{asin:'B09NBWWP79',destination:env.IRCatalog.amazon('B09NBWWP79')},image:null,manufacturerUrl:'https://www.logitech.com',expert:null};}
const catalog={schema:'missionmed.interview-ready.catalog.v1',categories:[{id:'webcam',name:'Cameras',intro:'',order:0,enabled:true}],products:[p('pj','pj',0),p('bc','bc',9),p('fc','fc',7),p('alt','bc',10,false)]};
let adapted=env.IRCatalog.adapt(copy(catalog));check(adapted[0].items.map(i=>i.t).join(',')==='bc,fc,pj','canonical horizontal tier order despite editorial orders');check(adapted[0].alternatives.length===1&&adapted[0].alternatives[0].catalogId==='alt','alternatives separate from primary three');check(adapted[0].items.every(i=>!i.saveToKitAllowed&&i.key.startsWith('catalog:')),'new stable product ids cannot claim legacy personal saving');check(adapted[0].items.every(i=>i.badges.length===0),'no automatic founder/marketing badges');
const old=copy(catalog);old.products[1].legacyKey='online:webcam:bc:B09NBWWP79';old.products[1].badges=['brian-favorite'];adapted=env.IRCatalog.adapt(old,[{items:[{key:old.products[1].legacyKey,image:'data:image/webp;base64,fixture'}]}]);check(adapted[0].items[0].saveToKitAllowed&&adapted[0].items[0].image.startsWith('data:image'),'validated original identity may reuse build-approved legacy asset');check(adapted[0].items[0].badges[0].label.includes('Brian'),'only explicitly configured badge shown');
const hidden=copy(catalog);hidden.products[0].archived=true;hidden.products[0].enabled=false;adapted=env.IRCatalog.adapt(hidden);check(adapted[0].items.length===2,'archived record excluded from student projection');check(env.IRCatalog.amazon('B09NBWWP79')==='https://www.amazon.com/dp/B09NBWWP79?tag=missionmatch-20','central exact affiliate destination');check(env.IRCatalog.amazon('')==='','no-purchase plan has no invented destination');
vm.runInContext(candidate('catalog-admin.js'),env);check(!env.IRCatalogAdminHelpers&&root.children.length===0,'ordinary registered context cannot load admin controls');
env.IRCatalog.context={endpoint:env.location.origin+'/wp-json/missionmed-ir/v1/catalog',admin:{endpoint:env.location.origin+'/wp-json/missionmed-ir/v1/catalog/admin',nonce:'fixture',subject:'subject'}};env.IRApplyPublishedCatalog=c=>applied.push(copy(c));env.IRCatalogLegacy=[];server={revision:1,publishedVersion:1,draft:copy(catalog),published:copy(catalog)};env.confirm=()=>true;
vm.runInContext(candidate('catalog-admin.js'),env);
const helpers=env.IRCatalogAdminHelpers;const different=copy(catalog);different.products.push({...p('mic','bc',0),category:'mic'});helpers.setPrimary(different,'alt');check(different.products.find(p=>p.id==='alt').primary&&!different.products.find(p=>p.id==='bc').primary,'choosing primary demotes only prior same tier/category');check(different.products.find(p=>p.id==='mic').primary,'primary switch preserves other categories');helpers.archive(different,'alt');check(different.products.find(p=>p.id==='alt').archived&&!different.products.find(p=>p.id==='alt').enabled&&!different.products.find(p=>p.id==='alt').primary,'archive retains identity and clears visibility/primary');helpers.relocate(different,'alt','mic','bc');check(different.products.find(p=>p.id==='alt').order===1&&!different.products.find(p=>p.id==='alt').primary&&different.products.find(p=>p.id==='alt').legacyKey==='','category move selects collision-free order and clears original personal identity');const count=different.products.length;helpers.move(different,'alt',-1);check(different.products.length===count,'reorder never destroys record');check(!helpers.blank().badges.length&&!helpers.blank().primary&&helpers.blank().legacyKey==='','new product begins with no primary badge or inherited personal key');
const flush=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setTimeout(r,0));};
(async()=>{await flush();const panel=root.children.find(e=>e.tag==='section'),toggle=root.children.find(e=>e.tag==='button'),actions=panel.children.find(e=>e.tag==='div');const b=label=>actions.children.find(e=>e.textContent===label);
  check(panel.hidden&&toggle.textContent==='Admin view','authorized admin starts in student view');toggle.onclick();check(!panel.hidden&&toggle.attributes['aria-expanded']==='true','actual admin can toggle admin view');check(b('Publish').disabled,'publishing unavailable before saved draft preview');
  const before=JSON.stringify(server.published);b('Preview saved draft').onclick();await flush();check(applied.length===1&&JSON.stringify(server.published)===before,'draft preview changes only local shopping projection');check(!b('Publish').disabled,'preview enables explicit publish');
  env.confirm=()=>false;const reqCount=requests.length;b('Publish').onclick();await flush();check(requests.length===reqCount,'declined publish confirmation makes zero writes');env.confirm=()=>true;b('Publish').onclick();await flush();const sent=requests.find(r=>r.options.method==='POST');check(sent.options.headers['X-WP-Nonce']==='fixture'&&sent.options.headers['X-IR-Subject']==='subject','admin POST carries nonce and server subject');check(JSON.parse(sent.options.body).previewDigest==='a'.repeat(64),'publish binds server-owned saved draft digest');check(server.revision===2&&server.publishedVersion===2,'explicit publish completes against current expected revision');
  toggle.onclick();check(panel.hidden&&applied.length===3,'student switch restores published projection');
  denied=true;b('Reload server draft').onclick();await flush();check(panel.hidden&&toggle.hidden,'revoked canonical capability conceals admin view on server rejection');
  await adversarialFixtures();
  await projectionVisibilityFixtures();
  process.stdout.write(`PASS admin UI ${n} assertions; fake DOM only, not browser/live acceptance\n`);
})().catch(e=>{console.error(e);process.exit(1);});

// Focused independent-repro regressions run real candidate functions, not cloned implementations.
const BASE='f64dbc6f6cc57fb4d89bf518ed626a9d42f34c9b';
const path=require('path'),cp=require('child_process'),repo=path.resolve(__dirname,'../../../..');
const source=f=>cp.execFileSync('git',['show',`${BASE}:interview-ready/${f}`],{cwd:repo,encoding:'utf8'});
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve};};
function raceEnvironment(){const root=new Element('header'),handlers={},applied=[],calls=[];
 const document={body:{},visibilityState:'visible',createElement:t=>new Element(t),querySelector:s=>s==='.topbar'?root:null,querySelectorAll:()=>[],addEventListener:(k,f)=>handlers[k]=f,dispatchEvent:()=>{}};
 const e={window:null,document,location:{origin:'https://missionmedinstitute.com',pathname:'/interview-ready/app/'},URL,JSON,crypto:require('crypto').webcrypto,TextEncoder,AbortController,setTimeout,clearTimeout,queueMicrotask,CustomEvent:class{},confirm:()=>true,addEventListener:(k,f)=>handlers[k]=f};e.window=e;
 const auth={endpoint:e.location.origin+'/wp-json/missionmed-ir/v1/catalog',admin:{endpoint:e.location.origin+'/wp-json/missionmed-ir/v1/catalog/admin',nonce:'fixture',subject:'subject'}};
 const publicJson=deferred();let adminFetch=async()=>({status:200,ok:true,json:async()=>data(1)});
 const data=revision=>{const draft={...copy(catalog),marker:'unpublished-draft'},published={...copy(catalog),marker:'published'};draft.products[1].editorial.title='UNPUBLISHED DRAFT';published.products[1].editorial.title='PUBLISHED CATALOG';return {subject:'subject',state:{revision,publishedVersion:revision,draft,published},draftDigest:'a'.repeat(64)};};
 e.fetch=async(u,o)=>{calls.push(o);return u.endsWith('/admin')?adminFetch(o):{ok:true,json:()=>publicJson.promise};};e.IRApplyPublishedCatalog=c=>applied.push(copy(c));e.IRCatalogLegacy=[];
 vm.createContext(e);e.CATALOG={online:[{id:'webcam',name:'Immutable Cameras',items:[{key:'online:webcam:bc:B09NBWWP79',t:'bc',asin:'B09NBWWP79',name:'IMMUTABLE EMBEDDED',why:'Original',pros:[],cons:[]}]}]};e.RESEARCH={};e.route=()=>{};
 const hookLine=lines.find(l=>l.startsWith('+    catalog_hook = ')),hook=JSON.parse(hookLine.slice(hookLine.indexOf('= ')+2));e.IRApplyPublishedCatalog=undefined;vm.runInContext(hook,e);const realApply=e.IRApplyPublishedCatalog;e.IRApplyPublishedCatalog=c=>{realApply(c);applied.push(copy(c));};
 vm.runInContext(candidate('catalog-runtime.js').replace('/* MMED_IR_CATALOG_CONTEXT */ null',JSON.stringify(auth)),e);vm.runInContext(candidate('catalog-admin.js'),e);
 const panel=root.children.find(x=>x.tag==='section'),toggle=root.children.find(x=>x.tag==='button'),actions=panel.children.find(x=>x.tag==='div'),b=label=>actions.children.find(x=>x.textContent===label);
 return {e,document,handlers,publicJson,data,applied,calls,panel,toggle,b,setFetch:fn=>adminFetch=fn};
}
async function adversarialFixtures(){
 // Actual production productVisual wrapper expects complete preserved credit and sealed ASSET URLs.
 const raw=JSON.parse(source('catalog.json')),allowed=new Set(JSON.parse(source('production-assets.json')).assets.map(x=>x.path));
 const canonical=raw.online.flatMap(c=>c.items).find(i=>i.imageCredit&&allowed.has(i.image));assert(canonical);
 const legacyItem={...canonical,key:`online:webcam:${canonical.t}:${canonical.asin}`},imgCatalog=copy(catalog);
 imgCatalog.products[0].legacyKey=legacyItem.key;imgCatalog.products[0].image={url:'https://example.org/unadmitted.webp',sourceUrl:'https://example.org/source',licenseEvidence:'https://example.org/rights',alt:'Claimed rights'};
 const sealed=env.IRCatalog.adapt(imgCatalog,[{items:[legacyItem]}])[0].items.find(i=>i.t===canonical.t);
 check(sealed.image===canonical.image&&sealed.imageCredit.changes===canonical.imageCredit.changes,'sealed legacy photo and full existing credit survive remote image claim');
 const deniedCatalog=copy(catalog);deniedCatalog.products[1].image=copy(imgCatalog.products[0].image);const denied=env.IRCatalog.adapt(deniedCatalog)[0].items[0];check(!denied.image&&!denied.imageCredit,'new remote image rejected closed despite admin rights claim');
 const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
 const renderer=vm.createContext({PHASE1:{assetProfile:'production'},ASSET:{[canonical.image.split('/').pop()]:'data:image/webp;base64,sealed'},esc,external:(u,l)=>`<a href="${esc(u)}">${l}</a>`,amazonUrl:()=>'',sceneFor:()=>'',productVisual:null});
 vm.runInContext("const assetFor=p=>ASSET[(p||'').split('/').pop()]||(Object.values(ASSET).includes(p)?p:'');",renderer);
 const completion=source('completion.js'),phase=source('phase1.js');vm.runInContext(completion.slice(completion.indexOf('productVisual=function'),completion.indexOf('\ntierCard=function')),renderer);vm.runInContext(phase.slice(phase.indexOf('const productVisualBeforePhaseOne'),phase.indexOf('const renderExpertsBeforePhaseOne')),renderer);
 renderer.item=sealed;let html=vm.runInContext('productVisual(item,{id:"webcam"})',renderer);check(html.includes('data:image/webp;base64,sealed')&&html.includes('image-credit'),'adapted licensed item renders through actual sealed production dependency without credit crash');
 renderer.item=denied;html=vm.runInContext('productVisual(item,{id:"webcam"})',renderer);check(html.includes('Original product photos')&&!html.includes('src=""')&&!html.includes('unadmitted.webp'),'unsupported remote media uses actual production source-link fallback');
 // Public decode resolving after saved-draft Preview must not steal projection ownership.
 let r=raceEnvironment();await flush();r.toggle.onclick();r.b('Preview saved draft').onclick();await flush();check(!r.b('Publish').disabled,'saved draft preview enables Publish');r.publicJson.resolve({catalog:{marker:'late-public'}});await flush();check(r.applied.length===1&&!r.applied.some(x=>x.marker==='late-public'),'late public JSON does not replace visible preview');
 r.toggle.onclick();check(r.b('Publish').disabled&&r.applied.length===2,'Student switch clears preview authorization and restores owned published projection');
 // Hide/pagehide while admin JSON is awaiting; old response cannot reveal controls.
 for(const kind of ['visibility','pagehide']){r=raceEnvironment();await flush();const json=deferred();r.setFetch(async()=>({status:200,ok:true,json:()=>json.promise}));r.b('Reload server draft').onclick();await flush();if(kind==='visibility'){r.document.visibilityState='hidden';r.handlers.visibilitychange();}else r.handlers.pagehide();json.resolve(r.data(2));await flush();check(r.toggle.hidden&&r.panel.hidden&&r.b('Publish').disabled,kind+' during decode keeps obsolete admin response concealed');}
 // Old GET completes after newer visible revalidation starts: old finally cannot unlock newer operation.
 r=raceEnvironment();await flush();const oldJson=deferred(),newJson=deferred();let fetchCount=0;r.setFetch(async()=>({status:200,ok:true,json:()=>++fetchCount===1?oldJson.promise:newJson.promise}));r.b('Reload server draft').onclick();await flush();r.document.visibilityState='hidden';r.handlers.visibilitychange();r.document.visibilityState='visible';r.handlers.visibilitychange();await flush();const before=r.calls.length;oldJson.resolve(r.data(2));await flush();check(r.toggle.hidden,'old GET cannot reveal controls during newer revalidation');r.b('Reload server draft').onclick();await flush();check(r.calls.length===before,'old completion does not reset newer inFlight ownership');newJson.resolve(r.data(3));await flush();check(!r.toggle.hidden&&r.b('Publish').disabled,'only newest revalidation publishes current admin controls');
 // Revocation and stale write decode share the same lifecycle fence.
 r=raceEnvironment();await flush();const oldPost=deferred();r.setFetch(async o=>o.method==='POST'?{status:200,ok:true,json:()=>oldPost.promise}:{status:403,ok:false});r.toggle.onclick();r.b('Preview saved draft').onclick();r.b('Publish').onclick();await flush();r.handlers.pagehide();r.handlers.pageshow({persisted:true});await flush();check(r.toggle.hidden,'revoked revalidation hides controls');oldPost.resolve(r.data(2));await flush();check(r.toggle.hidden&&r.panel.hidden&&r.b('Publish').disabled,'obsolete POST JSON after revocation cannot restore admin controls or Publish');
}

async function projectionVisibilityFixtures(){
 const visible=r=>r.applied[r.applied.length-1];const studentSafe=r=>r.e.CATALOG.online.flatMap(c=>c.items).every(i=>i.name!=='UNPUBLISHED DRAFT')&&r.e.RESEARCH.online===r.e.CATALOG.online;
 // Distinct draft/public reproducer: Preview -> hide -> visible GET 401/403.
 for(const code of [401,403]){const r=raceEnvironment();await flush();r.publicJson.resolve({catalog:{...copy(catalog),marker:'published'}});await flush();r.toggle.onclick();r.b('Preview saved draft').onclick();check(visible(r).marker==='unpublished-draft'&&r.e.CATALOG.online[0].items[0].name==='UNPUBLISHED DRAFT','fixture projects a genuinely distinct draft through actual CATALOG/RESEARCH hook');r.document.visibilityState='hidden';r.handlers.visibilitychange();check(visible(r).marker==='published','hide restores last published shopping projection');r.setFetch(async()=>({status:code,ok:false}));r.document.visibilityState='visible';r.handlers.visibilitychange();await flush();check(r.toggle.hidden&&visible(r).marker==='published'&&studentSafe(r),code+' revalidation preserves published shopping visibility');}
 // No published override: restore immutable embedded guide through existing adapter hook.
 for(const action of ['student','pagehide','revocation']){const r=raceEnvironment();await flush();r.e.IRCatalogLegacy=[{id:'webcam',name:'Immutable Cameras',intro:'embedded',items:[{key:'online:webcam:bc:B09NBWWP79',t:'bc',asin:'B09NBWWP79',name:'Immutable embedded item',why:'Original guide',pros:[],cons:[]}]}];r.setFetch(async()=>({status:200,ok:true,json:async()=>{const d=r.data(2);d.state.published=null;return d;}}));r.b('Reload server draft').onclick();await flush();r.toggle.onclick();r.b('Preview saved draft').onclick();check(visible(r).marker==='unpublished-draft','no-published fixture still presents saved draft preview');if(action==='student')r.toggle.onclick();else if(action==='pagehide')r.handlers.pagehide();else{r.setFetch(async()=>({status:403,ok:false}));r.b('Reload server draft').onclick();await flush();}check(visible(r).products[0].editorial.title==='Immutable embedded item'&&!visible(r).marker&&studentSafe(r),action+' restores original embedded guide when no published override exists');check(r.b('Publish').disabled,'leaving no-published preview cancels Publish authorization');}
 // New successful revalidation restores its latest published value, never its new draft.
 let r=raceEnvironment();await flush();r.toggle.onclick();r.b('Preview saved draft').onclick();r.handlers.pagehide();r.setFetch(async()=>({status:200,ok:true,json:async()=>{const d=r.data(7);d.state.published.marker='new-published';d.state.draft.marker='new-secret-draft';return d;}}));r.handlers.pageshow({persisted:true});await flush();check(!r.toggle.hidden&&visible(r).marker==='new-published'&&r.b('Publish').disabled,'fresh valid revalidation restores newest published catalog without previewing draft');
 // An obsolete publishing response cannot re-project a draft after hide/revoked revalidation.
 r=raceEnvironment();await flush();r.toggle.onclick();r.b('Preview saved draft').onclick();const late=deferred();r.setFetch(async o=>o.method==='POST'?{status:200,ok:true,json:()=>late.promise}:{status:403,ok:false});r.b('Publish').onclick();await flush();r.handlers.pagehide();r.handlers.pageshow({persisted:true});await flush();const old=r.data(8);old.state.published.marker='obsolete-post-projection';late.resolve(old);await flush();check(r.toggle.hidden&&visible(r).marker==='published'&&studentSafe(r),'late POST cannot replace safe published projection after concealment/revocation');
}
