/* Tests execute only added patch bytes in a fake DOM. No product/browser/provider writes. */
'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const lines=fs.readFileSync(__dirname+'/catalog-admin.patch','utf8').split('\n');
function candidate(name){let inside=false,out=[];for(const line of lines){if(line.startsWith('+++ ')){inside=line.slice(4)==='b/interview-ready/'+name;continue;}if(inside&&line.startsWith('--- '))break;if(inside&&line.startsWith('+')&&!line.startsWith('+++'))out.push(line.slice(1));}assert(out.length,'missing candidate '+name);return out.join('\n');}
let n=0;const check=(ok,label)=>{assert(ok,label);n++;};
const copy=v=>JSON.parse(JSON.stringify(v));
class Element {constructor(tag){this.tag=tag;this.children=[];this.attributes={};this.hidden=false;this.textContent='';this.value='';this.disabled=false;}append(...ns){this.children.push(...ns);}insertAdjacentElement(_,n){this.children.push(n);}replaceChildren(...ns){this.children=[...ns];}setAttribute(k,v){this.attributes[k]=v;}querySelector(){return null;}}
const root=new Element('header'),handlers={},requests=[],applied=[];
const document={body:{},visibilityState:'visible',createElement:t=>new Element(t),querySelector:s=>s==='.topbar'?root:null,querySelectorAll:()=>[],addEventListener:(k,f)=>{handlers[k]=f;},dispatchEvent:()=>{}};
const env={window:null,document,location:{origin:'https://missionmedinstitute.com',pathname:'/interview-ready/app/'},URL,JSON,crypto:require('crypto').webcrypto,TextEncoder,AbortController,setTimeout,clearTimeout,queueMicrotask,CustomEvent:class{constructor(t){this.type=t;}},addEventListener:(k,f)=>{handlers[k]=f;}};env.window=env;
let server,denied=false;env.fetch=async(url,options)=>{requests.push({url,options});if(denied)return{status:403,ok:false};const body=options.body&&JSON.parse(options.body);if(body){assert.strictEqual(body.expectedRevision,server.revision);server.revision++;if(body.action==='draft')server.draft=copy(body.catalog);else{assert.strictEqual(body.previewDigest,'a'.repeat(64));server.published=copy(server.draft);server.publishedVersion++;}}return{status:200,ok:true,json:async()=>({subject:'subject',state:copy(server),draftDigest:'a'.repeat(64)})};};
vm.createContext(env);vm.runInContext(candidate('catalog-runtime.js'),env);check(requests.length===0,'default null context produces no public/admin calls');
function p(id,tier,order,primary=true){return{id,category:'webcam',tier,order,primary,enabled:true,archived:false,badges:[],legacyKey:'',editorial:{title:id,verdict:'Verdict',brianTake:'',bestFor:'',notNeeded:'',features:[],pros:[],cons:[],setup:'',ecosystem:'',complexity:'Simple',requiredExtras:'',gainOverBusiness:'',gainOverFirst:'',specs:[]},amazon:{asin:'B09NBWWP79',destination:env.IRCatalog.amazon('B09NBWWP79')},image:null,manufacturerUrl:'https://www.logitech.com',expert:null};}
const catalog={schema:'missionmed.interview-ready.catalog.v1',categories:[{id:'webcam',name:'Cameras',intro:'',order:0,enabled:true}],products:[p('pj','pj',0),p('bc','bc',9),p('fc','fc',7),p('alt','bc',10,false)]};
let adapted=env.IRCatalog.adapt(copy(catalog));check(adapted[0].items.map(i=>i.t).join(',')==='bc,fc,pj','canonical horizontal tier order despite editorial orders');check(adapted[0].alternatives.length===1&&adapted[0].alternatives[0].catalogId==='alt','alternatives separate from primary three');check(adapted[0].items.every(i=>!i.saveToKitAllowed&&i.key.startsWith('catalog:')),'new stable product ids cannot claim legacy personal saving');check(adapted[0].items.every(i=>i.badges.length===0),'no automatic founder/marketing badges');
const old=copy(catalog);old.products[1].legacyKey='online:webcam:bc:B09NBWWP79';old.products[1].badges=['brian-favorite'];adapted=env.IRCatalog.adapt(old,[{items:[{key:old.products[1].legacyKey,image:'data:image/webp;base64,fixture'}]}]);check(adapted[0].items[0].saveToKitAllowed&&adapted[0].items[0].image.startsWith('data:image'),'validated original identity may reuse build-approved legacy asset');check(adapted[0].items[0].badges[0].label.includes('Brian'),'only explicitly configured badge shown');
const hidden=copy(catalog);hidden.products[0].archived=true;hidden.products[0].enabled=false;adapted=env.IRCatalog.adapt(hidden);check(adapted[0].items.length===2,'archived record excluded from student projection');check(env.IRCatalog.amazon('B09NBWWP79')==='https://www.amazon.com/dp/B09NBWWP79?tag=missionmatch-20','central exact affiliate destination');check(env.IRCatalog.amazon('')==='','no-purchase plan has no invented destination');
vm.runInContext(candidate('catalog-admin.js'),env);check(!env.IRCatalogAdminHelpers&&root.children.length===0,'ordinary registered context cannot load admin controls');
env.IRCatalog.context={endpoint:env.location.origin+'/wp-json/missionmed-ir/v1/catalog',admin:{endpoint:env.location.origin+'/wp-json/missionmed-ir/v1/catalog/admin',nonce:'fixture',subject:'subject'}};env.IRApplyPublishedCatalog=c=>applied.push(copy(c));env.IRCatalogLegacy=[];server={revision:1,publishedVersion:1,draft:copy(catalog),published:copy(catalog)};env.confirm=()=>true;
vm.runInContext(candidate('catalog-admin.js'),env);
const helpers=env.IRCatalogAdminHelpers;const different=copy(catalog);different.products.push({...p('mic','bc',0),category:'mic'});helpers.setPrimary(different,'alt');check(different.products.find(p=>p.id==='alt').primary&&!different.products.find(p=>p.id==='bc').primary,'choosing primary demotes only prior same tier/category');check(different.products.find(p=>p.id==='mic').primary,'primary switch preserves other categories');helpers.archive(different,'alt');check(different.products.find(p=>p.id==='alt').archived&&!different.products.find(p=>p.id==='alt').enabled&&!different.products.find(p=>p.id==='alt').primary,'archive retains identity and clears visibility/primary');helpers.relocate(different,'alt','mic','bc');check(different.products.find(p=>p.id==='alt').order===1&&!different.products.find(p=>p.id==='alt').primary&&different.products.find(p=>p.id==='alt').legacyKey==='','category move selects collision-free order and clears original personal identity');const count=different.products.length;helpers.move(different,'alt',-1);check(different.products.length===count,'reorder never destroys record');check(!helpers.blank().badges.length&&!helpers.blank().primary&&helpers.blank().legacyKey==='','new product begins with no primary badge or inherited personal key');
const flush=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setTimeout(r,0));};
(async()=>{await flush();const panel=root.children.find(e=>e.tag==='section'),toggle=root.children.find(e=>e.tag==='button'),actions=panel.children.find(e=>e.tag==='div');const b=label=>actions.children.find(e=>e.textContent===label);
  check(panel.hidden&&toggle.textContent==='Admin view','authorized admin starts in student view');toggle.onclick();check(!panel.hidden&&toggle.attributes['aria-expanded']==='true','actual admin can toggle admin view');check(b('Publish').disabled,'publishing unavailable before saved draft preview');
  const before=JSON.stringify(server.published);b('Preview saved draft').onclick();await flush();check(applied.length===1&&JSON.stringify(server.published)===before,'draft preview changes only local shopping projection');check(!b('Publish').disabled,'preview enables explicit publish');
  env.confirm=()=>false;const reqCount=requests.length;b('Publish').onclick();await flush();check(requests.length===reqCount,'declined publish confirmation makes zero writes');env.confirm=()=>true;b('Publish').onclick();await flush();const sent=requests.find(r=>r.options.method==='POST');check(sent.options.headers['X-WP-Nonce']==='fixture'&&sent.options.headers['X-IR-Subject']==='subject','admin POST carries nonce and server subject');check(JSON.parse(sent.options.body).previewDigest==='a'.repeat(64),'publish binds server-owned saved draft digest');check(server.revision===2&&server.publishedVersion===2,'explicit publish completes against current expected revision');
  toggle.onclick();check(panel.hidden&&applied.length===3,'student switch restores published projection');
  denied=true;b('Reload server draft').onclick();await flush();check(panel.hidden&&toggle.hidden,'revoked canonical capability conceals admin view on server rejection');
  process.stdout.write(`PASS admin UI ${n} assertions; fake DOM only, not browser/live acceptance\n`);
})().catch(e=>{console.error(e);process.exit(1);});
