<?php
/** Fixture tests of unapplied patch; no WordPress/provider/product writes. */
namespace {
define('ABSPATH',__DIR__); define('MMED_IR_CATALOG_ENABLED',true);
class WP_Error { public function __construct(public $code,public $message,public $data) {} }
class WP_REST_Response { public $headers=[]; public function __construct(public $data,public $status=200){} public function header($k,$v){$this->headers[$k]=$v;} }
class wpdb { public $dbh,$last_error='',$show_errors=false,$suppress_errors=false;public function __construct(){$this->dbh=new \MissionMed\InterviewReady\FixtureMysqli;}public function db_connect($allow=true){$GLOBALS['reconnects']++;return false;}public function check_connection($allow=true){return $this->db_connect($allow);}public function query($s){$this->last_error='';if(!$this->dbh->alive){$this->last_error='fixture';return false;}if($GLOBALS['failQuery']){$this->dbh->alive=false;$this->last_error='fixture';return $this->check_connection();}return 1;} }
}
namespace MissionMed\InterviewReady {
use \WP_Error;use \WP_REST_Response;use \wpdb;use \RuntimeException;
function is_wp_error($x){return $x instanceof WP_Error;}function wp_parse_url($v,$p=-1){return parse_url($v,$p);}function wp_json_encode($v,$f=0){return json_encode($v,$f);}function wp_salt($v){return 'fixture-only';}function home_url($p='/'){return 'https://missionmedinstitute.com'.$p;}function get_current_user_id(){return $GLOBALS['uid'];}function is_user_logged_in(){return get_current_user_id()>0;}function current_user_can($cap){return $cap==='manage_options'&&$GLOBALS['admin'];}function wp_verify_nonce($n,$a){return $n==='fixture'&&$a==='wp_rest';}function wp_create_nonce($a){return 'fixture';}function wp_cache_delete(...$args){}function add_action(...$args){}function add_filter(...$args){}function apply_filters($name,$default,$image){return $GLOBALS['allowImage'] && $image->url==='https://approved.example/product.jpg' && $image->sourceUrl==='https://approved.example/source' && $image->licenseEvidence==='https://approved.example/rights';}
class FixtureMysqli extends \mysqli {public $thread=9,$alive=true;public function __construct(){}}
class FixtureResult {public function __construct(public $row){}}
function mysqli_query($h,$sql){if(!$h->alive)throw new RuntimeException('disconnected');if(strpos($sql,'GET_LOCK')!==false){if($GLOBALS['denyLock']||$GLOBALS['lock']!==null)return new FixtureResult([$h->thread,0]);$GLOBALS['lock']=$h->thread;return new FixtureResult([$h->thread,1]);}if(strpos($sql,'IS_USED_LOCK')!==false)return new FixtureResult([$h->thread,$GLOBALS['lock']]);if(strpos($sql,'RELEASE_LOCK')!==false){$GLOBALS['lock']=null;$GLOBALS['released']++;return new FixtureResult([1]);}throw new RuntimeException('unscoped SQL');}
function mysqli_fetch_row($r){return $r->row;}function mysqli_free_result($r){}
function get_option($key,$fallback){global $wpdb;if($key!==MMed_IR_Catalog::OPTION)throw new RuntimeException('wrong option');$GLOBALS['reads']++;if(!$wpdb->query('fixture options read'))return null;return unserialize(serialize($GLOBALS['option']??$fallback));}
function put_option($key,$value,$autoload,$initial){global $wpdb;if($key!==MMed_IR_Catalog::OPTION||$autoload!==false||!($wpdb instanceof MMed_IR_Locked_DB))throw new RuntimeException('unscoped write');if($GLOBALS['writeHook']){$fn=$GLOBALS['writeHook'];$GLOBALS['writeHook']=null;$fn();}if(!$wpdb->query('fixture options write')||$GLOBALS['failWrite'])return false;if($initial&&$GLOBALS['option']!==null)return false;$GLOBALS['option']=unserialize(serialize($value));$GLOBALS['writes']++;return true;}
function add_option($key,$value,$deprecated,$autoload){return put_option($key,$value,$autoload,true);}function update_option($key,$value,$autoload){return put_option($key,$value,$autoload,false);}
class Request {public $headers,$body='',$method,$query=[],$url=[];public function __construct($method='GET',$body=null){$this->method=$method;$this->headers=['x-wp-nonce'=>'fixture','origin'=>home_url(''),'referer'=>home_url('/interview-ready/app/'),'sec-fetch-site'=>'same-origin','x-ir-subject'=>MMed_IR_Gateway::subject(get_current_user_id()),'content-type'=>'application/json'];if($body!==null)$this->body=wp_json_encode($body);}public function get_header($k){return $this->headers[$k]??'';}public function get_query_params(){return $this->query;}public function get_url_params(){return $this->url;}public function get_body(){return $this->body;}public function get_method(){return $this->method;}}
foreach(['uid'=>101,'admin'=>true,'option'=>null,'lock'=>null,'denyLock'=>false,'reads'=>0,'writes'=>0,'released'=>0,'reconnects'=>0,'failWrite'=>false,'failQuery'=>false,'writeHook'=>null,'allowImage'=>false] as $k=>$v)$GLOBALS[$k]=$v;
$wpdb=new wpdb;
$base=dirname(__DIR__,4).'/interview-ready/integration/missionmed-interview-ready.php';require $base;
function candidate($name){$lines=file(__DIR__.'/catalog-admin.patch');$inside=false;$code='';foreach($lines as $line){if(str_starts_with($line,'+++ ')){$inside=trim(substr($line,4))==='b/interview-ready/'.$name;continue;}if($inside&&str_starts_with($line,'--- '))break;if($inside&&str_starts_with($line,'+')&&!str_starts_with($line,'+++'))$code.=substr($line,1);}if(!$code)throw new RuntimeException('candidate missing');return $code;}
if (!class_exists(MMed_IR_Catalog::class,false)) eval(substr(candidate('integration/missionmed-interview-ready-catalog.php'),5));
$n=0;function expect($yes,$name){global $n;if(!$yes){fwrite(STDERR,'FAIL '.$name."\n");exit(1);}$n++;}function iscode($r,$code){return is_wp_error($r)&&$r->code==='ir_catalog_'.$code;}
function product($tier,$n){return(object)['id'=>'fixture-'.$tier,'category'=>'webcam','tier'=>$tier,'primary'=>true,'order'=>$n,'enabled'=>true,'archived'=>false,'badges'=>[],'editorial'=>(object)['title'=>'Fixture '.$tier,'verdict'=>'Grounded interview assessment','brianTake'=>'','bestFor'=>'','notNeeded'=>'','features'=>[],'pros'=>[],'cons'=>[],'setup'=>'','ecosystem'=>'','complexity'=>'Simple','requiredExtras'=>'','gainOverBusiness'=>'','gainOverFirst'=>'','specs'=>[]],'amazon'=>(object)['asin'=>'B09NBWWP79','destination'=>MMed_IR_Catalog::amazon('B09NBWWP79')],'image'=>null,'manufacturerUrl'=>'https://www.logitech.com/webcam','expert'=>null,'legacyKey'=>''];}
$c=(object)['schema'=>MMed_IR_Catalog::SCHEMA,'categories'=>[(object)['id'=>'webcam','name'=>'Cameras','intro'=>'','order'=>0,'enabled'=>true]],'products'=>[product('bc',0),product('fc',0),product('pj',0)]];
function clonec($c){return json_decode(wp_json_encode($c));}function cmd($revision,$action,$catalog=null,$digest='',$id=null){static $number=0;$number++;return(object)['action'=>$action,'expectedRevision'=>$revision,'commandId'=>$id??sprintf('00000000-0000-4000-8000-%012d',$number),'catalog'=>$catalog,'previewDigest'=>$digest];}
function post($c){return MMed_IR_Catalog::admin(new Request('POST',$c));}
expect(MMed_IR_Catalog::valid($c,true),'three primary tiers validate');
$bad=clonec($c);$bad->categories[0]->enabled=false;expect(MMed_IR_Catalog::valid($bad)&&!MMed_IR_Catalog::valid($bad,true),'empty student catalog cannot publish');
$bad=clonec($c);$bad->products[0]->legacyKey='online:webcam:bc:B09NBWWP79';expect(MMed_IR_Catalog::valid($bad),'original legacy key accepted');$bad->products[0]->amazon->asin='B0CW1S7XP5';$bad->products[0]->amazon->destination=MMed_IR_Catalog::amazon('B0CW1S7XP5');expect(!MMed_IR_Catalog::valid($bad),'legacy key cannot retarget different ASIN');
$bad=clonec($c);$bad->products[1]->primary=false;expect(MMed_IR_Catalog::valid($bad)&&!MMed_IR_Catalog::valid($bad,true),'incomplete draft cannot publish');
foreach(['tier','asin','tag','volatile','html','url','category','duplicate','badge','order','expert','spec','image'] as $case){$bad=clonec($c);$p=$bad->products[0];switch($case){case'tier':$p->tier='coach';break;case'asin':$p->amazon->asin='invalid';break;case'tag':$p->amazon->destination='https://www.amazon.com/dp/B09NBWWP79?tag=evil-20';break;case'volatile':$p->amazon->rating=4.9;break;case'html':$p->editorial->title='<script>bad</script>';break;case'url':$p->manufacturerUrl='javascript:alert(1)';break;case'category':$p->category='dress';break;case'duplicate':$bad->products[]=$p;break;case'badge':$p->badges=['auto-favorite'];break;case'order':$p->order=-1;break;case'expert':$p->expert=(object)['by'=>'Test','title'=>'Test','url'=>'https://name:password@example.com/'];break;case'spec':$p->editorial->specs=[(object)['name'=>'FPS','value'=>'60','evidenceUrl'=>'http://example.com']];break;case'image':$p->image=(object)['url'=>'https://approved.example/product.jpg','sourceUrl'=>'https://approved.example/source','licenseEvidence'=>'https://approved.example/rights','alt'=>'Product'];break;}expect(!MMed_IR_Catalog::valid($bad),'reject '.$case);}
$bad=clonec($c);$bad->products[0]->image=(object)['url'=>'https://approved.example/product.jpg','sourceUrl'=>'https://approved.example/source','licenseEvidence'=>'https://approved.example/rights','alt'=>'Product'];$GLOBALS['allowImage']=true;expect(MMed_IR_Catalog::valid($bad),'server approved exact image record');$bad->products[0]->image->licenseEvidence='https://approved.example/other';expect(!MMed_IR_Catalog::valid($bad),'image rights mismatch rejected');$GLOBALS['allowImage']=false;
foreach(['http://example.com','https://localhost/foo','https://127.0.0.1/x','https://example.com:444/x','https://user@example.com/x','https://example.com/x#fragment','https://example.com/\n'] as $u)expect(!MMed_IR_Catalog::url($u),'unsafe URL rejected');
$r=new Request;expect(MMed_IR_Catalog::admin_permission($r)===true,'canonical authorized admin admitted');$GLOBALS['admin']=false;expect(iscode(MMed_IR_Catalog::admin($r),'forbidden'),'ordinary registered user denied admin GET');expect(!isset(MMed_IR_Catalog::context(101)['admin']),'student context has no admin authority');$before=$GLOBALS['writes'];expect(iscode(post(cmd(0,'draft',$c)),'forbidden')&&$GLOBALS['writes']===$before,'student POST performs zero writes');$GLOBALS['uid']=0;expect(is_wp_error(MMed_IR_Catalog::admin($r)),'anonymous admin rejected');$pub=MMed_IR_Catalog::public_get(new Request);expect($pub->data['catalog']===null&&$GLOBALS['writes']===0,'anonymous public GET does not seed');$GLOBALS['uid']=101;$GLOBALS['admin']=true;
foreach(['x-wp-nonce'=>'','origin'=>'https://evil.example','sec-fetch-site'=>'cross-site','x-ir-subject'=>'spoof'] as $header=>$value){$bad=new Request;$bad->headers[$header]=$value;expect(is_wp_error(MMed_IR_Catalog::admin($bad)),'admin rejects '.$header);}
$bad=new Request;$bad->query=['user_id'=>1];expect(is_wp_error(MMed_IR_Catalog::admin($bad)),'owner query rejected');
$html='<body>/* MMED_IR_CATALOG_CONTEXT */ null<!-- MMED_IR_CATALOG_ADMIN_B64:'.base64_encode('window.fixtureAdmin=true;').' --></body>';
$GLOBALS['admin']=false;$student=MMed_IR_Catalog::inject($html,101);expect(!str_contains($student,'fixtureAdmin')&&!str_contains($student,'ADMIN_B64'),'student gets no admin executable or encoded payload');$GLOBALS['admin']=true;$admin=MMed_IR_Catalog::inject($html,101);expect(str_contains($admin,'<script>window.fixtureAdmin=true;</script>'),'actual admin gets executable');expect(!str_contains(MMed_IR_Catalog::inject($html,0),'fixtureAdmin'),'public never injects admin');
$d=cmd(0,'draft',$c);$a=post($d);expect($a instanceof WP_REST_Response&&$a->data['state']['revision']===1&&$a->data['state']['published']===null,'draft save preserves missing published');expect($a->data['state']['actorUid']===101,'actor from server');expect($GLOBALS['lock']===null&&$GLOBALS['released']===1,'draft lock released');$writes=$GLOBALS['writes'];expect(post($d)->data['state']['revision']===1&&$GLOBALS['writes']===$writes,'identical retry is idempotent');$reused=clonec($d);$reused->catalog->products[0]->editorial->title='Changed';expect(iscode(post($reused),'command_reused'),'command reuse content conflict');expect(iscode(post(cmd(0,'draft',$c)),'conflict'),'stale simultaneous admin conflicts');
expect(iscode(post(cmd(1,'publish',null,str_repeat('0',64))),'preview_required'),'wrong saved preview rejected');$pubcmd=cmd(1,'publish',null,$a->data['draftDigest']);$b=post($pubcmd);expect($b instanceof WP_REST_Response&&$b->data['state']['publishedVersion']===1,'previewed draft atomically published');$old=wp_json_encode($GLOBALS['option']['published']);$public=MMed_IR_Catalog::public_get(new Request);expect(!isset($public->data['state'],$public->data['actorUid'],$public->data['audit'])&&count($public->data['catalog']->products)===3,'public published-only projection');
$bad=clonec($c);$bad->products[0]->primary=false;$draft=post(cmd(2,'draft',$bad));expect($draft instanceof WP_REST_Response&&wp_json_encode($GLOBALS['option']['published'])===$old,'unfinished save retains last published');expect(iscode(post(cmd(3,'publish',null,$draft->data['draftDigest'])),'preview_required')&&wp_json_encode($GLOBALS['option']['published'])===$old,'unfinished publish preserves live catalog');
$deleted=clonec($c);array_pop($deleted->products);expect(iscode(post(cmd(3,'draft',$deleted)),'archive_required'),'hard removal of published id forbidden');
$archived=clonec($c);$archived->products[0]->archived=true;$archived->products[0]->enabled=false;$archived->products[0]->primary=false;$new=product('bc',1);$new->id='replacement';$archived->products[]=$new;$saved=post(cmd(3,'draft',$archived));$published=post(cmd(4,'publish',null,$saved->data['draftDigest']));expect($published instanceof WP_REST_Response&&count($GLOBALS['option']['published']->products)===4&&count(MMed_IR_Catalog::public_get(new Request)->data['catalog']->products)===3,'archive preserves admin record and replaces active primary');
$before=wp_json_encode($GLOBALS['option']);$GLOBALS['failWrite']=true;$failcmd=cmd(5,'draft',$archived);expect(iscode(post($failcmd),'write')&&wp_json_encode($GLOBALS['option'])===$before,'failed WP update retains full prior envelope');$GLOBALS['failWrite']=false;expect(post($failcmd) instanceof WP_REST_Response,'same command can retry failed write');
$GLOBALS['denyLock']=true;$before=wp_json_encode($GLOBALS['option']);expect(iscode(post(cmd(6,'draft',$archived)),'lock')&&wp_json_encode($GLOBALS['option'])===$before,'lock denial performs no write');$GLOBALS['denyLock']=false;
$GLOBALS['failQuery']=true;$before=wp_json_encode($GLOBALS['option']);expect(iscode(post(cmd(6,'draft',$archived)),'read')&&wp_json_encode($GLOBALS['option'])===$before&&$GLOBALS['reconnects']===0,'same connection read failure cannot reconnect/write');$GLOBALS['failQuery']=false;$wpdb=new wpdb;$GLOBALS['lock']=null;
$before=wp_json_encode($GLOBALS['option']);$GLOBALS['admin']=false;expect(iscode(post(cmd(6,'draft',$archived)),'forbidden')&&wp_json_encode($GLOBALS['option'])===$before,'revoked capability blocks subsequent command');$GLOBALS['admin']=true;
$GLOBALS['option']['revision']='corrupt';expect(iscode(MMed_IR_Catalog::public_get(new Request),'recovery_required'),'corrupt envelope fails closed without write');
fwrite(STDOUT,'PASS catalog admin '.$n.' fixture assertions; no provider/product write'."\n");
}
