-- Filename generated by `supabase migration new ivoc_recording_analysis_binding`.
begin;
set local lock_timeout = '3s';
set local statement_timeout = '20s';

-- Keep legacy media untouched. New seals can retain their actual capture clock;
-- browser Results updates cannot replace the immutable replay timebase.
alter table public.ivoc_recordings add column recording_timebase jsonb;
alter table public.ivoc_recordings add constraint ivoc_recording_timebase_identity
  check (recording_timebase is null or (
    jsonb_typeof(recording_timebase) = 'object'
    and recording_timebase->>'clock' = 'browser-monotonic-session'
    and recording_timebase->>'recordingId' = id::text
    and recording_timebase->>'sessionId' = session_id::text
    and recording_timebase->>'ownerSubject' = owner_subject
  ) is true);
create function public.ivoc_recording_timebase_guard()
returns trigger language plpgsql set search_path = public, pg_temp as $$
begin
  if old.status = 'saved' and new.recording_timebase is distinct from old.recording_timebase
  then raise exception 'ivoc_recording_timebase_immutable'; end if;
  return new;
end;
$$;
revoke all on function public.ivoc_recording_timebase_guard() from public, anon, authenticated, service_role;
create trigger ivoc_recording_timebase_guard before update on public.ivoc_recordings
  for each row execute function public.ivoc_recording_timebase_guard();

-- Dedicated server-produced result, never copied from a browser Results/spine
-- payload. Existing grants, FORCE RLS and owner/reviewer route checks stay intact.
alter table public.ivoc_results add column candidate_analysis jsonb;
create function public.ivoc_candidate_analysis_binding_guard()
returns trigger language plpgsql set search_path = public, pg_temp as $$
declare receipt jsonb;
begin
  if tg_op = 'UPDATE' and old.candidate_analysis is not null and new.candidate_analysis is distinct from old.candidate_analysis then
    -- At most two explicit semantic retries, preserving the original transcript
    -- and source receipt. A completed analysis can never be overwritten here.
    if (old.candidate_analysis->'result'->'analysis'->>'status' = 'UNAVAILABLE'
      and old.candidate_analysis->'receipt'->>'semanticAttempt' in ('1', '2')
      and new.candidate_analysis->'receipt'->'semanticAttempt' = to_jsonb((old.candidate_analysis->'receipt'->>'semanticAttempt')::int + 1)
      and new.candidate_analysis->'result'->'transcript' = old.candidate_analysis->'result'->'transcript'
      and new.candidate_analysis->'receipt'->>'sourceSealDigest' = old.candidate_analysis->'receipt'->>'sourceSealDigest'
      and new.candidate_analysis->'receipt'->>'replaySealDigest' = old.candidate_analysis->'receipt'->>'replaySealDigest'
      and new.candidate_analysis->'receipt'->>'createdAt' > old.candidate_analysis->'receipt'->>'createdAt') is not true
    then raise exception 'ivoc_candidate_analysis_retry_invalid'; end if;
  elsif (tg_op = 'INSERT' or old.candidate_analysis is null) and new.candidate_analysis is not null
    and (new.candidate_analysis->'receipt'->'semanticAttempt' = '1'::jsonb) is not true then
    raise exception 'ivoc_candidate_analysis_attempt_invalid';
  end if;
  if new.candidate_analysis is null then return new; end if;
  receipt := new.candidate_analysis->'receipt';
  if (jsonb_typeof(new.candidate_analysis) = 'object'
    and receipt->>'schema' = 'ivoc.self-practice-analysis.v1'
    and receipt->>'status' = 'SOURCE_BOUND'
    and receipt->>'sessionId' = new.session_id::text
    and receipt->>'ownerSubject' = new.owner_subject
    and new.candidate_analysis->'result'->>'sessionId' = new.session_id::text) is not true
  then raise exception 'ivoc_candidate_analysis_receipt_invalid'; end if;
  if not exists (
    select 1 from public.ivoc_recordings s
    join public.ivoc_recordings p on p.id = s.parent_recording_id
    join public.ivoc_sessions v on v.id = new.session_id
    where s.id::text = receipt->>'sourceRecordingId'
      and p.id::text = receipt->>'replayRecordingId'
      and s.session_id = new.session_id and p.session_id = new.session_id
      and s.owner_subject = new.owner_subject and p.owner_subject = new.owner_subject
      and v.owner_subject = new.owner_subject
      and s.recording_role = 'candidate_audio' and p.recording_role = 'conversation'
      and s.status = 'saved' and p.status = 'saved'
      and s.capture_receipt->>'status' = 'SEALED' and p.recording_timebase is not null
      and v.interviewer_provider = 'missionmed-static' and v.session_type in ('question', 'quick')
      and v.context->'promptReceipt' = receipt->'promptReceipt'
      and (jsonb_typeof(v.context->'promptReceipt') = 'object'
        and v.context->'promptReceipt'->>'schema' = 'ivoc.self-practice-prompt.v1'
        and v.context->'promptReceipt'->>'workflow' = 'SELF_PRACTICE'
        and v.context->'promptReceipt'->>'approval' = 'ACTIVE_AT_SELECTION'
        and jsonb_typeof(v.context->'promptReceipt'->'version') = 'number'
        and v.context->'promptReceipt'->>'version' ~ '^[1-9][0-9]*$'
        and v.context->'promptReceipt'->>'questionId' = v.question_id
        and v.context->'promptReceipt'->>'text' = v.question_text
        and v.context->'targetQuestions' = '1'::jsonb
        and v.context->'questionIds' = jsonb_build_array(v.question_id)) is true
  ) then raise exception 'ivoc_candidate_analysis_source_invalid'; end if;
  return new;
end;
$$;
revoke all on function public.ivoc_candidate_analysis_binding_guard() from public, anon, authenticated, service_role;
create trigger ivoc_candidate_analysis_binding_guard before insert or update on public.ivoc_results
  for each row execute function public.ivoc_candidate_analysis_binding_guard();
comment on column public.ivoc_results.candidate_analysis is
  'Server-produced self-practice analysis bound to separate microphone media and approved prompt; never biometric speaker verification. Browser Results and spine payloads do not populate this column.';
commit;
