-- MissionMed HQ Media System schema (VRS-9C)
-- Apply in Supabase SQL editor.

create extension if not exists pgcrypto;
create extension if not exists vector;
create table if not exists public.media_user_state (
  user_id text not null,
  video_id text not null,
  favorite boolean not null default false,
  rating smallint,
  updated_at timestamptz not null default now(),
  primary key (user_id, video_id),
  constraint media_user_state_rating_check check (rating is null or (rating >= 1 and rating <= 5))
);
create index if not exists idx_media_user_state_user_updated
  on public.media_user_state (user_id, updated_at desc);
create index if not exists idx_media_user_state_video
  on public.media_user_state (video_id);
create table if not exists public.media_tags (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default 'system',
  created_by text not null default 'system',
  created_at timestamptz not null default now(),
  constraint media_tags_type_check check (type in ('system', 'user'))
);
create unique index if not exists uq_media_tags_name_type
  on public.media_tags (lower(name), type);
create table if not exists public.media_video_tags (
  video_id text not null,
  tag_id bigint not null references public.media_tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (video_id, tag_id)
);
create index if not exists idx_media_video_tags_video
  on public.media_video_tags (video_id);
create table if not exists public.media_user_video_tags (
  user_id text not null,
  video_id text not null,
  tag_name text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, video_id, tag_name)
);
create index if not exists idx_media_user_video_tags_user_video
  on public.media_user_video_tags (user_id, video_id);
create table if not exists public.media_playlists (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  name text not null,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_media_playlists_user_updated
  on public.media_playlists (user_id, updated_at desc);
create table if not exists public.media_playlist_items (
  id bigint generated by default as identity primary key,
  playlist_id uuid not null references public.media_playlists(id) on delete cascade,
  video_id text not null,
  start_time double precision,
  end_time double precision,
  position integer not null default 0,
  added_by text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_media_playlist_items_playlist
  on public.media_playlist_items (playlist_id, position asc, created_at asc);
create table if not exists public.media_clips (
  id uuid primary key default gen_random_uuid(),
  video_id text not null,
  start_time double precision not null default 0,
  end_time double precision not null default 0,
  title text not null,
  tags jsonb not null default '[]'::jsonb,
  created_by text not null,
  created_at timestamptz not null default now(),
  constraint media_clips_time_check check (end_time >= start_time)
);
create index if not exists idx_media_clips_creator_created
  on public.media_clips (created_by, created_at desc);
create index if not exists idx_media_clips_video
  on public.media_clips (video_id);
create or replace function public.touch_media_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
drop trigger if exists trg_touch_media_playlists_updated_at on public.media_playlists;
create trigger trg_touch_media_playlists_updated_at
before update on public.media_playlists
for each row execute function public.touch_media_updated_at();
drop trigger if exists trg_touch_media_user_state_updated_at on public.media_user_state;
create trigger trg_touch_media_user_state_updated_at
before update on public.media_user_state
for each row execute function public.touch_media_updated_at();
-- Optional semantic RPC backing table (if not already created in VRS-8 flow):
create table if not exists public.media_transcript_chunks (
  chunk_id text primary key,
  video_id text not null,
  chunk_text text not null,
  embedding vector(1536) not null,
  start_time double precision not null default 0,
  end_time double precision not null default 0,
  transcript_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_media_transcript_chunks_video_id
  on public.media_transcript_chunks (video_id);
create index if not exists idx_media_transcript_chunks_embedding
  on public.media_transcript_chunks using ivfflat (embedding vector_cosine_ops) with (lists = 100);
create or replace function public.match_media_transcript_chunks(
  query_embedding vector(1536),
  match_count integer default 20
)
returns table (
  chunk_id text,
  video_id text,
  chunk_text text,
  start_time double precision,
  end_time double precision,
  similarity real
)
language sql
stable
as $$
  select
    c.chunk_id,
    c.video_id,
    c.chunk_text,
    c.start_time,
    c.end_time,
    1 - (c.embedding <=> query_embedding) as similarity
  from public.media_transcript_chunks c
  order by c.embedding <=> query_embedding
  limit greatest(match_count, 1);
$$;
