#!/usr/bin/env python3
"""Build non-recursive D1-408 combined handoffs and refresh the D1 bundle."""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path("/Users/brianb/MissionMed_AI_Sandbox/D1_TIMELINE_ENGINE")
REPORTS = ROOT / "reports"
EVIDENCE = ROOT / "evidence" / "408"
APP = ROOT / "app_demo_401"

REPORT_ORDER = [
    "D1_408_EXECUTION_REPORT.md",
    "D1_408_INGESTION_ARCHITECTURE.md",
    "D1_408_PDF_EXTRACTION_REPORT.md",
    "D1_408_ERAS_PARSER_REPORT.md",
    "D1_408_CV_PARSER_REPORT.md",
    "D1_408_DATE_NORMALIZATION_REPORT.md",
    "D1_408_EVENT_CLASSIFICATION_REPORT.md",
    "D1_408_CONFIDENCE_REPORT.md",
    "D1_408_DUPLICATE_CONFLICT_REPORT.md",
    "D1_408_PRIVACY_REPORT.md",
    "D1_408_DATA_MODEL.md",
    "D1_408_FIXTURE_REPORT.md",
    "D1_408_RUNTIME_TEST_REPORT.md",
    "D1_408_VISUAL_UX_QA_REPORT.md",
    "D1_408_SECURITY_AND_NO_TOUCH_REPORT.md",
    "D1_408_LIMITATIONS.md",
    "D1_408_NEXT_STEPS.md",
]

EVIDENCE_ORDER = [
    "test_results_408.md",
    "combined_test_summary_408.md",
    "network_request_audit_408.md",
    "console_error_audit_408.md",
    "manual_qa_checklist_408.md",
]


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> None:
    sources = [REPORTS / name for name in REPORT_ORDER] + [EVIDENCE / name for name in EVIDENCE_ORDER]
    missing = [str(path) for path in sources if not path.is_file()]
    if missing:
        raise SystemExit("Missing handoff inputs:\n" + "\n".join(missing))

    generated = datetime.now(timezone.utc).isoformat()
    lines = [
        "# D1-408 Complete Combined Handoff",
        "",
        f"Generated: {generated}",
        "",
        "This file contains the complete, unabridged contents of every D1-408 report and evidence Markdown file generated by this run. Prior combined handoffs are intentionally excluded.",
        "",
        "## Included Files",
        "",
    ]
    lines.extend(f"- `{path}`" for path in sources)
    lines.append("")
    for source in sources:
        relative = source.relative_to(ROOT)
        content = source.read_text(encoding="utf-8").rstrip()
        lines.extend([
            "---",
            "",
            f"## Full File: `{relative}`",
            "",
            content,
            "",
        ])

    combined = "\n".join(lines).rstrip() + "\n"
    root_target = ROOT / "D1_408_COMBINED_HANDOFF.md"
    report_target = REPORTS / "D1_408_COMBINED_HANDOFF.md"
    root_target.write_text(combined, encoding="utf-8")
    report_target.write_text(combined, encoding="utf-8")

    marker_start = "<!-- D1_408_COMBINED_START -->"
    marker_end = "<!-- D1_408_COMBINED_END -->"
    all_generated = ROOT / "D1_TIMELINE_ENGINE_ALL_GENERATED_MD_HANDOFF.md"
    existing = all_generated.read_text(encoding="utf-8") if all_generated.exists() else "# D1 Timeline Engine All Generated Markdown Handoff\n"
    block = f"{marker_start}\n\n{combined.rstrip()}\n\n{marker_end}"
    if marker_start in existing and marker_end in existing:
        prefix, remainder = existing.split(marker_start, 1)
        _, suffix = remainder.split(marker_end, 1)
        refreshed = prefix.rstrip() + "\n\n" + block + suffix
    else:
        refreshed = existing.rstrip() + "\n\n---\n\n" + block + "\n"
    all_generated.write_text(refreshed, encoding="utf-8")

    manifest = {
        "generatedAt": generated,
        "sourceCount": len(sources),
        "sources": [
            {
                "path": str(path),
                "sha256": digest(path.read_bytes()),
                "bytes": path.stat().st_size,
            }
            for path in sources
        ],
        "combined": [
            {"path": str(root_target), "sha256": digest(root_target.read_bytes()), "bytes": root_target.stat().st_size},
            {"path": str(report_target), "sha256": digest(report_target.read_bytes()), "bytes": report_target.stat().st_size},
        ],
        "combinedCopiesByteIdentical": root_target.read_bytes() == report_target.read_bytes(),
        "allGeneratedBundle": str(all_generated),
    }
    (EVIDENCE / "handoff_manifest_408.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(json.dumps({
        "sourceCount": len(sources),
        "combinedSha256": manifest["combined"][0]["sha256"],
        "combinedCopiesByteIdentical": manifest["combinedCopiesByteIdentical"],
    }))


if __name__ == "__main__":
    main()
