import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";

const here=path.dirname(fileURLToPath(import.meta.url));
const web=path.resolve(here,"..");
const read=(relative)=>fs.readFileSync(path.join(web,relative),"utf8");
const index=read("index.html"),legacy=read("js/app-legacy-406a.js"),ui=read("js/ui/product-410-ui.js");
const css=[read("styles/shell.css"),read("styles/timeline.css"),read("styles/product-410.css"),read("styles/responsive.css")].join("\n");

assert.equal((await import("node:crypto")).createHash("sha256").update(index).digest("hex"),"d93f31663946b4284397c87a6ae367e4d12942f69d2638265db7e1074602b1ef");
assert.match(ui,/query\("#bgfx"\)\?\.setAttribute\("aria-hidden","true"\)/);
assert.match(ui,/setAttribute\("aria-label","Timeline workspace routes"\)/);
assert.match(ui,/main\.id="mainContent"/);
assert.match(ui,/setAttribute\("aria-label","Timeline dialog"\)/);
assert.match(ui,/mode\.setAttribute\("role","group"\)/);
assert.match(ui,/LOCAL DEMO SESSION/);
assert.doesNotMatch(ui,/<b>SAFE TO LEAVE<\/b>/);
assert.match(legacy,/role="button" tabindex="0" aria-pressed/);
assert.match(legacy,/Press Enter to edit/);
assert.match(legacy,/board\.addEventListener\('keydown'/);
assert.match(legacy,/querySelectorAll\('\[data-ck\]'\)/);
assert.match(legacy,/querySelectorAll\('\[data-slot\]'\)/);
assert.match(legacy,/Timeline sticky note/);
assert.match(legacy,/select\(item\.dataset\.ev,false\);item\.focus\(\)/);
assert.match(legacy,/heading\.focus\(\{preventScroll:true\}\)/);
assert.match(legacy,/legacyModalReturnFocus/);
assert.match(legacy,/setLegacyModalIsolation\(true\)/);
assert.match(legacy,/returnCategory=target\?\.dataset\?\.ck/);
assert.match(legacy,/e\.key==='Escape'/);
assert.match(ui,/enforceResponsiveReviewOnly/);
assert.match(ui,/max-width: 860px/);
assert.match(ui,/\[role="button"\]/);
assert.match(ui,/control\.tabIndex=-1/);
assert.match(ui,/contenteditable','false'/);
assert.match(ui,/heading\.setAttribute\("role","heading"\)/);
assert.match(ui,/advisorQuestions410/);
assert.match(ui,/questions\.slice\(0,8\)/);
assert.match(css,/@media\(max-width:600px\)/);
assert.doesNotMatch(css,/section\[data-view="canvas"\] #canvasGrid\{pointer-events:none/);
assert.match(css,/:focus-visible/);
console.log("D1-413R UI/accessibility static contract: 33/33 PASS");
